# -*- coding: utf-8 -*-
GROUPS = [
    ('论证动词与语式（陈述式/虚拟式）', [
        ('El abogado sostuvo que la prueba ___ falsificada.',
         ['estuviera', 'esté', 'estaba', 'estuviese'], 2,
         'sostener 引出对事实的断言，从句要用陈述式 estaba 表确凿主张；estuviera、esté、estuviese 都是虚拟式，只在表意志或否定的动词后才用。'),
        ('El sindicato adujo que las condiciones laborales ___ empeorado en el último año.',
         ['hubieran', 'habían', 'hubiesen', 'hayan'], 1,
         'aducir 意为援引理由来支持己方主张，从句陈述事实，故用陈述式 habían；hubieran、hubiesen、hayan 是虚拟式，此处无否定也无意志触发语。'),
        ('El ministro negó que su equipo ___ filtrado el documento.',
         ['había', 'ha', 'hubiera', 'habrá'], 2,
         'negar 表达否定，否定削弱了从句的事实性，必须用虚拟式 hubiera filtrado；había、ha、habrá 是陈述式，不能跟在 negar que 之后。'),
        ('La jueza admitió que el acusado ___ en la escena del crimen.',
         ['hubiera estado', 'estuviera', 'había estado', 'hubiese estado'], 2,
         'admitir 表示承认既成事实，从句用陈述式 había estado；hubiera estado、estuviese estado 形式不成立，estuviera 是虚拟式，均不合承认事实的语境。'),
        ('Nadie cree que el proyecto ___ viable sin más fondos.',
         ['es', 'sea', 'era', 'será'], 1,
         '主句被否定时 creer 后的从句改用虚拟式，故为 sea；es、era、será 是陈述式，只出现在肯定主句里，如 creo que es viable。'),
    ]),
    ('表达同意与不同意', [
        ('No es que no me ___ tu propuesta, es que no tengo presupuesto.',
         ['gusta', 'guste', 'gustaría', 'gustó'], 1,
         'no es que 用来否认对方假定的前提，从句必须用虚拟式 guste；gusta、gustó 是陈述式，gustaría 是条件式，都不能出现在 no es que 之后。'),
        ('No es que el plan ___ malo, es que resulta inviable a corto plazo.',
         ['es', 'fue', 'sea', 'era'], 2,
         'no es que 否认「计划不好」这一前提，从句用虚拟式 sea；es、fue、era 是陈述式，用于肯定事实，与该否认结构不兼容。'),
        ('No es que no quiera firmar; ___ que necesito revisar el contrato.',
         ['sea', 'es', 'fuera', 'era'], 1,
         'es que 引出真实理由，用陈述式 es 说明实情；sea、fuera 是虚拟式，era 是过去时，都不能与表真实原因的 es que 搭配。'),
        ('—Todos compartimos esa idea. —Pues yo ___: creo que falta un matiz importante.',
         ['discrepe', 'discrepar', 'discrepo', 'discrepando'], 2,
         '独立句谓语用第一人称现在时陈述式 discrepo，表「我有不同意见」；discrepe 是虚拟式，discrepar 是原形，discrepando 是副动词，都不能单独作谓语。'),
        ('No comparto del todo esa afirmación, pero tampoco la ___.',
         ['rechace', 'rechazo', 'rechazar', 'rechazando'], 1,
         'pero 引出的并列主句用陈述式 rechazo，与 no comparto 一起表有限度的不同意；rechace 是虚拟式，rechazar 与 rechazando 不能充当限定谓语。'),
    ]),
    ('表达推测与保留', [
        ('No contesta al teléfono; ___ de estar en el extranjero.',
         ['deba', 'debe', 'debiera', 'debamos'], 1,
         '表推测要用 deber de 加不定式，第三人称现在时陈述式为 debe；deba、debiera、debamos 是虚拟式，不能构成这种推测结构。'),
        ('A lo mejor ___ mañana temprano y podemos desayunar juntos.',
         ['llegue', 'llegara', 'llega', 'llegase'], 2,
         'a lo mejor 固定要求陈述式，故用 llega；llegue、llegara、llegase 是虚拟式，只有 quizá、tal vez 一类副词才允许接虚拟式。'),
        ('En la medida ___ que aumentan los datos, crece también la incertidumbre.',
         ['de', 'a', 'en', 'con'], 2,
         '固定连接语是 en la medida en que，表示「随着……」；en la medida de 只用于 en la medida de lo posible，de、a、con 都不能与 que 构成该结构。'),
        ('Hasta cierto ___, tienes razón, pero tu conclusión me parece exagerada.',
         ['punto', 'grado', 'parte', 'medida'], 0,
         '固定表达 hasta cierto punto 表「在某种程度上」的保留；grado 常与 en 搭配，parte 和 medida 需说 en cierta medida，故此处只能用 punto。'),
        ('En principio, el problema ___ solución, aunque habrá que negociar.',
         ['tenga', 'tuviera', 'tiene', 'tuviese'], 2,
         'en principio 只表初步保留，不改变事实陈述的语气，故用陈述式 tiene；tenga、tuviera、tuviese 是虚拟式，此处没有否定或意志触发语。'),
    ]),
    ('程度与进展的动词搭配', [
        ('El número de contagios va ___ aumento desde la semana pasada.',
         ['de', 'en', 'a', 'por'], 1,
         '固定搭配 ir en aumento 表「持续上升」；de、por 不能构成该短语，ir a 后面要接不定式，不能直接接名词 aumento。'),
        ('La tensión en la frontera tiende a ___ en los meses de invierno.',
         ['agudiza', 'agudizado', 'agudizarse', 'agudizando'], 2,
         'tender a 后面必须接不定式，故用带代词的 agudizarse，与主语 la tensión 一致；agudiza 是变位动词，agudizado 是分词，agudizando 是副动词。'),
        ('El precio de la vivienda se ha ___ en los últimos dos años.',
         ['dispara', 'disparado', 'disparar', 'disparando'], 1,
         'haber 加分词构成完成时，故用 disparado，表「暴涨」；dispara 是变位动词，disparar 是原形，disparando 是副动词，都不能跟在 se ha 后面。'),
        ('Las quejas de los vecinos son cada vez ___.',
         ['más numerosas', 'más numerosos', 'mucho numerosas', 'muy numerosas'], 0,
         'cada vez 要求比较级 más，主语 quejas 是阴性复数，故用 numerosas；numerosos 性数不符，mucho 不能修饰比较级，muy 不能与 cada vez 连用。'),
        ('El consumo de tabaco va en ___ entre los adolescentes.',
         ['descender', 'descendiendo', 'descenso', 'bajo'], 2,
         'ir en descenso 是固定搭配，表「持续下降」，介词后需名词 descenso；descender 是原形，descendiendo 是副动词，bajo 是形容词，都不能跟在 en 之后。'),
    ]),
    ('拉丁语遗留结构与公文语域', [
        ('El que ___ daño a la comunidad responderá con su patrimonio.',
         ['causara', 'cause', 'causare', 'causa'], 2,
         '法律条文用将来虚拟式 causare，指「将来造成损害者」；causara 是过去虚拟式，cause 是现在虚拟式，causa 是陈述式，都不合公文的古体语域。'),
        ('Si ___ necesario, se convocará una reunión extraordinaria.',
         ['sea', 'sería', 'fuere', 'será'], 2,
         '条件从句用将来虚拟式 fuere，属法律文书的古体表达；si 后面不能用将来时 será，也不能用虚拟式 sea 或条件式 sería。'),
        ('___ el director ausente, la reunión se aplazó sin más trámites.',
         ['Estar', 'Estaba', 'Estuviera', 'Estando'], 3,
         '副动词绝对结构由 Estando 加自己的主语构成，在这里表原因；Estar 是原形，Estaba 是陈述式，Estuviera 是虚拟式，都不能构成该结构。'),
        ('En virtud ___ artículo quinto, se declara inadmisible el recurso.',
         ['de el', 'del', 'al', 'por el'], 1,
         '固定短语 en virtud de 与阳性单数冠词缩合为 del；de el 不能分写，al 是 a 与 el 的缩合，por el 与 en virtud 不搭配，同类还有 habida cuenta de。'),
        ('La ley fue aprobada y, ___ consiguiente, entrará en vigor mañana.',
         ['en', 'de', 'por', 'a'], 2,
         '固定连接语 por consiguiente 表「因此」，属书面语域；en、de、a 都不能与 consiguiente 构成该连接语，表结果还可用 por lo tanto 或 en consecuencia。'),
    ]),
    ('预设的识别与利用', [
        ('La pregunta «¿Por qué dejaste de fumar?» presupone que el destinatario ___ antes.',
         ['fuma', 'fumará', 'fumaba', 'fumaría'], 2,
         'dejar de 预设此前存在该行为，故用过去未完成时 fumaba 表示过去的习惯；fuma 是现在时，fumará 和 fumaría 表将来或假设，与该预设不符。'),
        ('—¿Por qué dejaste de venir a clase? —No es que ___ dejado de venir: nunca me matriculé.',
         ['he', 'había', 'haya', 'hube'], 2,
         '要否认对方的前提，须用 no es que 加虚拟式 haya dejado；he、había、hube 都是陈述式，no es que 之后必须用虚拟式才能否定该预设。'),
        ('Incluso los más escépticos ___ que la medida había funcionado.',
         ['admitieran', 'admitieron', 'admitan', 'admitiesen'], 1,
         'incluso 预设「连最怀疑的人也在此列」，从句叙述事实，用陈述式 admitieron；admitieran、admitan、admitiesen 是虚拟式，此处没有否定或意志触发语。'),
        ('La pregunta «¿Cuándo dejó de fumar Ana?» ___ que Ana fumaba.',
         ['presuponga', 'presuponer', 'presupone', 'presuponiendo'], 2,
         '主语是单数名词短语，谓语用陈述式 presupone；presuponga 是虚拟式，presuponer 是原形，presuponiendo 是副动词，都不能单独充当谓语。'),
        ('El adverbio «también» en «Ana también aprobó» presupone que ___ personas aprobaron.',
         ['otra', 'otras', 'otro', 'algunos'], 1,
         'también 预设除 Ana 外还有同类个体，personas 是阴性复数，故用 otras；otra 是单数，otro 是阳性单数，algunos 是阳性复数，与 personas 不一致。'),
    ]),
    ('修辞格的辨识', [
        ('«Un silencio atronador» es un ___ , pues une dos términos de sentido contrario.',
         ['litote', 'oxímoron', 'hipérbole', 'eufemismo'], 1,
         'oxímoron 把语义相悖的词并置，如 silencio 与 atronador；litote 是弱化表述，hipérbole 是夸大，eufemismo 是用委婉语替代刺耳词语。'),
        ('Decir «no está mal» de un concierto excelente es una ___ , porque atenúa lo positivo.',
         ['litote', 'hipérbole', 'preterición', 'ironía'], 0,
         'litote 用否定形式弱化表达，实则肯定「很好」；hipérbole 是夸大，preterición 是声明不提却又提及，ironía 是说反话，都不合此处的弱化肯定。'),
        ('«No voy a mencionar los errores de mi rival», y enseguida los enumera, es una ___.',
         ['eufemismo', 'hipérbole', 'preterición', 'oxímoron'], 2,
         'preterición 声称略过某话题却实际详述；eufemismo 是委婉替代，hipérbole 是夸大其词，oxímoron 是矛盾并置，都与「说不提却提」不符。'),
        ('Llamar «tercer grado» a la tortura es un ___ , que sustituye un término duro por otro suave.',
         ['eufemismo', 'hipérbole', 'litote', 'preterición'], 0,
         'eufemismo 用温和说法替代刺耳词语，故以 tercer grado 指代 tortura；hipérbole 是夸大，litote 是以否定弱化，preterición 是假装不提，都不是婉称。'),
        ('«¡Qué puntualidad la tuya!» a quien llega dos horas tarde es una ___ de tono mordaz.',
         ['litote', 'eufemismo', 'hipérbole', 'ironía'], 3,
         'ironía 说反话，字面赞扬实为批评，语气比 sarcasmo 含蓄；litote 是弱化，eufemismo 是婉称，hipérbole 是夸大，都不能解释这句反话。'),
    ]),
]
