# -*- coding: utf-8 -*-
"""批次 38：B1–C2 语法专项题库（12 组 / 60 题）

补齐 audit-gaps.mjs 报出的「语法点无对应练习」缺口。
只覆盖**可出题的语法结构**；与单元主题绑定的表达（餐饮句式、购物句式）
不硬拆成选择题——那会变成背搭配而不是理解语法。

每个主题对应 grammar-coverage.mjs 中已登记的映射。
"""
GROUPS = [
    ('建议表达 debes / deberías', [
        ('___ descansar más, tienes mala cara.', ['Deberías', 'Debes que', 'Deber', 'Deberías que'], 0,
         'deberías 是条件式，表委婉建议（你最好……），比 debes 客气。deber 后直接接不定式，不加 que。'),
        ('___ fumar aquí, está prohibido.', ['No debes', 'No deberías que', 'No debes que', 'No deber'], 0,
         '禁止用 no debes + 不定式。表「不应该」时 deberías 也可用，语气更委婉；但都不能加 que。'),
        ('Te ___ que lo pienses dos veces.', ['aconsejo', 'aconsejas', 'aconseja', 'aconsejo que'], 0,
         'aconsejar que + 虚拟式：Te aconsejo que lo pienses。主语不同时必须用从句，且从句用虚拟式。'),
        ('¿___ que le escriba?', ['Crees', 'Crees que', 'Crees a', 'Creer'], 0,
         '¿Crees que...? + 虚拟式（le escriba）表征询意见。creer 肯定式后接陈述式，疑问式常接虚拟式。'),
        ('Sería mejor que ___ ahora.', ['saliera', 'sale', 'saldrá', 'salía'], 0,
         'sería mejor que + 虚拟式过去时，表委婉建议。条件式主句 + 虚拟式从句是礼貌建议的典型结构。'),
    ]),
    ('条件句三型', [
        ('Si ___ tiempo, te acompaño.', ['tengo', 'tuviera', 'tendré', 'tuviese'], 0,
         '第一类真实条件句：si + 陈述式现在时，主句用现在时/将来时/命令式。si 从句中不能用将来时。'),
        ('Si ___ dinero, viajaría por el mundo.', ['tuviera', 'tengo', 'tendré', 'tenía'], 0,
         '第二类非现实条件句：si + 虚拟式过去时，主句用条件式。表示与现在事实相反。'),
        ('Si lo ___ sabido, habría venido.', ['hubiera', 'he', 'habré', 'había'], 0,
         '第三类与过去事实相反：si + 虚拟式过去完成时，主句用条件式完成时（habría venido）。'),
        ('Si ___ más temprano, habríamos llegado a tiempo.', ['hubiéramos salido', 'salimos', 'saldríamos', 'salíamos'], 0,
         '第三类条件句的从句用虚拟式过去完成时 hubiéramos salido，主句照旧用条件式完成时。'),
        ('Si ___ frío, ponte el abrigo.', ['hace', 'hiciera', 'hará', 'hiciese'], 0,
         '真实条件句用陈述式：si hace frío（如果冷）。此处是给对方的实际行动建议，不是假设。'),
    ]),
    ('义务与禁令的表达', [
        ('___ que respetar las normas.', ['Hay', 'Tiene', 'Es', 'Está'], 0,
         'hay que + 不定式表无人称的必要（所有人都该做）。对比 tener que 需有具体主语：tengo que respetar。'),
        ('Se ___ la entrada a menores.', ['prohíbe', 'prohíben', 'prohíbe que', 'prohibir'], 0,
         'prohibir 的无人称被动/无人称句：se prohíbe la entrada。主语是 la entrada（单数），所以用单数动词。'),
        ('Queda ___ fumar en todo el recinto.', ['prohibido', 'prohibida', 'prohibir', 'prohibiendo'], 0,
         'quedar prohibido 是正式文书的禁令句式，prohibido 作形容词与 quedar 构成状态，性数不随 recinto 变化。'),
        ('Es obligatorio ___ el casco.', ['llevar', 'lleva', 'llevando', 'que llevar'], 0,
         'es obligatorio + 不定式（无人称）。若指定对象则用 es obligatorio que + 虚拟式：Es obligatorio que lleves casco。'),
        ('No ___ dejar el coche aquí.', ['se puede', 'se pueden', 'se puede que', 'poder'], 0,
         'no se puede + 不定式表禁止。se 无人称，动词固定第三人称单数。'),
    ]),
    ('情感动词 + 虚拟式', [
        ('Me alegro de que ___ bien.', ['estés', 'estás', 'estarás', 'estabas'], 0,
         'alegrarse de que + 虚拟式。表情感的动词后接从句一律用虚拟式，因为表达的是主观反应而非事实陈述。'),
        ('Me sorprende que no ___ venido.', ['haya', 'ha', 'había', 'habría'], 0,
         'sorprender que + 虚拟式完成时（haya venido），因为从句动作先于主句。'),
        ('Siento que no ___ podido venir.', ['hayas', 'has', 'habías', 'habrás'], 0,
         'sentir que 表遗憾，用虚拟式。第二人称单数完成时为 hayas podido。'),
        ('Le molesta que ___ tan tarde.', ['llegues', 'llegas', 'llegarás', 'llegabas'], 0,
         'molestar que + 虚拟式。这类「使某人产生情绪」的动词结构，从句均用虚拟式。'),
        ('Es una pena que no ___ más tiempo.', ['tengamos', 'tenemos', 'tendremos', 'teníamos'], 0,
         'ser una pena que + 虚拟式。es una lástima / es una pena 都是同一类评价性结构。'),
    ]),
    ('转述与引述', [
        ('Dijo que ___ cansado.', ['estaba', 'está', 'estará', 'esté'], 0,
         '主句为过去时（dijo），从句时态要后退：está → estaba。这是间接引语的时态后移规则。'),
        ('Me preguntó si ___ ir.', ['podía', 'puedo', 'podría', 'pueda'], 0,
         '间接疑问用 si。主句过去时，从句相应后移：puedo → podía。'),
        ('Me pidió que le ___ la verdad.', ['dijera', 'digo', 'diré', 'decía'], 0,
         '请求类动词（pedir）后接 que + 虚拟式；主句过去时，从句用虚拟式过去时。'),
        ('Según el informe, las ventas ___ un diez por ciento.', ['crecieron', 'crecieran', 'crezcan', 'crecerían'], 0,
         'según + 信息来源后接陈述式，因为转述的是被认定的实际发生的事。'),
        ('Se dice que la empresa ___ cerrar.', ['va a', 'vaya a', 'fuera a', 'iría a'], 0,
         'se dice que 是无人称转述结构，后接陈述式。表示「据说」而不为内容背书。'),
    ]),
    ('将来时与预测', [
        ('Mañana ___ llover en el norte.', ['va a', 'vaya a', 'fuera a', 'iría a'], 0,
         'ir a + 不定式表近期将来。表示天气预测常用这个结构，比简单将来时更口语。'),
        ('En 2050 la población ___ un 20 %.', ['aumentará', 'aumente', 'aumentara', 'aumentaría'], 0,
         '简单将来时表远期预测。与 ir a 的区别：ir a 偏近期、有把握；简单将来时偏远期、推测。'),
        ('___ ser las tres cuando llamó.', ['Deberían', 'Deben', 'Deberán', 'Debieran'], 0,
         '条件式表推测（大概是……）。deberían ser las tres ＝ 当时应该是三点。'),
        ('Ya ___ haber llegado, salió hace horas.', ['debería', 'debe que', 'debiera que', 'debiendo'], 0,
         'debería haber + 分词表对过去的推测或委婉责备（本该已经……了）。'),
        ('Si todo va bien, el proyecto ___ listo en junio.', ['estará', 'esté', 'estuviera', 'estaría'], 0,
         '真实条件句下主句用将来时表预期结果。若 si 从句为虚拟式过去时，主句才用条件式。'),
    ]),
    ('历史叙述的时态', [
        ('En 1492 Colón ___ a América.', ['llegó', 'llegaba', 'llega', 'llegaría'], 0,
         '历史事件作为一次性完成的动作，用简单过去时 llegó。'),
        ('Cuando ___ joven, vivía en Sevilla.', ['era', 'fue', 'es', 'sería'], 0,
         '描述过去的持续状态或背景用未完成过去时。'),
        ('La guerra ___ en 1936 y ___ en 1939.', ['empezó / terminó', 'empezaba / terminaba', 'empieza / termina', 'empezaría / terminaría'], 0,
         '有明确起止时间的历史事件用简单过去时。未完成过去时会把它写成背景而非事件。'),
        ('En aquella época la gente ___ más cartas.', ['escribía', 'escribió', 'escribe', 'escribiría'], 0,
         '表过去时期的习惯性行为用未完成过去时。「那时候人们常……」'),
        ('Cuando llegamos, la fiesta ya ___.', ['había empezado', 'empezó', 'empezaba', 'ha empezado'], 0,
         '「过去的过去」用过去完成时（había empezado）。这是历史叙述中交代先后的标准手段。'),
    ]),
    ('数量与趋势表达', [
        ('Las ventas ___ un 15 % el año pasado.', ['crecieron', 'crecían', 'crecen', 'crecieran'], 0,
         '表具体变化幅度用简单过去时。西语百分比前不加介词：crecieron un 15 %。'),
        ('El paro ___ en dos puntos.', ['descendió', 'descendía', 'descienda', 'descendería'], 0,
         'descender en + 幅度，表下降了多少。动词与幅度搭配的介词是 en。'),
        ('La cifra se ___ respecto al año anterior.', ['duplicó', 'duplicaba', 'duplique', 'duplicaría'], 0,
         'duplicarse ＝ 翻倍。se duplicó respecto a 是与前一年相比的标准表达。'),
        ('El consumo ___ al alza desde marzo.', ['va', 'vaya', 'fuera', 'iría'], 0,
         'ir al alza / ir a la baja 是描述趋势的固定说法，用陈述式现在时表持续状态。'),
        ('Una de cada tres personas ___ afectada.', ['resultó', 'resultara', 'resulte', 'resultaría'], 0,
         'una de cada tres ＝ 每三人中有一人。表统计结果用简单过去时。'),
    ]),
    ('抽象论述的名词化', [
        ('___ de la desigualdad exige medidas estructurales.', ['La reducción', 'Reducir', 'Reduciendo', 'Al reducir'], 0,
         '名词化「la reducción de」是学术写作的主语形式。用不定式 Reducir 语法可行，但在正式论述中名词化更常见。'),
        ('El ___ de los datos revela una tendencia clara.', ['análisis', 'analizar', 'analizando', 'al analizar'], 0,
         '名词化 el análisis de 作主语。注意 análisis 单复数同形，冠词用 el。'),
        ('La ___ del sistema requiere consenso político.', ['transformación', 'transformar', 'transformando', 'al transformar'], 0,
         '名词化 la transformación del sistema。以 -ción 结尾的阴性名词是最常见的名词化形式。'),
        ('Su ___ de la realidad resulta sospechosa.', ['interpretación', 'interpretar', 'interpretando', 'al interpretar'], 0,
         '带所有格的名词化：su interpretación de la realidad。这比动词句更凝练，也更易带上评价色彩。'),
        ('La ___ de recursos no resuelve el problema de fondo.', ['escasez', 'escaso', 'escasear', 'escasamente'], 0,
         'la escasez 是由形容词派生出的抽象名词。抽象论述常靠这类名词承载论断。'),
    ]),
    ('强调句式', [
        ('Fue en 2019 ___ empezó todo.', ['cuando', 'que cuando', 'donde', 'cual'], 0,
         'fue + 时间 + cuando 是强调时间状语的固定结构。cuando 不能被 que 替代。'),
        ('Lo que me molesta ___ la falta de respeto.', ['es', 'son', 'está', 'hay'], 0,
         'lo que... es... 是强调句式。主语 lo que me molesta 视为单数，所以用 es。'),
        ('A él ___ quien deberías preguntar.', ['es a', 'es', 'fue', 'hay a'], 0,
         '强调人时用 a él es a quien...。注意前置词 a 在强调结构中出现两次。'),
        ('Fue entonces ___ decidí marcharme.', ['cuando', 'que', 'donde', 'cual'], 0,
         'fue entonces cuando 是强调时间状语的固定搭配。'),
        ('Lo ___ importante es no rendirse.', ['más', 'mucho', 'muy', 'tanto'], 0,
         'lo más importante ＝ 最重要的（东西）。lo + 比较级 + 形容词构成抽象名词性短语。'),
    ]),
    ('缓和语与谨慎表达', [
        ('___ sea un poco exagerado, pero es lo que pienso.', ['Quizá', 'Seguramente', 'Sin duda', 'Es evidente que'], 0,
         'quizá 后接虚拟式表不确定。seguramеnte / sin duda 表较高确信，后接陈述式。'),
        ('Hasta cierto ___, tienes razón.', ['punto', 'modo', 'caso', 'lugar'], 0,
         'hasta cierto punto ＝ 在某种程度上。这是给论断加限定的常用短语。'),
        ('Me ___ que la cifra no es del todo fiable.', ['parece', 'parezco', 'parecen', 'parecer'], 0,
         'me parece que + 陈述式表委婉判断。parecer 的结构与 gustar 类似，人用与格代词。'),
        ('Diría que la propuesta ___ viable, aunque con reservas.', ['es', 'sea', 'fuera', 'sería'], 0,
         'diría que（我会说）是缓和表达，后接陈述式，因为陈述的是说话人的判断内容。'),
        ('En principio ___ de acuerdo, pero hay matices.', ['estoy', 'esté', 'estuviera', 'estaría'], 0,
         'en principio（原则上）是缓和语，后接陈述式。这类短语常与 pero 连用给出保留。'),
    ]),
    ('评价性表达与判断', [
        ('___ llamativo que nadie protestara.', ['Resulta', 'Resultan', 'Resulta que', 'Resultar'], 0,
         'resultar + 形容词 + que 是引出评价的无人称结构。resulta 固定第三人称单数。'),
        ('Cabe ___ que la medida tendrá efectos secundarios.', ['señalar', 'señala', 'señalando', 'señalado'], 0,
         'cabe + 不定式 ＝ 值得/可以……。cabe señalar / cabe destacar / cabe preguntarse 是学术写作的常用句式。'),
        ('Es ___ que se hayan tomado esas medidas.', ['discutible', 'discutir', 'discutiendo', 'discusión'], 0,
         'es discutible que + 虚拟式。评价性形容词（discutible / lamentable / sorprendente）后接从句用虚拟式。'),
        ('No es que ___ caro, es que no lo necesito.', ['sea', 'es', 'será', 'era'], 0,
         'no es que + 虚拟式表否定理由（并不是说……）。后半句 es que 用陈述式给出真正原因。'),
        ('Llama la ___ que no se haya informado antes.', ['atención', 'atenta', 'atender', 'atento'], 0,
         'llamar la atención que 是无人称评价句式。从句用虚拟式，因为表达的是说话人的主观反应。'),
    ]),
]
