# -*- coding: utf-8 -*-
"""批次 48：C1 补两个单元（认知与学习科学 / 社会变迁与代际）

B1 补完后（606→717），C1 的 606 成为最低等级，本批补足。
选题避开 C1 已有的 12 个单元（论证修辞/经济社会/科技伦理/学术写作 等）。
"""

BATCH = {
    'C1': [
        {
            'id': 'c1-u16',
            'title': '认知与学习科学',
            'subtitle': 'Cognición y Ciencia del Aprendizaje',
            'lessons': 12,
            'duration': '约 50 分钟',
            'vocab': [
                ('La cognición', '认知', 'La cognición no es un proceso pasivo.'),
                ('El sesgo cognitivo', '认知偏差', 'Los sesgos cognitivos afectan al juicio.'),
                ('La heurística', '启发式（思维捷径）', 'La heurística ahorra tiempo pero engaña.'),
                ('La carga cognitiva', '认知负荷', 'La carga cognitiva limita el aprendizaje.'),
                ('La memoria de trabajo', '工作记忆', 'La memoria de trabajo es muy limitada.'),
                ('La memoria a largo plazo', '长期记忆', 'El conocimiento se consolida en la memoria a largo plazo.'),
                ('La retención', '保持、留存', 'La retención mejora con la práctica espaciada.'),
                ('La consolidación', '巩固', 'El sueño favorece la consolidación.'),
                ('El olvido', '遗忘', 'El olvido también cumple una función.'),
                ('El repaso espaciado', '间隔复习', 'El repaso espaciado es más eficaz que el intensivo.'),
                ('La práctica intercalada', '交错练习', 'La práctica intercalada mejora la transferencia.'),
                ('La transferencia', '迁移', 'La transferencia es la prueba real del aprendizaje.'),
                ('La recuperación activa', '主动回忆', 'La recuperación activa fortalece la memoria.'),
                ('La fluidez ilusoria', '流畅性错觉', 'Rereleer produce una fluidez ilusoria.'),
                ('La metacognición', '元认知', 'La metacognición permite regular el propio aprendizaje.'),
                ('La autorregulación', '自我调节', 'La autorregulación distingue a los buenos aprendices.'),
                ('El andamiaje', '支架式教学', 'El andamiaje se retira progresivamente.'),
                ('La zona de desarrollo próximo', '最近发展区', 'La zona de desarrollo próximo define el reto óptimo.'),
                ('El refuerzo', '强化', 'El refuerzo intermitente es más persistente.'),
                ('La motivación intrínseca', '内在动机', 'La motivación intrínseca sostiene el esfuerzo.'),
                ('La curva del olvido', '遗忘曲线', 'La curva del olvido se aplana con repasos.'),
                ('El efecto de primacía', '首因效应', 'El efecto de primacía favorece lo primero.'),
                ('El efecto de recencia', '近因效应', 'El efecto de recencia favorece lo último.'),
                ('La atención selectiva', '选择性注意', 'La atención selectiva filtra lo irrelevante.'),
                ('La atención sostenida', '持续注意', 'La atención sostenida se agota con el tiempo.'),
                ('La interferencia', '干扰', 'La interferencia dificulta el recuerdo.'),
                ('El contexto de aprendizaje', '学习情境', 'El contexto de aprendizaje condiciona el recuerdo.'),
                ('La interleaving', '交错安排', 'La interleaving parece más difícil pero rinde más.'),
                ('La curva de aprendizaje', '学习曲线', 'La curva de aprendizaje se estanca al principio.'),
                ('El rendimiento', '表现、成效', 'El rendimiento no siempre refleja el aprendizaje.'),
                ('La aptitud', '资质、天资', 'La aptitud importa menos que la práctica.'),
                ('La destreza', '技能、熟练度', 'La destreza se adquiere con repetición deliberada.'),
                ('La práctica deliberada', '刻意练习', 'La práctica deliberada exige feedback.'),
                ('La retroalimentación', '反馈', 'La retroalimentación inmediata acelera el progreso.'),
                ('El error productivo', '有效错误', 'El error productivo enseña más que el acierto casual.'),
                ('La intuición', '直觉', 'La intuición experta se apoya en patrones.'),
                ('El reconocimiento de patrones', '模式识别', 'El reconocimiento de patrones distingue al experto.'),
                ('La automatización', '自动化（技能）', 'La automatización libera recursos atencionales.'),
                ('La sobrecarga informativa', '信息过载', 'La sobrecarga informativa paraliza la decisión.'),
                ('El filtrado', '筛选', 'El filtrado de información es una habilidad clave.'),
                ('La curiosidad epistémica', '求知性好奇', 'La curiosidad epistémica impulsa la exploración.'),
                ('La disposición a aprender', '学习意愿', 'La disposición a aprender es previa al método.'),
                ('Consolidar', '巩固', 'Dormir bien consolida lo aprendido.'),
                ('Retener', '记住、保持', 'Retenemos mejor lo que recuperamos.'),
                ('Recuperar', '提取、回想', 'Recuperar la información la refuerza.'),
                ('Intercalar', '交错进行', 'Conviene intercalar distintos tipos de ejercicio.'),
                ('Automatizar', '使自动化', 'La lectura se automatiza con la práctica.'),
                ('Regular el esfuerzo', '调节投入', 'Aprender a regular el esfuerzo es decisivo.'),
                ('Detectar el error', '发现错误', 'Detectar el propio error requiere entrenamiento.'),
                ('Ajustar la dificultad', '调整难度', 'El buen docente ajusta la dificultad al alumno.'),
                ('Evaluar el progreso', '评估进展', 'Evaluar el progreso sin juzgar es más útil.'),
                ('Transferir a nuevos contextos', '迁移到新情境', 'Cuesta transferir lo aprendido a nuevos contextos.'),
                ('Aprender de los errores', '从错误中学习', 'Aprender de los errores exige analizarlos.'),
                ('Aplicar lo aprendido', '应用所学', 'Aplicar lo aprendido fija el conocimiento.'),
                ('Cuestionar las propias certezas', '质疑自己的确信', 'Cuestionar las propias certezas es incómodo pero necesario.'),
            ],
            'grammar': [
                {'title': '学术论述中的被动与无人称', 'desc': 'Se ha demostrado que / Los resultados sugieren que / Cabe concluir que —— 认知科学文献避免第一人称，用无人称或被动引出结论。注意 sugerir 后接陈述式（表证据指向）与虚拟式的区分。'},
                {'title': '表「程度变化」的动词', 'desc': 'consolidarse（巩固）、automatizarse（自动化）、estancarse（停滞）、deteriorarse（退化）、afianzarse（稳固）。这类自复动词表过程，比 ser + 形容词更能体现变化。'},
                {'title': '条件与对比的书面结构', 'desc': 'En la medida en que... , ...（随着……）；Cuanto más... , más...（越……越……）；A diferencia de...（与……不同）。这些是学术对比论述的常用框架。'},
            ],
        },
        {
            'id': 'c1-u17',
            'title': '社会变迁与代际',
            'subtitle': 'Cambio Social y Generaciones',
            'lessons': 12,
            'duration': '约 50 分钟',
            'vocab': [
                ('La generación', '代', 'Cada generación reinterpreta el pasado.'),
                ('La brecha generacional', '代沟', 'La brecha generacional se ha ampliado.'),
                ('El relevo generacional', '代际更替', 'El relevo generacional avanza lento.'),
                ('La cohorte', '同期群', 'Esa cohorte vivió la crisis.'),
                ('La pirámide demográfica', '人口金字塔', 'La pirámide demográfica se ha invertido.'),
                ('El envejecimiento', '老龄化', 'El envejecimiento presiona las cuentas públicas.'),
                ('La natalidad', '出生率', 'La natalidad cayó a mínimos históricos.'),
                ('La esperanza de vida', '预期寿命', 'La esperanza de vida sigue subiendo.'),
                ('La dependencia', '抚养/赡养比', 'La tasa de dependencia aumenta.'),
                ('La migración', '移民', 'La migración compensa la caída demográfica.'),
                ('La movilidad social', '社会流动', 'La movilidad social se ha estancado.'),
                ('La desigualdad', '不平等', 'La desigualdad se transmite entre generaciones.'),
                ('La cohesión', '凝聚力', 'La cohesión social se debilita.'),
                ('La identidad colectiva', '集体认同', 'La identidad colectiva se construye despacio.'),
                ('El arraigo', '扎根、归属', 'El arraigo al barrio es fuerte.'),
                ('El desarraigo', '背井离乡', 'El desarraigo acompaña a la migración.'),
                ('La integración', '融合', 'La integración exige políticas activas.'),
                ('La exclusión', '排斥', 'La exclusión tiene raíces estructurales.'),
                ('La precariedad', '不稳定状态', 'La precariedad juvenil se ha normalizado.'),
                ('La conciliación', '工作与家庭平衡', 'La conciliación sigue siendo difícil.'),
                ('La corresponsabilidad', '共同承担', 'Falta corresponsabilidad en el hogar.'),
                ('El rol de género', '性别角色', 'Los roles de género se transforman lentamente.'),
                ('El techo de cristal', '玻璃天花板', 'El techo de cristal persiste en la dirección.'),
                ('La brecha salarial', '薪酬差距', 'La brecha salarial se reduce muy despacio.'),
                ('La segregación', '隔离、分化', 'La segregación residencial aumenta.'),
                ('La gentrificación', '绅士化', 'La gentrificación expulsa a los vecinos.'),
                ('El relevo', '接替', 'No hay relevo en los oficios tradicionales.'),
                ('La tradición', '传统', 'La tradición se reinventa en cada época.'),
                ('La ruptura', '中断、断裂', 'La ruptura con el pasado fue parcial.'),
                ('La continuidad', '延续', 'Hay más continuidad de la que se cree.'),
                ('La nostalgia', '怀旧', 'La nostalgia idealiza lo que no existió.'),
                ('El estereotipo', '刻板印象', 'Los estereotipos simplifican lo complejo.'),
                ('El prejuicio', '偏见', 'El prejuicio se transmite sin querer.'),
                ('La convivencia', '共处', 'La convivencia requiere reglas claras.'),
                ('La solidaridad intergeneracional', '代际团结', 'La solidaridad intergeneracional sostiene el sistema.'),
                ('El pacto social', '社会契约', 'El pacto social necesita renovarse.'),
                ('La confianza institucional', '制度信任', 'La confianza institucional ha caído.'),
                ('La participación', '参与', 'La participación política cambia de forma.'),
                ('El asociacionismo', '结社', 'El asociacionismo vecinal es fuerte aquí.'),
                ('El voluntariado', '志愿服务', 'El voluntariado crece entre los jóvenes.'),
                ('Transformarse', '转变', 'El barrio se ha transformado en diez años.'),
                ('Acentuarse', '加剧', 'Las diferencias se acentúan con la crisis.'),
                ('Suavizarse', '缓和', 'La tendencia se ha suavizado.'),
                ('Invertirse', '逆转', 'La curva demográfica se ha invertido.'),
                ('Transmitirse', '传递', 'Los prejuicios se transmiten sin darse cuenta.'),
                ('Reivindicar', '主张、维护', 'Reivindican mejores condiciones laborales.'),
                ('Conciliar', '兼顾', 'Es difícil conciliar trabajo y familia.'),
                ('Integrarse', '融入', 'Los recién llegados se integran con el tiempo.'),
                ('Aferrarse a', '紧紧抓住、固守', 'Se aferra a las costumbres de su tierra.'),
                ('Romper con', '与……决裂', 'La nueva generación rompe con ciertos tabúes.'),
                ('Convivir con', '与……共处', 'Hay que aprender a convivir con la diferencia.'),
                ('Sentar las bases de', '为……奠定基础', 'Aquella ley sentó las bases del sistema actual.'),
                ('Dejar paso a', '让位于', 'La costumbre dejó paso a nuevas formas.'),
            ],
            'grammar': [
                {'title': '表「变化过程」的自复动词', 'desc': 'transformarse、acentuarse、suavizarse、invertirse、afianzarse —— 这些自复动词表渐进的变化过程，比「volverse + 形容词」更书面，是社会分析文本的高频结构。'},
                {'title': '代际与统计表述', 'desc': 'la generación X / los nacidos en los ochenta / la cohorte de 1985。描述代际时西语常用出生年代而非代际标签，写「los que nacieron en los setenta」比直译「70后」更自然。'},
                {'title': '让步与对比的书面连接', 'desc': 'Si bien es cierto que... , no lo es menos que...（虽说……但同样……）；A diferencia de generaciones anteriores...；Lejos de...（非但不……反而）。这类结构是代际议题论述的常用框架。'},
            ],
        },
    ],
}
