# -*- coding: utf-8 -*-
"""批次 43：补 A1/A2/B1 基础语块（87 条）

起因：audit 发现 COLLOCATIONS 600 条的等级分布是 B2 210 / C1 203 / C2 187，
A1/A2/B1 一条都没有。查看内容后确认这不是「缺低等级」，而是**整批都是面向
高级的书面惯用短语**（a la posta、en ciernes、de motu proprio、por antonomasia…）。
初学者需要的是另一类语块：日常动作与状态的高频固定搭配。
本批补入 A1/A2/B1 三个等级的基础语块。

（生成自脚本核对后的候选池：与现有 600 条逐条比对过，全部为新条目）
"""

BATCH = [
    # ---------------- A1 ----------------
    {'level': 'A1', 'pattern': 'hacer la cama', 'zh': '铺床', 'example': 'Hago la cama cada mañana.'},
    {'level': 'A1', 'pattern': 'hacer la compra', 'zh': '买菜、采购', 'example': 'Voy a hacer la compra el sábado.'},
    {'level': 'A1', 'pattern': 'hacer deporte', 'zh': '做运动', 'example': 'Hago deporte tres veces por semana.'},
    {'level': 'A1', 'pattern': 'hacer una pregunta', 'zh': '提个问题', 'example': '¿Puedo hacer una pregunta?'},
    {'level': 'A1', 'pattern': 'hacer un favor', 'zh': '帮个忙', 'example': '¿Me haces un favor?'},
    {'level': 'A1', 'pattern': 'dar las gracias', 'zh': '道谢', 'example': 'Le dio las gracias por la ayuda.'},
    {'level': 'A1', 'pattern': 'pedir perdón', 'zh': '道歉', 'example': 'Le pidió perdón por llegar tarde.'},
    {'level': 'A1', 'pattern': 'tener razón', 'zh': '有道理', 'example': 'Tienes razón, es mejor esperar.'},
    {'level': 'A1', 'pattern': 'tener ganas de', 'zh': '想做', 'example': 'Tengo ganas de verte pronto.'},
    {'level': 'A1', 'pattern': 'tener hambre', 'zh': '饿', 'example': 'Los niños tienen hambre ya.'},
    {'level': 'A1', 'pattern': 'tener sed', 'zh': '渴', 'example': 'Tengo sed, ¿hay agua?'},
    {'level': 'A1', 'pattern': 'tener frío', 'zh': '觉得冷', 'example': 'Tengo frío, voy a cerrar la ventana.'},
    {'level': 'A1', 'pattern': 'tener calor', 'zh': '觉得热', 'example': 'Tenemos calor en esta sala.'},
    {'level': 'A1', 'pattern': 'tener sueño', 'zh': '困', 'example': 'Tengo sueño, me voy a la cama.'},
    {'level': 'A1', 'pattern': 'tener miedo', 'zh': '害怕', 'example': 'El niño tiene miedo a la oscuridad.'},
    {'level': 'A1', 'pattern': 'tener prisa', 'zh': '赶时间', 'example': 'Perdona, tengo prisa.'},
    {'level': 'A1', 'pattern': 'tener suerte', 'zh': '运气好', 'example': 'Tuviste suerte con el examen.'},
    {'level': 'A1', 'pattern': 'dar un paseo', 'zh': '散步', 'example': 'Dimos un paseo junto al río.'},
    {'level': 'A1', 'pattern': 'ir de compras', 'zh': '去购物', 'example': 'El sábado fuimos de compras.'},
    {'level': 'A1', 'pattern': 'tomar un café', 'zh': '喝杯咖啡', 'example': '¿Tomamos un café juntos?'},
    {'level': 'A1', 'pattern': 'estar de acuerdo', 'zh': '同意', 'example': 'Estoy de acuerdo contigo.'},
    {'level': 'A1', 'pattern': 'estar cansado', 'zh': '累了', 'example': 'Estoy cansado, me voy a dormir.'},
    {'level': 'A1', 'pattern': 'estar contento', 'zh': '高兴', 'example': 'Estoy contento con el resultado.'},
    {'level': 'A1', 'pattern': 'llegar tarde', 'zh': '迟到', 'example': 'Siento llegar tarde.'},
    {'level': 'A1', 'pattern': 'llegar a tiempo', 'zh': '准时到', 'example': 'Conseguimos llegar a tiempo.'},
    {'level': 'A1', 'pattern': 'levantarse temprano', 'zh': '早起', 'example': 'Me levanto temprano los días de clase.'},
    {'level': 'A1', 'pattern': 'acostarse tarde', 'zh': '晚睡', 'example': 'Los fines de semana me acuesto tarde.'},
    {'level': 'A1', 'pattern': 'ponerse el abrigo', 'zh': '穿上大衣', 'example': 'Ponte el abrigo, hace frío.'},
    {'level': 'A1', 'pattern': 'sacar una foto', 'zh': '拍张照片', 'example': '¿Nos sacas una foto?'},
    {'level': 'A1', 'pattern': 'quedarse en casa', 'zh': '待在家', 'example': 'Hoy me quedo en casa.'},
    # ---------------- A2 ----------------
    {'level': 'A2', 'pattern': 'hacer un viaje', 'zh': '去旅行', 'example': 'Hicimos un viaje por el norte.'},
    {'level': 'A2', 'pattern': 'hacer ejercicio', 'zh': '做锻炼', 'example': 'El médico me recomienda hacer ejercicio.'},
    {'level': 'A2', 'pattern': 'hacer la maleta', 'zh': '收拾行李', 'example': 'Todavía no he hecho la maleta.'},
    {'level': 'A2', 'pattern': 'hacer una reserva', 'zh': '预订', 'example': 'Hice una reserva para dos personas.'},
    {'level': 'A2', 'pattern': 'hacer cola', 'zh': '排队', 'example': 'Había que hacer cola media hora.'},
    {'level': 'A2', 'pattern': 'tomar nota', 'zh': '记下来', 'example': 'Tomé nota de todo lo importante.'},
    {'level': 'A2', 'pattern': 'tomar el sol', 'zh': '晒太阳', 'example': 'Estuvimos tomando el sol en la playa.'},
    {'level': 'A2', 'pattern': 'dar un consejo', 'zh': '给建议', 'example': 'Le di un consejo que no siguió.'},
    {'level': 'A2', 'pattern': 'dar una vuelta', 'zh': '转一圈', 'example': 'Vamos a dar una vuelta por el centro.'},
    {'level': 'A2', 'pattern': 'tener por seguro', 'zh': '确信', 'example': 'Ten por seguro que vendrá.'},
    {'level': 'A2', 'pattern': 'tener confianza en', 'zh': '信任', 'example': 'Tengo confianza en su criterio.'},
    {'level': 'A2', 'pattern': 'tener interés en', 'zh': '对……有兴趣', 'example': 'Tiene interés en aprender chino.'},
    {'level': 'A2', 'pattern': 'poner a prueba', 'zh': '考验', 'example': 'La situación puso a prueba su paciencia.'},
    {'level': 'A2', 'pattern': 'poner en práctica', 'zh': '付诸实践', 'example': 'Puso en práctica lo aprendido.'},
    {'level': 'A2', 'pattern': 'ponerse nervioso', 'zh': '紧张起来', 'example': 'Se puso nervioso antes del examen.'},
    {'level': 'A2', 'pattern': 'llevarse bien con', 'zh': '与……相处好', 'example': 'Me llevo bien con mis compañeros.'},
    {'level': 'A2', 'pattern': 'estar a punto de', 'zh': '即将', 'example': 'Estaba a punto de salir cuando llamó.'},
    {'level': 'A2', 'pattern': 'estar de moda', 'zh': '流行', 'example': 'Ese color está muy de moda.'},
    {'level': 'A2', 'pattern': 'estar de vacaciones', 'zh': '在休假', 'example': 'Ahora están de vacaciones.'},
    {'level': 'A2', 'pattern': 'quedar en', 'zh': '约定', 'example': 'Quedamos en vernos a las seis.'},
    {'level': 'A2', 'pattern': 'salir de casa', 'zh': '出门', 'example': 'Salí de casa sin paraguas.'},
    {'level': 'A2', 'pattern': 'volver a', 'zh': '再次做', 'example': 'Volvió a intentarlo al día siguiente.'},
    {'level': 'A2', 'pattern': 'aprovechar el tiempo', 'zh': '利用时间', 'example': 'Aprovecha el tiempo libre para leer.'},
    {'level': 'A2', 'pattern': 'ganar dinero', 'zh': '赚钱', 'example': 'Gana poco dinero pero le gusta el trabajo.'},
    {'level': 'A2', 'pattern': 'gastar dinero', 'zh': '花钱', 'example': 'Gastamos demasiado en comida.'},
    {'level': 'A2', 'pattern': 'ahorrar dinero', 'zh': '存钱', 'example': 'Intento ahorrar dinero cada mes.'},
    {'level': 'A2', 'pattern': 'pedir prestado', 'zh': '借入', 'example': 'Le pedí prestado el coche.'},
    {'level': 'A2', 'pattern': 'guardar un secreto', 'zh': '保守秘密', 'example': 'Supo guardar el secreto durante años.'},
    {'level': 'A2', 'pattern': 'cambiar de idea', 'zh': '改变主意', 'example': 'Cambió de idea a última hora.'},
    # ---------------- B1 ----------------
    {'level': 'B1', 'pattern': 'llamar la atención', 'zh': '引起注意', 'example': 'El cartel llamó la atención de todos.'},
    {'level': 'B1', 'pattern': 'prestar atención', 'zh': '留心', 'example': 'Presta atención a los detalles.'},
    {'level': 'B1', 'pattern': 'perder la paciencia', 'zh': '失去耐心', 'example': 'Perdí la paciencia y me fui.'},
    {'level': 'B1', 'pattern': 'conseguir un objetivo', 'zh': '实现目标', 'example': 'Consiguió su objetivo tras años de trabajo.'},
    {'level': 'B1', 'pattern': 'plantear un problema', 'zh': '提出问题', 'example': 'La normativa plantea un problema serio.'},
    {'level': 'B1', 'pattern': 'surgir una duda', 'zh': '产生疑问', 'example': 'Me surgió una duda al leerlo.'},
    {'level': 'B1', 'pattern': 'adoptar una actitud', 'zh': '采取态度', 'example': 'Adoptó una actitud muy prudente.'},
    {'level': 'B1', 'pattern': 'correr el riesgo', 'zh': '冒风险', 'example': 'No vale la pena correr ese riesgo.'},
    {'level': 'B1', 'pattern': 'dar resultado', 'zh': '奏效', 'example': 'La estrategia dio resultado.'},
    {'level': 'B1', 'pattern': 'dar a conocer', 'zh': '公布', 'example': 'Dieron a conocer los resultados.'},
    {'level': 'B1', 'pattern': 'hacerse cargo de', 'zh': '接手、负责', 'example': 'Se hizo cargo del departamento.'},
    {'level': 'B1', 'pattern': 'estar en juego', 'zh': '事关重大', 'example': 'Está en juego la credibilidad del medio.'},
    {'level': 'B1', 'pattern': 'estar al tanto de', 'zh': '了解、知情', 'example': 'Estoy al tanto de lo ocurrido.'},
    {'level': 'B1', 'pattern': 'tener en cuenta que', 'zh': '考虑到（后接从句）', 'example': 'Ten en cuenta que cierra a las ocho.'},
    {'level': 'B1', 'pattern': 'salir bien', 'zh': '顺利', 'example': 'Al final todo salió bien.'},
    {'level': 'B1', 'pattern': 'salir mal', 'zh': '出岔子', 'example': 'La operación salió mal.'},
    {'level': 'B1', 'pattern': 'llevar a cabo una reforma', 'zh': '推行改革', 'example': 'El gobierno llevó a cabo una reforma fiscal.'},
    {'level': 'B1', 'pattern': 'insistir en la idea', 'zh': '坚持这一看法', 'example': 'Insistió en la idea de aplazar la decisión.'},
    {'level': 'B1', 'pattern': 'afrontar un problema', 'zh': '面对问题', 'example': 'Hay que afrontar el problema sin excusas.'},
    {'level': 'B1', 'pattern': 'aplicar una norma', 'zh': '适用规定', 'example': 'Aplicaron la norma desde el primer día.'},
    {'level': 'B1', 'pattern': 'cumplir un plazo', 'zh': '按期完成', 'example': 'Cumplimos el plazo sin dificultad.'},
    {'level': 'B1', 'pattern': 'carecer de sentido', 'zh': '没有意义', 'example': 'Su protesta carecía de sentido.'},
    {'level': 'B1', 'pattern': 'responder a una necesidad', 'zh': '回应需求', 'example': 'El plan responde a una necesidad urgente.'},
    {'level': 'B1', 'pattern': 'romper una relación', 'zh': '断绝关系', 'example': 'Rompió la relación con la empresa.'},
    {'level': 'B1', 'pattern': 'reparar en', 'zh': '留意到', 'example': 'Reparó en un detalle importante.'},
    {'level': 'B1', 'pattern': 'perder vigencia', 'zh': '失效', 'example': 'La norma perdió vigencia el año pasado.'},
    {'level': 'B1', 'pattern': 'experimentar un cambio', 'zh': '经历变化', 'example': 'El sector experimentó un cambio profundo.'},
    {'level': 'B1', 'pattern': 'tomar una decisión difícil', 'zh': '做艰难决定', 'example': 'Tuvo que tomar una decisión difícil.'}
]
