# -*- coding: utf-8 -*-
"""批次 46：第三批低年级搭配（113 条）

继续收窄搭配模块的等级落差（低年级 vs 高年级）。
候选模式先经脚本比对（129 个确认是新的），再写例句。
"""

BATCH = [
    # ---------------- A1 ----------------
    {'level': 'A1', 'pattern': 'hacer la cena', 'zh': '做晚饭', 'example': 'Hoy me toca hacer la cena.'},
    {'level': 'A1', 'pattern': 'hacer un bocadillo', 'zh': '做个三明治', 'example': 'Voy a hacer un bocadillo para el viaje.'},
    {'level': 'A1', 'pattern': 'hacer la tarea', 'zh': '做作业', 'example': 'Los niños tienen que hacer la tarea.'},
    {'level': 'A1', 'pattern': 'tomar algo en el bar', 'zh': '在酒吧喝点什么', 'example': 'Podemos tomar algo en el bar de la esquina.'},
    {'level': 'A1', 'pattern': 'dar pena', 'zh': '令人难过', 'example': 'Da pena ver esa casa abandonada.'},
    {'level': 'A1', 'pattern': 'tener familia', 'zh': '有家人', 'example': 'Aquí tengo familia y amigos.'},
    {'level': 'A1', 'pattern': 'tener un perro', 'zh': '养狗', 'example': 'Siempre he querido tener un perro.'},
    {'level': 'A1', 'pattern': 'tener un gato', 'zh': '养猫', 'example': 'Prefiere tener un gato antes que un perro.'},
    {'level': 'A1', 'pattern': 'estar muy bien', 'zh': '很好', 'example': 'El restaurante nuevo está muy bien.'},
    {'level': 'A1', 'pattern': 'estar solo', 'zh': '独自一人', 'example': 'A veces me gusta estar solo en casa.'},
    {'level': 'A1', 'pattern': 'ir al supermercado', 'zh': '去超市', 'example': 'Tengo que ir al supermercado esta tarde.'},
    {'level': 'A1', 'pattern': 'ir al trabajo', 'zh': '去上班', 'example': 'Suelo ir al trabajo andando.'},
    {'level': 'A1', 'pattern': 'ir a clase', 'zh': '去上课', 'example': 'Mañana tengo que ir a clase temprano.'},
    {'level': 'A1', 'pattern': 'venir a casa', 'zh': '来家里', 'example': '¿Quieres venir a casa el sábado?'},
    {'level': 'A1', 'pattern': 'llegar al trabajo', 'zh': '到公司', 'example': 'Suelo llegar al trabajo a las nueve.'},
    {'level': 'A1', 'pattern': 'volver del trabajo', 'zh': '下班回来', 'example': 'Cuando vuelvo del trabajo estoy agotado.'},
    {'level': 'A1', 'pattern': 'salir del trabajo', 'zh': '下班离开', 'example': 'Salgo del trabajo sobre las seis.'},
    {'level': 'A1', 'pattern': 'poner música', 'zh': '放音乐', 'example': '¿Puedes poner música más suave?'},
    {'level': 'A1', 'pattern': 'poner la televisión', 'zh': '开电视', 'example': 'Voy a poner la televisión un rato.'},
    {'level': 'A1', 'pattern': 'quedarse en la cama', 'zh': '赖床', 'example': 'Los domingos me gusta quedarme en la cama.'},
    {'level': 'A1', 'pattern': 'quedarse a cenar', 'zh': '留下来吃晚饭', 'example': '¿Te quieres quedar a cenar?'},
    {'level': 'A1', 'pattern': 'jugar al fútbol', 'zh': '踢足球', 'example': 'Los niños juegan al fútbol en el parque.'},
    {'level': 'A1', 'pattern': 'jugar a las cartas', 'zh': '打牌', 'example': 'Mi abuelo sabe jugar a las cartas muy bien.'},
    {'level': 'A1', 'pattern': 'ver una película', 'zh': '看一部电影', 'example': 'Anoche vimos una película muy buena.'},
    {'level': 'A1', 'pattern': 'escuchar la radio', 'zh': '听广播', 'example': 'Mientras desayuno, escucho la radio.'},
    {'level': 'A1', 'pattern': 'leer un libro', 'zh': '读一本书', 'example': 'Quiero leer un libro este mes.'},
    {'level': 'A1', 'pattern': 'leer en voz alta', 'zh': '朗读', 'example': 'Conviene leer en voz alta para practicar.'},
    {'level': 'A1', 'pattern': 'escribir una carta', 'zh': '写一封信', 'example': 'Antes era normal escribir una carta a mano.'},
    {'level': 'A1', 'pattern': 'comprar fruta', 'zh': '买水果', 'example': 'Bajo a comprar fruta al mercado.'},
    {'level': 'A1', 'pattern': 'comprar leche', 'zh': '买牛奶', 'example': 'No olvides comprar leche.'},
    {'level': 'A1', 'pattern': 'cocinar bien', 'zh': '做饭好吃', 'example': 'Mi madre sabe cocinar bien.'},
    {'level': 'A1', 'pattern': 'limpiar el baño', 'zh': '打扫浴室', 'example': 'Los sábados toca limpiar el baño.'},
    {'level': 'A1', 'pattern': 'ordenar la habitación', 'zh': '收拾房间', 'example': 'Tienes que ordenar la habitación.'},
    {'level': 'A1', 'pattern': 'tirar la basura', 'zh': '倒垃圾', 'example': '¿Puedes tirar la basura, por favor?'},
    {'level': 'A1', 'pattern': 'regar las plantas', 'zh': '浇花', 'example': 'Hay que regar las plantas cada dos días.'},
    {'level': 'A1', 'pattern': 'pasear al perro', 'zh': '遛狗', 'example': 'Suele pasear al perro por la mañana.'},
    {'level': 'A1', 'pattern': 'cuidar de', 'zh': '照顾', 'example': 'Ella cuida de sus abuelos.'},
    {'level': 'A1', 'pattern': 'contestar al teléfono', 'zh': '接电话', 'example': 'Nadie contestó al teléfono.'},
    # ---------------- A2 ----------------
    {'level': 'A2', 'pattern': 'hacer un plan', 'zh': '制定计划', 'example': 'Vamos a hacer un plan para el verano.'},
    {'level': 'A2', 'pattern': 'hacer tiempo libre', 'zh': '腾出空闲时间', 'example': 'Intento hacer tiempo libre los viernes.'},
    {'level': 'A2', 'pattern': 'hacer una pausa', 'zh': '休息一下', 'example': 'Conviene hacer una pausa cada dos horas.'},
    {'level': 'A2', 'pattern': 'tomar una decisión importante', 'zh': '做重要决定', 'example': 'Tuvo que tomar una decisión importante.'},
    {'level': 'A2', 'pattern': 'tomar el ascensor', 'zh': '坐电梯', 'example': 'Prefiero tomar el ascensor, vivo en el noveno.'},
    {'level': 'A2', 'pattern': 'dar la enhorabuena', 'zh': '道贺', 'example': 'Le di la enhorabuena por el ascenso.'},
    {'level': 'A2', 'pattern': 'dar las buenas noches', 'zh': '道晚安', 'example': 'Siempre da las buenas noches a sus hijos.'},
    {'level': 'A2', 'pattern': 'tener cuidado con el dinero', 'zh': '注意花钱', 'example': 'Hay que tener cuidado con el dinero.'},
    {'level': 'A2', 'pattern': 'tener una cita', 'zh': '有约', 'example': 'Mañana tengo una cita con el dentista.'},
    {'level': 'A2', 'pattern': 'estar de paso por', 'zh': '路过', 'example': 'Estoy de paso por la ciudad.'},
    {'level': 'A2', 'pattern': 'estar dispuesto', 'zh': '愿意', 'example': 'Estoy dispuesto a ayudar.'},
    {'level': 'A2', 'pattern': 'estar en el extranjero', 'zh': '在国外', 'example': 'Su hija está en el extranjero estudiando.'},
    {'level': 'A2', 'pattern': 'poner cara de', 'zh': '做出……的表情', 'example': 'Puso cara de sorpresa.'},
    {'level': 'A2', 'pattern': 'poner un ejemplo', 'zh': '举个例子', 'example': '¿Puedes poner un ejemplo?'},
    {'level': 'A2', 'pattern': 'poner la fecha', 'zh': '写上日期', 'example': 'No olvides poner la fecha en el documento.'},
    {'level': 'A2', 'pattern': 'llevar mucho tiempo', 'zh': '花了很长时间', 'example': 'Llevo mucho tiempo esperando esto.'},
    {'level': 'A2', 'pattern': 'llevar el pelo largo', 'zh': '留长发', 'example': 'Antes llevaba el pelo largo.'},
    {'level': 'A2', 'pattern': 'quedarse tranquilo', 'zh': '放心', 'example': 'Puedes quedarte tranquilo, todo está bien.'},
    {'level': 'A2', 'pattern': 'salir a cenar', 'zh': '出去吃晚饭', 'example': 'El viernes salimos a cenar.'},
    {'level': 'A2', 'pattern': 'salir a la calle', 'zh': '上街', 'example': 'Prefiero no salir a la calle con esta lluvia.'},
    {'level': 'A2', 'pattern': 'volver a casa tarde', 'zh': '很晚回家', 'example': 'No me gusta volver a casa tarde.'},
    {'level': 'A2', 'pattern': 'volver a llamar', 'zh': '再打一次电话', 'example': 'Si no contesta, vuelve a llamar en una hora.'},
    {'level': 'A2', 'pattern': 'perder la llave', 'zh': '丢钥匙', 'example': 'Perdí la llave del portal.'},
    {'level': 'A2', 'pattern': 'ganar un premio', 'zh': '获奖', 'example': 'Ganó un premio de fotografía.'},
    {'level': 'A2', 'pattern': 'apuntar en la agenda', 'zh': '记在日程本上', 'example': 'Apúntalo en la agenda para no olvidarlo.'},
    {'level': 'A2', 'pattern': 'apuntarse a clases', 'zh': '报名上课', 'example': 'Me he apuntado a clases de natación.'},
    {'level': 'A2', 'pattern': 'echar una siesta', 'zh': '睡午觉', 'example': 'Los domingos me gusta echar una siesta.'},
    {'level': 'A2', 'pattern': 'pasar la tarde', 'zh': '度过下午', 'example': 'Pasamos la tarde en el parque.'},
    {'level': 'A2', 'pattern': 'dejar a alguien en', 'zh': '把某人送到', 'example': 'Te dejo en tu casa de camino.'},
    {'level': 'A2', 'pattern': 'seguir las instrucciones', 'zh': '按照说明', 'example': 'Hay que seguir las instrucciones del manual.'},
    {'level': 'A2', 'pattern': 'contar con alguien', 'zh': '依靠某人', 'example': 'Puedes contar conmigo siempre.'},
    {'level': 'A2', 'pattern': 'contar un chiste', 'zh': '讲笑话', 'example': 'Sabe contar un chiste muy bien.'},
    {'level': 'A2', 'pattern': 'pedir ayuda', 'zh': '求助', 'example': 'No pasa nada por pedir ayuda.'},
    {'level': 'A2', 'pattern': 'guardar en el bolsillo', 'zh': '放进兜里', 'example': 'Guardó las llaves en el bolsillo.'},
    {'level': 'A2', 'pattern': 'sacar conclusiones', 'zh': '得出结论', 'example': 'Es pronto para sacar conclusiones.'},
    {'level': 'A2', 'pattern': 'sacar dinero', 'zh': '取钱', 'example': 'Tengo que sacar dinero del cajero.'},
    # ---------------- B1 ----------------
    {'level': 'B1', 'pattern': 'marcar la diferencia en', 'zh': '在……上拉开差距', 'example': 'El detalle marca la diferencia en el resultado.'},
    {'level': 'B1', 'pattern': 'abrir una puerta a', 'zh': '为……打开一扇门', 'example': 'Esa beca le abrió una puerta al futuro.'},
    {'level': 'B1', 'pattern': 'cerrar la sesión', 'zh': '退出登录', 'example': 'No olvides cerrar la sesión al terminar.'},
    {'level': 'B1', 'pattern': 'subrayar un punto', 'zh': '强调一点', 'example': 'Quisiera subrayar un punto importante.'},
    {'level': 'B1', 'pattern': 'destacar por', 'zh': '以……著称', 'example': 'La ciudad destaca por su arquitectura.'},
    {'level': 'B1', 'pattern': 'señalar con el dedo', 'zh': '用手指指', 'example': 'Es de mala educación señalar con el dedo.'},
    {'level': 'B1', 'pattern': 'reconocer un error', 'zh': '承认错误', 'example': 'Supo reconocer su error a tiempo.'},
    {'level': 'B1', 'pattern': 'asumir el mando', 'zh': '接手指挥', 'example': 'El nuevo director asumió el mando en enero.'},
    {'level': 'B1', 'pattern': 'plantear la cuestión de', 'zh': '提出……的问题', 'example': 'Conviene plantear la cuestión de los costes.'},
    {'level': 'B1', 'pattern': 'superar un problema', 'zh': '克服困难', 'example': 'Lograron superar un problema muy serio.'},
    {'level': 'B1', 'pattern': 'responder a las críticas', 'zh': '回应批评', 'example': 'El ministro respondió a las críticas con datos.'},
    {'level': 'B1', 'pattern': 'aplicar la ley', 'zh': '执法', 'example': 'La policía se limita a aplicar la ley.'},
    {'level': 'B1', 'pattern': 'cumplir una función', 'zh': '发挥功能', 'example': 'El prólogo cumple una función informativa.'},
    {'level': 'B1', 'pattern': 'representar un obstáculo', 'zh': '构成障碍', 'example': 'La falta de fondos representa un obstáculo serio.'},
    {'level': 'B1', 'pattern': 'suponer un riesgo', 'zh': '构成风险', 'example': 'Esa práctica puede suponer un riesgo.'},
    {'level': 'B1', 'pattern': 'constituir un ejemplo de', 'zh': '是……的一个例子', 'example': 'El caso constituye un ejemplo de buena gestión.'},
    {'level': 'B1', 'pattern': 'implicar un cambio', 'zh': '意味着变化', 'example': 'Aceptar eso implicaríaía un cambio de fondo.'},
    {'level': 'B1', 'pattern': 'derivar en', 'zh': '演变为', 'example': 'La discusión derivó en un acuerdo.'},
    {'level': 'B1', 'pattern': 'traducirse en beneficio de', 'zh': '转化为……的利益', 'example': 'El esfuerzo se tradujo en beneficio de todos.'},
    {'level': 'B1', 'pattern': 'llevar implícito', 'zh': '含有、意味着', 'example': 'Ese cargo lleva implícito mucho riesgo.'},
    {'level': 'B1', 'pattern': 'llevar a confusión', 'zh': '引起混淆', 'example': 'Ese titular puede llevar a confusión.'},
    {'level': 'B1', 'pattern': 'dar lugar a dudas', 'zh': '引起疑问', 'example': 'Su explicación dio lugar a dudas.'},
    {'level': 'B1', 'pattern': 'dar pie a', 'zh': '引出、使人得以', 'example': 'El informe da pie a nuevas preguntas.'},
    {'level': 'B1', 'pattern': 'hacer referencia a', 'zh': '提及、指向', 'example': 'El autor hace referencia a estudios previos.'},
    {'level': 'B1', 'pattern': 'hacer alusión a', 'zh': '暗指', 'example': 'Hizo alusión a un problema conocido por todos.'},
    {'level': 'B1', 'pattern': 'hacer balance de', 'zh': '对……做总结', 'example': 'Conviene hacer balance de lo conseguido.'},
    {'level': 'B1', 'pattern': 'hacer constar que', 'zh': '声明、载明', 'example': 'Quiero hacer constar que no estuve presente.'},
    {'level': 'B1', 'pattern': 'tener en consideración', 'zh': '予以考虑', 'example': 'Se tendrán en consideración todas las propuestas.'},
    {'level': 'B1', 'pattern': 'estar en condiciones de', 'zh': '有能力、有条件', 'example': 'No estamos en condiciones de responder aún.'},
    {'level': 'B1', 'pattern': 'estar a disposición de', 'zh': '供……使用', 'example': 'Los datos están a disposición de los investigadores.'},
    {'level': 'B1', 'pattern': 'poner de relieve la importancia de', 'zh': '凸显……的重要性', 'example': 'El informe pone de relieve la importancia del contexto.'},
    {'level': 'B1', 'pattern': 'poner en conocimiento de', 'zh': '告知', 'example': 'Puso los hechos en conocimiento de la autoridad.'},
    {'level': 'B1', 'pattern': 'tomar en consideración', 'zh': '加以考虑', 'example': 'El comité tomó en consideración su solicitud.'},
    {'level': 'B1', 'pattern': 'tomar medidas al respecto', 'zh': '就此采取措施', 'example': 'El ayuntamiento tomará medidas al respecto.'},
    {'level': 'B1', 'pattern': 'resultar evidente que', 'zh': '显然', 'example': 'Resulta evidente que falta información.'},
    {'level': 'B1', 'pattern': 'resultar útil para', 'zh': '对……有用', 'example': 'Ese resumen resulta útil para repasar.'},
    {'level': 'B1', 'pattern': 'contribuir a mejorar', 'zh': '有助于改善', 'example': 'La medida contribuye a mejorar el servicio.'},
    {'level': 'B1', 'pattern': 'contribuir al desarrollo de', 'zh': '促进……的发展', 'example': 'El programa contribuye al desarrollo de la región.'},
    {'level': 'B1', 'pattern': 'dimensionar el problema', 'zh': '衡量问题的规模', 'example': 'Cuesta dimensionar el problema sin datos.'}
]
