# -*- coding: utf-8 -*-
"""批次 34：A1/A2 语法专项题库（15 组 / 60 题）

补齐 audit-gaps.mjs 报出的「语法点无对应练习」缺口，
优先覆盖初学者每天都会用到的基础结构。
"""

GROUPS = [
    ('Tener 的用法与固定搭配', [
        ('___ veinte años.', ['Tengo', 'Soy', 'Estoy', 'Hay'], 0,
         '说年龄用 tener：tengo veinte años。西语不说「我是二十年」，ser/estar 都表达不出年龄。'),
        ('___ hambre, ¿podemos comer?', ['Tengo', 'Soy', 'Estoy', 'Hago'], 0,
         '表生理需求用 tener + 名词：tener hambre（饿）、tener sed（渴）、tener frío（冷）。不用 ser 或 estar。'),
        ('Mi hermano ___ sed.', ['tiene', 'es', 'está', 'hace'], 0,
         'tener 的第二、三人称有词干变化 e→ie：tengo, tienes, tiene, tenemos, tenéis, tienen。'),
        ('¿___ tú frío? Cierra la ventana.', ['Tienes', 'Eres', 'Estás', 'Haces'], 0,
         '问对方「你冷吗」用 ¿Tienes frío?。注意 tener frío 是「感到冷」，hacer frío 是「天气冷」。'),
    ]),
    ('Poder + 动词原形', [
        ('¿___ ayudarme, por favor?', ['Puedes', 'Poder', 'Puede que', 'Puedo'], 0,
         'poder + 不定式表能力或许可：¿Puedes ayudarme?。poder 词干变化 o→ue，但 nosotros/podemos 不变。'),
        ('No ___ ir a la fiesta, tengo trabajo.', ['puedo', 'puedes', 'puede', 'podemos'], 0,
         '第一人称用 puedo。poder 的变位：puedo, puedes, puede, podemos, podéis, pueden。'),
        ('___ entrar? (礼貌询问)', ['¿Se puede', '¿Se puedes', '¿Se poder', '¿Se puede que'], 0,
         '礼貌询问可否做某事用无人称 ¿Se puede...?，动词固定第三人称单数，不随问话人变化。'),
    ]),
    ('Querer + 动词原形', [
        ('___ aprender español.', ['Quiero', 'Querer', 'Quiero que', 'Quiere'], 0,
         'querer + 不定式表意愿：quiero aprender。主语相同用不定式；主语不同才用 que + 虚拟式。'),
        ('¿___ tú un café?', ['Quieres', 'Quiero', 'Quiere', 'Queréis'], 0,
         'tú 对应 quieres（e→ie 词干变化）。注意 querer un café 是「要一杯咖啡」的常用说法。'),
        ('Ella ___ venir con nosotros.', ['quiere', 'quiero', 'quieres', 'quieren'], 0,
         '第三人称单数 quiere。主语是 ella，所以用第三人称形式。'),
        ('No ___ que vengas, es tarde.', ['quiero', 'quiere', 'quieres', 'querer'], 0,
         '主语不同（我 vs 你）时必须用 que + 虚拟式：no quiero que vengas。这是不定式与从句的分界点。'),
    ]),
    ('频率副词与频率表达', [
        ('___ voy al gimnasio los lunes.', ['Siempre', 'Nunca', 'A veces', 'Casi'], 0,
         'siempre（总是）放在动词前。频率副词位置固定：在动词前、否定词后。'),
        ('No voy ___ al cine, casi no tengo tiempo.', ['nunca', 'siempre', 'a veces', 'todos'], 0,
         'nunca（从不）在否定句中可放在动词后：No voy nunca。也可说 Nunca voy（此时不再加 no）。'),
        ('Voy al cine ___ vez al mes.', ['una', 'un', 'uno', 'primera'], 0,
         '「每月一次」用 una vez al mes。vez 是阴性名词，所以用 una；频率用 al + 时间段。'),
        ('___ los días desayuno a las siete.', ['Todos', 'Todas', 'Cada', 'Siempre'], 0,
         'todos los días ＝ 每天。días 是阳性复数，所以用 todos；cada 后面直接接单数名词（cada día）。'),
    ]),
    ('Gustar 类动词的真正用法', [
        ('___ gustan los libros de historia.', ['Me', 'Yo', 'Mi', 'Mí'], 0,
         'gustar 的主语是被喜欢的事物（los libros），人用与格代词：me gustan。所以动词用复数 gustan。'),
        ('Me ___ el café con leche.', ['gusta', 'gustan', 'gusto', 'gustas'], 0,
         '主语是单数 el café，所以动词用 gusta。判断单复数看的是「被喜欢的东西」，不是人。'),
        ('A ella ___ encantan los gatos.', ['le', 'la', 'lo', 'les'], 0,
         'encantar 与 gustar 用法相同，人用与格代词：a ella le encantan。这里的 a ella 是强调形式。'),
        ('___ duele la cabeza.', ['Me', 'Yo', 'Mí', 'Mi'], 0,
         'doler 也属这一类：主语是 la cabeza，人用与格 me。所以是 me duele，不是 yo dueleo。'),
    ]),
    ('Jugar a + 运动与游戏', [
        ('___ al fútbol los sábados.', ['Juego', 'Jugar', 'Juego a', 'Juega'], 0,
         'jugar 后接运动必须加 a：jugar al fútbol。jugar 词干变化 u→ue：juego, juegas, juega...'),
        ('¿___ tú al tenis?', ['Juegas', 'Juegas a', 'Jugar', 'Jugáis'], 0,
         'tú 对应 juegas。注意 al 已经包含 a + el，所以不再重复写 a。'),
        ('Jugamos ___ cartas después de cenar.', ['a las', 'al', 'a los', 'a la'], 0,
         'cartas 是阴性复数，所以用 a las cartas。jugar a + 定冠词要与所玩事物的性数一致。'),
    ]),
    ('天气的表达', [
        ('Hoy ___ frío, ponte el abrigo.', ['hace', 'es', 'está', 'hay'], 0,
         '天气用 hacer + 名词：hace frío（冷）、hace calor（热）、hace sol（晴）、hace viento（刮风）。'),
        ('En el norte ___ mucho.', ['llueve', 'llover', 'lluevo', 'llueven'], 0,
         'llover（下雨）只有第三人称单数形式 llueve，没有主语。类似的有 nevar → nieva（下雪）。'),
        ('El cielo ___ nublado hoy.', ['está', 'es', 'hace', 'hay'], 0,
         '天气的暂时状态用 estar：el cielo está nublado。对比 el clima es húmedo（气候特征用 ser）。'),
        ('¿Qué tiempo ___ hoy?', ['hace', 'es', 'está', 'hay'], 0,
         '问天气的固定说法是 ¿Qué tiempo hace?。这是 hacer 表天气的典型用法。'),
    ]),
    ('现在进行时 estar + gerundio', [
        ('Ahora ___ estudiando, no me llames.', ['estoy', 'soy', 'tengo', 'hago'], 0,
         '现在进行时用 estar + 副动词：estoy estudiando（我正在学）。estar 按主语变位。'),
        ('¿Qué ___ haciendo?', ['estás', 'eres', 'tienes', 'haces'], 0,
         '问「你正在做什么」用 ¿Qué estás haciendo?。副动词 hacer → haciendo。'),
        ('Los niños ___ jugando en el parque.', ['están', 'son', 'tienen', 'hacen'], 0,
         '第三人称复数用 están。副动词不变位，只随 estar 变化。'),
        ('___ leyendo un libro muy interesante.', ['Estoy', 'Soy', 'Tengo', 'Hay'], 0,
         '第一人称 estoy + leyendo。注意 ir 的副动词是 yendo（不规则），oír → oyendo，leer → leyendo。'),
    ]),
    ('病痛与身体部位', [
        ('___ duele la garganta.', ['Me', 'Yo', 'Mi', 'Mí'], 0,
         'doler 的结构是「身体部位作主语 + 与格代词」：me duele la garganta。部位是单数用 duele。'),
        ('Me duelen ___ pies.', ['los', 'las', 'mis los', 'el'], 0,
         '部位是复数，所以动词用 duelen。说身体部位时用定冠词而不是所有格：me duelen los pies。'),
        ('Tengo ___ , creo que estoy resfriado.', ['tos', 'toser', 'toso', 'la tos'], 0,
         'tener + 病痛名词：tener tos（咳嗽）、tener fiebre（发烧）。注意 tos 前不加冠词。'),
        ('¿Te ___ algo? ¿Quieres una aspirina?', ['duele', 'duelen', 'doler', 'dolía'], 0,
         '问对方「哪里疼」用 ¿Te duele algo?。主语是 algo（单数），所以用 duele。'),
    ]),
    ('义务与必要性的表达', [
        ('___ que estudiar más.', ['Tengo', 'Soy', 'Estoy', 'Hay'], 0,
         'tener que + 不定式表个人必须：tengo que estudiar。tener 按主语变位。'),
        ('___ que respetar las normas.', ['Hay', 'Tiene', 'Tengo', 'Es'], 0,
         'hay que + 不定式表泛泛的必要（无人称，无主语）：hay que respetar。与 tener que 的区别在于是否有具体承担者。'),
        ('No ___ fumar aquí.', ['se debe', 'se deben', 'se debe que', 'se deber'], 0,
         '禁止用 no se debe + 不定式，或 no se puede。动词固定第三人称单数，因为是无施动者的规定。'),
        ('___ llegar puntual a la entrevista.', ['Deberías', 'Deber', 'Debes que', 'Debiendo'], 0,
         '条件式 deberías 表委婉建议（你应该……），比 debes 更客气。这是职场与礼貌场合的常用说法。'),
    ]),
    ('Llevar + 衣物与穿戴', [
        ('Hoy ___ un abrigo nuevo.', ['llevo', 'llevas', 'lleva', 'llevamos'], 0,
         'llevar + 衣物表「穿着、戴着」：llevo un abrigo。这是描述穿着的常用动词。'),
        ('¿___ tú gafas?', ['Llevas', 'Llevo', 'Lleva', 'Lleváis'], 0,
         'tú 对应 llevas。llevar 是规则 -ar 动词，变位无词干变化。'),
        ('Ella ___ una falda azul.', ['lleva', 'llevo', 'llevas', 'llevan'], 0,
         '第三人称单数 lleva。注意区分 llevar（穿着/携带）与 ponerse（穿上，表动作）。'),
        ('___ puesto el cinturón, por favor.', ['Lleva', 'Llevas', 'Llevar', 'Llevo'], 0,
         'llevar puesto 表「（保持）戴着/系着」的状态：lleva puesto el cinturón。这里是对第三人称的嘱咐。'),
    ]),
    ('表达位置与距离', [
        ('El banco está ___ del mercado.', ['al lado', 'en lado', 'a lado', 'de lado'], 0,
         'al lado de ＝ 在……旁边。这是表位置的固定短语，介词搭配不能改。'),
        ('Mi casa está ___ de aquí.', ['cerca', 'cercano', 'cerca a', 'cercas'], 0,
         'cerca de ＝ 在……附近。注意是 cerca de，不是 cerca a（这是常见错误）。'),
        ('La estación está ___ lejos.', ['muy', 'mucho', 'mucha', 'más mucho'], 0,
         'far 的程度用 muy 修饰：muy lejos。mucho 修饰动词（trabajo mucho），muy 修饰形容词/副词。'),
        ('¿___ está la parada de autobús?', ['Dónde', 'Cuándo', 'Cómo', 'Quién'], 0,
         '问位置用 dónde。estar 表位置：¿Dónde está...?。注意与 hay 的区别：hay 表存在，está 表具体位置。'),
    ]),
    ('钱与支付的表达', [
        ('¿___ pagar con tarjeta?', ['Puedo', 'Puede que', 'Puedo que', 'Poder'], 0,
         '询问可否用 poder 第一人称：¿Puedo pagar con tarjeta?。poder + 不定式表请求许可。'),
        ('El libro ___ diez euros.', ['cuesta', 'costa', 'cuestan', 'cuesta que'], 0,
         '说价格用 costar + 金额：cuesta diez euros。costar 词干变化 o→ue，主语是物品。'),
        ('Me ___ veinte euros.', ['debes', 'debes que', 'deber', 'debes a'], 0,
         'deber + 金额表「欠（钱）」：me debes veinte euros。注意 cobrar 是「收钱」，方向相反。'),
        ('Voy a pagar ___ plazos.', ['a', 'en', 'por', 'de'], 0,
         'a plazos ＝ 分期付款。这是固定说法，介词固定用 a。'),
    ]),
    ('Antes de / después de / al + 不定式', [
        ('___ de salir, apaga las luces.', ['Antes', 'Después', 'Al', 'Luego'], 0,
         'antes de + 不定式表「在……之前」：antes de salir。注意 de 不能省略。'),
        ('___ de cenar, vimos una película.', ['Después', 'Antes', 'Al', 'Durante'], 0,
         'después de + 不定式表「在……之后」：después de cenar。两个短语结构对称，只是时间方向相反。'),
        ('___ llegar a casa, me llamó.', ['Al', 'Antes', 'Después', 'En'], 0,
         'al + 不定式表「当……的时候（一……就）」：al llegar ＝ 到达时。这是西语非常高频的结构。'),
        ('___ de comer, tomamos café.', ['Después', 'Antes', 'Al', 'Para'], 0,
         'después de comer 表饭后。注意与 al comer（吃饭时）的语义差别。'),
    ]),
    ('Pagar / cobrar / deber 的区分', [
        ('Yo ___ el alquiler cada mes.', ['pago', 'cobro', 'debo', 'presto'], 0,
         'pagar ＝ 付钱（钱出去）。主语是付款人：yo pago el alquiler。'),
        ('Yo ___ mi sueldo el día uno.', ['cobro', 'pago', 'debo', 'presto'], 0,
         'cobrar ＝ 收钱（钱进来）。方向与 pagar 完全相反，这是最常混淆的一对。'),
        ('Te ___ diez euros del café de ayer.', ['debo', 'pago', 'cobro', 'presto'], 0,
         'deber ＝ 欠（钱）。te debo ＝ 我欠你。注意 prestar 是「借出」，pedir prestado 是「借入」。'),
        ('¿Me ___ diez euros hasta mañana?', ['prestas', 'debes', 'pagas', 'cobras'], 0,
         'prestar ＝ 借出（借给别人）。¿Me prestas...? ＝ 你能借我……吗？方向是「你给我」。'),
    ]),
]
