# -*- coding: utf-8 -*-
"""批次 41：补齐剩余可出题的语法点（16 组 / 64 题）

把 audit-gaps 报出的 38 个「无对应练习」逐个分类后，其中约 17 组是
真正可出题的语法结构，本批覆盖。与单元主题绑定的具体表达
（如「与艺术评论相关的表达」）不硬拆成选择题。
"""
GROUPS = [
    ('国家与语言名词', [
        ('Soy ___ China, de Shanghái.', ['de', 'en', 'a', 'desde'], 0,
         'ser de + 地点表籍贯来源。用 en 会变成「我在中国」，不表来源。'),
        ('Ella ___ tres idiomas.', ['habla', 'dice', 'cuenta', 'habla en'], 0,
         '说某种语言用 hablar + 语言名，不加介词：habla inglés / habla tres idiomas。'),
        ('Vivo en Francia, pero soy ___.', ['francés', 'Francia', 'francés de Francia', 'de francés'], 0,
         '国籍用形容词 francés；国名 Francia。中文说「我是法国（人）」，西语必须用国籍形容词。'),
        ('¿___ dónde eres?', ['De', 'En', 'A', 'Desde'], 0,
         '问籍贯固定用 ¿De dónde eres?。dónde 前的 de 不能省略。'),
        ('El inglés y el alemán son ___ europeas.', ['lenguas', 'idiomas europeos', 'lengua', 'idioma'], 0,
         'lenguas 是阴性复数，与 europeas 一致。idioma 虽指语言但是阳性，且此处需复数。'),
    ]),
    ('颜色词的特殊用法', [
        ('Tiene el pelo ___.', ['negro', 'negra', 'negros', 'negras'], 0,
         'pelo 是阳性单数，颜色词用 negro。注意西语说「他有黑头发」用 tener + 定冠词 + 名词 + 颜色。'),
        ('Lleva una camisa ___.', ['azul', 'azula', 'azules', 'azulas'], 0,
         'azul 是单复数同形（azul / azules），没有 azula 这种阴性形式。以 -e、-l、-z 等结尾的颜色词多数不变性。'),
        ('Los ojos ___ son poco comunes.', ['verdes', 'verde', 'verdes de', 'verdoso'], 0,
         'ojos 是阳性复数，颜色词用 verdes。'),
        ('Es de color ___.', ['vino', 'vina', 'vinos', 'al vino'], 0,
         'de color + 名词是固定结构（de color vino ＝ 酒红色），后面的名词不变。'),
        ('La puerta está ___.', ['pintada de blanco', 'pintada blanco', 'pintada en blanco', 'pintando blanco'], 0,
         '「被漆成白色」用 pintada de + 颜色。estar + 分词表结果状态，介词 de 引出颜色。'),
    ]),
    ('服务场景常用句式', [
        ('¿___ trae la carta, por favor?', ['Me', 'Mi', 'Yo', 'Mí'], 0,
         '¿Me trae...? 是请服务员拿东西的客气说法，用与格代词 me。'),
        ('¿___ algo más? —No, gracias.', ['Desea', 'Deseo', 'Deseas', 'Desean'], 0,
         '服务员问「还要别的吗」用 usted 形式 ¿Desea algo más?。'),
        ('¿Puedo ___ con tarjeta?', ['pagar', 'pago', 'pagando', 'que pagar'], 0,
         'poder + 不定式表请求许可：¿Puedo pagar con tarjeta?。'),
        ('¿Me lo puede ___ en una bolsa?', ['poner', 'pongo', 'poniendo', 'puesto'], 0,
         'poder + 不定式。购物时请店员装袋的常用说法。'),
        ('Estoy mirando, ___.', ['gracias', 'por favor', 'de nada', 'perdone'], 0,
         '「我只是看看，谢谢」是店员询问后顾客的固定应答，用 gracias 收尾。'),
    ]),
    ('电话用语', [
        ('¿___? Soy Ana.', ['Diga', 'Dice', 'Digo', 'Diciendo'], 0,
         '接电话说 ¿Diga?（喂）。这是西班牙固定用法，相当于英文的 hello。'),
        ('¿Puedo hablar ___ el señor López?', ['con', 'a', 'de', 'en'], 0,
         'hablar con alguien ＝ 与某人通话。hablar de 是「谈论」，语义不同。'),
        ('Se ha ___, vuelva a llamar.', ['cortado', 'cortar', 'cortando', 'corte'], 0,
         '「通话中断了」用 se ha cortado（haber + 分词）。cortarse 表通话被切断。'),
        ('¿Me pone con el departamento de ventas?', ['poner', 'pongo', 'puesto', 'poniendo'], 0,
         '¿Me pone con...? ＝ 能帮我转接到……吗？poner con 是转接的固定说法。'),
        ('Le llamo ___ parte del director.', ['de', 'en', 'por', 'a'], 0,
         'de parte de ＝ 代表某人、受某人所托。这是转达来电缘由的固定短语。'),
    ]),
    ('表目的的表达', [
        ('Estudio español ___ trabajar en España.', ['para', 'por', 'porque', 'para que'], 0,
         'para + 不定式表目的，且主从句主语相同。porque 后须接完整句子。'),
        ('Te lo digo ___ lo sepas.', ['para que', 'para', 'porque', 'por'], 0,
         'para que + 虚拟式：主从句主语不同时，目的从句用 para que 加虚拟式。'),
        ('Salí temprano ___ no llegar tarde.', ['para', 'por', 'por que', 'para que'], 0,
         '否定目的用 para no + 不定式。para que 后面要接从句，不能直接接不定式。'),
        ('Lo hice ___ ayudarte.', ['para', 'por', 'porque', 'a fin que'], 0,
         '表目的用 para + 不定式。por + 不定式通常表原因。'),
        ('A fin ___ que todos participen, cambiaremos el horario.', ['de', 'a', 'en', 'por'], 0,
         'a fin de que + 虚拟式是较正式的目的小句连接语。'),
    ]),
    ('金钱表达与小数', [
        ('Cuesta un euro ___ cincuenta.', ['con', 'y', 'de', 'punto'], 0,
         '西语小数用 con 连接整数与小数部分：un euro con cincuenta。也可以说 un euro cincuenta。'),
        ('Son mil ___ euros.', ['doscientos', 'dosciento', 'doscientas', 'dos cientos'], 0,
         'cientos 与数字连写：doscientos。euros 是阳性，用 doscientos。'),
        ('Un millón ___ euros es mucho dinero.', ['de', 'en', 'a', '—'], 0,
         'millón 后面必须加 de：un millón de euros。这是与 mil 的重要区别（mil euros 不加 de）。'),
        ('Cuesta veinte euros ___ con cincuenta.', ['y', 'con', 'punto', 'coma'], 0,
         '整数后面接小数用 y（veinte y cincuenta）或直接说 veinte con cincuenta。'),
        ('¿Me lo deja más ___?', ['barato', 'barata', 'baratos', 'barate'], 0,
         '问能否便宜点用 más barato（价钱是阳性的默认形式）。这是市场议价的常用说法。'),
    ]),
    ('相互动作的表达', [
        ('Ana y Luis ___ mucho.', ['se quieren', 'quieren', 'se quiere', 'quieren se'], 0,
         '相互动作用复数自复代词 se + 复数动词：se quieren ＝ 他们彼此相爱。'),
        ('Mi hermano y yo ___ por teléfono cada día.', ['nos hablamos', 'nos habla', 'hablamos nos', 'se hablamos'], 0,
         '第一人称复数相互动作用 nos + 复数动词：nos hablamos。'),
        ('Se ___ flores el uno al otro.', ['regalan', 'regala', 'regalan se', 'regalando'], 0,
         '用 el uno al otro 加强相互意义时，动词仍按复数变位：se regalan。'),
        ('No ___ hablan desde el verano.', ['se', 'nos', 'les', 'los'], 0,
         '第三人称复数的相互动作用 se：no se hablan（他们互相不说话了）。'),
        ('Se ___ a la entrada del cine.', ['encontraron', 'encontró', 'encontraron se', 'encontraba'], 0,
         '相遇用 encontrarse，复数为 se encontraron。注意简单过去时表一次性事件。'),
    ]),
    ('时态分工（方法与结果）', [
        ('El estudio se ___ con 200 participantes.', ['realizó', 'realiza', 'realizará', 'realizaría'], 0,
         '描述研究方法与过程用过去时（se realizó）。这是学术写作的固定分工。'),
        ('Los resultados ___ que la hipótesis es correcta.', ['muestran', 'mostraron', 'mostraban', 'mostrarían'], 0,
         '陈述研究发现与结论用现在时（muestran）。结果被视为对当下有效的论断。'),
        ('En la sección anterior ___ el marco teórico.', ['presentamos', 'presentamos que', 'presentando', 'presentar'], 0,
         '交代论文各部分的动作常用第一人称复数或无人称过去时。presentamos 是标准的论文用语。'),
        ('La muestra ___ de 300 textos.', ['constó', 'consta de siempre', 'constaba de que', 'constando'], 0,
         '描述已完成的取样用过去时 constó de。注意 constar de 是固定搭配。'),
        ('Estos datos ___ con los de estudios previos.', ['concuerdan', 'concordaron', 'concuerdan de', 'concordando'], 0,
         '讨论部分用现在时表达普遍的相符关系。concordar con 是固定搭配。'),
    ]),
    ('局限性与展望的固定表述', [
        ('Entre las ___ del estudio cabe mencionar el tamaño de la muestra.', ['limitaciones', 'limitación', 'limitado', 'limitar'], 0,
         '限制条件用复数名词 limitaciones。这是论文「局限性」一节的标准开头。'),
        ('Futuras investigaciones ___ abordar esta cuestión.', ['deberían', 'debían', 'deben que', 'debieron'], 0,
         '展望用条件式 deberían（应当会），语气克制，表示建议而非规定。'),
        ('Los resultados deben tomarse con ___.', ['cautela', 'cauteloso', 'cautelar', 'cautelas'], 0,
         'con cautela ＝ 谨慎地。这是论文结论中常见的保留表述。'),
        ('No es posible ___ estos resultados a otras poblaciones.', ['generalizar', 'generaliza', 'generalizando', 'generalizado'], 0,
         'es posible + 不定式。generalizar a ＝ 推广到，是讨论外部效度的固定动词。'),
        ('Queda ___ para futuros trabajos.', ['pendiente', 'pendientes', 'pender', 'pendiendo'], 0,
         'quedar pendiente ＝ 留待日后处理。这是论文结尾的常用句式。'),
    ]),
]
