#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批次 64：A2 补 2 个单元（叙事连词与话语标记 / 过去时对比与时间表达）

为什么补这两个：A2 的 17 个单元里，词汇集中在话题词（家庭、购物、旅行…），
但几乎没有「语法功能词」单元。连词与时间标记词是 A2→B1 最关键的台阶：
学习者常常话题词都会，却串不成一段连贯的叙述。
  - 叙事连词与话语标记：写作与口语衔接的骨架
  - 过去时对比与时间表达：imperfecto 与 indefinido 的标记词体系
     （A2 已有「谈论过去」，但只讲了简单过去时，没有两者的对比体系）

所有词头已用全库比对校验：与现有 5400+ 词条零重复（含仅冠词/大小写不同的情况）。
"""

BATCH = {
    'A2': [
        {
            'id': 'a2-u21', 'title': '叙事连词与话语标记', 'subtitle': 'Conectores y Marcadores del Discurso',
            'lessons': 10, 'duration': '约 40 分钟',
            'vocab': [
                ('El conector', '连接词', 'Un conector une ideas dentro del texto.'),
                ('La conjunción', '连词', 'La conjunción une palabras o frases.'),
                ('El marcador temporal', '时间标记词', 'El marcador temporal sitúa la acción.'),
                ('La secuencia', '顺序', 'La secuencia ordena los hechos.'),
                ('El orden cronológico', '时间顺序', 'El orden cronológico sigue las fechas.'),
                ('En primer lugar', '首先', 'En primer lugar, quiero agradecer su ayuda.'),
                ('A continuación', '接下来', 'A continuación, veremos un ejemplo.'),
                ('Poco después', '不久之后', 'Llegó el autobús poco después.'),
                ('Al mismo tiempo', '与此同时', 'Estudiaba y trabajaba al mismo tiempo.'),
                ('Mientras tanto', '在这期间', 'Yo cocinaba; mientras tanto, él ponía la mesa.'),
                ('Entretanto', '在此期间（书面）', 'Entretanto, la situación había cambiado.'),
                ('Al cabo de', '在……之后', 'Al cabo de dos horas salimos.'),
                ('Al final', '最终', 'Al final decidimos quedarnos.'),
                ('Finalmente', '最后', 'Finalmente encontramos la salida.'),
                ('Por último', '最后一点', 'Por último, una recomendación.'),
                ('Para terminar', '最后（收尾）', 'Para terminar, una pregunta.'),
                ('En resumen', '总之', 'En resumen, el plan funcionó.'),
                ('Por cierto', '顺便说一句', 'Por cierto, ¿viste mi mensaje?'),
                ('A propósito', '顺便一提', 'A propósito, felicidades por el trabajo.'),
                ('Por lo visto', '看来', 'Por lo visto, ya lo sabían.'),
                ('Al parecer', '据说、看来', 'Al parecer, el vuelo se retrasó.'),
                ('Desde luego', '当然（强调）', 'Desde luego que te ayudaré.'),
                ('En cambio', '相反（对比）', 'Yo prefiero el té; en cambio, ella toma café.'),
                ('De todos modos', '无论如何', 'De todos modos, avísame.'),
                ('De todas formas', '不管怎样', 'De todas formas, gracias.'),
                ('En cualquier caso', '无论如何（书面）', 'En cualquier caso, decide tú.'),
                ('Ya que', '既然', 'Ya que estás aquí, ayúdame.'),
                ('Dado que', '鉴于', 'Dado que no hay tiempo, empezamos.'),
                ('Debido a', '由于', 'Debido a la lluvia, no salimos.'),
                ('Gracias a', '多亏', 'Gracias a tu ayuda, terminé a tiempo.'),
                ('Con el fin de', '为了（正式）', 'Con el fin de ahorrar, apagamos las luces.'),
                ('En caso de que', '万一（+虚拟式）', 'En caso de que llueva, avísame.'),
                ('A no ser que', '除非（+虚拟式）', 'Iremos a la playa, a no ser que llueva.'),
                ('O sea', '也就是说', 'Es tarde, o sea, vámonos.'),
                ('Es decir', '即、也就是说', 'Somos cinco, es decir, falta uno.'),
                ('En otras palabras', '换句话说', 'En otras palabras, no estás de acuerdo.'),
                ('Por un lado', '一方面', 'Por un lado, es caro.'),
                ('Por otro lado', '另一方面', 'Por otro lado, es muy útil.'),
                ('En cuanto a', '关于', 'En cuanto al precio, hablamos mañana.'),
                ('Sobre todo', '尤其是', 'Me gustan las frutas, sobre todo el mango.'),
                ('En concreto', '具体来说', 'Quiero uno en concreto: ese.'),
                ('Es más', '而且（递进）', 'Es más, te lo puedo prestar.'),
            ],
            'grammar': [
                {'title': '叙事顺序的连接词', 'desc': '表时间推进：en primer lugar / a continuación / poco después / mientras tanto / al cabo de / finalmente。注意 al cabo de 后面接时间段（al cabo de dos horas），al final 表「最终」。'},
                {'title': '对比与递进的连接词', 'desc': '对比：en cambio / por el contrario / de todos modos。递进：es más / además / encima。注意 en cambio 与 por el contrario 都表对比，但后者更书面。'},
                {'title': '原因、目的与条件的连接', 'desc': '原因：ya que / dado que / debido a / gracias a。目的：con el fin de + 不定式。条件：en caso de que / a no ser que / con tal de que 后面都接虚拟式。'},
            ],
        },
        {
            'id': 'a2-u22', 'title': '过去时对比与时间表达', 'subtitle': 'Contraste de Pasados y Expresiones de Tiempo',
            'lessons': 10, 'duration': '约 40 分钟',
            'vocab': [
                ('La acción puntual', '一次性动作', 'La acción puntual ocurrió una sola vez.'),
                ('La acción habitual', '习惯性动作', 'La acción habitual se repite en el pasado.'),
                ('La acción en curso', '正在进行的动作', 'La acción en curso se describe con imperfecto.'),
                ('La circunstancia', '背景情况', 'La circunstancia describe el ambiente.'),
                ('El marco temporal', '时间框架', 'El marco temporal sitúa la escena.'),
                ('El fondo de la narración', '叙事背景', 'El fondo de la narración usa imperfecto.'),
                ('El primer plano', '前景事件', 'El primer plano usa indefinido.'),
                ('La secuencia narrativa', '叙事顺序', 'La secuencia narrativa alterna los dos tiempos.'),
                ('La anécdota', '小故事、轶事', 'Contó una anécdota de su viaje.'),
                ('La rutina pasada', '过去的日常', 'La rutina pasada se cuenta en imperfecto.'),
                ('La etapa', '阶段', 'En aquella etapa estudiaba música.'),
                ('El periodo', '时期', 'Fue un periodo muy tranquilo.'),
                ('La temporada', '季节、档期', 'Pasamos una temporada en la costa.'),
                ('En aquella época', '在那个年代', 'En aquella época no había internet.'),
                ('Por aquel entonces', '那时候', 'Por aquel entonces vivíamos en el campo.'),
                ('En aquellos años', '那些年', 'En aquellos años todo era más lento.'),
                ('De niño', '小时候', 'De niño jugaba en la calle.'),
                ('De joven', '年轻时', 'De joven trabajé de camarero.'),
                ('Cuando era niño', '我小时候', 'Cuando era niño vivía con mis abuelos.'),
                ('Todos los días', '每天', 'Todos los días iba andando al colegio.'),
                ('Cada verano', '每年夏天', 'Cada verano íbamos a la playa.'),
                ('De vez en cuando', '偶尔', 'De vez en cuando nos veíamos.'),
                ('Rara vez', '很少', 'Rara vez llegaba tarde.'),
                ('Una vez', '有一次', 'Una vez perdí el tren.'),
                ('La primera vez', '第一次', 'La primera vez fue en 2010.'),
                ('La última vez', '最后一次', 'La última vez hablamos en mayo.'),
                ('Aquella mañana', '那天早上', 'Aquella mañana hacía mucho frío.'),
                ('Esa tarde', '那天下午', 'Esa tarde terminamos el trabajo.'),
                ('Ese mismo día', '就在那天', 'Ese mismo día recibió la noticia.'),
                ('Al día siguiente', '第二天', 'Al día siguiente volvimos.'),
                ('La semana anterior', '前一周', 'La semana anterior había llovido.'),
                ('Hace dos años', '两年前', 'Hace dos años me mudé aquí.'),
                ('Hace mucho tiempo', '很久以前', 'Hace mucho tiempo vivía en Sevilla.'),
                ('Justo cuando', '正当……的时候', 'Justo cuando salía, sonó el teléfono.'),
                ('En cuanto', '一……就', 'En cuanto llegó, empezamos.'),
                ('Tan pronto como', '一……就（书面）', 'Tan pronto como terminó, se fue.'),
                ('Apenas', '刚……就', 'Apenas había salido cuando empezó a llover.'),
                ('A medida que', '随着', 'A medida que pasaba el tiempo, mejoraba.'),
                ('Conforme', '随着（书面）', 'Conforme avanzaba el curso, entendía más.'),
                ('De pronto', '突然', 'De pronto se apagó la luz.'),
                ('De golpe', '一下子', 'De golpe se puso a llover.'),
                ('Súbitamente', '突然（书面）', 'Súbitamente, todo cambió.'),
                ('Inesperadamente', '出乎意料地', 'Inesperadamente, ganó el premio.'),
                ('Acto seguido', '紧接着', 'Acto seguido, se marchó.'),
                ('Al rato', '过了一会儿', 'Al rato volvió con café.'),
                ('Lentamente', '缓慢地', 'Lentamente, la puerta se abrió.'),
                ('Progresivamente', '逐步地', 'Progresivamente, mejoró su nivel.'),
                ('De un día para otro', '一夜之间', 'De un día para otro, todo cambió.'),
                ('Desde entonces', '从那以后', 'Desde entonces no lo he visto.'),
                ('A partir de entonces', '从那时起', 'A partir de entonces estudió más.'),
                ('Hasta entonces', '在那之前', 'Hasta entonces nunca había viajado.'),
                ('Más adelante', '后来', 'Más adelante te lo cuento.'),
            ],
            'grammar': [
                {'title': '简单过去时 vs 未完成过去时', 'desc': '未完成过去时（imperfecto）画背景、写习惯、描述状态：De niño jugaba en la calle / Aquella mañana hacía frío。简单过去时（indefinido）推动情节、写一次性事件：Ese día salí temprano / De pronto se apagó la luz。两者常在同一段交替出现。'},
                {'title': '时间标记词决定时态', 'desc': 'hace dos años / el año pasado / una vez / aquella mañana → 简单过去时。todos los días / cada verano / de niño / siempre → 未完成过去时。看到标记词就能先定时态，这是 A2 最实用的判断法。'},
                {'title': '叙事中的时间衔接', 'desc': 'en cuanto / tan pronto como / apenas + 过去时表「一……就」。注意 apenas había salido cuando… 用「过去完成时 + cuando + 简单过去时」表示「刚……就……」。'},
            ],
        },
    ],
}
