# -*- coding: utf-8 -*-
"""批次 47：B1 补两个单元（消费与理财 / 旅行与文化）

B1 词汇 606 是六个等级里最低的（B2 639 / C2 623 / C1 606 / B1 606）。
目标第三阶段明确要求「A1/A2/B1 词汇」扩充。
选题避开 B1 已有的 13 个单元主题（工作/环境/科技/艺术/健康/租房/情绪/
城市/教育/媒体/数字生活），选日常高频但尚未覆盖的两块。
"""

BATCH = {
    'B1': [
        {
            'id': 'b1-u14',
            'title': '消费与理财',
            'subtitle': 'Consumo y Finanzas Personales',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('El presupuesto', '预算', 'Hago un presupuesto mensual.'),
                ('Los ingresos', '收入', 'Sus ingresos no cubren los gastos.'),
                ('Los gastos', '支出', 'Los gastos fijos son la mitad del sueldo.'),
                ('El ahorro', '储蓄', 'Destino un diez por ciento al ahorro.'),
                ('La deuda', '债务', 'Tardó años en pagar la deuda.'),
                ('El préstamo', '贷款', 'Pidió un préstamo para el coche.'),
                ('La hipoteca', '房贷', 'La hipoteca sube cada año.'),
                ('El interés', '利息', 'El interés del préstamo es alto.'),
                ('La cuota', '月供、分摊费', 'La cuota mensual es de cuatrocientos euros.'),
                ('El recibo', '账单', 'El recibo de la luz llegó caro.'),
                ('La factura', '发票、账单', 'Guarda la factura por si acaso.'),
                ('El descuento', '折扣', 'Aproveché el descuento de enero.'),
                ('La oferta', '特价、优惠', 'Había una oferta muy buena.'),
                ('El precio', '价格', 'El precio ha subido bastante.'),
                ('El coste', '成本、费用', 'El coste de la vida ha subido.'),
                ('El gasto fijo', '固定支出', 'Los gastos fijos no se pueden recortar.'),
                ('El gasto imprevisto', '意外支出', 'Tuve un gasto imprevisto.'),
                ('El saldo', '余额', 'Consulta el saldo antes de pagar.'),
                ('La transferencia', '转账', 'Hice una transferencia al casero.'),
                ('El plazo', '期限、分期', 'Lo pagué a plazos sin intereses.'),
                ('La nómina', '工资单', 'Cobro la nómina el día veinticinco.'),
                ('La cotización', '社保缴费', 'La cotización depende del salario.'),
                ('La pensión', '养老金', 'Su pensión es bastante baja.'),
                ('El subsidio', '补贴、救济金', 'Recibió un subsidio temporal.'),
                ('La renta', '收入、所得', 'La renta media de la zona es alta.'),
                ('El patrimonio', '财产', 'Heredó un patrimonio modesto.'),
                ('La inversión', '投资', 'Es una inversión a largo plazo.'),
                ('El riesgo', '风险', 'Toda inversión tiene riesgo.'),
                ('El beneficio', '利润、收益', 'Obtuvo un beneficio pequeño.'),
                ('La pérdida', '亏损', 'La empresa sufrió pérdidas.'),
                ('El impuesto', '税', 'Los impuestos subieron este año.'),
                ('La declaración', '申报', 'Presenté la declaración en abril.'),
                ('El fraude', '欺诈', 'Fue víctima de un fraude.'),
                ('La estafa', '诈骗', 'Cuidado con las estafas por internet.'),
                ('La garantía', '保修、保证', 'El producto tiene dos años de garantía.'),
                ('La devolución', '退货、退款', 'Pidió la devolución del importe.'),
                ('El reembolso', '报销、退款', 'El reembolso tarda una semana.'),
                ('La suscripción', '订阅', 'Cancelé la suscripción al mes.'),
                ('El gasto hormiga', '零散小额开销', 'Los gastos hormiga se acumulan.'),
                ('La cesta de la compra', '购物篮（生活成本）', 'La cesta de la compra se ha encarecido.'),
                ('Ahorrar', '储蓄', 'Ahorro para un viaje largo.'),
                ('Gastar', '花费', 'Gastamos demasiado en restaurantes.'),
                ('Invertir', '投资', 'Invirtió en formación.'),
                ('Endeudarse', '负债', 'Se endeudó para estudiar.'),
                ('Prestar', '借出', 'Me prestó dinero sin intereses.'),
                ('Pedir prestado', '借入', 'Pedí prestado a un amigo.'),
                ('Deber', '欠（钱）', 'Le debo veinte euros.'),
                ('Cobrar', '收取、领薪', 'Cobramos a final de mes.'),
                ('Pagar a plazos', '分期付款', 'Pagó la lavadora a plazos.'),
                ('Recortar gastos', '削减开支', 'Tuvimos que recortar gastos.'),
                ('Llegar a fin de mes', '勉强度日', 'Cada vez cuesta más llegar a fin de mes.'),
                ('Ajustarse al presupuesto', '控制在预算内', 'Intento ajustarme al presupuesto.'),
                ('Salir caro', '代价高', 'Ese error nos salió caro.'),
                ('Valer la pena', '值得', 'El esfuerzo valió la pena.'),
                ('Merecer la pena', '值得（同义）', 'Merece la pena invertir ahora.'),
                ('Correr el riesgo', '冒险', 'No vale la pena correr ese riesgo.'),
            ],
            'grammar': [
                {'title': '表「花费」的动词辨析', 'desc': 'gastar（花钱，主语是人）/ costar（值多少钱，主语是物）/ pagar（支付）/ cobrar（收取）。中文都说「花」，西语按视角分工：Me costó caro（这让我付了高价，主语是事）。'},
                {'title': '「省钱」与「够用」的固定表达', 'desc': 'llegar a fin de mes（勉强度日）、ajustarse al presupuesto（控制在预算内）、recortar gastos（削减开支）、los gastos hormiga（零散小额开销）。这些是西语谈论个人财务的常用语块，比直译更自然。'},
                {'title': '数字与百分比的表达', 'desc': 'un diez por ciento（百分之十）、la mitad de（一半）、un tercio de（三分之一）。注意百分比前不加 de 的场合：subió un 5 %（上涨 5%），而 el 5 % de los hogares（5% 的家庭）中要加 de。'},
            ],
        },
        {
            'id': 'b1-u15',
            'title': '旅行与文化体验',
            'subtitle': 'Viajes y Experiencia Cultural',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('El destino', '目的地', 'Elegimos un destino tranquilo.'),
                ('El itinerario', '行程', 'El itinerario incluye tres ciudades.'),
                ('La excursión', '短途游览', 'Hicimos una excursión al lago.'),
                ('El alojamiento', '住宿', 'El alojamiento estaba incluido.'),
                ('El hostal', '旅馆', 'Dormimos en un hostal del centro.'),
                ('El albergue', '青年旅舍', 'El albergue era barato y limpio.'),
                ('La pensión', '家庭旅馆', 'Reservamos una pensión familiar.'),
                ('La habitación doble', '双人房', 'Pedimos una habitación doble.'),
                ('La reserva', '预订', 'Confirmé la reserva por correo.'),
                ('La llegada', '抵达', 'La llegada está prevista a las seis.'),
                ('La salida', '出发、离开', 'La salida es a las ocho en punto.'),
                ('El equipaje', '行李', 'Facturé el equipaje en el mostrador.'),
                ('La maleta de mano', '手提行李', 'Solo llevo maleta de mano.'),
                ('El vuelo', '航班', 'El vuelo se retrasó dos horas.'),
                ('La escala', '中转、经停', 'Hicimos escala en Lisboa.'),
                ('El retraso', '延误', 'El retraso nos hizo perder el tren.'),
                ('La cancelación', '取消', 'La cancelación fue por mal tiempo.'),
                ('El seguro de viaje', '旅行保险', 'Contraté un seguro de viaje.'),
                ('La aduana', '海关', 'Pasamos la aduana sin problemas.'),
                ('El mostrador', '柜台', 'Factura en el mostrador número tres.'),
                ('La guía', '导游、指南', 'La guía explicaba la historia del barrio.'),
                ('El monumento', '古迹、纪念建筑', 'El monumento data del siglo doce.'),
                ('El casco antiguo', '老城区', 'El casco antiguo es peatonal.'),
                ('La costumbre', '习俗', 'Es costumbre quitarse los zapatos.'),
                ('La tradición', '传统', 'La tradición se mantiene viva.'),
                ('La artesanía', '手工艺', 'Compré artesanía local.'),
                ('El recuerdo', '纪念品、回忆', 'Traje un recuerdo para todos.'),
                ('La gastronomía', '饮食文化', 'La gastronomía local es excelente.'),
                ('El plato típico', '特色菜', 'Probé el plato típico de la región.'),
                ('La propina', '小费', 'Dejamos una propina generosa.'),
                ('El guía turístico', '导游（人）', 'El guía turístico hablaba cuatro idiomas.'),
                ('El turismo', '旅游业', 'El turismo sostiene la economía local.'),
                ('El viajero', '旅行者', 'El viajero busca experiencias auténticas.'),
                ('La estancia', '逗留', 'Nuestra estancia duró una semana.'),
                ('El trayecto', '路程', 'El trayecto fue largo pero cómodo.'),
                ('La ruta', '路线', 'Seguimos una ruta poco conocida.'),
                ('El paisaje', '风景', 'El paisaje era impresionante.'),
                ('El mirador', '观景台', 'Desde el mirador se ve toda la bahía.'),
                ('La temporada alta', '旺季', 'En temporada alta todo es más caro.'),
                ('La temporada baja', '淡季', 'Viajamos en temporada baja.'),
                ('Recorrer', '走遍、游历', 'Recorrimos la costa en coche.'),
                ('Alojarse', '住宿', 'Nos alojamos en un hotel pequeño.'),
                ('Reservar', '预订', 'Reservé con antelación.'),
                ('Facturar', '托运', 'Hay que facturar antes de las dos horas.'),
                ('Embarcar', '登机', 'Embarcamos por la puerta doce.'),
                ('Aterrizar', '着陆', 'Aterrizamos con veinte minutos de retraso.'),
                ('Hacer escala', '中转', 'Hicimos escala en Estambul.'),
                ('Perderse', '迷路、错过', 'Nos perdimos en el casco antiguo.'),
                ('Disfrutar de', '享用、享受', 'Disfrutamos de la gastronomía local.'),
                ('Aprovechar', '利用', 'Aprovechamos para visitar el museo.'),
                ('Valer la pena visitar', '值得一游', 'Vale la pena visitar el monasterio.'),
                ('Adaptarse a', '适应', 'Cuesta adaptarse a las costumbres locales.'),
                ('Sorprenderse de', '对……感到惊讶', 'Me sorprendí de la hospitalidad.'),
                ('Enriquecerse con', '因……而丰富', 'Uno se enriquece con otros modos de vida.'),
                ('Volver con ganas de', '回来时想……', 'Volví con ganas de repetir.'),
            ],
            'grammar': [
                {'title': '表「出发与到达」的动词搭配', 'desc': 'salir de（从某地出发）/ llegar a（到达某地）/ irse de viaje（出远门）/ volver de（从某地回来）。注意 salir para + 目的地 与 salir de + 出发地 的区别。'},
                {'title': '预订与取消的礼貌表达', 'desc': 'Quisiera reservar... / ¿Sería posible cambiar la reserva? / Lamento tener que cancelar... 旅行场景中提出请求或取消时，用条件式比直接命令式得体得多。'},
                {'title': '无人称 se 在旅行说明中的用法', 'desc': 'Se ruega puntualidad / No se permite el acceso con comida / Se recomienda reservar con antelación。告示类文本用无人称 se，学习者需要能读懂这类句式。'},
            ],
        },
    ],
}
