# -*- coding: utf-8 -*-
"""批次 26：A1 扩充（家庭与人物 / 衣服与购物）"""

BATCH = {
    'A1': [
        {
            'id': 'a1-u10',
            'title': '家庭成员与人物',
            'subtitle': 'La Familia y las Personas',
            'lessons': 10,
            'duration': '约 35 分钟',
            'vocab': [
                ('La familia', '家庭', 'Mi familia es pequeña.'),
                ('El padre', '父亲', 'Mi padre trabaja en un banco.'),
                ('La madre', '母亲', 'Mi madre es profesora.'),
                ('El hijo', '儿子', 'Tienen dos hijos.'),
                ('La hija', '女儿', 'Su hija estudia medicina.'),
                ('El niño', '男孩', 'El niño juega en el parque.'),
                ('La niña', '女孩', 'La niña lee un cuento.'),
                ('El bebé', '婴儿', 'El bebé duerme ahora.'),
                ('El chico', '小伙子', 'Ese chico es mi vecino.'),
                ('La chica', '姑娘', 'La chica del mostrador es amable.'),
                ('El hombre', '男人', 'Ese hombre es mi tío.'),
                ('La mujer', '女人', 'La mujer del abrigo rojo es Ana.'),
                ('El señor', '先生', 'El señor García trabaja aquí.'),
                ('La señora', '女士', 'La señora López es nuestra vecina.'),
                ('El amigo', '朋友（男）', 'Mi amigo vive en Sevilla.'),
                ('La amiga', '朋友（女）', 'Mi amiga estudia inglés.'),
                ('El compañero', '同事 / 同学', 'Mi compañero de piso es italiano.'),
                ('El jefe', '上司', 'Mi jefe es muy exigente.'),
                ('El vecino', '邻居', 'El vecino del tercero es simpático.'),
                ('La gente', '人们', 'Aquí hay mucha gente.'),
                ('Alto', '高的', 'Mi hermano es muy alto.'),
                ('Bajo', '矮的', 'Es más bajo que yo.'),
                ('Joven', '年轻的', 'Es un profesor joven.'),
                ('Mayor', '年长的', 'Mi hermana mayor vive en Roma.'),
                ('Rubio', '金发的', 'La niña es rubia.'),
                ('Moreno', '深色头发 / 深肤色的', 'Su novio es moreno.'),
                ('Los ojos', '眼睛', 'Tiene los ojos verdes.'),
                ('El pelo', '头发', 'Lleva el pelo corto.'),
                ('La cara', '脸', 'Tiene una cara simpática.'),
                ('La mano', '手', 'Levanta la mano, por favor.'),
                ('El pie', '脚', 'Me duelen los pies.'),
                ('La cabeza', '头', 'Me duele la cabeza.'),
                ('La boca', '嘴', 'Abre la boca, por favor.'),
                ('La nariz', '鼻子', 'Tiene la nariz pequeña.'),
                ('La oreja', '耳朵', 'Me duelen las orejas.'),
                ('El cuerpo', '身体', 'Hacer deporte es bueno para el cuerpo.'),
                ('Casado', '已婚的', 'Mi tía está casada.'),
                ('Soltero', '未婚的', 'Mi primo sigue soltero.'),
                ('El marido', '丈夫', 'Su marido es arquitecto.'),
                ('La esposa', '妻子', 'Su esposa trabaja en casa.'),
                ('El hijo único', '独生子', 'Es hijo único.'),
                ('La pareja', '伴侣 / 一对', 'Vienen con sus parejas.'),
                ('El grupo', '一群人', 'Un grupo de amigos esperaba fuera.'),
                ('La persona', '人（个体）', 'Es una persona muy amable.'),
                ('El nombre', '名字', '¿Cuál es tu nombre completo?'),
            ],
            'grammar': [
                {'title': '名词的性与数', 'desc': '西语名词分阴阳性：以 -o 结尾多为阳性（el libro），以 -a 结尾多为阴性（la casa）。有例外（el día, la mano）。复数一般加 -s，以辅音结尾加 -es。'},
                {'title': '形容词的位置', 'desc': '限定性形容词通常后置且区分意义（un amigo viejo 老朋友）；非限定性、表评价的形容词前置（un viejo amigo 一位老朋友）。初学阶段可先记住外观描述用后置。'},
                {'title': '物主形容词', 'desc': 'mi / tu / su / nuestro / vuestro / su + 名词。注意 su 既可指「他的」，也可指「她的」「您的」「他们的」，需靠语境判断。物主形容词只随被修饰名词变数：mis libros, nuestras casas。'},
            ],
        },
        {
            'id': 'a1-u11',
            'title': '衣服与购物',
            'subtitle': 'La Ropa y las Compras',
            'lessons': 10,
            'duration': '约 35 分钟',
            'vocab': [
                ('La ropa', '衣服', 'Llevo ropa cómoda.'),
                ('La camisa', '衬衫', 'Esta camisa es de algodón.'),
                ('La camiseta', 'T恤', 'Compré una camiseta negra.'),
                ('El pantalón', '裤子', 'Estos pantalones son largos.'),
                ('Los vaqueros', '牛仔裤', 'Llevo vaqueros casi siempre.'),
                ('La falda', '裙子', 'La falda es azul.'),
                ('El vestido', '连衣裙', 'Ese vestido es muy bonito.'),
                ('El jersey', '毛衣', 'Ponte un jersey, hace frío.'),
                ('El abrigo', '大衣', 'Necesito un abrigo de invierno.'),
                ('La chaqueta', '外套', 'Dejé la chaqueta en casa.'),
                ('El zapato', '鞋', 'Estos zapatos me aprietan.'),
                ('La zapatilla', '运动鞋', 'Uso zapatillas para correr.'),
                ('El calcetín', '袜子', 'Compré tres pares de calcetines.'),
                ('El sombrero', '帽子', 'Lleva un sombrero de paja.'),
                ('La bufanda', '围巾', 'En invierno uso bufanda.'),
                ('El bolso', '包（女用）', 'El bolso es de cuero.'),
                ('La mochila', '背包', 'Mi mochila pesa mucho.'),
                ('El cinturón', '腰带', 'Este cinturón es de piel.'),
                ('El reloj', '手表', 'Me regalaron un reloj.'),
                ('Las gafas', '眼镜', 'Necesito gafas para leer.'),
                ('La talla', '尺码', '¿Tiene una talla más?'),
                ('El color', '颜色', '¿Lo tiene en otro color?'),
                ('De algodón', '棉的', 'Prefiero las camisetas de algodón.'),
                ('De lana', '羊毛的', 'Este jersey es de lana.'),
                ('De cuero', '皮的', 'Los zapatos son de cuero.'),
                ('La tienda', '商店', 'La tienda abre a las diez.'),
                ('El centro comercial', '购物中心', 'Vamos al centro comercial.'),
                ('La rebaja', '打折', 'Compré esto en rebajas.'),
                ('El descuento', '折扣', 'Me hicieron un descuento.'),
                ('La oferta', '特价', 'Hay una oferta muy buena.'),
                ('El precio', '价格', 'El precio me parece alto.'),
                ('Barato', '便宜的', 'Es bastante barato.'),
                ('Caro', '贵的', 'Ese abrigo es muy caro.'),
                ('Gratis', '免费的', 'La entrada es gratis los domingos.'),
                ('Probarse', '试穿', '¿Puedo probármelo?'),
                ('El probador', '试衣间', 'El probador está al fondo.'),
                ('Quedar bien', '合身 / 合适', 'Esta camisa me queda bien.'),
                ('Quedar grande', '太大', 'Me queda grande la talla.'),
                ('Cambiar', '换货', '¿Puedo cambiarlo?'),
                ('Devolver', '退货', 'Quiero devolver esta compra.'),
                ('La caja', '收银台', 'Pague en la caja, por favor.'),
                ('El ticket', '小票', 'Guarde el ticket por si acaso.'),
                ('El escaparate', '橱窗', 'Me gustó el vestido del escaparate.'),
                ('El dependiente', '店员', 'El dependiente fue muy amable.'),
                ('La talla de zapato', '鞋码', 'Calzo un cuarenta y dos.'),
            ],
            'grammar': [
                {'title': '指示形容词', 'desc': 'este/esta/estos/estas（这）、ese/esa/esos/esas（那，离听话人近）、aquel/aquella/aquellos/aquellas（那，离双方都远）。可直接作代词：Quiero este（我要这个）。'},
                {'title': '颜色词作形容词', 'desc': '颜色词一般后置并与名词性数一致：una camisa blanca, unos zapatos negros。由名词而来的颜色词（rosa, naranja, violeta）性数不变：una camisa rosa。'},
                {'title': '购物常用句式', 'desc': '¿Cuánto cuesta? / ¿Cuánto vale?（多少钱）；¿Me lo puede envolver?（能包起来吗）；¿Tienen esto en otra talla?（有别的尺码吗）。注意直接宾语代词 lo/la 的使用。'},
            ],
        },
    ],
}
