# -*- coding: utf-8 -*-
"""批次 31：C1/C2 扩充（科学与技术伦理 / 法学与公正 / 艺术与审美）"""

BATCH = {
    'C1': [
        {
            'id': 'c1-u13',
            'title': '科学与技术伦理',
            'subtitle': 'Ciencia y Ética Tecnológica',
            'lessons': 12,
            'duration': '约 50 分钟',
            'vocab': [
                ('El avance', '进展', 'El avance técnico supera la regulación.'),
                ('El hallazgo', '研究发现', 'El hallazgo se publicó en Nature.'),
                ('El descubrimiento', '发现', 'El descubrimiento cambió el campo.'),
                ('La innovación', '创新', 'La innovación exige tolerar el error.'),
                ('La patente', '专利', 'La patente expira en dos años.'),
                ('La investigación aplicada', '应用研究', 'La investigación aplicada recibe más fondos.'),
                ('La financiación', '经费', 'La financiación pública se redujo.'),
                ('La revisión por pares', '同行评审', 'La revisión por pares tiene fallos.'),
                ('La reproducibilidad', '可复现性', 'La reproducibilidad es la base del método.'),
                ('El sesgo metodológico', '方法学偏误', 'El sesgo metodológico invalida el estudio.'),
                ('La validez', '效度', 'La validez del instrumento es discutible.'),
                ('La muestra', '样本', 'La muestra no es representativa.'),
                ('El grupo de control', '对照组', 'El grupo de control recibió placebo.'),
                ('El ensayo clínico', '临床试验', 'El ensayo clínico se suspendió.'),
                ('El efecto secundario', '副作用', 'Los efectos secundarios son leves.'),
                ('El riesgo', '风险', 'El riesgo es aceptable en relación al beneficio.'),
                ('La incertidumbre', '不确定性', 'La incertidumbre se comunica mal.'),
                ('El principio de precaución', '预防原则', 'El principio de precaución exige actuar sin certeza.'),
                ('La bioética', '生命伦理', 'La bioética plantea límites claros.'),
                ('El consentimiento informado', '知情同意', 'Falta consentimiento informado.'),
                ('La privacidad', '隐私', 'La privacidad se erosiona sin ruido.'),
                ('Los datos personales', '个人数据', 'Los datos personales se comercializan.'),
                ('El algoritmo', '算法', 'El algoritmo decide sin explicar por qué.'),
                ('La opacidad', '不透明', 'La opacidad del sistema impide reclamar.'),
                ('La trazabilidad', '可追溯性', 'Falta trazabilidad en la cadena.'),
                ('La automatización', '自动化', 'La automatización destruye tareas repetitivas.'),
                ('La obsolescencia', '淘汰、过时', 'La obsolescencia programada es rentable.'),
                ('El sesgo algorítmico', '算法偏差', 'El sesgo algorítmico reproduce desigualdades.'),
                ('La responsabilidad', '责任归属', 'La responsabilidad se diluye entre fabricantes.'),
                ('La rendición de cuentas', '问责', 'Sin rendición de cuentas no hay confianza.'),
                ('El riesgo sistémico', '系统性风险', 'El riesgo sistémico no se puede diversificar.'),
                ('La innovación disruptiva', '颠覆式创新', 'La innovación disruptiva arrasa el sector.'),
                ('El monopolio', '垄断', 'El monopolio tecnológico concentra poder.'),
                ('La dependencia tecnológica', '技术依赖', 'La dependencia tecnológica es una vulnerabilidad.'),
                ('La soberanía digital', '数字主权', 'La soberanía digital es objeto de disputa.'),
                ('El tecnooptimismo', '技术乐观主义', 'El tecnooptimismo evita las preguntas difíciles.'),
                ('La biotecnología', '生物技术', 'La biotecnología abre dilemas nuevos.'),
                ('La edición genética', '基因编辑', 'La edición genética hereditaria está prohibida.'),
                ('El transhumanismo', '超人类主义', 'El transhumanismo promete más de lo que puede.'),
                ('La sostenibilidad', '可持续性', 'La sostenibilidad exige cambiar el modelo.'),
                ('La huella de carbono', '碳足迹', 'La huella de carbono se mide mal.'),
                ('La transición energética', '能源转型', 'La transición energética tiene ganadores y perdedores.'),
                ('El residuo', '废弃物', 'Los residuos se exportan a otros países.'),
                ('El agotamiento', '枯竭', 'El agotamiento de recursos es previsible.'),
                ('La escalabilidad', '可扩展性', 'El problema no es técnico sino de escalabilidad.'),
                ('Plantear', '提出（问题）', 'Plantearon una objeción ética.'),
                ('Cuestionar', '质疑', 'Cuestión el marco entero.'),
                ('Regular', '监管', 'Regular la inteligencia artificial es urgente.'),
                ('Salvaguardar', '保障', 'Hay que salvaguardar los derechos.'),
                ('Anteponer', '优先考虑', 'Anteponen el beneficio al riesgo.'),
                ('Sopesar', '权衡', 'Sopesaron ventajas y peligros.'),
                ('Exacerbar', '加剧', 'La tecnología exacerba las brechas.'),
                ('Soslayar', '回避', 'El informe soslaya lo esencial.'),
            ],
            'grammar': [
                {'title': '表达义务与禁令（技术伦理）', 'desc': 'haber de / deber / tener que + 不定式（义务，语气递增）；estar obligado a；quedar prohibido；no caber + 不定式（不能……）：No cabe ignorar el riesgo。表示「必须谨慎」的无人称句：Cabe / Procede / Conviene + 不定式。'},
                {'title': '权衡与让步的句式', 'desc': 'si bien + 陈述式（虽则）；en la medida en que（在……范围内）；a condición de que + 虚拟式（条件是）；por mucho que + 虚拟式（无论多么）：Por mucho que se regule, siempre habrá vacíos。'},
                {'title': '被动与自复被动在学术文本', 'desc': 'El estudio fue replicado por tres equipos（被动）；Se replicó el estudio en tres laboratorios（自复被动）。学术写作更偏好自复被动，因为可以省略施动者。注意自复被动的主语是受事，动词与它保持数的一致。'},
            ],
        },
    ],
    'C2': [
        {
            'id': 'c2-u9',
            'title': '法学与公正',
            'subtitle': 'Derecho y Justicia',
            'lessons': 12,
            'duration': '约 55 分钟',
            'vocab': [
                ('El ordenamiento jurídico', '法律体系', 'El ordenamiento jurídico es jerárquico.'),
                ('La norma', '规范', 'La norma entró en vigor en enero.'),
                ('La ley orgánica', '组织法', 'Se aprobó una ley orgánica.'),
                ('El reglamento', '条例', 'El reglamento desarrolla la ley.'),
                ('La jurisprudencia', '判例', 'La jurisprudencia cambió de criterio.'),
                ('La doctrina', '学理', 'La doctrina está dividida.'),
                ('La laguna legal', '法律漏洞', 'Hay una laguna legal evidente.'),
                ('La analogía', '类推适用', 'Se resolvió por analogía.'),
                ('El precepto', '条文', 'El precepto es ambiguo.'),
                ('La vigencia', '生效', 'La norma perdió vigencia.'),
                ('La derogación', '废止', 'La derogación fue expresa.'),
                ('La retroactividad', '溯及力', 'Se prohíbe la retroactividad.'),
                ('La prescripción', '时效', 'La acción ha prescrito.'),
                ('La caducidad', '失权期间', 'La caducidad se produce a los seis meses.'),
                ('El plazo', '期限', 'El plazo es de diez días hábiles.'),
                ('La competencia', '管辖权限', 'El tribunal carece de competencia.'),
                ('La jurisdicción', '司法管辖权', 'La jurisdicción es internacional.'),
                ('La instancia', '审级', 'Se resolvió en primera instancia.'),
                ('La apelación', '上诉', 'Presentó apelación en plazo.'),
                ('El recurso', '救济手段', 'Interpuso un recurso de amparo.'),
                ('La sentencia', '判决', 'La sentencia fue unánime.'),
                ('El fallo', '裁决', 'El fallo estimó la demanda.'),
                ('El voto particular', '异议意见', 'Hubo un voto particular duro.'),
                ('El demandante', '原告', 'El demandante aportó pruebas.'),
                ('El demandado', '被告', 'El demandado no compareció.'),
                ('La carga de la prueba', '举证责任', 'La carga de la prueba es del demandante.'),
                ('El dolo', '故意', 'Actuó con dolo.'),
                ('La negligencia', '过失', 'Hubo negligencia grave.'),
                ('La culpa', '过错', 'La culpa es compartida.'),
                ('La responsabilidad civil', '民事责任', 'Exige responsabilidad civil.'),
                ('La indemnización', '损害赔偿', 'La indemnización se fijó en diez mil euros.'),
                ('El daño emergente', '直接损失', 'Se reconoció el daño emergente.'),
                ('El lucro cesante', '可得利益损失', 'No se probó el lucro cesante.'),
                ('La reparación', '赔偿、修复', 'La reparación debe ser integral.'),
                ('La tutela judicial', '司法保护', 'La tutela judicial debe ser efectiva.'),
                ('El debido proceso', '正当程序', 'Se vulneró el debido proceso.'),
                ('La presunción de inocencia', '无罪推定', 'La presunción de inocencia es un derecho.'),
                ('La cosa juzgada', '既判力', 'La cosa juzgada impide revisar.'),
                ('La equidad', '衡平', 'El juez resolvió según equidad.'),
                ('La proporcionalidad', '比例原则', 'La medida supera el test de proporcionalidad.'),
                ('La arbitrariedad', '专断', 'La decisión incurre en arbitrariedad.'),
                ('La motivación', '说理', 'La sentencia carece de motivación.'),
                ('El margen de apreciación', '裁量空间', 'El tribunal tiene margen de apreciación.'),
                ('La discrecionalidad', '自由裁量', 'La discrecionalidad no es arbitrariedad.'),
                ('La seguridad jurídica', '法律安定性', 'La seguridad jurídica exige predictibilidad.'),
                ('La positividad', '实定法', 'La positividad del derecho es un rasgo moderno.'),
                ('El iusnaturalismo', '自然法学派', 'El iusnaturalismo apela a principios previos.'),
                ('El positivismo jurídico', '法律实证主义', 'El positivismo jurídico separa derecho y moral.'),
                ('La lex talionis', '同态复仇原则', 'La lex talionis reaparece en el debate.'),
                ('La discrecionalidad judicial', '司法裁量', 'La discrecionalidad judicial tiene límites.'),
                ('Prescribir', '（时效）届满', 'La acción penal ha prescrito.'),
                ('Prescindir de', '舍弃、不考虑', 'No se puede prescindir de la prueba.'),
                ('Conculcar', '侵害', 'La norma conculca un derecho fundamental.'),
                ('Amparar', '保护、支持', 'La ley ampara al consumidor.'),
                ('Eximir', '免除', 'La cláusula exime de responsabilidad.'),
                ('Imputar', '归责于', 'Se le imputa un delito leve.'),
                ('Subsanar', '补正', 'El defecto se subsanó a tiempo.'),
                ('Dirimir', '裁决（争议）', 'El tribunal dirimió la controversia.'),
            ],
            'grammar': [
                {'title': '法律文本的无人称与将来时', 'desc': '法律条文常用第三人称将来时表义务：El arrendatario abonará la renta（承租人应支付租金）；El que causare daño responderá（造成损害者须负责）——注意后者用虚拟式将来时（-re 形式），是西班牙刑法典的标志性句式。'},
                {'title': '条件与后果的法律句式', 'desc': 'si + 陈述式（现实条件）；si + 虚拟式过去未完成 + 条件式（反事实）；a condición de que / siempre que / en tanto que + 虚拟式；de lo contrario / caso contrario（否则）。'},
                {'title': '否定命令与禁止', 'desc': 'queda prohibido / no se admitirá / en ningún caso se podrá + 不定式。法律禁止性规范不用命令式，而用无人称或被动结构，因为规范对象是所有人而非某个具体的人。'},
            ],
        },
        {
            'id': 'c2-u10',
            'title': '艺术与审美判断',
            'subtitle': 'Arte y Juicio Estético',
            'lessons': 12,
            'duration': '约 55 分钟',
            'vocab': [
                ('La estética', '美学', 'La estética moderna nace en el siglo XVIII.'),
                ('El juicio estético', '审美判断', 'El juicio estético aspira a validez universal.'),
                ('El gusto', '品味', 'Sobre gustos no hay disputa, decían.'),
                ('La sensibilidad', '感受力', 'Su sensibilidad capta matices mínimos.'),
                ('La belleza', '美', 'La belleza no es una propiedad objetiva.'),
                ('Lo sublime', '崇高', 'Lo sublime produce placer y espanto.'),
                ('Lo grotesco', '怪诞', 'Lo grotesco desestabiliza lo familiar.'),
                ('La fealdad', '丑', 'La fealdad también puede conmover.'),
                ('La mímesis', '摹仿', 'La mímesis no es copia sino construcción.'),
                ('La representación', '再现', 'La representación nunca es neutral.'),
                ('La forma', '形式', 'La forma es contenido sedimentado.'),
                ('El contenido', '内容', 'El contenido exige una forma propia.'),
                ('La composición', '构图', 'La composición empuja la mirada al centro.'),
                ('El encuadre', '取景', 'El encuadre excluye más de lo que muestra.'),
                ('La textura', '质感', 'La textura sugiere el paso del tiempo.'),
                ('El trazo', '笔触', 'El trazo revela la mano del artista.'),
                ('La paleta', '色调', 'La paleta se vuelve más fría al final.'),
                ('El claroscuro', '明暗对比', 'El claroscuro concentra la atención.'),
                ('La perspectiva', '透视', 'La perspectiva organiza el espacio.'),
                ('El lienzo', '画布', 'El lienzo quedó sin terminar.'),
                ('La obra', '作品', 'La obra admite lecturas opuestas.'),
                ('El autor', '作者', 'El autor renegó de su obra temprana.'),
                ('La autoría', '作者身份', 'La autoría está en disputa.'),
                ('El original', '原作', 'El original se conserva en el museo.'),
                ('La reproducción', '复制品', 'La reproducción pierde el aura.'),
                ('La copia', '摹本', 'Es una copia del siglo XIX.'),
                ('El aura', '灵光', 'La técnica reproductiva disuelve el aura.'),
                ('El canon', '正典', 'El canon excluye tanto como incluye.'),
                ('La vanguardia', '先锋派', 'La vanguardia rompió con la tradición.'),
                ('El manifiesto', '宣言', 'El manifiesto declaraba la ruptura.'),
                ('La ruptura', '断裂', 'La ruptura fue más retórica que real.'),
                ('La provocación', '挑衅', 'La provocación agotó su efecto.'),
                ('La ironía', '反讽', 'La ironía es el modo dominante.'),
                ('El pastiche', '拼贴、仿作', 'El pastiche cita sin creer.'),
                ('La cita', '引述', 'La cita convierte la historia en material.'),
                ('La apropiación', '挪用', 'La apropiación cuestiona la autoría.'),
                ('El kitsch', '媚俗', 'El kitsch imita el efecto sin la causa.'),
                ('La crítica', '批评', 'La crítica también crea valor.'),
                ('El comisario', '策展人', 'El comisario propuso otro relato.'),
                ('La curaduría', '策展', 'La curaduría ordena la lectura.'),
                ('El montaje', '蒙太奇', 'El montaje produce el sentido.'),
                ('La instalación', '装置艺术', 'La instalación ocupa toda la sala.'),
                ('El performance', '行为艺术', 'El performance duraba ocho horas.'),
                ('La recepción', '接受', 'La recepción inicial fue hostil.'),
                ('El espectador', '观众', 'El espectador completa la obra.'),
                ('La interpretación', '阐释', 'Toda interpretación es situada.'),
                ('El significado', '意义', 'El significado no está fijado de antemano.'),
                ('La polisemia', '多义性', 'La polisemia de la imagen es deliberada.'),
                ('El discurso', '话语', 'El discurso del museo legitima.'),
                ('Conmover', '打动人', 'La película conmueve sin manipular.'),
                ('Desconcertar', '令人困惑', 'La obra desconcierta a propósito.'),
                ('Subvertir', '颠覆', 'Subvierte las convenciones del género.'),
                ('Interpelar', '质询', 'La obra interpela al espectador.'),
                ('Estetizar', '美化', 'Estetizar el horror es un riesgo.'),
                ('Banalizar', '使平庸化', 'La repetición banaliza la imagen.'),
                ('Trascender', '超越', 'El arte trasciende lo anecdótico.'),
                ('Prescindir de', '舍弃', 'Prescinde de todo ornamento.'),
                ('Reivindicar', '维护、主张', 'Reivindica una tradición olvidada.'),
            ],
            'grammar': [
                {'title': '表达评价与判断的句式', 'desc': 'No es que + 虚拟式（并不是说……）：No es que la obra sea fea, es que no dice nada。lo que + 动词 + es（真正……的是）：Lo que conmueve no es el tema, sino el modo。这两个句式是表达审美判断的核心工具。'},
                {'title': '让步与反衬', 'desc': 'por + 形容词 + que + 虚拟式：Por hermosa que sea, no basta；si bien；aun a riesgo de；lejos de + 不定式（非但不……反而）：Lejos de agotarse, el debate se reavivó。'},
                {'title': 'ser 与 estar 的表意差异（评价语境）', 'desc': 'La obra es bella（本质评价）vs La obra está expuesta（状态、位置）。评价作品内在性质用 ser；描述作品的临时状态或展出情况用 estar。混淆会直接改变句子的意思。'},
            ],
        },
    ],
}
