# -*- coding: utf-8 -*-
"""批次 32：B1 扩充（技术与数字生活 / 环境与可持续）"""

BATCH = {
    'B1': [
        {
            'id': 'b1-u11',
            'title': '技术与数字生活',
            'subtitle': 'Tecnología y Vida Digital',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('La tecnología', '技术', 'La tecnología cambia muy rápido.'),
                ('La herramienta', '工具', 'Es una herramienta muy útil.'),
                ('El dispositivo', '设备', 'Este dispositivo es antiguo.'),
                ('El aparato', '机器、装置', 'El aparato dejó de funcionar.'),
                ('El móvil', '手机', 'Me he quedado sin móvil.'),
                ('La tableta', '平板', 'Leo en la tableta por la noche.'),
                ('El ordenador portátil', '笔记本电脑', 'El portátil pesa poco.'),
                ('La pantalla', '屏幕', 'La pantalla está rayada.'),
                ('El teclado', '键盘', 'El teclado no responde.'),
                ('La batería', '电池', 'La batería dura todo el día.'),
                ('El cargador', '充电器', 'Olvidé el cargador en casa.'),
                ('La conexión', '连接', 'La conexión es muy lenta aquí.'),
                ('La red', '网络', 'No hay red en el sótano.'),
                ('Los datos móviles', '移动数据', 'Se me acabaron los datos móviles.'),
                ('El archivo', '文件', 'Guardé el archivo en la nube.'),
                ('La carpeta', '文件夹', 'Crea una carpeta nueva.'),
                ('La nube', '云端', 'Subí las fotos a la nube.'),
                ('La copia de seguridad', '备份', 'Hago copia de seguridad cada semana.'),
                ('La contraseña', '密码', 'Cambié la contraseña ayer.'),
                ('La cuenta', '账号', 'No recuerdo la cuenta.'),
                ('El usuario', '用户', 'El usuario debe aceptar las condiciones.'),
                ('La aplicación', '应用程序', 'Descargué una aplicación nueva.'),
                ('La actualización', '更新', 'La actualización tarda mucho.'),
                ('El programa', '程序', 'Este programa ya no se usa.'),
                ('La pantalla táctil', '触摸屏', 'La pantalla táctil no responde.'),
                ('El altavoz', '扬声器', 'El altavoz suena mal.'),
                ('Los auriculares', '耳机', 'Ponerse los auriculares ayuda a concentrarse.'),
                ('La cámara', '摄像头', 'La cámara hace fotos muy nítidas.'),
                ('El vídeo', '视频', 'Grabé un vídeo corto.'),
                ('La grabación', '录音、录像', 'La grabación tiene mala calidad.'),
                ('El enlace', '链接', 'Mándame el enlace, por favor.'),
                ('El mensaje', '消息', 'Te escribí un mensaje esta mañana.'),
                ('El correo', '电子邮件', 'Reviso el correo dos veces al día.'),
                ('La notificación', '通知', 'Desactivé todas las notificaciones.'),
                ('La suscripción', '订阅', 'La suscripción se renueva sola.'),
                ('El ancho de banda', '带宽', 'Necesitamos más ancho de banda.'),
                ('La privacidad', '隐私', 'La privacidad importa cada vez más.'),
                ('La huella digital', '数字足迹', 'Tu huella digital es difícil de borrar.'),
                ('El rastro', '痕迹', 'Todo deja un rastro digital.'),
                ('El riesgo', '风险', 'El riesgo de fraude ha crecido.'),
                ('La estafa', '诈骗', 'Me intentaron hacer una estafa.'),
                ('El fraude', '欺诈', 'El fraude se denunció a la policía.'),
                ('La seguridad', '安全', 'La seguridad de la red es básica.'),
                ('Actualizar', '更新', 'Actualiza el sistema cuando puedas.'),
                ('Descargar', '下载', 'Descargué el archivo en un minuto.'),
                ('Subir', '上传', 'Subí las fotos al grupo.'),
                ('Guardar', '保存', 'Guarda el documento antes de salir.'),
                ('Instalar', '安装', 'Instalé el programa sin problemas.'),
                ('Conectar', '连接', 'No consigo conectar el altavoz.'),
                ('Configurar', '配置', '¿Me ayudas a configurar el correo?'),
                ('Bloquear', '封锁、锁定', 'Bloqueé su número.'),
                ('Compartir', '分享', 'Comparte el documento conmigo.'),
                ('Hacer copia de seguridad', '做备份', 'Haz copia antes de actualizar.'),
                ('Darse de baja', '注销、退订', 'Me di de baja del servicio.'),
            ],
            'grammar': [
                {'title': '技术文本中的被动与无人称', 'desc': 'Se ha actualizado la aplicación / Los datos se guardan automáticamente / No se permite compartir la contraseña。技术说明习惯用自复被动，因为重点是操作本身而非执行者。irse 与自复被动的区分：Se guardan los datos（被保存）vs Se guardan los datos ellos（他们自己保存）。'},
                {'title': '命令式在操作指引中的用法', 'desc': '操作说明用命令式：Pulsa / Guarda / Introduce / No cierres la ventana。肯定命令式与否定命令式的人称不同：Pulsa（tú 肯定）vs No pulses（tú 否定）；正式场合用 Pulse / Guarde。'},
                {'title': '动作的结果状态：estar + 分词', 'desc': 'La aplicación está actualizada（已更新状态）；El archivo está guardado；La batería está agotada。注意与被动语态的区别：fue actualizada 强调动作，está actualizada 强调结果状态。'},
            ],
        },
        {
            'id': 'b1-u12',
            'title': '环境与可持续',
            'subtitle': 'Medio Ambiente y Sostenibilidad',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('El medio ambiente', '环境', 'Hay que proteger el medio ambiente.'),
                ('El entorno', '周边环境', 'El entorno natural es privilegiado.'),
                ('La naturaleza', '自然', 'La naturaleza se recupera despacio.'),
                ('El ecosistema', '生态系统', 'El ecosistema está en peligro.'),
                ('La biodiversidad', '生物多样性', 'La biodiversidad disminuye cada año.'),
                ('La especie', '物种', 'Hay especies en peligro de extinción.'),
                ('La extinción', '灭绝', 'La extinción avanza más rápido de lo previsto.'),
                ('El hábitat', '栖息地', 'Su hábitat se reduce por la construcción.'),
                ('La contaminación', '污染', 'La contaminación del aire empeora.'),
                ('El contaminante', '污染物', 'Se vierten contaminantes al río.'),
                ('El residuo', '废弃物', 'Los residuos se separan por tipo.'),
                ('La basura', '垃圾', 'La basura orgánica va al contenedor marrón.'),
                ('El reciclaje', '回收', 'El reciclaje empieza en casa.'),
                ('El plástico', '塑料', 'El plástico tarda siglos en degradarse.'),
                ('El vertido', '倾倒、排放', 'El vertido afectó a la costa.'),
                ('El vertedero', '垃圾填埋场', 'El vertedero está al límite.'),
                ('La emisión', '排放', 'Las emisiones deben reducirse.'),
                ('El efecto invernadero', '温室效应', 'El efecto invernadero se intensifica.'),
                ('El cambio climático', '气候变化', 'El cambio climático ya es visible.'),
                ('El calentamiento', '变暖', 'El calentamiento global es inequívoco.'),
                ('La sequía', '干旱', 'La sequía afecta a los embalses.'),
                ('La inundación', '洪水', 'Las inundaciones son cada vez más frecuentes.'),
                ('La ola de calor', '热浪', 'La ola de calor duró una semana.'),
                ('El nivel del mar', '海平面', 'El nivel del mar sigue subiendo.'),
                ('El glaciar', '冰川', 'Los glaciares retroceden.'),
                ('La energía renovable', '可再生能源', 'La energía renovable crece rápido.'),
                ('La energía solar', '太阳能', 'Instalaron energía solar en el tejado.'),
                ('La energía eólica', '风能', 'La energía eólica es barata.'),
                ('El consumo', '消耗', 'Reducir el consumo es lo más eficaz.'),
                ('La eficiencia', '效率', 'La eficiencia energética ahorra dinero.'),
                ('El ahorro', '节约', 'El ahorro de agua es urgente.'),
                ('La huella ecológica', '生态足迹', 'Nuestra huella ecológica es insostenible.'),
                ('La sostenibilidad', '可持续性', 'La sostenibilidad no es un eslogan.'),
                ('La protección', '保护', 'La protección del litoral es competencia pública.'),
                ('La reserva natural', '自然保护区', 'La reserva natural protege aves migratorias.'),
                ('La especie invasora', '入侵物种', 'La especie invasora daña el ecosistema.'),
                ('El pesticida', '农药', 'Los pesticidas afectan a las abejas.'),
                ('La agricultura ecológica', '有机农业', 'La agricultura ecológica gana terreno.'),
                ('El producto de proximidad', '本地产品', 'Compramos producto de proximidad.'),
                ('El envase', '包装', 'El envase es innecesario.'),
                ('La bolsa reutilizable', '可重复使用袋', 'Llevo siempre una bolsa reutilizable.'),
                ('El transporte público', '公共交通', 'Usar transporte público reduce emisiones.'),
                ('El coche eléctrico', '电动汽车', 'El coche eléctrico aún es caro.'),
                ('La movilidad', '出行', 'La movilidad sostenible es prioritaria.'),
                ('Reciclar', '回收', 'Reciclamos el vidrio y el papel.'),
                ('Reutilizar', '重复使用', 'Reutiliza los envases de cristal.'),
                ('Reducir', '减少', 'Hay que reducir el consumo de carne.'),
                ('Contaminar', '污染', 'La fábrica contamina el río.'),
                ('Preservar', '保护、维护', 'Preservar el suelo es clave.'),
                ('Agotar', '耗尽', 'Agotamos los recursos más rápido de lo que se regeneran.'),
                ('Derrochar', '浪费', 'No derroches agua.'),
                ('Concienciar', '提高意识', 'La campaña busca concienciar a la gente.'),
                ('Comprometerse a', '承诺', 'Se comprometió a reducir residuos.'),
                ('Prescindir de', '不用、舍弃', 'Es difícil prescindir del coche.'),
            ],
            'grammar': [
                {'title': '表达义务与必要性的多种方式', 'desc': 'hay que + 不定式（泛泛的必要，无人称）；deber + 不定式（道义上应当）；tener que（客观必须）；es necesario / urgente / imprescindible + 不定式 或 que + 虚拟式。hay que 没有主语，是最常用的公共呼吁句式。'},
                {'title': '未来时与条件式预测', 'desc': '未来时表预测：Las temperaturas subirán dos grados。条件式表假设后果：Si no actuamos, las consecuencias serían irreversibles。注意 si 从句不能用未来时或条件式：Si no actuamos（现在时），不能用 si no actuaremos。'},
                {'title': '被动与结果状态（环保语境）', 'desc': 'Se han reducido las emisiones（被减少了）；Las emisiones han sido reducidas（被动，强调动作来源）；Las emisiones están reducidas（结果状态）。三种说法在报告文体中都可出现，语义侧重不同。'},
            ],
        },
    ],
}
