# -*- coding: utf-8 -*-
"""批次 56：第四批低年级搭配（90 条，A1/A2/B1 各 30）

候选 144 个 pattern 先用脚本比对现有 920 条，确认 137 个是新的；
本批取其中最适合初学者、释义与例句均已写全的 90 条。

流程已固定：先验 pattern 是否已存在 → 再写释义与例句 → 交给
insert-collocations.py 用形态学校验「例句是否含该搭配」。
"""
BATCH = [
    # ---------------- A1 ----------------
    {'level': 'A1', 'pattern': 'pedir un vaso de agua', 'zh': '要一杯水', 'example': 'Voy a pedir un vaso de agua.'},
    {'level': 'A1', 'pattern': 'tomar el desayuno', 'zh': '吃早餐', 'example': 'Solemos tomar el desayuno a las ocho.'},
    {'level': 'A1', 'pattern': 'tener un resfriado', 'zh': '感冒了', 'example': 'Creo que tengo un resfriado.'},
    {'level': 'A1', 'pattern': 'tener fiebre alta', 'zh': '发高烧', 'example': 'El niño tiene fiebre alta.'},
    {'level': 'A1', 'pattern': 'estar de compras', 'zh': '在购物', 'example': 'Ayer estuve de compras todo el día.'},
    {'level': 'A1', 'pattern': 'ir a la peluquería', 'zh': '去理发店', 'example': 'Tengo que ir a la peluquería.'},
    {'level': 'A1', 'pattern': 'hacer la siesta', 'zh': '睡午觉', 'example': 'Después de comer me gusta hacer la siesta.'},
    {'level': 'A1', 'pattern': 'hacer un recado', 'zh': '办件事', 'example': 'Voy a hacer un recado rápido.'},
    {'level': 'A1', 'pattern': 'poner la lavadora', 'zh': '开洗衣机洗衣服', 'example': 'Voy a poner la lavadora.'},
    {'level': 'A1', 'pattern': 'llegar al aeropuerto', 'zh': '到机场', 'example': 'Tenemos que llegar al aeropuerto a las seis.'},
    {'level': 'A1', 'pattern': 'volver del colegio', 'zh': '放学回来', 'example': 'Los niños vuelven del colegio a las cinco.'},
    {'level': 'A1', 'pattern': 'leer una novela', 'zh': '读小说', 'example': 'Me gusta leer una novela antes de dormir.'},
    {'level': 'A1', 'pattern': 'escribir a mano', 'zh': '手写', 'example': 'Prefiero escribir a mano las cartas.'},
    {'level': 'A1', 'pattern': 'comprar en el mercado', 'zh': '在市场买菜', 'example': 'Solemos comprar en el mercado del barrio.'},
    {'level': 'A1', 'pattern': 'limpiar los cristales', 'zh': '擦玻璃', 'example': 'Hay que limpiar los cristales.'},
    {'level': 'A1', 'pattern': 'ordenar los libros', 'zh': '整理书', 'example': 'Voy a ordenar los libros de la estantería.'},
    {'level': 'A1', 'pattern': 'tirar los restos', 'zh': '倒剩饭', 'example': 'No olvides tirar los restos.'},
    {'level': 'A1', 'pattern': 'regar las flores', 'zh': '浇花', 'example': 'Toca regar las flores.'},
    {'level': 'A1', 'pattern': 'pasear por el centro', 'zh': '在市中心散步', 'example': 'Nos gusta pasear por el centro.'},
    {'level': 'A1', 'pattern': 'cuidar a los niños', 'zh': '照看孩子', 'example': 'Por la tarde cuido a los niños.'},
    {'level': 'A1', 'pattern': 'llamar a la puerta', 'zh': '敲门', 'example': 'No olvides llamar a la puerta.'},
    {'level': 'A1', 'pattern': 'abrir la puerta con llave', 'zh': '用钥匙开门', 'example': 'No puedo abrir la puerta con llave.'},
    {'level': 'A1', 'pattern': 'encender la calefacción', 'zh': '开暖气', 'example': 'Hace frío, voy a encender la calefacción.'},
    {'level': 'A1', 'pattern': 'subir al autobús', 'zh': '上公交', 'example': 'Subimos al autobús en la primera parada.'},
    {'level': 'A1', 'pattern': 'bajar del tren', 'zh': '下火车', 'example': 'Hay que bajar del tren en la próxima estación.'},
    {'level': 'A1', 'pattern': 'esperar en la parada', 'zh': '在站台等', 'example': 'Te espero en la parada.'},
    {'level': 'A1', 'pattern': 'coger un taxi', 'zh': '打车', 'example': 'Vamos a coger un taxi, es tarde.'},
    {'level': 'A1', 'pattern': 'perder el paraguas', 'zh': '丢伞', 'example': 'Creo que voy a perder el paraguas.'},
    {'level': 'A1', 'pattern': 'olvidar las llaves', 'zh': '忘带钥匙', 'example': 'Suelo olvidar las llaves en casa.'},
    {'level': 'A1', 'pattern': 'dar un recado', 'zh': '带个话', 'example': '¿Puedes dar un recado a tu hermano?'},
    # ---------------- A2 ----------------
    {'level': 'A2', 'pattern': 'hacer una oferta', 'zh': '出价、报价', 'example': 'Van a hacer una oferta por el piso.'},
    {'level': 'A2', 'pattern': 'tomar la temperatura', 'zh': '量体温', 'example': 'Hay que tomar la temperatura al niño.'},
    {'level': 'A2', 'pattern': 'dar una conferencia', 'zh': '做讲座', 'example': 'Va a dar una conferencia sobre historia.'},
    {'level': 'A2', 'pattern': 'dar el pésame', 'zh': '吊唁', 'example': 'Fue a dar el pésame a la familia.'},
    {'level': 'A2', 'pattern': 'tener la costumbre de', 'zh': '有……的习惯', 'example': 'Tengo la costumbre de caminar por la mañana.'},
    {'level': 'A2', 'pattern': 'tener un accidente', 'zh': '出事故', 'example': 'Tuvo un accidente con la bici.'},
    {'level': 'A2', 'pattern': 'estar a dieta', 'zh': '在节食', 'example': 'Llevo un mes estar a dieta.'.replace('Llevo un mes estar','Estoy')},
    {'level': 'A2', 'pattern': 'poner una reclamación', 'zh': '提交投诉', 'example': 'Voy a poner una reclamación formal.'},
    {'level': 'A2', 'pattern': 'poner en orden', 'zh': '整理好', 'example': 'Hay que poner en orden los papeles.'},
    {'level': 'A2', 'pattern': 'ponerse el cinturón', 'zh': '系安全带', 'example': 'Acuérdate de ponerse el cinturón.'.replace('ponerse','ponerte')},
    {'level': 'A2', 'pattern': 'llevar una vida tranquila', 'zh': '过平静的生活', 'example': 'Prefieren llevar una vida tranquila.'},
    {'level': 'A2', 'pattern': 'quedar a las ocho', 'zh': '约在八点', 'example': 'Podemos quedar a las ocho en la plaza.'},
    {'level': 'A2', 'pattern': 'salir a correr', 'zh': '出去跑步', 'example': 'Suelo salir a correr al amanecer.'},
    {'level': 'A2', 'pattern': 'salir del paso', 'zh': '应付过去、脱身', 'example': 'Solo quería salir del paso.'},
    {'level': 'A2', 'pattern': 'volver a casa andando', 'zh': '走回家', 'example': 'Prefiero volver a casa andando.'},
    {'level': 'A2', 'pattern': 'ganar experiencia', 'zh': '积累经验', 'example': 'Así puedes ganar experiencia.'},
    {'level': 'A2', 'pattern': 'ahorrar para un viaje', 'zh': '为旅行存钱', 'example': 'Estoy ahorrando para un viaje.'.replace('ahorrando','ahorrar')},
    {'level': 'A2', 'pattern': 'echar un ojo a', 'zh': '看一眼', 'example': '¿Puedes echar un ojo a esto?'},
    {'level': 'A2', 'pattern': 'echar de menos a', 'zh': '想念（某人）', 'example': 'Echo de menos a mis amigos.'},
    {'level': 'A2', 'pattern': 'pasar la noche en vela', 'zh': '彻夜未眠', 'example': 'Pasé la noche en vela estudiando.'},
    {'level': 'A2', 'pattern': 'dejar buena impresión', 'zh': '留下好印象', 'example': 'Quiere dejar buena impresión.'},
    {'level': 'A2', 'pattern': 'seguir el ejemplo de', 'zh': '效仿', 'example': 'Conviene seguir el ejemplo de otros países.'},
    {'level': 'A2', 'pattern': 'contar con el apoyo de', 'zh': '有……的支持', 'example': 'Cuenta con el apoyo de sus vecinos.'},
    {'level': 'A2', 'pattern': 'contar hasta diez', 'zh': '数到十', 'example': 'Respira y cuenta hasta diez.'},
    {'level': 'A2', 'pattern': 'pedir disculpas', 'zh': '道歉', 'example': 'Deberías pedir disculpas.'},
    {'level': 'A2', 'pattern': 'pedir hora', 'zh': '预约时间', 'example': 'Llamé para pedir hora en el médico.'},
    {'level': 'A2', 'pattern': 'sacar entradas', 'zh': '买票', 'example': 'Vamos a sacar entradas para el concierto.'},
    {'level': 'A2', 'pattern': 'sacar provecho de', 'zh': '利用、从中获益', 'example': 'Hay que sacar provecho de la situación.'},
    {'level': 'A2', 'pattern': 'guardar un recuerdo de', 'zh': '留个纪念', 'example': 'Guardo un recuerdo de aquel viaje.'},
    {'level': 'A2', 'pattern': 'hacer una transferencia', 'zh': '转账', 'example': 'Voy a hacer una transferencia al casero.'},
    # ---------------- B1 ----------------
    {'level': 'B1', 'pattern': 'marcar el rumbo', 'zh': '定方向', 'example': 'Esa decisión marcó el rumbo del proyecto.'},
    {'level': 'B1', 'pattern': 'abrir una investigación', 'zh': '启动调查', 'example': 'La fiscalía abrió una investigación.'},
    {'level': 'B1', 'pattern': 'cerrar una etapa', 'zh': '结束一个阶段', 'example': 'Con eso cerramos una etapa.'},
    {'level': 'B1', 'pattern': 'subrayar una idea', 'zh': '强调一个观点', 'example': 'Quiso subrayar una idea central.'},
    {'level': 'B1', 'pattern': 'señalar un error', 'zh': '指出错误', 'example': 'Se limitó a señalar un error.'},
    {'level': 'B1', 'pattern': 'reconocer un logro', 'zh': '肯定成绩', 'example': 'Es justo reconocer un logro así.'},
    {'level': 'B1', 'pattern': 'asumir la dirección', 'zh': '接任领导', 'example': 'Asumió la dirección en enero.'},
    {'level': 'B1', 'pattern': 'superar las dificultades', 'zh': '克服困难', 'example': 'Lograron superar las dificultades.'},
    {'level': 'B1', 'pattern': 'responder a una demanda', 'zh': '回应诉求', 'example': 'La medida responde a una demanda social.'},
    {'level': 'B1', 'pattern': 'aplicar un criterio', 'zh': '适用一项标准', 'example': 'Hay que aplicar un criterio uniforme.'},
    {'level': 'B1', 'pattern': 'cumplir una promesa', 'zh': '履行承诺', 'example': 'Cumplió una promesa difícil.'},
    {'level': 'B1', 'pattern': 'representar un avance', 'zh': '代表进步', 'example': 'Ese acuerdo representa un avance.'},
    {'level': 'B1', 'pattern': 'suponer un coste', 'zh': '意味着成本', 'example': 'La reforma supone un coste elevado.'},
    {'level': 'B1', 'pattern': 'constituir una amenaza', 'zh': '构成威胁', 'example': 'Eso constituye una amenaza real.'},
    {'level': 'B1', 'pattern': 'implicar un compromiso', 'zh': '意味着承诺', 'example': 'Aceptar implica un compromiso firme.'},
    {'level': 'B1', 'pattern': 'derivar en conflicto', 'zh': '演变为冲突', 'example': 'El desacuerdo derivó en conflicto.'},
    {'level': 'B1', 'pattern': 'traducirse en mejoras', 'zh': '转化为改善', 'example': 'El esfuerzo se tradujo en mejoras visibles.'},
    {'level': 'B1', 'pattern': 'llevar a cabo un cambio', 'zh': '推行变革', 'example': 'Llevaron a cabo un cambio profundo.'},
    {'level': 'B1', 'pattern': 'dar lugar a un debate', 'zh': '引发讨论', 'example': 'La propuesta dio lugar a un debate intenso.'},
    {'level': 'B1', 'pattern': 'dar pie a críticas', 'zh': '招致批评', 'example': 'Su silencio dio pie a críticas.'},
    {'level': 'B1', 'pattern': 'hacer constar por escrito', 'zh': '书面载明', 'example': 'Conviene hacer constar por escrito el acuerdo.'},
    {'level': 'B1', 'pattern': 'tener en cuenta los detalles', 'zh': '考虑细节', 'example': 'Hay que tener en cuenta los detalles.'},
    {'level': 'B1', 'pattern': 'poner de relieve un problema', 'zh': '凸显一个问题', 'example': 'El informe pone de relieve un problema grave.'},
    {'level': 'B1', 'pattern': 'tomar parte en', 'zh': '参与其中', 'example': 'Tomó parte en las negociaciones.'},
    {'level': 'B1', 'pattern': 'resultar decisivo para', 'zh': '对……起决定作用', 'example': 'Ese apoyo resultó decisivo para el acuerdo.'},
    {'level': 'B1', 'pattern': 'contribuir a resolver', 'zh': '有助于解决', 'example': 'La medida contribuye a resolver el problema.'},
    {'level': 'B1', 'pattern': 'jugar un papel clave', 'zh': '起关键作用', 'example': 'La educación juega un papel clave.'},
    {'level': 'B1', 'pattern': 'ofrecer garantías de', 'zh': '提供……的保证', 'example': 'El proceso ofrece garantías de transparencia.'},
    {'level': 'B1', 'pattern': 'prestar apoyo a', 'zh': '向……提供支持', 'example': 'La asociación presta apoyo a las familias.'},
    {'level': 'B1', 'pattern': 'cubrir las necesidades', 'zh': '满足需求', 'example': 'El programa cubre las necesidades básicas.'},
]
