# -*- coding: utf-8 -*-
"""批次 35：补「听说材料里出现但词库没有」的词汇（缺口审计驱动）

来源：audit-gaps.mjs 报出听力 keyVocab 与口语 vocab 里共 114 个单词
不在 3509 词库中——学习者在听说材料里碰到这些词却查不到、也复习不到。
本批按这些词实际出现的等级把它们补进词库（含中释义与例句）。

分三批插入：B2 / C1 / C2
"""

B2 = {
    'B2': [
        {
            'id': 'b2-u12',
            'title': '政策与公共讨论词汇',
            'subtitle': 'Política y Debate Público',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('La retención', '留存、保留', 'La retención de talento es un reto.'),
                ('Indiscutible', '无可争议的', 'Su mérito es indiscutible.'),
                ('Irreversible', '不可逆的', 'El daño parece irreversible.'),
                ('El desarraigo', '背井离乡', 'El desarraigo marca a los migrantes.'),
                ('El anclaje', '锚定、归属感', 'Buscan un anclaje en la comunidad.'),
                ('Mitigar', '缓解', 'La medida busca mitigar el impacto.'),
                ('Peatonalizar', '改为步行街', 'Van a peatonalizar el centro.'),
                ('La lanzadera', '接驳车', 'Hay una lanzadera hasta el aeropuerto.'),
                ('Repuntar', '回升', 'El empleo empieza a repuntar.'),
                ('Procrastinar', '拖延', 'Procrastino cuando la tarea es difícil.'),
                ('La pereza', '懒惰', 'Me da pereza salir con este frío.'),
                ('La aversión', '厌恶', 'Siente aversión por el riesgo.'),
                ('La rehabilitación', '改造、康复', 'La rehabilitación del barrio avanza.'),
                ('El realojamiento', '重新安置', 'El realojamiento afectó a treinta familias.'),
                ('La intervención', '介入、干预', 'La intervención pública fue decisiva.'),
                ('Descalificar', '贬低、取消资格', 'Descalificar al rival no es un argumento.'),
                ('Acumularse', '累积', 'Los problemas se acumulan.'),
                ('Generalizar', '概括、推广', 'Generalizar a partir de un caso es arriesgado.'),
                ('La devolución', '退款、退还', 'Pidió la devolución del importe.'),
                ('Encajar', '适应、接受', 'No encaja bien las críticas.'),
                ('Radicalmente', '根本地', 'Su postura cambió radicalmente.'),
                ('Principalmente', '主要地', 'El público es principalmente joven.'),
                ('El blog', '博客', 'Escribe un blog sobre viajes.'),
                ('Avisar', '通知', 'Avísame cuando llegues.'),
                ('Enfocar', '着手、聚焦', 'Hay que enfocar el problema de otro modo.'),
                ('Discutir', '争论、讨论', 'Discutieron durante horas sin acuerdo.'),
                ('La pereza mental', '思维惰性', 'La pereza mental es difícil de vencer.'),
                ('El desajuste', '错配、失衡', 'Hay un desajuste entre oferta y demanda.'),
                ('La sobrecarga', '超负荷', 'La sobrecarga laboral afecta la salud.'),
                ('El repunte', '回升', 'Se observa un repunte de la inflación.'),
                ('Sostenido', '持续的', 'El crecimiento sostenido sorprendió.'),
                ('Alarmante', '令人担忧的', 'La cifra es alarmante.'),
                ('Previsible', '可预见的', 'El resultado era previsible.'),
                ('Contundente', '有力的、压倒性的', 'Su respuesta fue contundente.'),
                ('Sistemático', '系统性的', 'Hay un sesgo sistemático.'),
                ('Palpable', '显而易见的', 'La mejora es palpable.'),
                ('Ineludible', '不可避免的', 'El debate era ineludible.'),
                ('La contrapartida', '对价、代价', 'Toda ventaja tiene su contrapartida.'),
                ('El margen de mejora', '改进空间', 'Todavía hay margen de mejora.'),
                ('A corto plazo', '短期内', 'A corto plazo no habrá cambios.'),
                ('A largo plazo', '长期内', 'A largo plazo el efecto se diluye.'),
                ('En la práctica', '实际上', 'En la práctica la norma no se aplica.'),
                ('De hecho', '事实上', 'De hecho, ocurrió lo contrario.'),
                ('A fin de cuentas', '归根结底', 'A fin de cuentas, decide el dinero.'),
                ('En cierto modo', '在某种程度上', 'En cierto modo tiene razón.'),
                ('Sin duda', '毫无疑问', 'Sin duda es la mejor opción.'),
                ('Cabe destacar', '值得指出', 'Cabe destacar el papel de las familias.'),
                ('Resulta llamativo', '引人注意', 'Resulta llamativo que nadie protestara.'),
            ],
            'grammar': [
                {'title': '公共讨论中的评价性表达', 'desc': 'Cabe destacar / Resulta llamativo / Llama la atención que —— 这三组用于引出值得注意之处的句式，是评论与报道的高频开头。注意 llamar la atención que 后面用陈述式或虚拟式取决于是否强调主观评价。'},
                {'title': '表示「程度变化」的动词搭配', 'desc': 'mitigar（缓解）、agravar（加剧）、repuntar（回升）、estancarse（停滞）、dispararse（飙升）。这类动词在描述趋势时比「subir/bajar」更精确，是 B2 阶段应掌握的语域升级。'},
                {'title': '让步与限定的常用短语', 'desc': 'a fin de cuentas / en cierto modo / hasta cierto punto / en la práctica —— 这些短语用来给论断加限定，避免绝对化。学术与评论写作中，没有限定语的断言通常会被视为不严谨。'},
            ],
        },
    ],
}

C1 = {
    'C1': [
        {
            'id': 'c1-u14',
            'title': '论证与批评词汇',
            'subtitle': 'Argumentación y Crítica',
            'lessons': 12,
            'duration': '约 50 分钟',
            'vocab': [
                ('Condicionar', '制约、决定', 'El contexto condiciona la interpretación.'),
                ('Disentir', '持不同意见', 'Disentir es legítimo en democracia.'),
                ('Insostenible', '站不住脚的', 'Esa posición es insostenible.'),
                ('Plausible', '貌似成立的', 'Es una hipótesis plausible.'),
                ('Idealizar', '理想化', 'Idealizar el pasado es un error.'),
                ('Reglamentar', '立规管制', 'Regular no es lo mismo que reglamentar todo.'),
                ('Viable', '可行的', 'La propuesta no es viable.'),
                ('La alarma', '警报、恐慌', 'La alarma social fue exagerada.'),
                ('El umbral', '门槛、阈值', 'Se superó el umbral de tolerancia.'),
                ('El abandono', '放弃、荒废', 'El abandono del campo es creciente.'),
                ('Modelar', '塑造', 'La escuela modela expectativas.'),
                ('Fiable', '可靠的', 'La fuente no es fiable.'),
                ('Engañoso', '有误导性的', 'El titular es engañoso.'),
                ('Lexicalizar', '词汇化', 'Ciertas expresiones se lexicalizan con el uso.'),
                ('Gratuito', '无根据的', 'Es una afirmación gratuita.'),
                ('Revertir', '扭转、归复', 'La tendencia puede revertirse.'),
                ('Folclórico', '民俗的', 'Se explota una imagen folclórica del país.'),
                ('El desacoplamiento', '脱钩', 'El desacoplamiento tiene costes.'),
                ('Impopular', '不受欢迎的', 'La medida resultó impopular.'),
                ('Replantear', '重新考虑', 'Conviene replantear el enfoque.'),
                ('La captura', '俘获、捕获', 'La captura regulatoria es un riesgo real.'),
                ('Domesticar', '驯化', 'Domesticar el discurso público no es fácil.'),
                ('Incomodar', '使不适', 'La pregunta incomoda a muchos.'),
                ('Agravarse', '恶化', 'La situación se agravó en invierno.'),
                ('Amilanarse', '畏缩', 'No se amilanó ante la crítica.'),
                ('Determinante', '决定性的', 'El factor determinante fue el coste.'),
                ('Simplificar', '简化', 'Simplificar en exceso distorsiona.'),
                ('La concreción', '具体化、明确', 'Falta concreción en la propuesta.'),
                ('La certidumbre', '确定性', 'Vendemos certidumbre, no verdad.'),
                ('La contundencia', '有力、果断', 'La contundencia del informe sorprendió.'),
                ('La laxitud', '宽松、松懈', 'Se critica la laxitud de los controles.'),
                ('La opacidad', '不透明', 'La opacidad impide exigir responsabilidades.'),
                ('El sesgo', '偏向', 'El sesgo del estudio es evidente.'),
                ('El contrapeso', '制衡', 'La prensa actúa como contrapeso.'),
                ('La salvaguarda', '保障措施', 'La salvaguarda de derechos es prioritaria.'),
                ('Ineludible', '无可回避的', 'La reforma es ineludible.'),
                ('Escaso', '稀少的', 'El apoyo fue escaso.'),
                ('Ambiguo', '含糊的', 'Un texto ambiguo admite varias lecturas.'),
                ('Taxativo', '斩钉截铁的', 'Fue taxativo al negarlo.'),
                ('Laxo', '松懈的', 'El control es demasiado laxo.'),
                ('Cauteloso', '谨慎的', 'Conviene ser cauteloso con las cifras.'),
                ('Sesgado', '有偏向的', 'El relato está sesgado.'),
                ('Sustancial', '实质性的', 'No hubo cambios sustanciales.'),
                ('Tangencial', '边缘的、间接的', 'Su papel fue tangencial.'),
            ],
            'grammar': [
                {'title': '批评性表述的分寸', 'desc': 'es una afirmación gratuita（无根据之论）/ resulta engañoso（有误导性）/ no se sostiene（站不住）。批评他人论证时，西语学术写作习惯把评价落在「论证」而非「人」上，避免 ad hominem 的语感。'},
                {'title': '表「制约」与「决定」的动词梯度', 'desc': 'condicionar（制约，有影响但非唯一因素）< determinar（决定）< provocar（导致）。选词精度直接决定论断强度，这是 C1 写作的关键区分。'},
                {'title': '无人称结构与客观化', 'desc': 'Cabe señalar / Procede recordar / Conviene precisar / Resulta oportuno matizar —— 用无人称句引出自己的判断，既保持客观语气，又暗示立场。这是学术书面语与新闻评论的通用手法。'},
            ],
        },
    ],
}

C2 = {
    'C2': [
        {
            'id': 'c2-u11',
            'title': '精确表达与语域',
            'subtitle': 'Precisión Léxica y Registro',
            'lessons': 12,
            'duration': '约 55 分钟',
            'vocab': [
                ('Hurtar', '窃取', 'Le hurtaron la cartera en el metro.'),
                ('Escabullirse', '溜走、脱身', 'Se escabulló sin dar explicaciones.'),
                ('El fatalismo', '宿命论', 'El fatalismo paraliza la acción.'),
                ('Irreprochable', '无可指摘的', 'Su conducta fue irreprochable.'),
                ('Nefasto', '有害的、恶劣的', 'Tuvo un efecto nefasto.'),
                ('La renuncia', '放弃、辞让', 'La renuncia a ese derecho es significativa.'),
                ('Jerarquizar', '分级排序', 'Hay que jerarquizar las prioridades.'),
                ('El disparate', '荒谬之言', 'Eso es un disparate.'),
                ('La invención', '发明、杜撰', 'La invención de tradiciones es un fenómeno conocido.'),
                ('Negociable', '可协商的', 'Ese punto no es negociable.'),
                ('Falsear', '篡改、歪曲', 'Falsearon los datos.'),
                ('Encadenar', '串联、接连', 'Encadenó una serie de argumentos.'),
                ('Refutable', '可反驳的', 'Toda hipótesis científica es refutable.'),
                ('Contradecir', '反驳、与……矛盾', 'Los hechos contradicen esa versión.'),
                ('Corregirse', '自我纠正', 'Un buen método sabe corregirse.'),
                ('El procedimiento', '程序、方法', 'El procedimiento es impecable.'),
                ('La ética', '伦理', 'La ética no es un adorno del método.'),
                ('El empobrecimiento', '贫化', 'El empobrecimiento del debate es visible.'),
                ('El pluralismo', '多元主义', 'El pluralismo exige tolerar el disenso.'),
                ('Legislar', '立法', 'Legislar sobre esto es complejo.'),
                ('El acierto', '成功之举、判断准确', 'Fue un acierto estratégico.'),
                ('Modesto', '朴素的、有限的', 'Su alcance es modesto pero real.'),
                ('Impecable', '无可挑剔的', 'La ejecución fue impecable.'),
                ('La coartada', '借口、不在场证明', 'Esa cifra sirve de coartada.'),
                ('La incompetencia', '无能', 'La incompetencia no explica todo.'),
                ('La tirantez', '紧张关系', 'La tirantez entre ambos es evidente.'),
                ('El aplauso', '掌声、赞许', 'Buscaba el aplauso fácil.'),
                ('Contrafactual', '反事实的', 'El razonamiento contrafactual es exigente.'),
                ('Contrastable', '可核验的', 'La afirmación no es contrastable.'),
                ('Nulo', '零、无效的', 'El efecto fue nulo.'),
                ('La inteligibilidad', '可理解性', 'La inteligibilidad del texto se resiente.'),
                ('Jamás', '从不、永不', 'Jamás lo admitió.'),
                ('Rehuir', '回避', 'Rehúye las preguntas directas.'),
                ('El lastre', '包袱、累赘', 'Ese prejuicio es un lastre.'),
                ('Zanjar', '了结、解决', 'Zanjaron la disputa con un pacto.'),
                ('La ingenuidad', '天真', 'Sería ingenuidad creerlo.'),
                ('Pretender', '意图、企图', 'Pretende zanjar el debate con una cifra.'),
                ('Mediar', '调解、介于', 'Medió entre las dos partes.'),
                ('Empeñarse', '执意、坚持', 'Se empeñó en negar la evidencia.'),
                ('La patraña', '弥天大谎', 'Todo resultó una patraña.'),
                ('Complacer', '取悦', 'Complacer al público no es argumentar.'),
                ('Redoblar', '加倍', 'Redobló sus esfuerzos.'),
                ('El brío', '劲头、锐气', 'Defendió su tesis con brío.'),
                ('Irresoluble', '无法解决的', 'El conflicto es irresoluble en esos términos.'),
                ('Resbaladizo', '易滑的、棘手的', 'Es un terreno resbaladizo.'),
                ('El cultismo', '文雅词、拉丁借词', 'El cultismo eleva el registro.'),
                ('La asepsia', '无菌、超然', 'La asepsia del informe es engañosa.'),
                ('La aquiescencia', '默许', 'Su aquiescencia fue silenciosa.'),
                ('El escollo', '障碍', 'Quedan dos escollos por salvar.'),
                ('El trasfondo', '背景、底层', 'El trasfondo ideológico es claro.'),
                ('La tesitura', '处境', 'En esa tesitura, dimitir era lo prudente.'),
            ],
            'grammar': [
                {'title': '否定范围的精确表达', 'desc': 'jamás（永不，比 nunca 更强）/ en absoluto / de ningún modo / ni mucho menos（更谈不上）。ni mucho menos 用于追加否定：「这不容易，更谈不上显而易见」。'},
                {'title': '表「回避」与「坚持」的动词', 'desc': 'rehuir + 名词（回避某事）/ eludir / soslayar / esquivar；empeñarse en + 不定式（执意做）/ obstinarse en / insistir en。这些动词的语义强度与语域各不相同。'},
                {'title': '学术语域的名词化倾向', 'desc': '西语学术写作大量使用名词化：aqueous、asepsia、inteligibilidad、contrastabilidad。名词化能提高信息密度，但过度使用会让句子难以理解——判断标准是「读者能否一眼找到动作的主体」。'},
            ],
        },
    ],
}


BATCH = {}
for d in (B2, C1, C2):
    BATCH.update(d)
