#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批次 78：C2 补 2 个单元（体育与竞技文化 / 饮食文化与烹饪）→ C2 达 20 单元

为什么补这两个：
  - 体育与竞技文化：B2 本轮已补「体育与健康管理」（训练与伤病层面），
    但 C2 层面缺体育作为文化与社会现象（商业化、民族主义、性别差距、青训伦理）
  - 饮食文化与烹饪：全库没有「饮食文化」单元 —— 而美食是西班牙语世界的核心文化载体，
    C2 阅读（文化评论、地方志）大量涉及食材、产地、品鉴与餐饮业变迁

所有词头已用全库比对校验：与现有 6200+ 词条零重复。
"""

BATCH = {
    'C2': [
        {
            'id': 'c2-u19', 'title': '体育与竞技文化', 'subtitle': 'Deporte y Cultura Competitiva',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
('El deporte de élite', '精英体育', 'El deporte de élite exige dedicación total.'),
                ('El alto rendimiento', '高水平竞技', 'El alto rendimiento se mide en resultados.'),
                ('El deportista de élite', '精英运动员', 'El deportista de élite entrena dos veces al día.'),
                ('La disciplina férrea', '铁一般的自律', 'La disciplina férrea sostiene años de carrera.'),
                ('La rutina implacable', '无情的日常训练', 'La rutina implacable no admite excusas.'),
                ('La exigencia física', '身体极限要求', 'La exigencia física pasa factura.'),
                ('El límite del cuerpo', '身体的极限', 'El límite del cuerpo se alcanza y se rompe.'),
                ('La superación personal', '自我超越', 'La superación personal es el motor del deporte.'),
                ('La marca personal', '个人最好成绩', 'Bajó su marca personal en tres segundos.'),
                ('La plusmarca mundial', '世界纪录', 'La plusmarca mundial resistió doce años.'),
                ('La épica deportiva', '体育史诗', 'La épica deportiva se construye en los últimos minutos.'),
                ('La hazaña', '壮举', 'La hazaña se recordó durante décadas.'),
                ('El hito histórico', '历史里程碑', 'Aquel partido fue un hito histórico.'),
                ('La trayectoria deportiva', '运动生涯', 'Su trayectoria deportiva duró quince años.'),
                ('El palmarés', '荣誉榜', 'Su palmarés incluye tres medallas.'),
                ('La retirada anticipada', '提前退役', 'La retirada anticipada sorprendió a todos.'),
                ('El ocaso del deportista', '运动员的黄昏期', 'El ocaso del deportista llega pronto.'),
                ('La segunda carrera', '第二职业', 'Pocos planifican su segunda carrera.'),
                ('El patrocinio deportivo', '体育赞助', 'El patrocinio deportivo financia clubes modestos.'),
                ('El derecho de imagen', '肖像权', 'El derecho de imagen se negocia aparte.'),
                ('El traspaso', '转会', 'El traspaso se cerró por sesenta millones.'),
                ('La cláusula de rescisión', '解约金条款', 'La cláusula de rescisión era prohibitiva.'),
                ('El mercado de fichajes', '转会市场', 'El mercado de fichajes cierra el 31 de agosto.'),
                ('La cantera', '青训体系', 'La cantera surte al primer equipo.'),
                ('La formación de base', '基础培养', 'La formación de base importa más que el resultado.'),
                ('El talento precoz', '早熟的天才', 'El talento precoz necesita protección.'),
                ('La presión mediática', '媒体压力', 'La presión mediática aplasta a los jóvenes.'),
                ('El escrutinio constante', '持续的审视', 'El escrutinio constante no deja espacio privado.'),
                ('La fama temprana', '年少成名', 'La fama temprana tiene un precio alto.'),
                ('La confianza mutua en el equipo', '队内互信', 'La confianza mutua en el equipo gana partidos.'),
                ('El liderazgo deportivo', '体育领导力', 'El liderazgo deportivo se ejerce con el ejemplo.'),
                ('La cohesión del grupo', '团队凝聚力', 'La cohesión del grupo se nota fuera del campo.'),
                ('La dinámica del vestuario', '更衣室生态', 'La dinámica del vestuario decide temporadas.'),
                ('El conflicto interno', '内部矛盾', 'El conflicto interno se filtró a la prensa.'),
                ('La gestión de egos', '管理自我', 'La gestión de egos es la tarea más difícil.'),
                ('La cultura del esfuerzo', '奋斗文化', 'La cultura del esfuerzo se enseña en la base.'),
                ('La igualdad de género en el deporte', '体育中的性别平等', 'La igualdad de género en el deporte avanza despacio.'),
                ('El deporte femenino', '女子体育', 'El deporte femenino gana visibilidad.'),
                ('La brecha salarial deportiva', '体育薪资差距', 'La brecha salarial deportiva sigue siendo enorme.'),
                ('El deporte adaptado', '残疾人体育', 'El deporte adaptado tiene cada vez más licencias.'),
                ('El deporte inclusivo', '包容性体育', 'El deporte inclusivo adapta reglas y espacios.'),
                ('El juego limpio', '公平竞赛', 'El juego limpio es un valor antes que una norma.'),
                ('La deportividad', '体育风度', 'La deportividad se ve al perder.'),
                ('El juego sucio', '不正当手段', 'El juego sucio mancha el resultado.'),
                ('La violencia en el deporte', '体育暴力', 'La violencia en el deporte se combate con prevención.'),
                ('Los ultras', '极端球迷', 'Los ultras organizan la protesta y la violencia.'),
                ('La seguridad en los estadios', '球场安全', 'La seguridad en los estadios exige coordinación.'),
                ('La rivalidad histórica', '历史宿怨', 'La rivalidad histórica se hereda entre aficiones.'),
                ('El derbi', '同城德比', 'El derbi paraliza la ciudad.'),
                ('La afición incondicional', '无条件的球迷支持', 'La afición incondicional anima aunque se pierda.'),
            ],
            'grammar': [
                {'title': '评价与判断的高阶句式', 'desc': 'Lo que hace grande a un deportista es… / No es tanto el resultado cuanto la actitud / Más que un récord, fue un símbolo。注意 no es tanto A cuanto B（与其说是 A，不如说是 B）是 C2 的高阶对比句式。'},
                {'title': '表达因果、让步与限度的精密结构', 'desc': 'a fuerza de + 不定式 / por mucho que + 虚拟式 / en la medida en que / aun a riesgo de。por mucho que insista（无论他怎么坚持）后面必须用虚拟式。'},
                {'title': '抽象论述的名词化与被动', 'desc': 'La mercantilización del deporte ha convertido… / Se ha pasado de X a Y / La presión mediática se ejerce desde múltiples frentes。注意 pasarse de A a B（从 A 变成 B）是评论常用结构。'},
            ],
        },
        {
            'id': 'c2-u20', 'title': '饮食文化与烹饪', 'subtitle': 'Cultura Gastronómica y Cocina',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
('La cocina de autor', '创意料理', 'La cocina de autor busca un sello propio.'),
                ('La cocina de mercado', '市场时令料理', 'La cocina de mercado improvisa con lo que hay.'),
                ('La cocina de temporada', '应季料理', 'La cocina de temporada respeta el ciclo natural.'),
                ('El producto de temporada', '应季食材', 'El producto de temporada sabe mejor.'),
                ('La denominación de origen', '原产地命名', 'La denominación de origen protege al productor.'),
                ('La indicación geográfica protegida', '受保护地理标志', 'La indicación geográfica protegida certifica el origen.'),
                ('La cadena corta de comercialización', '短链销售', 'La cadena corta de comercialización elimina intermediarios.'),
                ('El mercado de abastos', '批发菜场', 'El mercado de abastos abre de madrugada.'),
                ('La lonja', '鱼市', 'La lonja subasta el pescado del día.'),
                ('El pescado de lonja', '鱼市直供鱼', 'El pescado de lonja llega fresco a la mesa.'),
                ('El marisco', '海鲜', 'El marisco se paga a precio de oro.'),
                ('El percebe', '鹅颈藤壶', 'El percebe se recoge entre las rocas.'),
                ('El bogavante', '欧洲龙虾', 'El bogavante es un lujo en la carta.'),
                ('La almeja', '蛤蜊', 'Las almejas se abren al calor.'),
                ('El mejillón', '贻贝', 'El mejillón se cultiva en bateas.'),
                ('El calamar', '鱿鱼', 'El calamar a la romana es típico.'),
                ('El pulpo', '章鱼', 'El pulpo a la gallega se sirve con pimentón.'),
                ('La merluza', '无须鳕', 'La merluza se cocina al pilpil.'),
                ('El bacalao', '鳕鱼', 'El bacalao se desala antes de cocinar.'),
                ('El atún rojo', '蓝鳍金枪鱼', 'El atún rojo se corta para sashimi.'),
                ('El rape', '鮟鱇鱼', 'El rape es ideal para guisos.'),
                ('El rodaballo', '大菱鲆', 'El rodaballo se hace a la plancha.'),
                ('La dorada', '金头鲷', 'La dorada se toma a la sal.'),
                ('La lubina', '狼鲈', 'La lubina a la espalda es un clásico.'),
                ('La anguila', '鳗鱼', 'La anguila se sirve en guiso.'),
                ('El cerdo ibérico', '伊比利亚猪', 'El cerdo ibérico se cría en dehesa.'),
                ('La bellota', '橡果', 'La bellota da sabor al jamón.'),
                ('La curación', '腌制风干', 'La curación dura más de dos años.'),
                ('El secado', '风干', 'El secado al aire concentra el sabor.'),
                ('El curado en sal', '盐渍', 'El curado en sal se hace en bodega.'),
                ('El embutido', '腌肠、香肠', 'El embutido se cura en tripa natural.'),
                ('El chorizo', '西班牙辣香肠', 'El chorizo se come en bocadillo.'),
                ('La morcilla', '血肠', 'La morcilla se fríe con cebolla.'),
                ('La cecina', '风干牛肉', 'La cecina se corta muy fina.'),
                ('El queso curado', '陈年奶酪', 'El queso curado ralla bien.'),
                ('El queso de oveja', '羊奶酪', 'El queso de oveja tiene sabor intenso.'),
                ('El queso de cabra', '山羊奶酪', 'El queso de cabra se sirve con miel.'),
                ('La cuajada', '凝乳', 'La cuajada se endulza con miel.'),
                ('La miel de romero', '迷迭香蜂蜜', 'La miel de romero es clara y aromática.'),
                ('El aceite de oliva virgen extra', '特级初榨橄榄油', 'El aceite de oliva virgen extra no se calienta en exceso.'),
                ('La almazara', '榨油坊', 'La almazara muele la aceituna en frío.'),
                ('La aceituna', '橄榄', 'La aceituna se aliña con hierbas.'),
                ('La cata', '品鉴', 'La cata exige silencio y atención.'),
                ('El catador', '品鉴师', 'El catador describió el aroma.'),
                ('El sumiller', '侍酒师', 'El sumiller recomendó un blanco joven.'),
                ('La bodega', '酒庄、酒窖', 'La bodega guarda barricas de roble.'),
                ('La barrica de roble', '橡木桶', 'La barrica de roble aporta vainilla.'),
                ('El vino de crianza', '陈酿葡萄酒', 'El vino de crianza pasa dos años en barrica.'),
                ('El vino de reserva', '珍藏葡萄酒', 'El vino de reserva aguanta bien el tiempo.'),
                ('La fermentación', '发酵', 'La fermentación alcohólica produce el vino.'),
            ],
            'grammar': [
                {'title': '描述与品鉴的词汇场', 'desc': 'a la plancha / al horno / a la sal / en su punto / al dente / bien hecho / poco hecho。注意「火候」用 el punto：La carne, en su punto。'},
                {'title': '表达来源、做法与传承', 'desc': 'de origen / procedente de / criado en / curado durante / elaborado artesanalmente。注意过去分词短语作后置定语：un queso curado durante dos años。'},
                {'title': '评价性表达（美食评论）', 'desc': 'destaca por / sobresale / resulta excesivo / no está a la altura de / merece la pena。注意 no estar a la altura de（配不上、达不到水准）是委婉的负面评价。'},
            ],
        },
    ],
}
