#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批次 74：B2 补 2 个单元（体育与健康管理 / 人际关系与家庭结构）→ B2 达 20 单元

为什么补这两个：B2 已有「健康与营养」（b2-u14）与「心理学与人际关系」（b2-u8），
但：
  - 体育与健康管理：B2 缺竞技体育（训练、伤病、赛事、反兴奋剂）这一语域，
    而 a2-u18 只有基础运动词
  - 人际关系与家庭结构：b2-u8 偏心理机制，缺家庭结构与法律层面
    （监护权、抚养费、收养、代际共居）—— 这是 B2 阅读（社会报道、法律咨询）的常见主题

所有词头已用全库比对校验：与现有 6000+ 词条零重复。
"""

BATCH = {
    'B2': [
        {
            'id': 'b2-u19', 'title': '体育与健康管理', 'subtitle': 'Deporte y Gestión de la Salud',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
                ('El rendimiento deportivo', '运动表现', 'El rendimiento deportivo depende del descanso.'),
                ('La preparación física', '体能训练', 'La preparación física empieza en agosto.'),
                ('El entrenamiento de fuerza', '力量训练', 'El entrenamiento de fuerza mejora la densidad ósea.'),
                ('El entrenamiento aeróbico', '有氧训练', 'El entrenamiento aeróbico cuida el corazón.'),
                ('Los estiramientos', '拉伸', 'Los estiramientos evitan lesiones.'),
                ('La recuperación muscular', '肌肉恢复', 'La recuperación muscular exige dormir bien.'),
                ('Las agujetas', '肌肉酸痛', 'Tengo agujetas de la carrera.'),
                ('La lesión muscular', '肌肉损伤', 'La lesión muscular lo dejó fuera un mes.'),
                ('El esguince', '扭伤', 'Se hizo un esguince de tobillo.'),
                ('La fractura por estrés', '应力性骨折', 'La fractura por estrés es típica en corredores.'),
                ('La tendinitis', '肌腱炎', 'La tendinitis se trata con reposo.'),
                ('La fisioterapia', '物理治疗', 'La fisioterapia aceleró la recuperación.'),
                ('El fisioterapeuta', '物理治疗师', 'El fisioterapeuta revisó la rodilla.'),
                ('El vendaje', '绷带包扎', 'Le pusieron un vendaje compresivo.'),
                ('El masaje deportivo', '运动按摩', 'El masaje deportivo alivia la sobrecarga.'),
                ('La crioterapia', '冷疗', 'La crioterapia reduce la inflamación.'),
                ('La hidratación', '补水', 'La hidratación es clave en verano.'),
                ('La bebida isotónica', '电解质饮料', 'La bebida isotónica repone sales.'),
                ('La suplementación', '营养补充', 'La suplementación debe ser prudente.'),
                ('La proteína de suero', '乳清蛋白', 'La proteína de suero se toma después de entrenar.'),
                ('Los aminoácidos', '氨基酸', 'Los aminoácidos ayudan a recuperar.'),
                ('El dopaje', '使用兴奋剂', 'El dopaje destruye la credibilidad del deporte.'),
                ('La sustancia prohibida', '违禁物质', 'La sustancia prohibida aparece en la lista anual.'),
                ('El control antidopaje', '兴奋剂检查', 'El control antidopaje se hizo por sorpresa.'),
                ('La sanción deportiva', '体育处罚', 'La sanción deportiva fue de dos años.'),
                ('La descalificación', '取消资格', 'La descalificación cambió el podio.'),
                ('El preparador físico', '体能教练', 'El preparador físico ajustó las cargas.'),
                ('El cuerpo técnico', '教练组', 'El cuerpo técnico analizó el rival.'),
                ('La estrategia de partido', '比赛策略', 'La estrategia de partido sorprendió al rival.'),
                ('La alineación', '首发阵容', 'La alineación dejó fuera al delantero.'),
                ('El banquillo', '替补席', 'Desde el banquillo animó a sus compañeros.'),
                ('El suplente', '替补球员', 'El suplente marcó al entrar.'),
                ('El tiempo añadido', '补时', 'Marcó en el tiempo añadido.'),
                ('El tanto', '进球', 'El tanto llegó en el minuto noventa.'),
                ('La asistencia', '助攻', 'Su asistencia fue decisiva.'),
                ('La posesión del balón', '控球率', 'La posesión del balón fue del setenta por ciento.'),
                ('La defensa en zona', '区域防守', 'La defensa en zona cerró los espacios.'),
                ('El contraataque', '反击', 'El contraataque sentenció el partido.'),
                ('El marcaje', '盯人', 'El marcaje individual anuló a su estrella.'),
                ('La falta personal', '个人犯规', 'La falta personal le costó la expulsión.'),
                ('La expulsión', '罚下场', 'La expulsión dejó al equipo con diez.'),
                ('La segunda parte', '下半场', 'En la segunda parte cambió el ritmo.'),
                ('El resultado final', '最终比分', 'El resultado final fue de dos a uno.'),
                ('La victoria ajustada', '艰难取胜', 'Fue una victoria ajustada por la mínima.'),
                ('La racha', '连场战绩', 'El equipo lleva una racha de cinco victorias.'),
                ('La moral del equipo', '球队士气', 'La moral del equipo está alta.'),
                ('El estadio', '体育场', 'El estadio se llenó una hora antes.'),
                ('La grada', '看台', 'La grada cantó hasta el final.'),
                ('El podio', '领奖台', 'Subió al podio por primera vez.'),
                ('El récord', '纪录', 'Batió el récord nacional.'),
                ('La plusmarca', '最好成绩', 'Su plusmarca aguantó diez años.'),
                ('Los Juegos Olímpicos', '奥运会', 'Los Juegos Olímpicos se celebran cada cuatro años.'),
            ],
            'grammar': [
                {'title': '表达因果、条件与让步（体育语境）', 'desc': 'a causa de / debido a / siempre que + 虚拟式 / aunque + 陈述式或虚拟式。注意 aunque + 陈述式表已知事实（Aunque está lesionado, juega），aunque + 虚拟式表假设（Aunque estuviera lesionado, jugaría）。'},
                {'title': '数量与程度的中级表达', 'desc': 'el doble de / la mitad de / un tercio de / cada vez más / mucho menos que。注意 la mitad de los jugadores 后动词随 la mitad 走单数：La mitad del equipo está lesionado。'},
                {'title': '被动与无人称在报道中', 'desc': 'fue sancionado / se le impuso una multa / se anunció que + 陈述式。体育报道常用自复被动与无人称，注意与格代词不可省：Se le impuso una sanción de dos años。'},
            ],
        },
        {
            'id': 'b2-u20', 'title': '人际关系与家庭结构', 'subtitle': 'Relaciones Personales y Estructura Familiar',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
                ('El noviazgo', '恋爱关系', 'Su noviazgo duró tres años.'),
                ('El matrimonio', '婚姻', 'El matrimonio se celebró en junio.'),
                ('La boda civil', '民政婚礼', 'Se casaron por lo civil.'),
                ('La unión estable', '稳定伴侣关系', 'La unión estable tiene efectos legales.'),
                ('La pareja de hecho', '事实伴侣', 'Se registraron como pareja de hecho.'),
                ('La custodia compartida', '共同监护', 'Pidieron la custodia compartida.'),
                ('La pensión alimenticia', '抚养费', 'La pensión alimenticia se revisa cada año.'),
                ('El régimen de visitas', '探视安排', 'El régimen de visitas se fijó en sentencia.'),
                ('La mediación familiar', '家庭调解', 'La mediación familiar evitó el juicio.'),
                ('El cónyuge', '配偶', 'El cónyuge no pudo asistir.'),
                ('La madrastra', '继母', 'Su madrastra lo trató siempre bien.'),
                ('El padrastro', '继父', 'El padrastro firmó la autorización.'),
                ('El hermanastro', '继兄弟', 'Tiene dos hermanastros mayores.'),
                ('La familia monoparental', '单亲家庭', 'La familia monoparental recibe ayuda.'),
                ('La familia numerosa', '多子女家庭', 'La familia numerosa tiene descuentos.'),
                ('La familia adoptiva', '收养家庭', 'La familia adoptiva pasó por un proceso largo.'),
                ('La adopción', '收养', 'La adopción tardó casi tres años.'),
                ('La tutela', '监护权', 'El juez le otorgó la tutela.'),
                ('El tutor legal', '法定监护人', 'El tutor legal firmó por el menor.'),
                ('La guarda y custodia', '监护与照护', 'La guarda y custodia quedó para la madre.'),
                ('El parentesco', '亲属关系', 'El parentesco se calcula por grados.'),
                ('El lazo familiar', '家庭纽带', 'El lazo familiar se mantuvo pese a la distancia.'),
                ('El yerno', '女婿', 'Su yerno cocina muy bien.'),
                ('La nuera', '儿媳', 'La nuera los visita cada domingo.'),
                ('El padrino', '教父、伴郎', 'El padrino pronunció unas palabras.'),
                ('El ahijado', '教子', 'Su ahijado cumple diez años.'),
                ('La viudedad', '丧偶', 'La viudedad le cambió la vida.'),
                ('El luto', '服丧', 'Guardó luto un año.'),
                ('La ausencia', '缺席、失去', 'La ausencia del padre se notaba.'),
                ('El apoyo emocional', '情感支持', 'El apoyo emocional fue fundamental.'),
                ('El conflicto familiar', '家庭矛盾', 'El conflicto familiar venía de años atrás.'),
                ('La reconciliación familiar', '家庭和解', 'La reconciliación familiar llegó en Navidad.'),
                ('La corresponsabilidad doméstica', '家务共担', 'La corresponsabilidad doméstica mejora la convivencia.'),
                ('La conciliación familiar', '家庭与工作平衡', 'La conciliación familiar sigue siendo difícil.'),
                ('El cuidado de los mayores', '照护老人', 'El cuidado de los mayores recae en las familias.'),
                ('La crianza', '养育', 'La crianza exige paciencia.'),
                ('La disciplina positiva', '正面管教', 'La disciplina positiva evita el castigo.'),
                ('El vínculo afectivo', '情感联结', 'El vínculo afectivo se construye en los primeros años.'),
                ('La confianza mutua', '相互信任', 'La confianza mutua es la base.'),
                ('La fidelidad', '忠诚', 'La fidelidad no se negocia.'),
                ('La dependencia emocional', '情感依赖', 'La dependencia emocional aísla.'),
                ('El desamor', '失恋、情伤', 'El desamor lo dejó sin ánimo.'),
                ('La amistad duradera', '长久友谊', 'La amistad duradera resiste la distancia.'),
                ('El círculo íntimo', '亲密圈子', 'Solo su círculo íntimo lo sabía.'),
                ('La red de apoyo', '支持网络', 'La red de apoyo familiar lo sostuvo.'),
                ('La soledad no deseada', '非自愿孤独', 'La soledad no deseada afecta a los mayores.'),
                ('El aislamiento social', '社会隔离', 'El aislamiento social agrava la enfermedad.'),
                ('La convivencia intergeneracional', '代际共居', 'La convivencia intergeneracional tiene ventajas.'),
                ('El hogar', '家（情感意义）', 'El hogar no es solo un piso.'),
                ('La unidad familiar', '家庭完整', 'La unidad familiar se mantuvo unida.'),
            ],
            'grammar': [
                {'title': '表达关系与状态的自复动词', 'desc': 'llevarse bien/mal con / parecerse a / separarse de / reconciliarse con / enamorarse de。注意这些动词的介词固定，且自复代词随人变化：Me llevo bien con ella。'},
                {'title': '让步与对比的书面连接', 'desc': 'mientras que / a diferencia de / en cambio / si bien。注意 mientras que 表对比时用陈述式，与表时间的 mientras（当……时）不同。'},
                {'title': '评价与情感的名词化', 'desc': 'el apoyo / el cuidado / la crianza / la convivencia。把动作写成名词便于论述：El cuidado de los mayores recae en las familias。注意 recaer en（落到……身上）是固定搭配。'},
            ],
        },
    ],
}
