# -*- coding: utf-8 -*-
"""批次 57：A1 补两个单元（学校与文具 / 动物与自然）

A1（602）仍是最低等级。选题避开 A1 已有 16 个单元
（问候/数字时间/家庭物品/自我介绍/日常活动/购物/餐厅/交通/颜色/
人物/衣服/天气/爱好/补充词/家与房间/身体与健康）。
「学校与文具」「动物与自然」两块尚未覆盖，且都是 A1 高频基础词。
"""

BATCH = {
    'A1': [
        {
            'id': 'a1-u19',
            'title': '学校与文具',
            'subtitle': 'La Escuela y el Material',
            'lessons': 10,
            'duration': '约 35 分钟',
            'vocab': [
                ('La escuela', '学校', 'Mi escuela está cerca de casa.'),
                ('El colegio', '小学', 'Los niños van al colegio andando.'),
                ('El instituto', '中学', 'Mi hermano estudia en el instituto.'),
                ('La universidad', '大学', 'Estudia en la universidad.'),
                ('La clase', '课、班级', 'La clase empieza a las nueve.'),
                ('El aula', '教室', 'El aula es grande y luminosa.'),
                ('El alumno', '学生', 'Los alumnos preguntan mucho.'),
                ('El estudiante', '大学生、求学者', 'Es un estudiante aplicado.'),
                ('El maestro', '老师（小学）', 'El maestro explica muy bien.'),
                ('La profesora', '女教师', 'La profesora de inglés es británica.'),
                ('El compañero', '同学、同伴', 'Mi compañero me presta el bolígrafo.'),
                ('La asignatura', '科目', 'Mi asignatura favorita es historia.'),
                ('La materia', '学科', 'Es una materia difícil.'),
                ('El horario', '课程表', 'Mira el horario de clases.'),
                ('El recreo', '课间休息', 'En el recreo jugamos al fútbol.'),
                ('La pizarra', '黑板', 'La profesora escribe en la pizarra.'),
                ('El pupitre', '课桌', 'Mi pupitre está al fondo.'),
                ('La silla', '椅子', 'Falta una silla en el aula.'),
                ('El libro', '书', 'El libro tiene muchas fotos.'),
                ('El cuaderno', '笔记本', 'Escribo en un cuaderno nuevo.'),
                ('La hoja', '纸张、页', 'Dame una hoja, por favor.'),
                ('El bolígrafo', '圆珠笔', '¿Me prestas un bolígrafo?'),
                ('El lápiz', '铅笔', 'Escribo con lápiz.'),
                ('La goma', '橡皮', '¿Tienes una goma?'),
                ('La regla', '尺子', 'Traza la línea con la regla.'),
                ('El sacapuntas', '卷笔刀', 'Se me olvidó el sacapuntas.'),
                ('La mochila', '书包', 'La mochila pesa mucho.'),
                ('El estuche', '笔袋', 'Guardo los lápices en el estuche.'),
                ('El rotulador', '记号笔', 'Subrayo con rotulador amarillo.'),
                ('La carpeta', '文件夹', 'Guardo los deberes en la carpeta.'),
                ('El diccionario', '词典', 'Busco la palabra en el diccionario.'),
                ('La palabra', '单词', 'No entiendo esta palabra.'),
                ('La frase', '句子', 'Traduce esta frase al español.'),
                ('El ejercicio', '练习', 'Hicimos cinco ejercicios.'),
                ('El deber', '作业', 'Tengo muchos deberes hoy.'),
                ('La tarea', '任务、作业', 'La tarea es para el lunes.'),
                ('El examen', '考试', 'El examen es el viernes.'),
                ('La nota', '分数', 'Saqué buena nota.'),
                ('La pregunta', '问题', 'Tengo una pregunta.'),
                ('La respuesta', '回答', 'Tu respuesta es correcta.'),
                ('El error', '错误', 'Corrige los errores.'),
                ('La lección', '课、课文', 'La lección tres es fácil.'),
                ('El tema', '主题、单元', 'El tema dos trata de la familia.'),
                ('La página', '页', 'Abre el libro por la página veinte.'),
                ('Aprender', '学习', 'Quiero aprender español.'),
                ('Estudiar', '学习、研读', 'Estudio dos horas al día.'),
                ('Enseñar', '教', 'Mi padre enseña matemáticas.'),
                ('Explicar', '讲解', '¿Puedes explicarlo otra vez?'),
                ('Preguntar', '提问', 'Pregunta si no entiendes.'),
                ('Contestar', '回答', 'Contesta en voz alta.'),
                ('Repetir', '重复', 'Repite la palabra, por favor.'),
                ('Escribir', '写', 'Escribe tu nombre aquí.'),
                ('Leer', '读', 'Leo un cuento cada noche.'),
                ('Dibujar', '画画', 'Dibuja un gato en el cuaderno.'),
                ('Subrayar', '划线', 'Subraya las palabras nuevas.'),
                ('Corregir', '改正、批改', 'El profesor corrige los ejercicios.'),
                ('Aprobar', '通过（考试）', 'Aprobé el examen de inglés.'),
                ('Suspender', '不及格', 'Suspendí las matemáticas.'),
                ('Repasar', '复习', 'Repaso antes del examen.'),
            ],
            'grammar': [
                {'title': '「上课/考试」的固定搭配', 'desc': 'tener clase（有课）/ dar clase（授课）/ hacer un examen（参加考试）/ aprobar un examen（通过）/ suspender（不及格）。注意「参加考试」用 hacer，不用 tomar（tomar 是拉美用法）。'},
                {'title': '学科名称与冠词', 'desc': 'las matemáticas / la historia / el inglés / la educación física。学科名一般带定冠词，且首字母不大写（与英语不同）。说「我的数学不好」用 Se me dan mal las matemáticas。'},
                {'title': 'aprender / estudiar / enseñar 的分工', 'desc': 'aprender ＝ 学会（结果）；estudiar ＝ 学习、研读（过程）；enseñar ＝ 教。注意 aprender 后接名词时不加介词（aprendo inglés），接不定式时要加 a（aprendo a nadar）。'},
            ],
        },
        {
            'id': 'a1-u20',
            'title': '动物与自然',
            'subtitle': 'Animales y Naturaleza',
            'lessons': 10,
            'duration': '约 35 分钟',
            'vocab': [
                ('El animal', '动物', 'Los animales necesitan agua.'),
                ('El perro', '狗', 'Mi perro se llama Toby.'),
                ('El gato', '猫', 'El gato duerme todo el día.'),
                ('El pájaro', '鸟', 'Los pájaros cantan al amanecer.'),
                ('El pez', '鱼', 'El pez nada muy rápido.'),
                ('El caballo', '马', 'Monta a caballo los domingos.'),
                ('La vaca', '牛', 'La vaca da leche.'),
                ('El cerdo', '猪', 'En el pueblo crían cerdos.'),
                ('La gallina', '母鸡', 'La gallina pone huevos.'),
                ('La oveja', '绵羊', 'Las ovejas pastan en el prado.'),
                ('El conejo', '兔子', 'El conejo come zanahorias.'),
                ('El ratón', '老鼠', 'Un ratón entró en la cocina.'),
                ('La abeja', '蜜蜂', 'Las abejas hacen miel.'),
                ('La mariposa', '蝴蝶', 'Una mariposa se posó en la flor.'),
                ('La hormiga', '蚂蚁', 'Las hormigas trabajan sin parar.'),
                ('El león', '狮子', 'El león es un animal salvaje.'),
                ('El oso', '熊', 'El oso duerme en invierno.'),
                ('El lobo', '狼', 'El lobo vive en el bosque.'),
                ('La serpiente', '蛇', 'La serpiente es peligrosa.'),
                ('El árbol', '树', 'El árbol da sombra.'),
                ('La flor', '花', 'Compré flores para mi madre.'),
                ('La hierba', '草', 'La hierba está muy verde.'),
                ('La hoja', '叶子', 'Las hojas caen en otoño.'),
                ('La rama', '树枝', 'El pájaro está en la rama.'),
                ('La raíz', '根', 'La raíz es muy profunda.'),
                ('El bosque', '森林', 'Paseamos por el bosque.'),
                ('El campo', '田野、乡下', 'Mis abuelos viven en el campo.'),
                ('El río', '河', 'El río pasa por el pueblo.'),
                ('El lago', '湖', 'El lago está tranquilo.'),
                ('La montaña', '山', 'La montaña está cubierta de nieve.'),
                ('El mar', '海', 'El mar está frío hoy.'),
                ('La playa', '海滩', 'La playa está llena en agosto.'),
                ('La isla', '岛', 'Es una isla pequeña.'),
                ('El cielo', '天空', 'El cielo está despejado.'),
                ('La estrella', '星星', 'Se ven muchas estrellas.'),
                ('La luna', '月亮', 'La luna está llena esta noche.'),
                ('El sol', '太阳', 'El sol calienta mucho.'),
                ('La piedra', '石头', 'Tropecé con una piedra.'),
                ('La arena', '沙子', 'La arena está caliente.'),
                ('El aire', '空气', 'El aire de la montaña es puro.'),
                ('El fuego', '火', 'Encendimos un fuego en la playa.'),
                ('El agua', '水', 'Bebe mucha agua en verano.'),
                ('La tierra', '土地、地球', 'La tierra está seca.'),
                ('El mundo', '世界', 'Quiere viajar por el mundo.'),
                ('La naturaleza', '自然', 'Me gusta la naturaleza.'),
                ('El medio ambiente', '环境', 'Hay que cuidar el medio ambiente.'),
                ('El clima', '气候', 'El clima aquí es suave.'),
                ('Salvaje', '野生的', 'Es un animal salvaje.'),
                ('Doméstico', '家养的', 'El perro es un animal doméstico.'),
                ('Peligroso', '危险的', 'Ese perro parece peligroso.'),
                ('Cuidar', '照顾、爱护', 'Cuido de mi gato.'),
                ('Alimentar', '喂养', 'Alimento a los pájaros en invierno.'),
                ('Pasear', '散步、遛', 'Paseo al perro cada mañana.'),
                ('Volar', '飞', 'Los pájaros vuelan alto.'),
                ('Nadar', '游泳', 'Los peces nadan en el río.'),
                ('Correr', '跑', 'El caballo corre por el prado.'),
                ('Cantar', '鸣叫、唱', 'Los pájaros cantan por la mañana.'),
                ('Plantar', '种植', 'Plantamos un árbol en el patio.'),
                ('Regar', '浇水', 'Riego las flores cada dos días.'),
                ('Recoger', '采摘、收拾', 'Recogimos fresas en el campo.'),
            ],
            'grammar': [
                {'title': '动物的量与集合表达', 'desc': 'un rebaño de ovejas（一群羊）/ una bandada de pájaros（一群鸟）/ un enjambre de abejas（一群蜂）。不同动物用不同的集合名词，这是 A1-B1 逐步习得的词汇。'},
                {'title': '无人称句表自然现象', 'desc': 'Llueve / Nieva / Hace sol / Amanece。自然现象用第三人称单数或无主语结构，与「天气表达」一脉相承。'},
                {'title': 'parecer + 形容词的用法', 'desc': 'Ese perro parece peligroso（那狗看起来危险）。parecer 表「看起来」，直接接形容词，不用 estar。与「es peligroso」（确实是危险的）语气不同。'},
            ],
        },
    ],
}
