#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批次 63：C1 补 2 个单元（全球卫生治理 / 信息生态与平台治理）

为什么补这两个：C1 是六个等级里单元数最少的（14 个），且缺两个高阶话题：
  - 全球卫生治理：全库没有任何等级覆盖公共卫生与流行病学词汇
  - 信息生态与平台治理：B2 有「媒体与信息素养」，C1 精读已有「算法时代的注意力经济」
    与「平衡报道如何沦为判断力的让渡」，但单元词汇层面缺这一主题

所有词头已用全库比对校验：与现有 5300+ 词条零重复（含仅冠词/大小写不同的情况）。
"""

BATCH = {
    'C1': [
        {
            'id': 'c1-u18', 'title': '全球卫生与公共健康治理', 'subtitle': 'Salud Global y Gobernanza Sanitaria',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
('La salud pública', '公共卫生', 'La salud pública protege a toda la población.'),
                ('El sistema sanitario', '医疗体系', 'El sistema sanitario combina recursos públicos y privados.'),
                ('La cobertura sanitaria', '医疗保障覆盖', 'La cobertura sanitaria universal es un objetivo pendiente.'),
                ('El acceso a la atención', '获得医疗服务', 'El acceso a la atención depende del territorio.'),
                ('La atención primaria', '基层医疗', 'La atención primaria resuelve la mayoría de consultas.'),
                ('La atención hospitalaria', '住院医疗', 'La atención hospitalaria concentra los casos graves.'),
                ('La consulta externa', '门诊', 'La consulta externa atiende sin ingreso.'),
                ('El ingreso hospitalario', '住院', 'El ingreso hospitalario duró cuatro días.'),
                ('El alta médica', '出院许可', 'Recibió el alta médica el viernes.'),
                ('La enfermería', '护理', 'La enfermería asume gran parte del cuidado.'),
                ('El personal sanitario', '医护人员', 'El personal sanitario trabajó sin descanso.'),
                ('El historial clínico', '病历', 'El historial clínico recoge el tratamiento previo.'),
                ('La historia clínica electrónica', '电子病历', 'La historia clínica electrónica agiliza las consultas.'),
                ('El tratamiento crónico', '慢性病治疗', 'El tratamiento crónico exige constancia.'),
                ('La adherencia terapéutica', '治疗依从性', 'La adherencia terapéutica mejora con recordatorios.'),
                ('La pauta posológica', '用药方案', 'La pauta posológica indica dosis y horarios.'),
                ('El efecto adverso', '不良反应', 'El efecto adverso obligó a cambiar el fármaco.'),
                ('La contraindicación', '禁忌症', 'La contraindicación aparece en el prospecto.'),
                ('La interacción farmacológica', '药物相互作用', 'La interacción farmacológica puede anular el efecto.'),
                ('El ensayo aleatorizado', '随机对照试验', 'El ensayo aleatorizado reparte el azar entre grupos.'),
                ('El doble ciego', '双盲', 'El doble ciego evita que la expectativa sesgue el resultado.'),
                ('El placebo', '安慰剂', 'El placebo produce mejora sin principio activo.'),
                ('La medicina basada en la evidencia', '循证医学', 'La medicina basada en la evidencia parte de estudios sistemáticos.'),
                ('La guía clínica', '临床指南', 'La guía clínica unifica criterios de tratamiento.'),
                ('El protocolo sanitario', '医疗规程', 'El protocolo sanitario define cada paso.'),
                ('La vigilancia epidemiológica', '流行病监测', 'La vigilancia epidemiológica detecta brotes temprano.'),
                ('El brote epidémico', '疫情暴发', 'El brote epidémico se contuvo en dos semanas.'),
                ('El contagio', '传染', 'El contagio ocurre por vía respiratoria.'),
                ('La tasa de incidencia', '发病率', 'La tasa de incidencia mide casos nuevos.'),
                ('La tasa de letalidad', '病死率', 'La tasa de letalidad depende de la edad.'),
                ('La inmunidad de grupo', '群体免疫', 'La inmunidad de grupo protege a quien no puede vacunarse.'),
                ('La vacunación masiva', '大规模接种', 'La vacunación masiva redujo los ingresos.'),
                ('La cobertura vacunal', '疫苗接种率', 'La cobertura vacunal varía por comunidad.'),
                ('La cepa', '病毒株', 'Una cepa nueva puede escapar a la inmunidad.'),
                ('La mutación', '变异', 'La mutación cambió el comportamiento del virus.'),
                ('La zoonosis', '人畜共患病', 'La zoonosis salta de animales a personas.'),
                ('La endemia', '地方性流行', 'La endemia mantiene casos estables en el tiempo.'),
                ('El vector', '传播媒介', 'El mosquito actúa como vector de la enfermedad.'),
                ('La cuarentena', '隔离检疫', 'La cuarentena se aplicó a los contactos.'),
                ('El rastreo de contactos', '接触者追踪', 'El rastreo de contactos corta las cadenas de contagio.'),
                ('La detección precoz', '早期发现', 'La detección precoz mejora el pronóstico.'),
                ('La prueba diagnóstica', '诊断检测', 'La prueba diagnóstica tarda veinticuatro horas.'),
                ('El falso positivo', '假阳性', 'Un falso positivo obliga a repetir la prueba.'),
                ('La sensibilidad diagnóstica', '检测灵敏度', 'La sensibilidad diagnóstica detecta casos leves.'),
                ('La especificidad', '检测特异度', 'La especificidad descarta a los sanos.'),
                ('El certificado sanitario', '健康证明', 'El certificado sanitario acredita la vacunación.'),
                ('La cooperación sanitaria internacional', '国际卫生合作', 'La cooperación sanitaria internacional comparte datos.'),
                ('La emergencia sanitaria', '卫生紧急状态', 'La emergencia sanitaria se declaró en marzo.'),
                ('La asignación de recursos', '资源分配', 'La asignación de recursos planteó dilemas éticos.'),
                ('El triaje', '分诊', 'El triaje ordena la atención por gravedad.'),
                ('La priorización', '优先排序', 'La priorización de pacientes siguió criterios clínicos.'),
                ('La equidad sanitaria', '卫生公平', 'La equidad sanitaria exige corregir desigualdades.'),
                ('Los determinantes sociales de la salud', '健康的社会决定因素', 'Los determinantes sociales explican parte de las diferencias.'),
                ('La prevención primaria', '一级预防', 'La prevención primaria actúa antes de la enfermedad.'),
                ('La promoción de la salud', '健康促进', 'La promoción de la salud trabaja sobre hábitos.'),
                ('La carga de la enfermedad', '疾病负担', 'La carga de la enfermedad se mide en años perdidos.'),
            ],
            'grammar': [
                {'title': '卫生政策文本的无人称与被动', 'desc': 'se recomienda / se desaconseja / queda establecido que。注意区分 se recomienda + 不定式（建议做某事）与 se recomienda que + 虚拟式：Se recomienda que se vacune la población de riesgo。'},
                {'title': '表达因果、条件与例外（卫生语境）', 'desc': 'a condición de que + 虚拟式 / salvo en caso de / siempre que se cumplan los requisitos。例外条款常用 salvo que + 虚拟式：Salvo que exista contraindicación。'},
                {'title': '数量、比例与趋势的学术表述', 'desc': 'la tasa de / la proporción de / un tercio de la población / duplicarse respecto a。注意 tasa（率）与 proporción（比例）在学术文本中不能互换：tasa 以时间为分母。'},
            ],
        },
        {
            'id': 'c1-u19', 'title': '信息生态与平台治理', 'subtitle': 'Ecosistema Informativo y Gobernanza de Plataformas',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
('La información errónea', '错误信息（非故意）', 'La información errónea se difunde sin mala fe.'),
                ('La noticia falsa', '假新闻', 'La noticia falsa imita el formato del periodismo.'),
                ('La cadena de reenvíos', '转发链', 'La cadena de reenvíos pierde el origen.'),
                ('La verificación de datos', '事实核查', 'La verificación de datos exige tiempo.'),
                ('El verificador', '核查员', 'El verificador comprueba cada afirmación.'),
                ('La agencia de verificación', '核查机构', 'La agencia de verificación publica sus métodos.'),
                ('La fuente anónima', '匿名信源', 'La fuente anónima exige corroboración.'),
                ('La filtración interesada', '有动机的泄露', 'La filtración interesada busca influir.'),
                ('La manipulación informativa', '信息操控', 'La manipulación informativa distorsiona el debate.'),
                ('La autocensura', '自我审查', 'La autocensura limita lo que se publica.'),
                ('La polarización', '两极分化', 'La polarización reduce el espacio común.'),
                ('La cámara de eco', '回音室', 'La cámara de eco repite la misma posición.'),
                ('La burbuja de filtros', '过滤气泡', 'La burbuja de filtros oculta lo que no confirma.'),
                ('El sesgo de algoritmo', '算法偏见', 'El sesgo de algoritmo reproduce desigualdades.'),
                ('La recomendación algorítmica', '算法推荐', 'La recomendación algorítmica guía lo que leemos.'),
                ('La viralidad', '病毒式传播', 'La viralidad premia la emoción, no la exactitud.'),
                ('El alcance orgánico', '自然触达', 'El alcance orgánico cayó tras el cambio.'),
                ('La amplificación', '放大效应', 'La amplificación multiplica el error.'),
                ('El microtargeting', '精准投放', 'El microtargeting adapta el mensaje a cada perfil.'),
                ('La segmentación de audiencias', '受众细分', 'La segmentación de audiencias fragmenta el debate.'),
                ('La publicidad programática', '程序化广告', 'La publicidad programática decide en milisegundos.'),
                ('El modelo de negocio', '商业模式', 'El modelo de negocio depende de la atención.'),
                ('La economía de la atención', '注意力经济', 'La economía de la atención compite por el tiempo.'),
                ('El tiempo de permanencia', '停留时长', 'El tiempo de permanencia mide el enganche.'),
                ('El titular llamativo', '吸睛标题', 'El titular llamativo promete más de lo que dice.'),
                ('El sensacionalismo', '耸动报道', 'El sensacionalismo exagera para captar clics.'),
                ('El amarillismo', '黄色新闻手法', 'El amarillismo explota el escándalo.'),
                ('La posverdad', '后真相', 'La posverdad apela a la emoción antes que al dato.'),
                ('La narrativa dominante', '主流叙事', 'La narrativa dominante deja fuera otras voces.'),
                ('La agenda mediática', '媒体议程', 'La agenda mediática decide qué se discute.'),
                ('La espiral del silencio', '沉默的螺旋', 'La espiral del silencio silencia la opinión minoritaria.'),
                ('La trazabilidad de la fuente', '信源可追溯', 'La trazabilidad de la fuente permite auditar.'),
                ('La corrección', '更正', 'La corrección se publica en el mismo lugar.'),
                ('El derecho de rectificación', '更正权', 'El derecho de rectificación protege al afectado.'),
                ('La competencia informacional', '信息素养', 'La competencia informacional enseña a evaluar fuentes.'),
                ('La verificación cruzada', '交叉核实', 'La verificación cruzada busca una segunda fuente.'),
                ('La consulta experta', '专家咨询', 'La consulta experta aporta contexto técnico.'),
                ('La controversia artificial', '人为制造的争议', 'La controversia artificial da voz a una minoría ínfima.'),
                ('La falsa equivalencia', '虚假对等', 'La falsa equivalencia equipara evidencia y opinión.'),
                ('El negacionismo', '否认主义', 'El negacionismo rechaza la evidencia disponible.'),
                ('La teoría conspirativa', '阴谋论', 'La teoría conspirativa explica todo con un solo actor.'),
                ('La exposición selectiva', '选择性接触', 'La exposición selectiva evita lo que incomoda.'),
                ('La identidad de grupo', '群体认同', 'La identidad de grupo refuerza la cohesión.'),
                ('La tribu digital', '网络部落', 'La tribu digital comparte códigos y enemigos.'),
                ('La comunidad virtual', '虚拟社区', 'La comunidad virtual se organiza sin territorio.'),
                ('La moderación de contenidos', '内容审核', 'La moderación de contenidos aplica normas públicas.'),
                ('Las normas comunitarias', '社区准则', 'Las normas comunitarias definen lo permitido.'),
                ('La retirada de contenido', '下架内容', 'La retirada de contenido exige motivación.'),
                ('La desmonetización', '取消变现', 'La desmonetización castiga al creador infractor.'),
                ('La responsabilidad de intermediario', '中介责任', 'La responsabilidad de intermediario limita la plataforma.'),
                ('El puerto seguro', '避风港原则', 'El puerto seguro exime si se retira con diligencia.'),
                ('La diligencia debida', '尽职义务', 'La diligencia debida obliga a evaluar riesgos.'),
                ('La transparencia algorítmica', '算法透明度', 'La transparencia algorítmica permite auditar decisiones.'),
                ('La auditoría algorítmica', '算法审计', 'La auditoría algorítmica revisa sesgos y efectos.'),
                ('La regulación de plataformas', '平台监管', 'La regulación de plataformas fija deberes de cuidado.'),
                ('El servicio digital', '数字服务', 'El servicio digital se presta sin presencia física.'),
                ('La competencia desleal', '不正当竞争', 'La competencia desleal abusa de la posición dominante.'),
                ('La posición dominante', '市场支配地位', 'La posición dominante obliga a deberes especiales.'),
            ],
            'grammar': [
                {'title': '论证中的让步与反驳（高阶）', 'desc': 'si bien / aun admitiendo que / conviene matizar que / cabe objetar que。aun admitiendo que 后面用虚拟式，表示「即便承认」；cabe + 不定式是无人称的学术表达。'},
                {'title': '表达限定、范围与保留', 'desc': 'en la medida en que / en tanto que / desde el punto de vista de / en lo que respecta a。en tanto que 表「就……而言」时不带虚拟式；表「只要」时用陈述式。'},
                {'title': '元语言论述的名词化', 'desc': '把论断写成名词短语以便评价：afirmar → la afirmación，cuestionar → el cuestionamiento，matizar → el matiz。学术写作常用 la afirmación según la cual…（……这一论断）。'},
            ],
        },
    ],
}
