# -*- coding: utf-8 -*-
"""批次 51：A1 补两个单元（家与房间 / 身体与健康）

A1（484）在补完 A2 后成为最低等级，也点名在目标第三阶段里。
选题避开 A1 已有 14 个单元（问候/数字时间/家庭物品/自我介绍/日常活动/
购物/餐厅/交通/颜色/人物/衣服/天气/爱好/补充词）。
"""

BATCH = {
    'A1': [
        {
            'id': 'a1-u17',
            'title': '家与房间',
            'subtitle': 'La Casa y las Habitaciones',
            'lessons': 12,
            'duration': '约 35 分钟',
            'vocab': [
                ('La casa', '房子', 'Mi casa tiene dos plantas.'),
                ('El piso', '公寓', 'Vivimos en un piso pequeño.'),
                ('El apartamento', '公寓（拉美常用）', 'Alquilan un apartamento amueblado.'),
                ('La habitación', '房间、卧室', 'Mi habitación da al patio.'),
                ('El dormitorio', '卧室', 'El dormitorio es pequeño pero luminoso.'),
                ('El salón', '客厅', 'Vemos la tele en el salón.'),
                ('La cocina', '厨房', 'La cocina es muy estrecha.'),
                ('El baño', '浴室、卫生间', 'El baño está al fondo.'),
                ('El pasillo', '走廊', 'Hay libros por todo el pasillo.'),
                ('El balcón', '阳台', 'Desayunamos en el balcón.'),
                ('La terraza', '露台', 'La terraza da al mar.'),
                ('El garaje', '车库', 'El garaje es compartido.'),
                ('El trastero', '储藏室', 'Guardamos las maletas en el trastero.'),
                ('La planta', '楼层', 'Vivo en la tercera planta.'),
                ('El ascensor', '电梯', 'El ascensor no funciona hoy.'),
                ('La escalera', '楼梯', 'Subimos por la escalera.'),
                ('La puerta', '门', 'Cierra la puerta, por favor.'),
                ('La ventana', '窗户', 'Abre la ventana un poco.'),
                ('La pared', '墙', 'Pintamos la pared de blanco.'),
                ('El suelo', '地板、地面', 'El suelo es de madera.'),
                ('El techo', '天花板、屋顶', 'El techo es muy alto.'),
                ('La mesa', '桌子', 'La mesa está junto a la ventana.'),
                ('La silla', '椅子', 'Falta una silla.'),
                ('El sofá', '沙发', 'El gato duerme en el sofá.'),
                ('La cama', '床', 'La cama es muy cómoda.'),
                ('El armario', '衣柜', 'La ropa está en el armario.'),
                ('El cajón', '抽屉', 'Las llaves están en el cajón.'),
                ('La estantería', '书架', 'La estantería está llena.'),
                ('La lámpara', '台灯、灯', 'Enciende la lámpara, por favor.'),
                ('El espejo', '镜子', 'Se mira en el espejo.'),
                ('La nevera', '冰箱', 'La leche está en la nevera.'),
                ('El horno', '烤箱', 'El horno tarda en calentar.'),
                ('El microondas', '微波炉', 'Caliento la sopa en el microondas.'),
                ('El lavabo', '洗手池', 'El lavabo está ocupado.'),
                ('La ducha', '淋浴', 'La ducha tiene poca presión.'),
                ('La bañera', '浴缸', 'Prefiero la bañera a la ducha.'),
                ('La toalla', '毛巾', 'Necesito una toalla limpia.'),
                ('El jabón', '肥皂', 'Se acabó el jabón.'),
                ('La almohada', '枕头', 'La almohada es demasiado blanda.'),
                ('La manta', '毯子', 'Hace frío, pon otra manta.'),
                ('La sábana', '床单', 'Cambio las sábanas los domingos.'),
                ('La cortina', '窗帘', 'Corre las cortinas, hay mucho sol.'),
                ('La alfombra', '地毯', 'La alfombra del salón es vieja.'),
                ('El cuadro', '画、画框', 'El cuadro cuelga de la pared.'),
                ('La llave', '钥匙', 'He perdido las llaves.'),
                ('El timbre', '门铃', 'Llama al timbre dos veces.'),
                ('El vecino', '邻居', 'El vecino de arriba hace ruido.'),
                ('El alquiler', '租金', 'El alquiler incluye los gastos.'),
                ('El casero', '房东', 'El casero vive en el mismo edificio.'),
                ('Amueblado', '带家具的', 'El piso viene amueblado.'),
                ('Ordenado', '整洁的', 'Su habitación está siempre ordenada.'),
                ('Desordenado', '凌乱的', 'Mi escritorio está desordenado.'),
                ('Luminoso', '采光好的', 'El salón es muy luminoso.'),
                ('Silencioso', '安静的', 'Es un barrio silencioso.'),
                ('Céntrico', '市中心的', 'El piso es céntrico y caro.'),
                ('Limpiar', '打扫', 'Limpio el baño los sábados.'),
                ('Ordenar', '整理', 'Hay que ordenar la habitación.'),
                ('Guardar', '收起来、放好', 'Guarda la ropa en el armario.'),
                ('Colgar', '挂', 'Cuelga el abrigo en la percha.'),
                ('Tirar', '扔掉', 'Tira esos papeles viejos.'),
            ],
            'grammar': [
                {'title': 'estar 与 hay 表位置的区别', 'desc': 'hay 表「有、存在」（不确定或首次提及）：Hay una mesa en el salón。está 表「已知事物的具体位置」：La mesa está junto a la ventana。这是 A1 阶段最容易混淆的一对。'},
                {'title': '序数词表楼层', 'desc': 'la primera planta / la segunda planta / la tercera。注意西班牙的「一层」是 planta baja（底楼），中国的「一楼」在西班牙叫 planta baja，「二楼」才是 primera planta。'},
                {'title': '方位短语', 'desc': 'junto a（紧挨）/ al lado de（旁边）/ enfrente de（对面）/ delante de（前面）/ detrás de（后面）/ encima de（上面）/ debajo de（下面）。都是「短语 + de + 名词」结构，de 不能省略。'},
            ],
        },
        {
            'id': 'a1-u18',
            'title': '身体与健康',
            'subtitle': 'El Cuerpo y la Salud',
            'lessons': 12,
            'duration': '约 35 分钟',
            'vocab': [
                ('La cabeza', '头', 'Me duele la cabeza.'),
                ('El pelo', '头发', 'Tiene el pelo rubio.'),
                ('La cara', '脸', 'Tiene la cara muy seria.'),
                ('El ojo', '眼睛', 'Le duelen los ojos de leer.'),
                ('La nariz', '鼻子', 'Tiene la nariz tapada.'),
                ('La boca', '嘴', 'Abre la boca, por favor.'),
                ('La oreja', '耳朵', 'Me pica la oreja.'),
                ('El diente', '牙齿', 'Me duele un diente.'),
                ('La garganta', '喉咙', 'Tengo la garganta irritada.'),
                ('El cuello', '脖子', 'Me duele el cuello.'),
                ('El hombro', '肩膀', 'Tengo el hombro cargado.'),
                ('El brazo', '胳膊', 'Se rompió el brazo jugando.'),
                ('La mano', '手', 'Lávate las manos.'),
                ('El dedo', '手指、脚趾', 'Me corté un dedo.'),
                ('La espalda', '背', 'Me duele la espalda al sentarme.'),
                ('El pecho', '胸', 'Siento presión en el pecho.'),
                ('La barriga', '肚子', 'Me duele la barriga.'),
                ('La pierna', '腿', 'Tengo la pierna cansada.'),
                ('La rodilla', '膝盖', 'Se hizo daño en la rodilla.'),
                ('El pie', '脚', 'Me duelen los pies de caminar.'),
                ('La salud', '健康', 'La salud es lo más importante.'),
                ('El síntoma', '症状', '¿Qué síntomas tiene?'),
                ('La fiebre', '发烧', 'Tiene fiebre desde ayer.'),
                ('La tos', '咳嗽', 'Tengo tos y me duele el pecho.'),
                ('El resfriado', '感冒', 'Cogí un resfriado en invierno.'),
                ('La gripe', '流感', 'La gripe dura una semana.'),
                ('El dolor', '疼痛', 'El dolor va y viene.'),
                ('El dolor de cabeza', '头痛', 'Tengo un dolor de cabeza fuerte.'),
                ('La herida', '伤口', 'La herida ya está cerrada.'),
                ('La quemadura', '烧伤、烫伤', 'Se puso hielo en la quemadura.'),
                ('La alergia', '过敏', 'Tengo alergia al polen.'),
                ('El medicamento', '药物', 'Tome el medicamento con agua.'),
                ('La pastilla', '药片', 'Una pastilla cada ocho horas.'),
                ('La receta', '处方', 'El médico me dio una receta.'),
                ('El médico', '医生', 'El médico me escuchó con atención.'),
                ('La enfermera', '护士', 'La enfermera puso la inyección.'),
                ('El dentista', '牙医', 'Voy al dentista dos veces al año.'),
                ('El hospital', '医院', 'Lo llevaron al hospital.'),
                ('La farmacia', '药店', 'La farmacia de guardia está cerca.'),
                ('La consulta', '诊室、门诊', 'La consulta es a las cinco.'),
                ('La cita médica', '就医预约', 'Tengo cita médica el jueves.'),
                ('La urgencia', '急诊', 'Fuimos a urgencias de noche.'),
                ('La ambulancia', '救护车', 'Llamaron a una ambulancia.'),
                ('El tratamiento', '治疗', 'El tratamiento dura tres meses.'),
                ('La vacuna', '疫苗', 'Ya tengo la vacuna puesta.'),
                ('El análisis', '化验', 'Los análisis salieron bien.'),
                ('La radiografía', 'X 光片', 'Le hicieron una radiografía.'),
                ('Descansar', '休息', 'Debe descansar unos días.'),
                ('Curarse', '痊愈', 'Se curó en una semana.'),
                ('Empeorar', '恶化', 'El dolor empeoró por la noche.'),
                ('Mejorar', '好转', 'Ya empiezo a mejorar.'),
                ('Sentirse bien', '感觉好', 'Hoy me siento bien.'),
                ('Sentirse mal', '感觉不好', 'Me siento mal desde ayer.'),
                ('Guardar cama', '卧床', 'Tuvo que guardar cama tres días.'),
                ('Guardar reposo', '静养', 'El médico le dijo que guardara reposo.'),
                ('Hacer ejercicio', '做运动', 'Hacer ejercicio mejora el ánimo.'),
                ('Dejar de fumar', '戒烟', 'Dejó de fumar por salud.'),
                ('Cuidarse', '保重身体', 'Tienes que cuidarte más.'),
            ],
            'grammar': [
                {'title': 'doler 的用法（复习与扩展）', 'desc': '身体部位作主语，人用与格代词：me duele la cabeza / me duelen los pies。单复数由部位决定。同类还有 picar（痒）、molestar（不适）。'},
                {'title': 'tener + 症状名词', 'desc': 'tener fiebre / tener tos / tener gripe / tener dolor de... —— 注意这些名词前不加冠词：Tengo fiebre（我发烧）。加冠词会变成特指「那种烧」。'},
                {'title': '建议与义务的初级表达', 'desc': 'debes + 不定式（你应该）/ tienes que（你必须）/ hay que（应该，无人称）/ es mejor que + 虚拟式（最好是）。看病场景中医生常用这些句式给出建议。'},
            ],
        },
    ],
}
