# -*- coding: utf-8 -*-
"""批次 27：A2 扩充（交通出行 / 学习与考试）"""

BATCH = {
    'A2': [
        {
            'id': 'a2-u10',
            'title': '城市交通与出行',
            'subtitle': 'Transporte Urbano',
            'lessons': 11,
            'duration': '约 40 分钟',
            'vocab': [
                ('El metro', '地铁', 'El metro es más rápido.'),
                ('La línea', '线路', 'Tome la línea dos.'),
                ('La estación', '车站', 'Bájese en la próxima estación.'),
                ('El andén', '站台', 'El tren sale del andén tres.'),
                ('El billete', '车票', 'Un billete sencillo, por favor.'),
                ('El abono', '月票', 'Compré el abono mensual.'),
                ('La tarjeta de transporte', '交通卡', 'Recargué la tarjeta de transporte.'),
                ('El autobús', '公交车', 'El autobús pasa cada diez minutos.'),
                ('La parada', '公交站', 'La parada está a la derecha.'),
                ('El tranvía', '有轨电车', 'El tranvía va por el centro.'),
                ('El taxi', '出租车', 'Pedimos un taxi.'),
                ('La parada de taxi', '出租车候客点', 'Hay una parada de taxi enfrente.'),
                ('El conductor', '司机', 'El conductor fue muy amable.'),
                ('El pasajero', '乘客', 'Los pasajeros esperaban en el andén.'),
                ('El tráfico', '交通流量', 'Hay mucho tráfico a esta hora.'),
                ('El atasco', '堵车', 'Me pilló un atasco enorme.'),
                ('La hora punta', '高峰时段', 'Evito el metro en hora punta.'),
                ('El semáforo', '红绿灯', 'Gire en el semáforo.'),
                ('La acera', '人行道', 'Camina por la acera.'),
                ('El cruce', '路口', 'Gire a la izquierda en el cruce.'),
                ('La rotonda', '环岛', 'Tome la segunda salida de la rotonda.'),
                ('La esquina', '拐角', 'Está en la esquina.'),
                ('La dirección', '方向、地址', 'Vamos en dirección contraria.'),
                ('El sentido', '方向', 'Circulaba en sentido prohibido.'),
                ('El carril', '车道', 'Circula por el carril derecho.'),
                ('El aparcamiento', '停车场', 'El aparcamiento está completo.'),
                ('Aparcar', '停车', 'Es difícil aparcar aquí.'),
                ('La multa', '罚单', 'Me pusieron una multa.'),
                ('El límite de velocidad', '限速', 'El límite es de cincuenta.'),
                ('El cinturón', '安全带', 'Ponte el cinturón, por favor.'),
                ('El casco', '头盔', 'Lleva casco siempre.'),
                ('La gasolina', '汽油', 'La gasolina ha subido otra vez.'),
                ('Repostar', '加油', 'Paramos a repostar.'),
                ('El peaje', '过路费', 'Pagamos el peaje en efectivo.'),
                ('La autopista', '高速公路', 'La autopista estaba cortada.'),
                ('El desvío', '绕行', 'Hay un desvío por obras.'),
                ('La obra', '施工', 'Las obras durarán dos meses.'),
                ('El retraso', '延误', 'El tren lleva veinte minutos de retraso.'),
                ('La frecuencia', '班次频率', 'La frecuencia es de ocho minutos.'),
                ('La salida', '出口、发车', 'La salida es por la puerta dos.'),
                ('La llegada', '到达', 'La llegada está prevista a las seis.'),
                ('Perderse', '迷路', 'Me perdí en el centro.'),
                ('El mapa', '地图', 'Mira el mapa del metro.'),
                ('La aplicación', '应用程序', 'Uso una aplicación para el transporte.'),
                ('Coger', '乘坐、赶上', 'Coge el autobús número doce.'),
                ('Perder el tren', '错过火车', 'Perdí el tren por cinco minutos.'),
                ('Transbordar', '换乘', 'Hay que transbordar en Sol.'),
                ('Ir a pie', '步行', 'Vamos a pie, está cerca.'),
                ('Cerca / Lejos', '近 / 远', 'Está lejos de aquí.'),
                ('A la derecha / izquierda', '向右 / 向左', 'Gire a la derecha.'),
            ],
            'grammar': [
                {'title': '命令式指路（usted 与 tú）', 'desc': 'tú：Gira, Sigue, Toma（不规则：ve, ven, di, haz, pon, sal, sé, ten）。usted：Gire, Siga, Tome（用虚拟式第三人称形式）。公共场所标识多用 usted 形式。'},
                {'title': 'ir a + 不定式表将来', 'desc': 'Voy a coger el metro（我要坐地铁）。比将来时更口语，也用于表达近期计划。注意与 ir a + 地点（去某地）区分。'},
                {'title': '表达距离与位置', 'desc': 'estar a + 距离（Está a cinco minutos）；quedar + 距离（Me queda lejos）；estar cerca/lejos de；al lado de / enfrente de / detrás de / entre A y B。'},
            ],
        },
        {
            'id': 'a2-u11',
            'title': '学习与考试',
            'subtitle': 'Estudios y Exámenes',
            'lessons': 11,
            'duration': '约 40 分钟',
            'vocab': [
                ('El colegio', '小学 / 学校', 'Mis hijos van al colegio.'),
                ('El instituto', '中学', 'Estudia en un instituto público.'),
                ('La universidad', '大学', 'Estudia en la universidad.'),
                ('La asignatura', '科目', 'La historia es mi asignatura favorita.'),
                ('La clase', '课', 'La clase empieza a las nueve.'),
                ('El aula', '教室', 'El aula está en el segundo piso.'),
                ('El profesor', '老师', 'El profesor explica muy bien.'),
                ('El alumno', '学生', 'Los alumnos hicieron preguntas.'),
                ('El horario', '课程表', 'Mira el horario de clases.'),
                ('El semestre', '学期', 'El semestre termina en junio.'),
                ('La carrera', '专业、学业', 'Estudio la carrera de Derecho.'),
                ('La nota', '分数', 'Saqué una buena nota.'),
                ('Aprobar', '及格', 'Aprobé el examen por poco.'),
                ('Suspender', '不及格', 'Suspendí las matemáticas.'),
                ('El examen', '考试', 'El examen es el martes.'),
                ('El parcial', '期中考', 'Tengo un parcial la semana que viene.'),
                ('El final', '期末考', 'El examen final es en junio.'),
                ('La convocatoria', '考期', 'La segunda convocatoria es en septiembre.'),
                ('El temario', '考纲、课程内容', 'El temario es muy amplio.'),
                ('Repasar', '复习', 'Repasaré los apuntes esta noche.'),
                ('Los apuntes', '笔记', 'Le pedí los apuntes a Ana.'),
                ('El resumen', '摘要', 'Hice un resumen de dos páginas.'),
                ('El trabajo', '作业、论文', 'Tengo que entregar el trabajo el viernes.'),
                ('La práctica', '练习', 'Hicimos una práctica en grupo.'),
                ('El plazo', '截止日期', 'El plazo termina hoy.'),
                ('Entregar', '提交', 'Entregué el trabajo a tiempo.'),
                ('La beca', '奖学金', 'Solicité una beca Erasmus.'),
                ('Matricularse', '注册', 'Me matriculé en septiembre.'),
                ('La matrícula', '注册费', 'La matrícula cuesta mil euros.'),
                ('El aula de estudio', '自习室', 'La biblioteca tiene aulas de estudio.'),
                ('La biblioteca', '图书馆', 'Estudio en la biblioteca.'),
                ('El préstamo', '借阅', 'El préstamo dura quince días.'),
                ('La investigación', '研究', 'Su investigación es sobre el clima.'),
                ('El título', '学位、证书', 'Obtuvo el título en junio.'),
                ('El máster', '硕士', 'Hace un máster en economía.'),
                ('El doctorado', '博士', 'Empezó el doctorado este año.'),
                ('El compañero de clase', '同学', 'Mi compañero de clase es de Perú.'),
                ('El grupo de trabajo', '小组', 'El grupo de trabajo tiene cinco personas.'),
                ('La exposición', '课堂报告', 'Hice una exposición sobre Cervantes.'),
                ('El debate', '讨论', 'Participamos en un debate.'),
                ('Aprender de memoria', '背诵', 'No sirve aprender de memoria sin entender.'),
                ('Ponerse nervioso', '紧张', 'Me pongo nervioso antes de los exámenes.'),
                ('Concentrarse', '集中注意力', 'No consigo concentrarme con ruido.'),
                ('Aprovechar el tiempo', '利用时间', 'Hay que aprovechar el tiempo.'),
                ('Suspender por los pelos', '勉强没过', 'Suspendí por los pelos.'),
                ('Sacar buenas notas', '取得好成绩', 'Siempre saca buenas notas.'),
                ('Estar en el paro', '失业', 'Lleva un año en el paro.'),
                ('La formación', '培训', 'Hice un curso de formación.'),
                ('El curso', '课程', 'Hice un curso de verano.'),
                ('La titulación', '学历', 'Se exige titulación universitaria.'),
                ('El esfuerzo', '努力', 'Con esfuerzo se consigue todo.'),
            ],
            'grammar': [
                {'title': 'tener que / hay que / deber', 'desc': 'tener que + 不定式（某人必须）：Tengo que estudiar；hay que + 不定式（客观需要、无人称）：Hay que entregarlo hoy；deber + 不定式（应该，含建议）：Deberías repasar。'},
                {'title': 'antes de / después de / al + 不定式', 'desc': 'antes de entregar（提交之前）；después de estudiar（学完之后）；al terminar（一结束就）。注意后接不定式而非从句，主语与主句一致。'},
                {'title': '表目的的表达', 'desc': 'para + 不定式（为了）：Estudio para aprobar；para que + 虚拟式（为了某人做某事）：Te lo digo para que lo sepas；a fin de + 不定式（较正式）。'},
            ],
        },
    ],
}
