# -*- coding: utf-8 -*-
"""批次 37：补最后 6 个真内容词缺口（由主审计的「内容词」分类报出）+ B1 扩充"""

BATCH = {
    'B1': [
        {
            'id': 'b1-u13',
            'title': '补充常用词与表达',
            'subtitle': 'Vocabulario Complementario',
            'lessons': 10,
            'duration': '约 35 分钟',
            'vocab': [
                ('La disponibilidad', '可用性、可支配性', 'Confirma tu disponibilidad para el lunes.'),
                ('Erosionar', '侵蚀、削弱', 'La crisis erosionó la confianza.'),
                ('Estructural', '结构性的', 'Es un problema estructural, no coyuntural.'),
                ('El incentivo', '激励、诱因', 'El incentivo funcionó mejor que la multa.'),
                ('Sonrojarse', '脸红', 'Se sonrojó al oír el elogio.'),
                ('Transcribir', '转写、抄录', 'Transcribió la entrevista completa.'),
                ('La contrapartida', '对价、代价', 'Toda ventaja tiene su contrapartida.'),
                ('El margen', '余地、利润率', 'No hay margen para más recortes.'),
                ('La trayectoria', '轨迹、履历', 'Su trayectoria profesional es sólida.'),
                ('El planteamiento', '思路、方案', 'El planteamiento inicial era distinto.'),
                ('La repercusión', '影响、反响', 'La noticia tuvo gran repercusión.'),
                ('El alcance', '范围、影响面', 'El alcance del acuerdo es limitado.'),
                ('La magnitud', '规模、量级', 'No se conocía la magnitud del daño.'),
                ('El umbral', '门槛、阈值', 'Superó el umbral de rentabilidad.'),
                ('La dotación', '拨款、配备', 'La dotación de personal se redujo.'),
                ('El reparto', '分配', 'El reparto de tareas fue desigual.'),
                ('La asignación', '拨给、分配', 'La asignación presupuestaria es insuficiente.'),
                ('El desfase', '时间差、错位', 'Hay un desfase entre lo previsto y lo real.'),
                ('La franja', '时段、区带', 'La franja horaria de mayor audiencia es la noche.'),
                ('El conglomerado', '集聚体、集团', 'Es un conglomerado de empresas.'),
                ('La sinergia', '协同效应', 'La sinergia entre equipos fue clave.'),
                ('El baremo', '评分标准', 'El baremo se hizo público.'),
                ('La ratio', '比率', 'La ratio alumnos por aula es alta.'),
                ('El cómputo', '总计、核算', 'El cómputo final dio otro resultado.'),
                ('La salvedad', '保留、例外', 'Aceptó con una salvedad importante.'),
                ('El resquicio', '缝隙、可乘之机', 'La norma deja un resquicio legal.'),
                ('La tesitura', '处境、局面', 'En esa tesitura, dimitir era lo prudente.'),
                ('El trasfondo', '背景、底层', 'El trasfondo del conflicto es económico.'),
                ('El escollo', '障碍、暗礁', 'Quedan dos escollos por salvar.'),
                ('La aquiescencia', '默许', 'Su aquiescencia fue silenciosa.'),
                ('El cúmulo', '堆集、一连串', 'Fue un cúmulo de malentendidos.'),
                ('La tesitura económica', '经济处境', 'La tesitura económica es delicada.'),
                ('El repunte', '回升', 'Se observa un repunte del consumo.'),
                ('El declive', '衰落', 'El declive industrial empezó en los ochenta.'),
                ('La pujanza', '兴盛、强劲', 'La pujanza del sector sorprendió.'),
                ('El estancamiento', '停滞', 'El estancamiento salarial persiste.'),
                ('La merma', '减少、损耗', 'Hubo una merma en la producción.'),
                ('El reparto de competencias', '职权划分', 'El reparto de competencias es confuso.'),
                ('El entramado', '体系、网络', 'El entramado institucional es complejo.'),
                ('La gobernanza', '治理', 'La gobernanza del agua es un reto.'),
                ('La rendición de cuentas', '问责', 'Sin rendición de cuentas no hay confianza.'),
                ('El contrapeso', '制衡', 'La prensa actúa como contrapeso.'),
                ('La salvaguarda', '保障', 'La salvaguarda de derechos es prioritaria.'),
                ('El resorte', '手段、弹簧', 'Usó todos los resortes a su alcance.'),
                ('La palanca', '杠杆、手段', 'La educación es la palanca del cambio.'),
                ('El catalizador', '催化剂', 'La crisis actuó como catalizador.'),
                ('La antesala', '前厅、前奏', 'La reunión fue la antesala del acuerdo.'),
                ('El punto de inflexión', '转折点', 'Ese año fue un punto de inflexión.'),
                ('La senda', '路径', 'La economía vuelve a la senda del crecimiento.'),
                ('El horizonte', '前景、视野', 'El horizonte de recuperación se aleja.'),
                ('La cesión', '让与、转让', 'La cesión de competencias fue polémica.'),
                ('El óbice', '障碍', 'No hay óbice legal para hacerlo.'),
                ('La rémora', '拖累', 'Esa deuda es una rémora para el país.'),
                ('El acicate', '激励', 'La competencia es un acicate.'),
                ('La réplica', '回应、复制品', 'Su réplica llegó tarde y sin datos.'),
            ],
            'grammar': [
                {'title': '经济与社会语域的名词化', 'desc': 'estancamiento、repunte、declive、merma、pujanza —— 这些名词由动词派生（estancarse→estancamiento），在新闻报道中比动词形式更常见。掌握名词化是从 B1 迈向 B2 的关键一步。'},
                {'title': '结构性与周期性问题的区分', 'desc': 'estructural（结构性的）vs coyuntural（周期性的、暂时的）。这是经济评论中最重要的一对概念，用错会直接改变论断的性质：结构性问题无法靠短期措施解决。'},
                {'title': '表「手段与障碍」的名词', 'desc': 'palanca（杠杆）/ resorte（手段）/ acicate（激励）/ catalizador（催化剂）表推动因素；óbice / rémora / escollo / lastre 表阻碍。写作时按「推动 vs 阻碍」分两栏记忆。'},
            ],
        },
    ],
}
