# -*- coding: utf-8 -*-
"""批次 52：补齐新增单元的结构类语法点（10 组 / 40 题）

第 9-10 轮新增 10 个单元，带来 29 个新语法点。逐条分类后：
- 约 10 个是可出题的**结构**，本批覆盖
- 其余是与单元主题绑定的**表达**（餐饮句式、运动搭配、可持续表达等），
  已在搭配库里作为语块覆盖，不硬拆成选择题
"""
GROUPS = [
    ('序数与楼层', [
        ('Vivo en la ___ planta.', ['tercera', 'tres', 'tercero', 'trece'], 0,
         '序数词修饰阴性名词 planta 时用 tercera（tercero → tercera）。基数词 tres 不能直接修饰 planta。'),
        ('Mi oficina está en el ___ piso.', ['quinto', 'cinco', 'quinta', 'quintos'], 0,
         'piso 是阳性单数，用序数词 quinto。注意序数词要与名词的性数一致。'),
        ('La tienda está en la planta ___.', ['baja', 'bajo', 'primera baja', 'bajos'], 0,
         'planta baja ＝ 底楼。西班牙的 planta baja 相当于中国的「一楼」，primera planta 才是「二楼」。'),
        ('Es el ___ día de clase.', ['primer', 'primero', 'primera', 'uno'], 0,
         '序数词 primero 在阳性单数名词前要省略 -o：el primer día。同类还有 tercero → tercer。'),
    ]),
    ('方位与位置', [
        ('La farmacia está ___ del supermercado.', ['enfrente', 'enfrente a', 'en frente', 'frente'], 0,
         'enfrente de ＝ 在……对面。这是「短语 + de + 名词」结构，de 不能省。'),
        ('El gato está ___ la mesa.', ['debajo de', 'debajo', 'bajo de', 'abajo'], 0,
         'debajo de ＝ 在……下面。debajo 是副词，接名词必须加 de。'),
        ('Las llaves están ___ del cajón.', ['encima', 'encima a', 'en cima', 'arriba'], 0,
         'encima de ＝ 在……上面。arriba 表方向（向上），不能接名词。'),
        ('El coche está ___ de la casa.', ['delante', 'delante a', 'en delante', 'antes'], 0,
         'delante de ＝ 在……前面。与 detrás de（在后面）相对。'),
    ]),
    ('食物状态与烹饪方式', [
        ('Quiero la carne poco ___.', ['hecha', 'hecho', 'hacer', 'hecha de'], 0,
         'poco hecho/a ＝ 半熟。形容词要与 carne（阴性）一致，所以用 hecha。'),
        ('El pescado está a la ___.', ['plancha', 'plano', 'planchado', 'planchar'], 0,
         'a la plancha ＝ 铁板煎。这是固定搭配，plancha 不能变形。'),
        ('Prefiero la carne al ___.', ['punto', 'horno', 'puntos', 'punto de'], 0,
         'al punto ＝ 中等熟度。与 poco hecho（半熟）、muy hecho（全熟）构成肉的三种熟度。'),
        ('El pollo está ___ horno.', ['al', 'a el', 'en el', 'de'], 0,
         'al horno ＝ 烤箱烤的。a + el 缩合为 al，不能分写。'),
    ]),
    ('比赛结果', [
        ('Ganamos ___ dos a uno.', ['por', 'a', 'de', 'en'], 0,
         'ganar por + 比分 ＝ 以某比分获胜。比分内部用 a 连接：dos a uno。'),
        ('El partido terminó en ___.', ['empate', 'empatar', 'empatado', 'empates'], 0,
         'terminar en empate ＝ 以平局结束。empate 是名词，前面用 en。'),
        ('Perdimos ___ el equipo rival.', ['contra', 'a', 'con', 'de'], 0,
         'perder contra ＝ 输给。也可以用 perder con，但 contra 更明确表「对抗」。'),
        ('El marcador quedó dos ___ cero.', ['a', 'y', 'por', 'con'], 0,
         '比分用 a 连接两个数字：dos a cero。不用 y（那是加法）。'),
    ]),
    ('花费类动词辨析', [
        ('Este abrigo me ___ doscientos euros.', ['costó', 'gastó', 'pagó', 'cobró'], 0,
         'costar 的主语是物品，人用与格代词：me costó doscientos euros（这花了我 200 欧）。'),
        ('___ demasiado dinero en restaurantes.', ['Gasto', 'Cuesto', 'Cobro', 'Costo'], 0,
         'gastar 的主语是人（我花钱）。costar 的主语是物，cobrar 是「收取」。'),
        ('El camarero nos ___ la cuenta.', ['cobró', 'gastó', 'costó', 'pagó'], 0,
         'cobrar ＝ 收取（服务员向我们收账）。pagar 方向相反，是付款方。'),
        ('Le ___ veinte euros por el taxi.', ['pagué', 'cobré', 'gasté', 'costé'], 0,
         'pagar ＝ 支付。pagué 的主语是付款人，le 指收款方。'),
    ]),
    ('出发与到达的动词搭配', [
        ('Salimos ___ Madrid el lunes.', ['para', 'de', 'a', 'en'], 0,
         'salir para + 目的地 ＝ 出发前往。salir de + 出发地 才是「从某地出发」。'),
        ('El tren llega ___ Sevilla a las ocho.', ['a', 'en', 'de', 'para'], 0,
         'llegar a + 地点 ＝ 到达某地。这是固定搭配，不能用 en。'),
        ('Volvimos ___ Roma el domingo.', ['de', 'a', 'en', 'para'], 0,
         'volver de + 地点 ＝ 从某地回来。volver a 后接不定式则表「再次做」。'),
        ('Nos fuimos ___ viaje sin avisar.', ['de', 'a', 'en', 'para'], 0,
         'irse de viaje ＝ 出远门。这是固定搭配，de 不能换。'),
    ]),
    ('变化过程的自复动词', [
        ('El barrio se ha ___ mucho en diez años.', ['transformado', 'transformando', 'transformar', 'transforma'], 0,
         'transformarse 表「经历转变」。haber + 分词构成完成时，所以用 transformado。'),
        ('Las diferencias se han ___.', ['acentuado', 'acentuando', 'acentuar', 'acentúan'], 0,
         'acentuarse ＝ 加剧。完成时用过去分词 acentuado。'),
        ('La tendencia se ha ___.', ['suavizado', 'suavizando', 'suavizar', 'suaviza'], 0,
         'suavizarse ＝ 缓和。这类自复动词表过程，与「ser + 形容词」不同——后者是静态描述。'),
        ('La curva demográfica se ha ___.', ['invertido', 'invirtiendo', 'invertir', 'invierte'], 0,
         'invertirse ＝ 逆转。注意 invertir 的分词不规则拼写为 invertido。'),
    ]),
    ('义务与许可的层级', [
        ('No ___ fumar aquí; está prohibido.', ['se debe', 'se deben', 'se debe que', 'deber'], 0,
         'no se debe + 不定式 ＝ 不应该。无人称结构，动词固定第三人称单数。'),
        ('___ de estar durmiendo; no contesta.', ['Debe', 'Debe que', 'Deba', 'Debiendo'], 0,
         'deber de + 不定式 ＝ 推测（他大概在睡）。注意与 deber + 不定式（应当）的区别。'),
        ('___ actuar con prudencia.', ['Se debe', 'Se deben', 'Se debe de', 'Deben'], 0,
         'se debe + 不定式 ＝ 应当（无人称）。加 de 就变成推测了，语义不同。'),
        ('No ___ justificar esa decisión.', ['cabe', 'caben', 'cabe que', 'caber'], 0,
         'no cabe + 不定式 ＝ 无法、没有余地。书面语中表「不可能/不该」的正式说法。'),
    ]),
    ('表「制约」与「决定」的动词梯度', [
        ('El contexto ___ la interpretación.', ['condiciona', 'determina que', 'condiciona a', 'condición'], 0,
         'condicionar ＝ 制约（有影响但非唯一因素）。主语是语境，直接接宾语，不加介词。'),
        ('El coste ___ la decisión final.', ['determinó', 'condicionó a', 'determinó a', 'determina que'], 0,
         'determinar ＝ 决定（更强）。determinar 直接接宾语，不定式或从句才需要介词/连词。'),
        ('La falta de datos ___ el retraso.', ['provocó', 'condicionó a', 'provocó a', 'provoca que'], 0,
         'provocar ＝ 导致（最强）。condicionar < determinar < provocar 是强度递增的三档。'),
        ('Su actitud ___ en parte el resultado.', ['influyó', 'influyó a', 'influye que', 'influencia'], 0,
         'influir en ＝ 对……有影响。注意介词固定为 en，不是 a。'),
    ]),
    ('自复动词表投入与兴趣', [
        ('Se ___ al ciclismo tras la lesión.', ['aficionó', 'aficiona a', 'aficionando', 'afición'], 0,
         'aficionarse a ＝ 迷上。aficionó 是第三人称简单过去时，注意保留 a。'),
        ('Me he ___ a un torneo de pádel.', ['apuntado', 'apuntando', 'apuntar', 'apunta'], 0,
         'apuntarse a ＝ 报名参加。完成时用过去分词 apuntado。'),
        ('Se ___ a los videojuegos muy pronto.', ['enganchó', 'engancha a', 'enganchando', 'enganche'], 0,
         'engancharse a ＝ 上瘾、迷上。这类自复动词都表「使自己投入某事」。'),
        ('___ mucho a la lectura desde niño.', ['Se aficionó', 'Aficionó', 'Se aficionando', 'Aficionarse'], 0,
         '自复动词必须带代词：se aficionó。缺了 se 句子不成立。'),
    ]),
]
