# -*- coding: utf-8 -*-
"""批次 29：难度曲线打平（A1 ×2 / A2 ×2 / B1 ×2）

B2 已有 551 词，明显高于其他等级。本批补低等级，让曲线平滑。
"""

BATCH = {
    'A1': [
        {
            'id': 'a1-u14',
            'title': '天气与季节',
            'subtitle': 'El Tiempo y las Estaciones',
            'lessons': 10,
            'duration': '约 35 分钟',
            'vocab': [
                ('El tiempo', '天气', '¿Qué tiempo hace hoy?'),
                ('Hace sol', '晴天', 'Hoy hace sol y no hace frío.'),
                ('Hace calor', '天热', 'En verano hace mucho calor.'),
                ('Hace frío', '天冷', 'En diciembre hace frío.'),
                ('Hace viento', '刮风', 'Hace viento, cierra la ventana.'),
                ('Llueve', '下雨', 'Llueve mucho en abril.'),
                ('Nieva', '下雪', 'En la montaña nieva en enero.'),
                ('La lluvia', '雨', 'Me gusta el sonido de la lluvia.'),
                ('La nieve', '雪', 'La nieve cubrió el parque.'),
                ('El sol', '太阳', 'El sol sale a las siete.'),
                ('La nube', '云', 'No hay ni una nube.'),
                ('El cielo', '天空', 'El cielo está gris.'),
                ('La primavera', '春天', 'En primavera todo florece.'),
                ('El verano', '夏天', 'En verano vamos a la playa.'),
                ('El otoño', '秋天', 'En otoño llueve más.'),
                ('El invierno', '冬天', 'El invierno aquí es suave.'),
                ('La estación', '季节', 'Mi estación favorita es el otoño.'),
                ('La temperatura', '温度', 'La temperatura baja por la noche.'),
                ('Los grados', '度', 'Estamos a treinta grados.'),
                ('El paraguas', '雨伞', 'Coge el paraguas, va a llover.'),
                ('El abrigo', '大衣', 'Ponte el abrigo, hace frío.'),
                ('La bufanda', '围巾', 'Llevo bufanda en invierno.'),
                ('El gorro', '帽子', 'El niño perdió su gorro.'),
                ('Los guantes', '手套', 'Necesito guantes para la nieve.'),
                ('Las botas', '靴子', 'Con estas botas no te mojas.'),
                ('La playa', '海滩', 'La playa está llena en agosto.'),
                ('El mar', '海', 'El mar está tranquilo hoy.'),
                ('La montaña', '山', 'Subimos a la montaña el sábado.'),
                ('El campo', '乡下', 'Mis abuelos viven en el campo.'),
                ('La ciudad', '城市', 'La ciudad es ruidosa pero cómoda.'),
                ('La nube gris', '乌云', 'Mira esas nubes grises.'),
                ('El pronóstico', '天气预报', 'El pronóstico dice que lloverá.'),
                ('La tormenta', '暴风雨', 'Hubo una tormenta anoche.'),
                ('El arcoíris', '彩虹', 'Después de la lluvia salió un arcoíris.'),
                ('El clima', '气候', 'El clima de aquí es húmedo.'),
                ('Húmedo', '潮湿的', 'El aire está muy húmedo.'),
                ('Seco', '干燥的', 'El verano es seco en el sur.'),
                ('Nublado', '多云的', 'Hoy está nublado.'),
                ('Despejado', '晴朗的', 'El cielo está despejado.'),
                ('Fresco', '凉爽的', 'Por la mañana hace fresco.'),
                ('La brisa', '微风', 'Una brisa suave entra por la ventana.'),
                ('El charco', '水坑', 'Los niños saltan en los charcos.'),
                ('Mojarse', '淋湿', 'Me mojé esperando el autobús.'),
                ('Abrigar', '保暖', 'Abrígate bien antes de salir.'),
                ('Refrescarse', '乘凉', 'Nos refrescamos a la sombra.'),
                ('La sombra', '阴凉处', 'Sentémonos a la sombra.'),
                ('El calor', '热', 'No soporto este calor.'),
                ('La niebla', '雾', 'Había niebla en la carretera.'),
                ('El granizo', '冰雹', 'El granizo dañó los cultivos.'),
                ('La ola de calor', '热浪', 'Una ola de calor azota el sur.'),
            ],
            'grammar': [
                {'title': '天气的表达方式', 'desc': 'hacer + 名词：Hace sol / Hace frío / Hace viento。下雨下雪用专门动词：Llueve / Nieva（第三人称单数，无主语）。说温度用 estar a + 数字 + grados：Estamos a treinta grados。'},
                {'title': 'estar + 形容词表天气状态', 'desc': 'El cielo está nublado / despejado。天气状态是暂时的，用 estar 不用 ser。对比：El clima es húmedo（气候特征，用 ser）。'},
                {'title': '季节与介词', 'desc': 'en + 季节：en primavera / en verano / en otoño / en invierno。en + 月份：en enero。注意月份和季节首字母不大写。'},
            ],
        },
        {
            'id': 'a1-u15',
            'title': '爱好与休闲',
            'subtitle': 'Aficiones y Tiempo Libre',
            'lessons': 10,
            'duration': '约 35 分钟',
            'vocab': [
                ('La afición', '爱好', 'Mi mayor afición es la fotografía.'),
                ('El tiempo libre', '空闲时间', '¿Qué haces en tu tiempo libre?'),
                ('El pasatiempo', '消遣', 'Leer es un buen pasatiempo.'),
                ('Leer', '阅读', 'Leo antes de dormir.'),
                ('Escribir', '写作', 'Escribo en un diario.'),
                ('Dibujar', '画画', 'Dibujo en cuadernos pequeños.'),
                ('Pintar', '绘画', 'Pinta acuarelas los domingos.'),
                ('Cantar', '唱歌', 'Canta en un coro.'),
                ('Bailar', '跳舞', 'Bailamos salsa los viernes.'),
                ('Tocar la guitarra', '弹吉他', 'Toco la guitarra desde niño.'),
                ('El instrumento', '乐器', '¿Tocas algún instrumento?'),
                ('La música', '音乐', 'Escucho música mientras cocino.'),
                ('La canción', '歌曲', 'Esta canción me encanta.'),
                ('El concierto', '演唱会', 'Fuimos a un concierto anoche.'),
                ('La película', '电影', 'Vimos una película en casa.'),
                ('El cine', '电影院', 'El cine está al lado del mercado.'),
                ('El libro', '书', 'Este libro es muy interesante.'),
                ('La novela', '小说', 'Leo una novela policiaca.'),
                ('La revista', '杂志', 'Compro una revista de viajes.'),
                ('El cómic', '漫画', 'De niño leía muchos cómics.'),
                ('El juego', '游戏', 'Es solo un juego, no te enfades.'),
                ('Jugar a', '玩（运动/游戏）', 'Juego al tenis los sábados.'),
                ('El ajedrez', '国际象棋', 'Aprendí a jugar al ajedrez.'),
                ('Las cartas', '纸牌', 'Jugamos a las cartas en familia.'),
                ('El deporte', '运动', 'Hago deporte tres veces por semana.'),
                ('Correr', '跑步', 'Corro por el parque al amanecer.'),
                ('Nadar', '游泳', 'Nado mejor que corro.'),
                ('Montar en bici', '骑自行车', 'Monto en bici para ir al trabajo.'),
                ('El equipo', '球队', 'Mi equipo ganó el partido.'),
                ('El partido', '比赛', 'El partido empieza a las nueve.'),
                ('Ganar', '赢', 'Ganamos por dos a uno.'),
                ('Perder', '输', 'Es normal perder a veces.'),
                ('El gimnasio', '健身房', 'Voy al gimnasio por la mañana.'),
                ('El entrenamiento', '训练', 'El entrenamiento dura una hora.'),
                ('La excursión', '远足', 'Hicimos una excursión al lago.'),
                ('Acampar', '露营', 'Acampamos junto al río.'),
                ('Pescar', '钓鱼', 'Mi tío pesca los domingos.'),
                ('La fotografía', '摄影', 'La fotografía me relaja mucho.'),
                ('La colección', '收藏', 'Tengo una colección de sellos.'),
                ('El sello', '邮票', 'Este sello es muy antiguo.'),
                ('El taller', '工作坊', 'Hago un taller de cerámica.'),
                ('La cerámica', '陶艺', 'La cerámica requiere paciencia.'),
                ('Tejer', '编织', 'Mi abuela teje bufandas.'),
                ('El club', '俱乐部', 'Me uní a un club de lectura.'),
                ('La reunión', '聚会', 'La reunión del club es el martes.'),
                ('Divertirse', '玩得开心', 'Nos divertimos mucho juntos.'),
                ('Descansar', '休息', 'Descanso los domingos.'),
                ('Aburrirse', '觉得无聊', 'Me aburro en casa todo el día.'),
                ('Apasionar', '使着迷', 'Me apasiona la historia.'),
                ('Dedicar tiempo a', '把时间用于', 'Dedico tiempo a aprender idiomas.'),
            ],
            'grammar': [
                {'title': 'jugar a + 运动/游戏', 'desc': 'jugar 后面接运动或游戏时必须加 a：Juego al tenis / Juego a las cartas。jugar al + 阳性运动（al fútbol），jugar a la + 阴性（a la pelota）。u→ue 变位：juego / juegas / juega。'},
                {'title': '表示频率的说法', 'desc': 'todos los días / una vez a la semana / dos veces por semana / los sábados / de vez en cuando / casi nunca / siempre。注意「每周两次」用 dos veces por semana 或 a la semana。'},
                {'title': 'gustar / encantar / apasionar', 'desc': '这类动词的主语是被喜欢的事物：Me gusta leer / Me encantan los libros。apasionar 语气最强：Me apasiona la historia（我对历史着迷）。复数事物用复数动词。'},
            ],
        },
    ],
    'A2': [
        {
            'id': 'a2-u15',
            'title': '工作与职业',
            'subtitle': 'Trabajo y Profesiones',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('El oficio', '手艺、职业', 'Aprendió el oficio de su padre.'),
                ('La profesión', '职业', '¿Cuál es tu profesión?'),
                ('El puesto', '职位', 'Consiguió un puesto en una empresa.'),
                ('La empresa', '公司', 'Trabajo en una empresa pequeña.'),
                ('El jefe', '上司、老板', 'Mi jefe es exigente pero justo.'),
                ('El compañero', '同事', 'Mis compañeros son muy amables.'),
                ('El horario', '工作时间', 'Mi horario es de nueve a seis.'),
                ('El turno', '班次', 'Hago el turno de noche.'),
                ('La jornada', '工作日', 'La jornada laboral es de ocho horas.'),
                ('El sueldo', '工资', 'El sueldo no es muy alto.'),
                ('El salario', '薪水', 'Piden experiencia y buen salario.'),
                ('La nómina', '工资单', 'La nómina llega el día veinticinco.'),
                ('El contrato', '合同', 'Firmé un contrato temporal.'),
                ('La plantilla', '员工总数', 'La plantilla creció este año.'),
                ('La entrevista', '面试', 'Tuve una entrevista ayer.'),
                ('El currículum', '简历', 'Envié mi currículum por correo.'),
                ('La solicitud', '申请', 'Rellené la solicitud en línea.'),
                ('El título', '学历、证书', 'Tiene el título de ingeniero.'),
                ('La experiencia', '经验', 'Necesitan tres años de experiencia.'),
                ('El ascenso', '升职', 'Le dieron un ascenso merecido.'),
                ('El despido', '解雇', 'El despido fue improcedente.'),
                ('El paro', '失业', 'Estuvo en el paro seis meses.'),
                ('La baja', '休假、病假', 'Está de baja por enfermedad.'),
                ('Las vacaciones', '假期', 'Tengo veinte días de vacaciones.'),
                ('El permiso', '许可、请假', 'Pedí un permiso de dos días.'),
                ('La reunión', '会议', 'La reunión duró dos horas.'),
                ('El proyecto', '项目', 'Trabajo en un proyecto nuevo.'),
                ('La tarea', '任务', 'Terminé la tarea antes de comer.'),
                ('El plazo', '截止期限', 'El plazo termina el viernes.'),
                ('La entrega', '交付', 'La entrega es la próxima semana.'),
                ('El informe', '报告', 'Escribí el informe mensual.'),
                ('La herramienta', '工具', 'Usamos varias herramientas digitales.'),
                ('El ordenador', '电脑', 'Trabajo todo el día con el ordenador.'),
                ('La impresora', '打印机', 'La impresora no funciona.'),
                ('El correo electrónico', '电子邮件', 'Te lo mando por correo electrónico.'),
                ('La llamada', '电话', 'Recibí una llamada del cliente.'),
                ('El cliente', '客户', 'El cliente está contento.'),
                ('El proveedor', '供应商', 'Cambiamos de proveedor.'),
                ('La factura', '发票', 'Envié la factura ayer.'),
                ('El presupuesto', '预算', 'El presupuesto es limitado.'),
                ('El gasto', '支出', 'Redujimos los gastos.'),
                ('El beneficio', '利润', 'La empresa tuvo beneficios.'),
                ('La pérdida', '亏损', 'Sufrimos pérdidas este trimestre.'),
                ('El socio', '合伙人', 'Mi socio se encarga de las ventas.'),
                ('El autónomo', '个体经营者', 'Trabaja como autónomo.'),
                ('El funcionario', '公务员', 'Su madre es funcionaria.'),
                ('Solicitar', '申请', 'Solicité una beca.'),
                ('Contratar', '雇用', 'La contrataron en marzo.'),
                ('Renunciar', '辞职', 'Renunció por motivos personales.'),
                ('Ascender', '晋升', 'Ascendió a jefa de equipo.'),
                ('Despedir', '解雇', 'Despidieron a dos personas.'),
                ('Encargarse de', '负责', 'Me encargo de los pedidos.'),
                ('Cumplir con', '完成、遵守', 'Cumplimos con los plazos.'),
            ],
            'grammar': [
                {'title': '职业的表达与冠词', 'desc': '说职业时一般不加冠词：Soy ingeniero / Es profesora。但带修饰语时要加：Es un ingeniero muy bueno。trabajar de + 职业：Trabaja de enfermera。trabajar en + 地点/公司。'},
                {'title': 'estar de + 名词表状态', 'desc': 'estar de baja（病假）/ estar de vacaciones（休假）/ estar de turno（值班）/ estar en paro（失业）。这是固定搭配，不能用 ser 替换。'},
                {'title': '被动语态与无人称句（职场语境）', 'desc': 'se + 动词第三人称是职场书面语高频结构：Se solicita experiencia / Se valorará el inglés / Se ofrece contrato indefinido。这是招聘启事的标准句式，主语是职位或条件。'},
            ],
        },
        {
            'id': 'a2-u16',
            'title': '银行与支付',
            'subtitle': 'Banca y Pagos',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('El banco', '银行', 'Voy al banco por la mañana.'),
                ('La sucursal', '分行', 'La sucursal más cercana está aquí.'),
                ('La caja', '柜台、收银台', 'Pague en la caja número tres.'),
                ('El cajero automático', '自动取款机', 'No hay cajero en esta calle.'),
                ('La ventanilla', '窗口', 'Espere en la ventanilla dos.'),
                ('La cuenta', '账户', 'Abrí una cuenta nueva.'),
                ('La cuenta corriente', '活期账户', 'El sueldo entra en mi cuenta corriente.'),
                ('La libreta', '存折', 'Ya no uso libreta.'),
                ('El saldo', '余额', 'Consulta el saldo en la app.'),
                ('El ingreso', '存款、入账', 'Hice un ingreso de cien euros.'),
                ('La retirada', '取款', 'La retirada tiene comisión.'),
                ('La transferencia', '转账', 'Hice una transferencia al casero.'),
                ('La domiciliación', '自动扣款', 'Tengo domiciliados los recibos.'),
                ('El recibo', '账单', 'El recibo de la luz subió.'),
                ('El extracto', '对账单', 'Reviso el extracto cada mes.'),
                ('La comisión', '手续费', 'El banco cobra una comisión.'),
                ('El interés', '利息', 'El interés del préstamo es bajo.'),
                ('El préstamo', '贷款', 'Pedimos un préstamo hipotecario.'),
                ('La hipoteca', '房贷', 'Pagamos la hipoteca en treinta años.'),
                ('El crédito', '信贷', 'Le concedieron el crédito.'),
                ('El aval', '担保', 'Necesita un aval para el alquiler.'),
                ('La deuda', '债务', 'Pagó toda la deuda.'),
                ('El ahorro', '储蓄', 'Vivo de mis ahorros.'),
                ('La inversión', '投资', 'Es una inversión a largo plazo.'),
                ('El efectivo', '现金', '¿Puedo pagar en efectivo?'),
                ('La tarjeta', '卡', 'Se me olvidó la tarjeta.'),
                ('La tarjeta de crédito', '信用卡', 'Pago con tarjeta de crédito.'),
                ('La tarjeta de débito', '借记卡', 'La de débito descuenta al momento.'),
                ('El contacto', '非接触式（支付）', 'Pago sin contacto, por favor.'),
                ('El billete', '纸币', 'No tengo billetes pequeños.'),
                ('La moneda', '硬币、货币', 'Guardo monedas en un bote.'),
                ('El cambio', '零钱、找零', 'Quédese con el cambio.'),
                ('El vuelto', '找零', 'Me dio mal el vuelto.'),
                ('La factura', '发票', 'Necesito la factura con IVA.'),
                ('El impuesto', '税', 'Los impuestos subieron este año.'),
                ('El IVA', '增值税', 'El IVA está incluido en el precio.'),
                ('La declaración', '申报', 'Hice la declaración de la renta.'),
                ('El seguro', '保险', 'Contraté un seguro de viaje.'),
                ('La prima', '保费', 'La prima anual es de trescientos euros.'),
                ('La póliza', '保单', 'Guarda la póliza en un cajón.'),
                ('La nómina', '工资单', 'El banco pide dos nóminas.'),
                ('El presupuesto', '预算', 'Ajustamos el presupuesto familiar.'),
                ('El gasto', '开支', 'Controlo los gastos con una app.'),
                ('La cuota', '月供、分摊费', 'La cuota mensual es de doscientos.'),
                ('Ingresar', '存入', 'Ingresé el cheque esta mañana.'),
                ('Retirar', '取出', 'Retiré cincuenta euros.'),
                ('Transferir', '转账', 'Te transfiero el dinero hoy.'),
                ('Ahorrar', '储蓄', 'Ahorro para un viaje.'),
                ('Endeudarse', '负债', 'Se endeudó para comprar el piso.'),
                ('Deber', '欠（钱）', 'Le debo veinte euros a Ana.'),
                ('Pagar a plazos', '分期付款', 'Pagué la lavadora a plazos.'),
            ],
            'grammar': [
                {'title': '金钱表达与小数', 'desc': '欧元用逗号表示小数：1,50 € 读作 un euro con cincuenta。金额后接 mil / millón：dos mil euros / un millón de euros（millón 后要加 de）。'},
                {'title': 'pagar / cobrar / deber 的区分', 'desc': 'pagar = 付钱（Pago el alquiler）；cobrar = 收钱（Cobro el sueldo el día 1）；deber = 欠（Te debo 20 euros）。同一个「钱」的动作，方向完全不同。'},
                {'title': '被动 se 与无人称 se（银行语境）', 'desc': 'Se aceptan tarjetas / Se cobra comisión / No se admiten devoluciones。无人称 se 用于告示，动词与后面的名词保持数的一致：Se acepta efectivo（单）/ Se aceptan tarjetas（复）。'},
            ],
        },
    ],
    'B1': [
        {
            'id': 'b1-u9',
            'title': '教育与学习',
            'subtitle': 'Educación y Aprendizaje',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('La enseñanza', '教学', 'La enseñanza pública es gratuita.'),
                ('La formación', '培训、教育', 'Hice un curso de formación.'),
                ('El alumnado', '学生（总称）', 'El alumnado participó en el debate.'),
                ('El docente', '教师', 'Los docentes piden más recursos.'),
                ('El profesorado', '教师（总称）', 'El profesorado se reunió ayer.'),
                ('El aula', '教室', 'El aula tiene treinta alumnos.'),
                ('El curso', '课程、学年', 'Este curso es más difícil.'),
                ('La asignatura', '科目', 'Mi asignatura favorita es historia.'),
                ('El temario', '教学大纲', 'El temario incluye diez temas.'),
                ('El plan de estudios', '培养方案', 'El plan de estudios cambió.'),
                ('La evaluación', '评估', 'La evaluación es continua.'),
                ('El examen', '考试', 'El examen será el jueves.'),
                ('La prueba', '测验', 'Hicimos una prueba sorpresa.'),
                ('La nota', '分数', 'Saqué buena nota en matemáticas.'),
                ('El suspenso', '不及格', 'Hubo muchos suspensos.'),
                ('La matrícula', '注册', 'La matrícula se abre en septiembre.'),
                ('El expediente', '学业档案', 'Su expediente es excelente.'),
                ('El título', '学位', 'Obtuvo el título el año pasado.'),
                ('La beca', '奖学金', 'Le concedieron una beca Erasmus.'),
                ('La plaza', '名额', 'Solo quedan dos plazas libres.'),
                ('El aula virtual', '线上课堂', 'Seguí la clase en el aula virtual.'),
                ('La plataforma', '平台', 'La plataforma está caída.'),
                ('El apunte', '笔记', '¿Me prestas tus apuntes?'),
                ('El resumen', '摘要', 'Hice un resumen del capítulo.'),
                ('El esquema', '提纲', 'Estudia con esquemas.'),
                ('La bibliografía', '参考书目', 'La bibliografía es muy extensa.'),
                ('La fuente', '资料来源', 'Cita siempre tus fuentes.'),
                ('El plagio', '抄袭', 'El plagio se castiga con suspenso.'),
                ('La cita', '引文', 'La cita está mal atribuida.'),
                ('El trabajo', '论文、作业', 'Entrego el trabajo el viernes.'),
                ('La presentación', '演示、报告', 'La presentación duró veinte minutos.'),
                ('El debate', '讨论', 'Participé en un debate.'),
                ('La práctica', '实践', 'La teoría sin práctica no sirve.'),
                ('El taller', '工作坊', 'Asistí a un taller de escritura.'),
                ('El seminario', '研讨课', 'El seminario es los miércoles.'),
                ('La conferencia', '讲座', 'La conferencia fue muy interesante.'),
                ('El ponente', '主讲人', 'El ponente habló de inteligencia artificial.'),
                ('La investigación', '研究', 'Se dedica a la investigación.'),
                ('El estudio', '研究、学习', 'Un estudio reciente lo confirma.'),
                ('La hipótesis', '假设', 'La hipótesis no se confirmó.'),
                ('La muestra', '样本', 'La muestra era demasiado pequeña.'),
                ('El dato', '数据', 'Los datos apoyan esa idea.'),
                ('El resultado', '结果', 'Los resultados fueron sorprendentes.'),
                ('La conclusión', '结论', 'La conclusión es discutible.'),
                ('La metodología', '方法论', 'La metodología está bien explicada.'),
                ('Aprender de memoria', '死记硬背', 'No sirve aprender de memoria.'),
                ('Razonar', '推理', 'Hay que razonar, no repetir.'),
                ('Resumir', '概括', 'Resume el texto en diez líneas.'),
                ('Citar', '引用', 'Cita la página exacta.'),
                ('Corregir', '批改、纠正', 'El profesor corrigió los exámenes.'),
                ('Suspender', '不及格', 'Suspendí el primer examen.'),
                ('Matricularse en', '注册（课程）', 'Me matriculé en dos asignaturas.'),
                ('Esforzarse por', '努力做', 'Se esfuerza por mejorar.'),
                ('Profundizar en', '深入研究', 'Profundizó en el tema.'),
            ],
            'grammar': [
                {'title': '表示「学习/研究」的动词搭配', 'desc': 'estudiar + 学科（直接接）；aprender a + 不定式（学会做某事）；investigar sobre + 主题；profundizar en + 领域；especializarse en。注意 aprender 后面接名词时不加 a：Aprendo inglés。'},
                {'title': '学术文本的无人称与被动', 'desc': 'Se observa que / Se puede concluir que / Los datos fueron analizados —— 学术写作避免第一人称，常用无人称 se 或被动语态。中文习惯说「我们发现」，西语学术文本更常写 Se observa。'},
                {'title': '表示目的与结果的连接词', 'desc': 'para + 不定式（目的）；a fin de que + 虚拟式（正式目的）；de modo que / de manera que + 陈述式（结果）；por lo tanto / en consecuencia（因此）。'},
            ],
        },
        {
            'id': 'b1-u10',
            'title': '媒体与信息',
            'subtitle': 'Medios de Comunicación e Información',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('La prensa', '报界、新闻界', 'La prensa cubrió el suceso.'),
                ('El periódico', '报纸', 'Leo el periódico cada mañana.'),
                ('La revista', '杂志', 'Esa revista es mensual.'),
                ('El diario', '日报', 'El diario publicó la noticia.'),
                ('El titular', '标题', 'El titular era sensacionalista.'),
                ('La portada', '头版', 'El escándalo salió en portada.'),
                ('La noticia', '新闻', 'La noticia se difundió rápido.'),
                ('El reportaje', '报道', 'Escribió un reportaje de investigación.'),
                ('La crónica', '纪实报道', 'Su crónica desde la frontera es notable.'),
                ('La entrevista', '采访', 'La entrevista se emitió anoche.'),
                ('La columna', '专栏', 'Su columna se publica los lunes.'),
                ('El editorial', '社论', 'El editorial criticó la medida.'),
                ('La sección', '版面', 'Trabaja en la sección de cultura.'),
                ('La fuente', '消息来源', 'Protegió a sus fuentes.'),
                ('El corresponsal', '驻外记者', 'Es corresponsal en Bruselas.'),
                ('El redactor', '编辑、撰稿人', 'El redactor jefe aprobó el texto.'),
                ('La difusión', '传播', 'La difusión del vídeo fue masiva.'),
                ('La audiencia', '受众', 'La audiencia creció un diez por ciento.'),
                ('El índice de audiencia', '收视率', 'El índice de audiencia bajó.'),
                ('La emisión', '播出', 'La emisión se canceló.'),
                ('El directo', '直播', 'Lo vimos en directo.'),
                ('La grabación', '录制', 'La grabación se filtró.'),
                ('La rueda de prensa', '新闻发布会', 'Dio una rueda de prensa breve.'),
                ('El comunicado', '新闻稿、声明', 'Publicaron un comunicado escueto.'),
                ('El boletín', '简报', 'Recibo un boletín semanal.'),
                ('La suscripción', '订阅', 'Cancelé la suscripción.'),
                ('El muro de pago', '付费墙', 'El artículo está tras un muro de pago.'),
                ('La publicidad', '广告', 'La publicidad financia el medio.'),
                ('El anuncio', '广告、通告', 'Ese anuncio es engañoso.'),
                ('La propaganda', '宣传', 'Es pura propaganda.'),
                ('El rumor', '传闻', 'El rumor resultó falso.'),
                ('La desinformación', '虚假信息', 'La desinformación se propaga rápido.'),
                ('La verificación', '事实核查', 'La verificación desmintió el dato.'),
                ('El bulo', '假消息', 'Ese bulo circuló durante semanas.'),
                ('La manipulación', '操纵', 'Hubo manipulación de imágenes.'),
                ('El sesgo', '偏向', 'El sesgo del medio es evidente.'),
                ('La objetividad', '客观性', 'La objetividad total no existe.'),
                ('La imparcialidad', '公正', 'Se exige imparcialidad a la prensa.'),
                ('El contraste', '多方核对', 'Falta contraste en esa información.'),
                ('La censura', '审查', 'Denunciaron la censura.'),
                ('La libertad de prensa', '新闻自由', 'La libertad de prensa está en riesgo.'),
                ('La credibilidad', '公信力', 'El medio perdió credibilidad.'),
                ('El medio', '媒体', 'Los medios públicos son independientes.'),
                ('El soporte', '载体', 'El soporte digital ganó terreno.'),
                ('La tirada', '发行量', 'La tirada cayó a la mitad.'),
                ('Difundir', '传播', 'Difundieron la noticia sin verificar.'),
                ('Publicar', '发表', 'Publicaron la investigación ayer.'),
                ('Informar de', '报道、告知', 'Informaron de los detalles.'),
                ('Enterarse de', '得知', 'Me enteré de la noticia tarde.'),
                ('Contrastar', '核实', 'Hay que contrastar la información.'),
                ('Desmentir', '辟谣、否认', 'El ministerio desmintió la cifra.'),
                ('Citar a', '引述', 'El artículo cita a tres expertos.'),
                ('Manipular', '操纵', 'Manipularon las cifras.'),
                ('Sesgar', '使有偏向', 'La selección de datos sesga el resultado.'),
            ],
            'grammar': [
                {'title': '转述别人说的话', 'desc': '直接引语改间接引语：动词时态后退（presente→imperfecto，pretérito→pluscuamperfecto），人称和指示词调整（hoy→aquel día，aquí→allí）。Dicen que + 陈述式；Piden que + 虚拟式。'},
                {'title': '表示「据说」的无人称结构', 'desc': 'Se dice que / Se comenta que / Se rumorea que / Al parecer / Según fuentes + 陈述式。新闻语体常用这些结构来保持距离，不为主张背书。'},
                {'title': '被动语态在新闻中的用法', 'desc': '新闻标题常用被动或分词结构省略助动词：Detenido el autor del robo（= Ha sido detenido）。正文中则用 ser + 分词：El informe fue publicado ayer。'},
            ],
        },
    ],
}
