# -*- coding: utf-8 -*-
"""批次 30：C1 扩充（论证与修辞 / 经济与社会）

B2 551 / C2 414，C1 只有 349，是最低等级。本批补 C1。
"""

BATCH = {
    'C1': [
        {
            'id': 'c1-u11',
            'title': '论证与修辞',
            'subtitle': 'Argumentación y Retórica',
            'lessons': 12,
            'duration': '约 50 分钟',
            'vocab': [
                ('La premisa', '前提', 'La conclusión se apoya en dos premisas.'),
                ('La inferencia', '推论', 'Esa inferencia no se sostiene.'),
                ('El razonamiento', '推理', 'Su razonamiento tiene un salto lógico.'),
                ('La falacia', '谬误', 'Es una falacia de hombre de paja.'),
                ('El sofisma', '诡辩', 'Su argumento es un sofisma elegante.'),
                ('La contradicción', '矛盾', 'Hay una contradicción en el texto.'),
                ('La paradoja', '悖论', 'La paradoja admite varias lecturas.'),
                ('La antinomia', '二律背反', 'La antinomia no se resuelve con datos.'),
                ('El axioma', '公理', 'Parte de un axioma discutible.'),
                ('El postulado', '公设', 'El postulado es razonable pero no obvio.'),
                ('La hipótesis', '假设', 'La hipótesis queda por verificar.'),
                ('La tesis', '论点', 'Su tesis central es más modesta.'),
                ('La objeción', '反对意见', 'Anticipo una objeción previsible.'),
                ('La refutación', '驳斥', 'La refutación fue contundente.'),
                ('La réplica', '回应', 'Su réplica llegó tarde.'),
                ('El contraargumento', '反论', 'Falta responder al contraargumento.'),
                ('La concesión', '让步', 'Hace una concesión estratégica.'),
                ('La salvedad', '限定条件', 'Añade una salvedad importante.'),
                ('El matiz', '细微差别', 'Ese matiz cambia el sentido.'),
                ('La ambigüedad', '歧义', 'La ambigüedad se explota a propósito.'),
                ('La vaguedad', '含糊', 'La vaguedad oculta la falta de prueba.'),
                ('La imprecisión', '不精确', 'La imprecisión terminológica confunde.'),
                ('La coherencia', '连贯性', 'El texto carece de coherencia interna.'),
                ('La consistencia', '一致性', 'Sus tesis mantienen consistencia.'),
                ('La pertinencia', '相关性', 'Ese ejemplo no tiene pertinencia.'),
                ('La relevancia', '相关度', 'La relevancia del dato es dudosa.'),
                ('La evidencia', '证据', 'La evidencia es circunstancial.'),
                ('La prueba', '证明', 'Aporta una prueba documental.'),
                ('El indicio', '迹象', 'Solo hay indicios, no pruebas.'),
                ('El testimonio', '证词', 'El testimonio es de segunda mano.'),
                ('La corroboración', '佐证', 'Falta corroboración independiente.'),
                ('La carga de la prueba', '举证责任', 'La carga de la prueba recae en quien afirma.'),
                ('La falacia ad hominem', '人身攻击谬误', 'Respondió con un ad hominem.'),
                ('La generalización', '以偏概全', 'Esa generalización es apresurada.'),
                ('La correlación', '相关性（统计）', 'Correlación no implica causalidad.'),
                ('La causalidad', '因果性', 'Confunde correlación con causalidad.'),
                ('El sesgo de confirmación', '确认偏误', 'El sesgo de confirmación lo explica.'),
                ('La retórica', '修辞术', 'La retórica no sustituye al argumento.'),
                ('La elocuencia', '雄辩', 'Su elocuencia impresiona, pero no convence.'),
                ('La persuasión', '说服', 'La persuasión opera por vías no racionales.'),
                ('La disuasión', '劝阻', 'Apeló a la disuasión, no al argumento.'),
                ('La ironía', '反讽', 'La ironía se lee como desdén.'),
                ('La hipérbole', '夸张', 'La hipérbole debilita la tesis.'),
                ('El eufemismo', '委婉语', 'El eufemismo encubre una decisión dura.'),
                ('La metáfora', '隐喻', 'La metáfora organiza todo el texto.'),
                ('La analogía', '类比', 'La analogía se rompe en el detalle.'),
                ('La premisa implícita', '隐含前提', 'Hay una premisa implícita problemática.'),
                ('El lugar común', '老生常谈', 'Repite lugares comunes sin examinarlos.'),
                ('La petición de principio', '循环论证', 'Incurre en petición de principio.'),
                ('Refutar', '驳斥', 'Refutó la objeción punto por punto.'),
                ('Rebatir', '反驳', 'Rebatió el argumento con datos.'),
                ('Objetar', '提出异议', 'Objetó que faltaba contexto.'),
                ('Aducir', '援引（理由）', 'Adujo razones de peso.'),
                ('Inferir', '推断', 'De ahí se infiere lo contrario.'),
                ('Deducir', '演绎', 'Dedujo una conclusión excesiva.'),
                ('Presuponer', '预设', 'Presupone lo que quiere demostrar.'),
                ('Cuestionar', '质疑', 'Cuestión la premisa, no la conclusión.'),
                ('Matizar', '补充限定', 'Conviene matizar esa afirmación.'),
                ('Corroborar', '佐证', 'Los hechos corroboran su versión.'),
                ('Sostener', '主张', 'Sostiene que la razón basta.'),
                ('Esgrimir', '举出（论据）', 'Esgrimió un argumento jurídico.'),
            ],
            'grammar': [
                {'title': '论证类动词的句式', 'desc': 'sostener / aducir / objetar / refutar 后面常接 que + 陈述式（陈述具体主张）：Sostiene que la razón basta。若表示要求或建议则用虚拟式：Objetó que no se hiciera así。区分关键在从句所表达的是「事实主张」还是「意志」。'},
                {'title': '让步与限定：aunque / si bien / no obstante', 'desc': 'aunque + 陈述式（已知事实）：Aunque es difícil, merece la pena；aunque + 虚拟式（假设）：Aunque sea difícil, lo haré。si bien / no obstante / ahora bien 用于书面转折，比 pero 更正式。'},
                {'title': '无人称与自复被动在学术论证中', 'desc': 'Se sostiene que / Se argumenta que / Se ha señalado que —— 引用他人观点时用无人称 se 保持距离。Se infiere de ello que 是学术写作中引出结论的标准句式。'},
            ],
        },
        {
            'id': 'c1-u12',
            'title': '经济与社会',
            'subtitle': 'Economía y Sociedad',
            'lessons': 12,
            'duration': '约 50 分钟',
            'vocab': [
                ('El crecimiento', '增长', 'El crecimiento se estancó.'),
                ('La recesión', '衰退', 'La recesión duró dos años.'),
                ('La crisis', '危机', 'La crisis golpeó a las familias.'),
                ('La inflación', '通货膨胀', 'La inflación erosiona el salario.'),
                ('La deflación', '通货紧缩', 'La deflación retrasa el consumo.'),
                ('El poder adquisitivo', '购买力', 'El poder adquisitivo cayó.'),
                ('El producto interior bruto', '国内生产总值', 'El producto interior bruto creció un dos por ciento.'),
                ('La renta', '收入', 'La renta media subió ligeramente.'),
                ('La desigualdad', '不平等', 'La desigualdad se ha ampliado.'),
                ('La redistribución', '再分配', 'La redistribución es objeto de disputa.'),
                ('La fiscalidad', '税制', 'La fiscalidad premia el ahorro.'),
                ('El impuesto', '税', 'Subieron los impuestos al consumo.'),
                ('La subvención', '补贴', 'La subvención está mal diseñada.'),
                ('El subsidio', '救济金', 'El subsidio cubre apenas lo esencial.'),
                ('La prestación', '福利给付', 'La prestación por desempleo se agotó.'),
                ('La cotización', '社保缴费', 'La cotización depende del salario.'),
                ('El sistema de pensiones', '养老金制度', 'El sistema de pensiones es insostenible.'),
                ('El déficit', '赤字', 'El déficit supera el límite acordado.'),
                ('La deuda pública', '公共债务', 'La deuda pública sigue creciendo.'),
                ('El superávit', '盈余', 'El superávit comercial fue récord.'),
                ('El presupuesto público', '公共预算', 'El presupuesto público se aprobó con retraso.'),
                ('La austeridad', '紧缩', 'La austeridad tuvo costes sociales.'),
                ('El ajuste', '调整', 'El ajuste recayó sobre los salarios.'),
                ('La productividad', '生产率', 'La productividad apenas mejoró.'),
                ('La competitividad', '竞争力', 'La competitividad depende del coste energético.'),
                ('El mercado laboral', '劳动力市场', 'El mercado laboral se precarizó.'),
                ('La temporalidad', '临时就业比例', 'La temporalidad afecta a los jóvenes.'),
                ('La precariedad', '不稳定、朝不保夕', 'La precariedad se normalizó.'),
                ('El paro estructural', '结构性失业', 'El paro estructural no cede.'),
                ('La contratación', '招聘', 'La contratación se frenó en otoño.'),
                ('La masa salarial', '工资总额', 'La masa salarial se mantuvo estable.'),
                ('El convenio colectivo', '集体协议', 'El convenio colectivo se renovó.'),
                ('La negociación colectiva', '集体谈判', 'La negociación colectiva se rompió.'),
                ('El sindicato', '工会', 'El sindicato convocó una huelga.'),
                ('La patronal', '雇主协会', 'La patronal rechazó la propuesta.'),
                ('La huelga', '罢工', 'La huelga paralizó el transporte.'),
                ('La movilidad social', '社会流动', 'La movilidad social se ha estancado.'),
                ('La cohesión social', '社会凝聚力', 'La cohesión social se debilita.'),
                ('La exclusión', '社会排斥', 'La exclusión tiene causas múltiples.'),
                ('La vulnerabilidad', '脆弱性', 'La vulnerabilidad se concentra en la infancia.'),
                ('La dependencia', '依赖（人口）', 'La dependencia demográfica presiona las cuentas.'),
                ('El envejecimiento', '老龄化', 'El envejecimiento es irreversible.'),
                ('La natalidad', '出生率', 'La natalidad cayó a mínimos.'),
                ('La migración', '移民', 'La migración compensa la caída demográfica.'),
                ('La integración', '融合', 'La integración exige tiempo y política.'),
                ('La vivienda', '住房', 'La vivienda se ha vuelto inaccesible.'),
                ('El alquiler', '租金', 'El alquiler subió un treinta por ciento.'),
                ('La especulación', '投机', 'La especulación expulsa a los vecinos.'),
                ('Gravar', '征税', 'Gravan las rentas altas.'),
                ('Recaudar', '征收（税款）', 'Se recaudó menos de lo previsto.'),
                ('Repartir', '分配', 'Hay que repartir mejor la carga.'),
                ('Sostener', '支撑、维持', 'El consumo sostiene la actividad.'),
                ('Estancarse', '停滞', 'Los salarios se estancaron.'),
                ('Precarizar', '使不稳定', 'La reforma precarizó el empleo.'),
                ('Ajustar', '调整', 'Ajustaron las plantillas.'),
                ('Reactivar', '刺激复苏', 'El plan busca reactivar la demanda.'),
                ('Frenar', '遏制', 'Las medidas frenaron la subida.'),
                ('Agudizar', '加剧', 'La crisis agudizó la desigualdad.'),
                ('Aliviar', '缓解', 'La medida alivia poco a los hogares.'),
            ],
            'grammar': [
                {'title': '经济数据的中文表达对应', 'desc': 'crecer un 2 % = 增长 2%；subir/bajar un 10 % = 上涨/下跌 10%；duplicarse = 翻倍；caer a mínimos = 跌至最低；superar el límite = 超出上限。注意西语百分比前的动词不需要介词：creció un dos por ciento。'},
                {'title': '无人称 se 与社会议题表述', 'desc': 'Se ha ampliado la desigualdad / Se recortaron las ayudas / Se gravó el patrimonio。这类句子把动作聚焦在事件本身而非施动者，是新闻与社会评论的常见写法——中文翻译时往往要补出主语或改成「被」字句。'},
                {'title': '因果与后果的连接方式', 'desc': 'a causa de / debido a / por culpa de（含负面评价）+ 名词；como consecuencia de；de ahí que + 虚拟式（因此……）；lo que se tradujo en + 名词（结果是）。de ahí que 后面必须用虚拟式，这是 C1 常考点。'},
            ],
        },
    ],
}
