# -*- coding: utf-8 -*-
"""批次 45：继续补 A1/A2/B1 搭配（120 条）

流程改进：上一批先写满 120 条再插入，被工具拦下 33 条重复。这次**先用脚本
验证 pattern 是否已存在**，只为确认是新的模式写例句（候选 152 → 新 144）。

注意：例句里允许出现变位形（estar ocupado 配 estoy ocupado 是正常用法），
所以这里不做字面包含检查，交给 insert-collocations.py 的形态学校验。
"""

BATCH = [
    # ---------------- A1 ----------------
    {'level': 'A1', 'pattern': 'ir al médico', 'zh': '去看医生', 'example': 'Tengo fiebre, quiero ir al médico hoy.'},
    {'level': 'A1', 'pattern': 'ir a la playa', 'zh': '去海滩', 'example': 'En agosto solemos ir a la playa.'},
    {'level': 'A1', 'pattern': 'tomar el autobús', 'zh': '坐公交', 'example': 'Prefiero tomar el autobús que el coche.'},
    {'level': 'A1', 'pattern': 'dar un beso', 'zh': '亲一下', 'example': 'Suele dar un beso al despedirse.'},
    {'level': 'A1', 'pattern': 'dar la mano', 'zh': '握手', 'example': 'Es costumbre dar la mano al presentarse.'},
    {'level': 'A1', 'pattern': 'tener cuidado', 'zh': '小心', 'example': 'Hay que tener cuidado con el escalón.'},
    {'level': 'A1', 'pattern': 'tener tiempo', 'zh': '有时间', 'example': 'Hoy no voy a tener tiempo para cocinar.'},
    {'level': 'A1', 'pattern': 'estar en casa', 'zh': '在家', 'example': 'Esta tarde prefiero estar en casa.'},
    {'level': 'A1', 'pattern': 'estar ocupado', 'zh': '忙', 'example': 'Ahora mismo no puedo, estoy ocupado.'},
    {'level': 'A1', 'pattern': 'estar listo', 'zh': '准备好了', 'example': 'Avísame cuando estés listo.'},
    {'level': 'A1', 'pattern': 'estar de pie', 'zh': '站着', 'example': 'Tuvimos que estar de pie todo el viaje.'},
    {'level': 'A1', 'pattern': 'estar sentado', 'zh': '坐着', 'example': 'Prefiero estar sentado cerca de la ventana.'},
    {'level': 'A1', 'pattern': 'ponerse contento', 'zh': '高兴起来', 'example': 'Suele ponerse contento con cualquier regalo.'},
    {'level': 'A1', 'pattern': 'ponerse triste', 'zh': '难过起来', 'example': 'Se puede poner triste con esa noticia.'},
    {'level': 'A1', 'pattern': 'llevar gafas', 'zh': '戴眼镜', 'example': 'Mi padre empezó a llevar gafas muy joven.'},
    {'level': 'A1', 'pattern': 'llevar dinero', 'zh': '带钱', 'example': 'No me gusta llevar dinero encima.'},
    {'level': 'A1', 'pattern': 'quedarse dormido', 'zh': '睡着', 'example': 'Es fácil quedarse dormido en el sofá.'},
    {'level': 'A1', 'pattern': 'salir con amigos', 'zh': '和朋友出去', 'example': 'Me gusta salir con amigos los viernes.'},
    {'level': 'A1', 'pattern': 'volver a casa', 'zh': '回家', 'example': 'Prefiero volver a casa antes de las diez.'},
    {'level': 'A1', 'pattern': 'llegar a casa', 'zh': '到家', 'example': 'Suelo llegar a casa muy cansado.'},
    {'level': 'A1', 'pattern': 'ver la televisión', 'zh': '看电视', 'example': 'Nos gusta ver la televisión después de cenar.'},
    {'level': 'A1', 'pattern': 'escuchar música', 'zh': '听音乐', 'example': 'Me gusta escuchar música mientras estudio.'},
    {'level': 'A1', 'pattern': 'leer el periódico', 'zh': '看报', 'example': 'Mi abuelo suele leer el periódico cada mañana.'},
    {'level': 'A1', 'pattern': 'hablar por teléfono', 'zh': '打电话', 'example': 'Estoy hablando por teléfono con mi madre.'},
    {'level': 'A1', 'pattern': 'escribir un mensaje', 'zh': '发消息', 'example': 'Voy a escribir un mensaje cuando llegue.'},
    {'level': 'A1', 'pattern': 'comprar pan', 'zh': '买面包', 'example': 'Bajo a comprar pan a la panadería.'},
    {'level': 'A1', 'pattern': 'beber agua', 'zh': '喝水', 'example': 'Conviene beber agua durante todo el día.'},
    {'level': 'A1', 'pattern': 'comer fuera', 'zh': '在外面吃', 'example': 'Los sábados solemos comer fuera.'},
    {'level': 'A1', 'pattern': 'dormir bien', 'zh': '睡得好', 'example': 'Anoche pude dormir bien por fin.'},
    {'level': 'A1', 'pattern': 'dormir mal', 'zh': '睡不好', 'example': 'Suelo dormir mal cuando hace calor.'},
    {'level': 'A1', 'pattern': 'vivir solo', 'zh': '独居', 'example': 'Mi hermano prefiere vivir solo.'},
    {'level': 'A1', 'pattern': 'trabajar mucho', 'zh': '工作很努力', 'example': 'Suele trabajar mucho y descansar poco.'},
    {'level': 'A1', 'pattern': 'estudiar mucho', 'zh': '学习很用功', 'example': 'Tiene que estudiar mucho para aprobar.'},
    {'level': 'A1', 'pattern': 'descansar un poco', 'zh': '休息一下', 'example': 'Vamos a descansar un poco aquí.'},
    {'level': 'A1', 'pattern': 'abrir la ventana', 'zh': '开窗', 'example': '¿Puedes abrir la ventana? Hace calor.'},
    {'level': 'A1', 'pattern': 'cerrar la puerta', 'zh': '关门', 'example': 'No olvides cerrar la puerta al salir.'},
    {'level': 'A1', 'pattern': 'encender la luz', 'zh': '开灯', 'example': 'Voy a encender la luz, no veo nada.'},
    {'level': 'A1', 'pattern': 'apagar el móvil', 'zh': '关手机', 'example': 'Prefiero apagar el móvil durante la cena.'},
    {'level': 'A1', 'pattern': 'limpiar la casa', 'zh': '打扫屋子', 'example': 'Los sábados toca limpiar la casa.'},
    {'level': 'A1', 'pattern': 'lavar la ropa', 'zh': '洗衣服', 'example': 'Tengo que lavar la ropa hoy.'},
    {'level': 'A1', 'pattern': 'poner la mesa', 'zh': '摆餐具', 'example': 'Mi hermana suele poner la mesa.'},
    {'level': 'A1', 'pattern': 'recoger la mesa', 'zh': '收拾餐桌', 'example': 'Después de comer, toca recoger la mesa.'},
    # ---------------- A2 ----------------
    {'level': 'A2', 'pattern': 'hacer la limpieza', 'zh': '打扫', 'example': 'Los domingos solemos hacer la limpieza general.'},
    {'level': 'A2', 'pattern': 'hacer amigos', 'zh': '交朋友', 'example': 'Es fácil hacer amigos en el gimnasio.'},
    {'level': 'A2', 'pattern': 'hacer una llamada', 'zh': '打个电话', 'example': 'Tengo que hacer una llamada urgente.'},
    {'level': 'A2', 'pattern': 'hacer un curso', 'zh': '上课程', 'example': 'Quiero hacer un curso de fotografía.'},
    {'level': 'A2', 'pattern': 'hacer un examen', 'zh': '参加考试', 'example': 'Mañana tenemos que hacer un examen.'},
    {'level': 'A2', 'pattern': 'hacer caso', 'zh': '听话、理会', 'example': 'Deberías hacer caso a tu médico.'},
    {'level': 'A2', 'pattern': 'tomar una copa', 'zh': '喝一杯', 'example': '¿Quieres tomar una copa antes de cenar?'},
    {'level': 'A2', 'pattern': 'tomar el tren', 'zh': '乘火车', 'example': 'Prefiero tomar el tren al autobús.'},
    {'level': 'A2', 'pattern': 'dar un abrazo', 'zh': '抱一下', 'example': 'Suele dar un abrazo al despedirse.'},
    {'level': 'A2', 'pattern': 'dar la bienvenida', 'zh': '欢迎', 'example': 'El director quiere dar la bienvenida a los nuevos.'},
    {'level': 'A2', 'pattern': 'tener éxito', 'zh': '成功', 'example': 'La campaña logró tener mucho éxito.'},
    {'level': 'A2', 'pattern': 'tener problemas', 'zh': '有麻烦', 'example': 'Empezamos a tener problemas con el coche.'},
    {'level': 'A2', 'pattern': 'tener la culpa', 'zh': '有过错', 'example': 'No quiero tener la culpa de lo que pasó.'},
    {'level': 'A2', 'pattern': 'estar de buen humor', 'zh': '心情好', 'example': 'Hoy parece estar de buen humor.'},
    {'level': 'A2', 'pattern': 'estar en forma', 'zh': '身体状态好', 'example': 'Corro para estar en forma.'},
    {'level': 'A2', 'pattern': 'estar seguro de', 'zh': '确信', 'example': 'Puedo estar seguro de que vendrá.'},
    {'level': 'A2', 'pattern': 'estar orgulloso de', 'zh': '为……自豪', 'example': 'Deberías estar orgulloso de tu equipo.'},
    {'level': 'A2', 'pattern': 'estar harto de', 'zh': '对……厌烦', 'example': 'Ya estoy harto de este ruido.'},
    {'level': 'A2', 'pattern': 'estar acostumbrado a', 'zh': '习惯于', 'example': 'Ya estoy acostumbrado a madrugar.'},
    {'level': 'A2', 'pattern': 'poner una queja', 'zh': '投诉', 'example': 'Voy a poner una queja en recepción.'},
    {'level': 'A2', 'pattern': 'poner el despertador', 'zh': '设定闹钟', 'example': 'No olvides poner el despertador.'},
    {'level': 'A2', 'pattern': 'llevarse un susto', 'zh': '吓一跳', 'example': 'Es fácil llevarse un susto con ese ruido.'},
    {'level': 'A2', 'pattern': 'llevar la cuenta', 'zh': '记账', 'example': 'Prefiero llevar la cuenta de los gastos.'},
    {'level': 'A2', 'pattern': 'quedar con alguien', 'zh': '和某人约见', 'example': 'Suelo quedar con alguien a las seis.'},
    {'level': 'A2', 'pattern': 'quedarse sin', 'zh': '用完、失去', 'example': 'Podemos quedarnos sin gasolina.'},
    {'level': 'A2', 'pattern': 'salir de dudas', 'zh': '消除疑问', 'example': 'Pregúntale y podrás salir de dudas.'},
    {'level': 'A2', 'pattern': 'salir de viaje', 'zh': '出发旅行', 'example': 'Pensamos salir de viaje el viernes.'},
    {'level': 'A2', 'pattern': 'volver a empezar', 'zh': '重新开始', 'example': 'Si falla, tendremos que volver a empezar.'},
    {'level': 'A2', 'pattern': 'perder el tren', 'zh': '错过火车', 'example': 'No quiero perder el tren otra vez.'},
    {'level': 'A2', 'pattern': 'echar de menos', 'zh': '想念', 'example': 'Es normal echar de menos a la familia.'},
    {'level': 'A2', 'pattern': 'echar un vistazo', 'zh': '看一眼', 'example': '¿Puedes echar un vistazo a este documento?'},
    {'level': 'A2', 'pattern': 'pasar un rato', 'zh': '待一会儿', 'example': 'Nos gusta pasar un rato en la plaza.'},
    {'level': 'A2', 'pattern': 'dejar de fumar', 'zh': '戒烟', 'example': 'Decidió dejar de fumar hace un año.'},
    {'level': 'A2', 'pattern': 'dejar un mensaje', 'zh': '留言', 'example': 'Puedes dejar un mensaje después del tono.'},
    {'level': 'A2', 'pattern': 'seguir adelante', 'zh': '继续前进', 'example': 'A pesar de todo, decidimos seguir adelante.'},
    {'level': 'A2', 'pattern': 'seguir un consejo', 'zh': '听从建议', 'example': 'Voy a seguir tu consejo.'},
    {'level': 'A2', 'pattern': 'apuntarse a', 'zh': '报名参加', 'example': 'Quiero apuntarme a un curso de baile.'},
    {'level': 'A2', 'pattern': 'darse por vencido', 'zh': '认输', 'example': 'No conviene darse por vencido tan pronto.'},
    {'level': 'A2', 'pattern': 'sacarse el carné', 'zh': '考取驾照', 'example': 'Quiere sacarse el carné de conducir.'},
    {'level': 'A2', 'pattern': 'guardar la calma', 'zh': '保持冷静', 'example': 'Hay que guardar la calma en una emergencia.'},
    {'level': 'A2', 'pattern': 'tener ganas de viajar', 'zh': '想去旅行', 'example': 'Ahora mismo tengo ganas de viajar.'},
    # ---------------- B1 ----------------
    {'level': 'B1', 'pattern': 'tomar la palabra', 'zh': '发言', 'example': 'Varios vecinos quisieron tomar la palabra.'},
    {'level': 'B1', 'pattern': 'tomar partido', 'zh': '选边', 'example': 'El periódico decidió tomar partido.'},
    {'level': 'B1', 'pattern': 'tomar el control', 'zh': '掌控', 'example': 'La nueva directora supo tomar el control.'},
    {'level': 'B1', 'pattern': 'dar por hecho', 'zh': '视为既定', 'example': 'No conviene dar por hecho que aceptarán.'},
    {'level': 'B1', 'pattern': 'dar un paso adelante', 'zh': '主动迈出一步', 'example': 'Alguien tiene que dar un paso adelante.'},
    {'level': 'B1', 'pattern': 'dar marcha atrás', 'zh': '反悔、撤回', 'example': 'El gobierno prefirió dar marcha atrás.'},
    {'level': 'B1', 'pattern': 'dar la impresión de', 'zh': '给人……的印象', 'example': 'Suele dar la impresión de no escuchar.'},
    {'level': 'B1', 'pattern': 'tener acceso a', 'zh': '有权使用、能获得', 'example': 'No todos pueden tener acceso a esa información.'},
    {'level': 'B1', 'pattern': 'estar al día', 'zh': '了解最新情况', 'example': 'Intento estar al día leyendo la prensa.'},
    {'level': 'B1', 'pattern': 'estar en contacto con', 'zh': '与……保持联系', 'example': 'Procuro estar en contacto con mis compañeros.'},
    {'level': 'B1', 'pattern': 'estar conforme con', 'zh': '对……满意', 'example': 'No puedo estar conforme con ese resultado.'},
    {'level': 'B1', 'pattern': 'poner en cuestión', 'zh': '质疑', 'example': 'Su informe tiende a poner en cuestión esa cifra.'},
    {'level': 'B1', 'pattern': 'poner a disposición', 'zh': '提供给', 'example': 'Decidieron poner los datos a disposición del público.'},
    {'level': 'B1', 'pattern': 'poner el foco en', 'zh': '聚焦于', 'example': 'Conviene poner el foco en las causas.'},
    {'level': 'B1', 'pattern': 'poner en valor', 'zh': '凸显价值', 'example': 'El proyecto busca poner en valor el patrimonio local.'},
    {'level': 'B1', 'pattern': 'llevar a la práctica', 'zh': '付诸实施', 'example': 'Es más difícil llevar a la práctica que planear.'},
    {'level': 'B1', 'pattern': 'llevar un registro de', 'zh': '记录', 'example': 'Conviene llevar un registro de todos los pedidos.'},
    {'level': 'B1', 'pattern': 'hacer balance', 'zh': '做总结、盘点', 'example': 'A final de año toca hacer balance.'},
    {'level': 'B1', 'pattern': 'hacer uso de', 'zh': '使用', 'example': 'Puede hacer uso de su derecho a réplica.'},
    {'level': 'B1', 'pattern': 'marcar tendencia', 'zh': '引领趋势', 'example': 'Esa empresa suele marcar tendencia.'},
    {'level': 'B1', 'pattern': 'abrir paso a', 'zh': '为……开辟道路', 'example': 'El acuerdo puede abrir paso a nuevas negociaciones.'},
    {'level': 'B1', 'pattern': 'cerrar el paso a', 'zh': '挡住、阻断', 'example': 'La normativa busca cerrar el paso a los abusos.'},
    {'level': 'B1', 'pattern': 'subrayar la importancia de', 'zh': '强调……的重要性', 'example': 'Quiso subrayar la importancia de actuar pronto.'},
    {'level': 'B1', 'pattern': 'destacar el papel de', 'zh': '突出……的作用', 'example': 'El estudio pretende destacar el papel de las familias.'},
    {'level': 'B1', 'pattern': 'señalar la necesidad de', 'zh': '指出……的必要性', 'example': 'Los expertos suelen señalar la necesidad de invertir.'},
    {'level': 'B1', 'pattern': 'reconocer el mérito de', 'zh': '承认……的功绩', 'example': 'Supo reconocer el mérito de todo el equipo.'},
    {'level': 'B1', 'pattern': 'asumir un compromiso', 'zh': '作出承诺', 'example': 'La empresa decidió asumir un compromiso firme.'},
    {'level': 'B1', 'pattern': 'plantear una alternativa', 'zh': '提出一个替代方案', 'example': 'Van a plantear una alternativa más barata.'},
    {'level': 'B1', 'pattern': 'superar las expectativas', 'zh': '超出预期', 'example': 'Los resultados lograron superar las expectativas.'},
    {'level': 'B1', 'pattern': 'afrontar el reto', 'zh': '面对挑战', 'example': 'Hay que afrontar el reto con realismo.'},
    {'level': 'B1', 'pattern': 'responder con rapidez', 'zh': '迅速回应', 'example': 'La administración supo responder con rapidez.'},
    {'level': 'B1', 'pattern': 'aplicar medidas', 'zh': '实施措施', 'example': 'Decidieron aplicar medidas de emergencia.'},
    {'level': 'B1', 'pattern': 'aplicar el sentido común', 'zh': '运用常识', 'example': 'Basta con aplicar el sentido común.'},
    {'level': 'B1', 'pattern': 'poner en tela de juicio', 'zh': '对……提出怀疑', 'example': 'Nadie debería poner en tela de juicio su honestidad.'},
    {'level': 'B1', 'pattern': 'tener constancia de', 'zh': '有……的记录、确知', 'example': 'No tenemos constancia de ese acuerdo.'},
    {'level': 'B1', 'pattern': 'tener la impresión de', 'zh': '有……的印象', 'example': 'Tengo la impresión de que ya nos conocíamos.'},
    {'level': 'B1', 'pattern': 'cumplir con la palabra', 'zh': '履行诺言', 'example': 'Supo cumplir con su palabra y volvió.'}
]
