#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批次 60：B1 补 2 个单元（会议与职场沟通 / 服务业与客户沟通）

为什么补这两个：B1 原有 15 个单元、平均 46.5 词/单元，而 A1 是 18 个单元、
平均 39.2 词/单元 —— 年级越高单元越「重」。补到 17 个单元后 B1 降到约 43 词/单元。
主题选这两个是因为现有 B1 覆盖了职业发展、教育、媒体、科技、环境、健康、
住房、情绪、城市、旅行、消费，但没有专门处理「会议沟通」与「客户服务沟通」，
而这两者正是 B1 阶段最需要实际运用的场景。

所有词头已用全库比对校验过：与现有 5000+ 词条零重复（含仅冠词/大小写不同的情况）。
"""

BATCH = {
    'B1': [
        {
            'id': 'b1-u16', 'title': '会议与职场沟通', 'subtitle': 'Reuniones y Comunicación Laboral',
            'lessons': 12, 'duration': '约 45 分钟',
            'vocab': [
('La junta directiva', '董事会', 'La junta directiva se reúne cada trimestre.'),
                ('El comité', '委员会', 'El comité aprobó el nuevo plan.'),
                ('La sesión', '场次、会议（一场）', 'La sesión duró dos horas.'),
                ('El jefe de departamento', '部门主管', 'El jefe de departamento firmó el informe.'),
                ('El moderador de la mesa', '圆桌主持人', 'El moderador de la mesa abrió el debate.'),
                ('El punto del día', '议程上的议题', 'Pasamos al segundo punto del día.'),
                ('El tema pendiente', '待议事项', 'Queda un tema pendiente para mañana.'),
                ('El borrador', '草稿', 'Te envío el borrador del acta.'),
                ('El documento de trabajo', '工作文件', 'El documento de trabajo tiene diez páginas.'),
                ('La nota de prensa', '新闻稿', 'Publicaron una nota de prensa muy breve.'),
                ('El informe anual', '年度报告', 'El informe anual resume los resultados.'),
                ('La memoria anual', '年度总结报告', 'La memoria anual incluye las cuentas.'),
                ('El organigrama', '组织架构图', 'El organigrama muestra tres niveles.'),
                ('El departamento', '部门', 'Trabajo en el departamento de ventas.'),
                ('La sede', '总部、办公地点', 'La sede central está en Madrid.'),
                ('El personal', '员工（总称）', 'El personal recibió la noticia hoy.'),
                ('El compañero de trabajo', '同事', 'Mi compañero de trabajo me ayudó mucho.'),
                ('La jornada laboral', '工作时间', 'La jornada laboral es de ocho horas.'),
                ('El horario flexible', '弹性工作时间', 'La empresa ofrece horario flexible.'),
                ('El teletrabajo', '远程办公', 'El teletrabajo ya es habitual aquí.'),
                ('La excedencia', '停薪留职', 'Pidió una excedencia de seis meses.'),
                ('La evaluación del desempeño', '绩效评估', 'La evaluación del desempeño es anual.'),
                ('La entrevista de evaluación', '评估面谈', 'Tuve la entrevista de evaluación ayer.'),
                ('El ascenso interno', '内部晋升', 'El ascenso interno se anunció el lunes.'),
                ('La vacante', '职位空缺', 'Hay una vacante en contabilidad.'),
                ('El candidato', '候选人、应聘者', 'El candidato tiene buena experiencia.'),
                ('La incorporación', '入职', 'Mi incorporación será el 1 de marzo.'),
                ('El preaviso', '提前通知期', 'El preaviso es de quince días.'),
                ('La carta de recomendación', '推荐信', 'Pedí una carta de recomendación a mi jefe.'),
                ('Abordar un tema', '着手谈一个话题', 'Vamos a abordar un tema delicado.'),
                ('Retomar un tema', '重新拾起话题', 'Retomamos el tema la próxima semana.'),
                ('Aportar una idea', '提出一个想法', 'Cada uno puede aportar una idea.'),
                ('Dar el visto bueno', '给予批准', 'El director dio el visto bueno al plan.'),
                ('La ratificación', '批准、追认', 'Falta la ratificación del consejo.'),
                ('Someter a votación', '付诸表决', 'Sometemos la propuesta a votación.'),
                ('Aprobar por unanimidad', '一致通过', 'Se aprobó por unanimidad.'),
                ('La mayoría simple', '简单多数', 'Basta con la mayoría simple.'),
                ('La minoría', '少数派', 'La minoría pidió más tiempo.'),
                ('Reiterar', '重申', 'Quiero reiterar nuestra postura.'),
                ('Insistir en', '坚持强调', 'Insiste en que no hay problema.'),
                ('La insistencia', '坚持（名词）', 'Su insistencia fue decisiva.'),
                ('Contestar a', '回复、回应', 'Contestó a todas las preguntas.'),
                ('Rebatir con datos', '用数据反驳', 'Rebatió la crítica con datos.'),
                ('Carecer de sentido', '没有意义', 'Esa decisión carece de sentido.'),
                ('Ponerse de acuerdo', '达成一致', 'Nos pusimos de acuerdo en diez minutos.'),
                ('Llegar a un punto muerto', '陷入僵局', 'La negociación llegó a un punto muerto.'),
                ('Desbloquear la situación', '打破僵局', 'Su propuesta desbloqueó la situación.'),
                ('El plan de acción', '行动方案', 'El plan de acción tiene tres fases.'),
                ('El responsable de área', '区域/业务负责人', 'Cada responsable de área presenta su parte.'),
                ('El plazo improrrogable', '不可延长的期限', 'El plazo improrrogable vence el viernes.'),
            ],
            'grammar': [
                {'title': '表达同意与不同意', 'desc': '同意：Estoy de acuerdo con… / Tienes razón en… / Comparto tu opinión。不同意：No estoy de acuerdo / No comparto esa idea / Discrepo en ese punto。西班牙语里直接说 No estoy de acuerdo 是正常的，不必像中文那样先铺垫半天。'},
                {'title': '礼貌地插话与请求发言', 'desc': 'Perdona, ¿puedo decir algo? / Si me permites… / ¿Me dejas terminar? / Solo un apunte。请求发言也可以用 pedir la palabra：Quisiera pedir la palabra。'},
                {'title': '推迟、期限与履约', 'desc': 'posponer / aplazar + hasta + 时间：Se aplaza hasta el martes。cumplir el plazo（按期）/ no llegar al plazo（赶不上）/ incumplir（违约）。注意 plazo 是「期限」，不是「广场」（plaza）；fecha límite 是「截止日期」。'},
            ],
        },
        {
            'id': 'b1-u17', 'title': '服务业与客户沟通', 'subtitle': 'Atención al Cliente y Servicios',
            'lessons': 12, 'duration': '约 45 分钟',
            'vocab': [
('El servicio de atención', '服务窗口/客服', 'El servicio de atención funciona 24 horas.'),
                ('La línea de atención', '服务热线', 'Llame a la línea de atención gratuita.'),
                ('El número de incidencias', '故障单号', 'Anote el número de incidencias.'),
                ('La incidencia', '故障、异常事件', 'Registramos la incidencia enseguida.'),
                ('Reportar una incidencia', '报障', 'Puede reportar una incidencia en línea.'),
                ('El ticket de soporte', '工单', 'Abrió un ticket de soporte ayer.'),
                ('El pedido', '订单', 'Su pedido sale hoy del almacén.'),
                ('El pedido pendiente', '待处理订单', 'Tiene dos pedidos pendientes.'),
                ('El envío', '发货、寄送', 'El envío tarda tres días.'),
                ('El plazo de envío', '发货时限', 'El plazo de envío es de 48 horas.'),
                ('El transportista', '承运商、快递员', 'El transportista llamó antes de llegar.'),
                ('La entrega a domicilio', '送货上门', 'Ofrecemos entrega a domicilio gratis.'),
                ('El punto de recogida', '自提点', 'Elija un punto de recogida cercano.'),
                ('La cola', '排队队伍', 'Había una cola muy larga.'),
                ('El turno de espera', '等候顺序', 'Espere su turno de espera.'),
                ('El tiempo de espera', '等待时长', 'El tiempo de espera es de diez minutos.'),
                ('La demora prevista', '预计延误', 'La demora prevista es de dos horas.'),
                ('El aviso', '通知、提醒', 'Recibí un aviso del banco.'),
                ('Notificar', '通知（动词）', 'Le notificaremos la resolución por escrito.'),
                ('El correo de confirmación', '确认邮件', 'Le llegará un correo de confirmación.'),
                ('La confirmación', '确认（名词）', 'Espero la confirmación del pedido.'),
                ('Confirmar el pedido', '确认订单', 'Pulse aquí para confirmar el pedido.'),
                ('Modificar el pedido', '修改订单', 'Puede modificar el pedido hasta el viernes.'),
                ('La política de devoluciones', '退货政策', 'Lea la política de devoluciones.'),
                ('El embalaje', '包装', 'El embalaje llegó en buen estado.'),
                ('El precinto', '封条', 'El precinto estaba roto.'),
                ('El artículo defectuoso', '有缺陷的商品', 'Puede devolver el artículo defectuoso.'),
                ('La tara', '包装重量、皮重', 'Hay que descontar la tara del peso.'),
                ('La hoja de reclamaciones', '投诉单', 'Pido la hoja de reclamaciones.'),
                ('El libro de reclamaciones', '投诉登记簿', 'El libro de reclamaciones es obligatorio.'),
                ('La hoja de quejas', '意见反馈单', 'Rellenó la hoja de quejas del hotel.'),
                ('El responsable de tienda', '店长', 'El responsable de tienda resolvió el caso.'),
                ('El encargado', '负责人、主管', 'El encargado revisó la factura.'),
                ('La atención telefónica', '电话客服', 'La atención telefónica es rápida.'),
                ('La llamada perdida', '未接来电', 'Tengo una llamada perdida tuya.'),
                ('La transferencia de llamada', '转接电话', 'Solicité la transferencia de llamada.'),
                ('Pasar con', '转接给（某人）', 'Le paso con el departamento técnico.'),
                ('El tono amable', '友善的语气', 'Mantenga un tono amable siempre.'),
                ('El trato cordial', '亲切的接待', 'El trato cordial deja buena impresión.'),
                ('Repetir la información', '重复信息', '¿Puede repetir la información, por favor?'),
                ('Confirmar los datos', '核对信息', 'Voy a confirmar los datos personales.'),
                ('El acuse de recibo', '收讫确认', 'Firme el acuse de recibo del paquete.'),
                ('La firma electrónica', '电子签名', 'La firma electrónica tiene validez legal.'),
                ('El código de seguimiento', '物流单号', 'Introduzca el código de seguimiento.'),
                ('El seguimiento del envío', '物流跟踪', 'El seguimiento del envío se ve en la web.'),
                ('El plazo de entrega estimado', '预计送达时间', 'El plazo de entrega estimado es de 5 días.'),
                ('La fecha estimada de entrega', '预计送达日期', 'La fecha estimada de entrega es el martes.'),
                ('La amabilidad', '亲切、和善', 'La amabilidad del personal nos sorprendió.'),
                ('La bienvenida', '欢迎（名词）', 'Nos dieron una bienvenida muy cálida.'),
                ('Dar la bienvenida', '表示欢迎', 'La empresa da la bienvenida a los nuevos.'),
                ('La atención preferente', '优先服务', 'Los socios tienen atención preferente.'),
                ('La cita concertada', '已约定的会面', 'La cita concertada es a las diez.'),
            ],
            'grammar': [
                {'title': '处理投诉的礼貌句式（usted）', 'desc': 'Sentimos las molestias. / Le pido disculpas por la demora. / ¿Podría darme su número de pedido? / Vamos a solucionarlo enseguida。服务业交谈用 usted，动词随 usted 变位（puede / tiene / desea）。'},
                {'title': '条件句处理客户要求', 'desc': 'Si + 现在时，主句用现在时或将来时：Si nos da su correo, le enviamos la factura。此处是陈述式条件句，虚拟式要到 B2 才系统学，这里只需认识「条件用陈述式」。'},
                {'title': '无人称 se 与服务场景', 'desc': 'Se atiende por orden de llegada（按到达顺序接待）。Se ruega puntualidad（请准时）。这类无人称 se 常见于通知与告示，主语不出现。'},
            ],
        },
    ],
}
