# -*- coding: utf-8 -*-
"""批次 53：B2 补两个单元（健康与营养 / 城市与住房）

B2（639）在补完 A1/A2 后成为最低等级。选题避开 B2 已有 13 个单元
（文化身份/全球化/论证观点/媒体素养/职场/法律/科技/心理/艺术/历史/
消费财务/公共政策/论证反驳）。
"""

BATCH = {
    'B2': [
        {
            'id': 'b2-u14',
            'title': '健康与营养',
            'subtitle': 'Salud y Nutrición',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('La nutrición', '营养', 'La nutrición influye más de lo que parece.'),
                ('El nutriente', '营养素', 'Cada nutriente cumple una función.'),
                ('La dieta equilibrada', '均衡饮食', 'Una dieta equilibrada no excluye nada.'),
                ('La alimentación', '饮食', 'La alimentación cambió en dos generaciones.'),
                ('El ultraprocesado', '超加工食品', 'Los ultraprocesados dominan la cesta.'),
                ('El azúcar añadido', '添加糖', 'El azúcar añadido se esconde en todo.'),
                ('La grasa saturada', '饱和脂肪', 'Conviene moderar la grasa saturada.'),
                ('La fibra', '纤维', 'La fibra mejora la digestión.'),
                ('La proteína', '蛋白质', 'La proteína de origen vegetal basta.'),
                ('Las calorías', '卡路里', 'No todas las calorías son equivalentes.'),
                ('La ración', '份量', 'La ración recomendada es pequeña.'),
                ('El etiquetado', '标签标识', 'El etiquetado frontal ayuda a decidir.'),
                ('La fecha de caducidad', '保质期', 'Mira la fecha de caducidad.'),
                ('El conservante', '防腐剂', 'Lleva conservantes y colorantes.'),
                ('El aditivo', '添加剂', 'No todos los aditivos son dañinos.'),
                ('La carencia', '缺乏', 'La carencia de hierro es frecuente.'),
                ('El déficit', '不足、赤字', 'Hay déficit de vitamina D en invierno.'),
                ('El exceso', '过量', 'El exceso de sal eleva la tensión.'),
                ('La obesidad', '肥胖', 'La obesidad infantil preocupa.'),
                ('El sobrepeso', '超重', 'El sobrepeso tiene causas múltiples.'),
                ('La diabetes', '糖尿病', 'La diabetes tipo 2 es prevenible.'),
                ('La hipertensión', '高血压', 'La hipertensión no da síntomas.'),
                ('El colesterol', '胆固醇', 'El colesterol alto se controla.'),
                ('El sedentarismo', '久坐不动', 'El sedentarismo es un factor de riesgo.'),
                ('El hábito', '习惯', 'Los hábitos se forman despacio.'),
                ('La prevención', '预防', 'La prevención sale más barata.'),
                ('El cribado', '筛查', 'El cribado detecta casos tempranos.'),
                ('La vacunación', '疫苗接种', 'La vacunación protege al grupo.'),
                ('La inmunidad', '免疫力', 'La inmunidad disminuye con la edad.'),
                ('El sistema inmunitario', '免疫系统', 'El sistema inmunitario se debilita.'),
                ('La enfermedad crónica', '慢性病', 'Las enfermedades crónicas se acumulan.'),
                ('El trastorno', '失调、障碍', 'Es un trastorno del sueño.'),
                ('La salud mental', '心理健康', 'La salud mental ya no es tabú.'),
                ('El bienestar', '身心安康', 'El bienestar no es solo ausencia de enfermedad.'),
                ('La esperanza de vida', '预期寿命', 'La esperanza de vida se estancó.'),
                ('El envejecimiento activo', '积极老龄化', 'El envejecimiento activo mejora la calidad de vida.'),
                ('La consulta', '就诊', 'La consulta dura quince minutos.'),
                ('El diagnóstico', '诊断', 'El diagnóstico llegó tarde.'),
                ('El pronóstico', '预后', 'El pronóstico es favorable.'),
                ('El tratamiento', '治疗', 'El tratamiento requiere constancia.'),
                ('La dosis', '剂量', 'No superes la dosis indicada.'),
                ('El efecto secundario', '副作用', 'Los efectos secundarios son leves.'),
                ('La adherencia', '依从性', 'La adherencia al tratamiento es baja.'),
                ('La automedicación', '自行用药', 'La automedicación es un riesgo.'),
                ('La sanidad pública', '公共卫生体系', 'La sanidad pública es universal aquí.'),
                ('La lista de espera', '候诊名单', 'Las listas de espera se alargaron.'),
                ('Alimentarse', '进食、摄食', 'Conviene alimentarse con variedad.'),
                ('Equilibrar', '使均衡', 'Cuesta equilibrar trabajo y descanso.'),
                ('Prevenir', '预防', 'Prevenir es mejor que curar.'),
                ('Reducir el consumo de', '减少……的摄入', 'Conviene reducir el consumo de sal.'),
                ('Sustituir por', '用……替代', 'Sustituye el azúcar por fruta.'),
                ('Aumentar la ingesta de', '增加……的摄入', 'Aumenta la ingesta de verduras.'),
                ('Llevar una vida sana', '过健康生活', 'Intenta llevar una vida sana.'),
                ('Cuidar la alimentación', '注意饮食', 'Hay que cuidar la alimentación.'),
                ('Hacer la compra consciente', '有意识地购物', 'Hacer la compra consciente requiere leer etiquetas.'),
                ('Consultar al médico', '就医咨询', 'Conviene consultar al médico antes.'),
            ],
            'grammar': [
                {'title': '表达建议与必要性的梯度', 'desc': 'conviene + 不定式（宜于）/ es recomendable que + 虚拟式 / hay que / deberías。健康话题中避免命令式，用这些结构给出建议更符合语域。'},
                {'title': '量化与程度表达', 'desc': 'reducir el consumo de / aumentar la ingesta de / moderar / limitar a。这些动词与名词的固定搭配是营养类文本的核心，比「comer menos/más」精确得多。'},
                {'title': '无人称与被动在健康报道中', 'desc': 'Se recomienda dormir ocho horas / Se ha demostrado que / Está asociado a。健康新闻习惯用无人称结构保持客观，注意 asociar 后接 a 或 con 均可。'},
            ],
        },
        {
            'id': 'b2-u15',
            'title': '城市与住房',
            'subtitle': 'Ciudad y Vivienda',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('El urbanismo', '城市规划', 'El urbanismo condiciona la vida diaria.'),
                ('La ordenación del territorio', '国土规划', 'La ordenación del territorio es competencia autonómica.'),
                ('El planeamiento', '规划编制', 'El planeamiento tarda años.'),
                ('El PGOU', '总体规划', 'El PGOU se revisó en 2015.'),
                ('La recalificación', '用地性质变更', 'La recalificación multiplicó el valor.'),
                ('El suelo', '土地', 'El suelo urbanizable escasea.'),
                ('La edificabilidad', '容积率', 'La edificabilidad se limitó por ley.'),
                ('La parcela', '地块', 'La parcela quedó vacía.'),
                ('El promotor', '开发商', 'El promotor paralizó las obras.'),
                ('La promoción', '开发项目', 'La promoción incluye cien viviendas.'),
                ('La obra', '工程、施工', 'La obra lleva dos años parada.'),
                ('El promotor público', '公共开发商', 'El promotor público construye alquiler asequible.'),
                ('La vivienda protegida', '保障房', 'La vivienda protegida es insuficiente.'),
                ('La vivienda pública', '公共住房', 'La vivienda pública se destina al alquiler.'),
                ('El alquiler asequible', '可负担租金', 'Falta alquiler asequible en el centro.'),
                ('El alquiler turístico', '旅游短租', 'El alquiler turístico expulsa vecinos.'),
                ('La especulación', '投机', 'La especulación encarece el suelo.'),
                ('La burbuja', '泡沫', 'La burbuja inmobiliaria estalló en 2008.'),
                ('El desahucio', '强制搬迁', 'Los desahucios se frenaron con la moratoria.'),
                ('La moratoria', '暂停期', 'La moratoria duró dos años.'),
                ('El desalojo', '清场、驱逐', 'El desalojo se aplazó.'),
                ('La okupación', '非法占住', 'La okupación genera debate.'),
                ('El arrendamiento', '租赁', 'El arrendamiento se regula por ley.'),
                ('El arrendatario', '承租方', 'El arrendatario paga la fianza.'),
                ('El arrendador', '出租方', 'El arrendador debe mantener la vivienda.'),
                ('La subrogación', '合同承受', 'La subrogación protege al inquilino.'),
                ('La actualización de la renta', '租金调整', 'La actualización de la renta se limita al IPC.'),
                ('El IPC', '消费者物价指数', 'El IPC marcó máximos.'),
                ('La carestía', '物价高昂', 'La carestía de la vivienda es estructural.'),
                ('El hacinamiento', '过度拥挤', 'El hacinamiento afecta a la salud.'),
                ('La infravivienda', '不合格住房', 'La infravivienda persiste en algunos barrios.'),
                ('La rehabilitación', '翻新改造', 'La rehabilitación energética es subvencionada.'),
                ('La eficiencia energética', '能源效率', 'La eficiencia energética reduce la factura.'),
                ('El aislamiento', '隔热隔音', 'El aislamiento del edificio es pobre.'),
                ('La movilidad', '出行', 'La movilidad sostenible exige inversión.'),
                ('La peatonalización', '步行化', 'La peatonalización del centro avanza.'),
                ('El aparcamiento', '停车', 'El aparcamiento disuasorio es gratis.'),
                ('La densidad', '密度', 'La densidad alta favorece el transporte público.'),
                ('La dispersión urbana', '城市蔓延', 'La dispersión urbana encarece los servicios.'),
                ('La periferia', '城市边缘', 'La periferia creció sin equipamientos.'),
                ('El equipamiento', '公共设施', 'El barrio carece de equipamientos.'),
                ('La dotación', '配套设施', 'La dotación de zonas verdes es escasa.'),
                ('El planeamiento urbanístico', '城市规划编制', 'El planeamiento urbanístico se bloqueó.'),
                ('La participación ciudadana', '公众参与', 'La participación ciudadana fue limitada.'),
                ('La alegación', '异议申述', 'Presentaron alegaciones al plan.'),
                ('El recurso', '申诉、救济', 'El recurso fue desestimado.'),
                ('La expropiación', '征收', 'La expropiación se compensó.'),
                ('El justiprecio', '合理补偿价', 'El justiprecio lo fijó el jurado.'),
                ('Urbanizar', '开发建设', 'Urbanizaron toda la ladera.'),
                ('Rehabilitar', '翻新', 'Rehabilitaron el casco antiguo.'),
                ('Requalificar', '改变用地性质', 'Requcalificaron el suelo industrial.'),
                ('Encarecerse', '变贵', 'La vivienda se ha encarecido mucho.'),
                ('Encarecer', '使变贵', 'La especulación encarece el alquiler.'),
                ('Encabezar', '居首、领先', 'Madrid encabeza la subida de precios.'),
                ('Limitar', '限制', 'Limit	aron los precios del alquiler.'),
                ('Regular', '规范', 'Hay que regular el alquiler turístico.'),
                ('Frenar', '遏制', 'La medida busca frenar la subida.'),
            ],
            'grammar': [
                {'title': '被动与无人称在城市政策文本中', 'desc': 'Se aprobó el plan / Se limitaron los precios / Fue recurrido por varios colectivos。政策文本大量使用被动与无人称，把焦点放在措施本身而非施动者。'},
                {'title': '表达措施与效果的连接', 'desc': 'con el objetivo de + 不定式（为了）/ a fin de + 不定式 / lo que supone + 名词（这意味着）/ con el resultado de que。政策评估类文本靠这些结构连接措施与后果。'},
                {'title': '数据与趋势的表述', 'desc': 'encabezar la subida（涨幅居首）/ duplicarse en una década（十年翻倍）/ situarse por encima de（高于）/ registrar un descenso（录得下降）。写住房数据时的常用搭配。'},
            ],
        },
    ],
}
