# -*- coding: utf-8 -*-
"""批次 50：A2 补两个单元（餐厅与点菜 / 运动与休闲）

C2 补完后 A2（467）成为最低等级，而目标第三阶段明确点名 A1/A2/B1 词汇。
选题避开 A2 已有 13 个单元（家庭/外貌/过去/喜好/天气/医院/工作学习/
旅行预订/打电话/交通/考试/职业/银行）。
"""

BATCH = {
    'A2': [
        {
            'id': 'a2-u17',
            'title': '餐厅与点菜',
            'subtitle': 'Restaurantes y Comida',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('La carta', '菜单', '¿Nos trae la carta, por favor?'),
                ('El menú del día', '今日套餐', 'El menú del día incluye postre.'),
                ('El primer plato', '头盘', 'De primer plato, una sopa.'),
                ('El segundo plato', '主菜', 'De segundo, pescado a la plancha.'),
                ('El postre', '甜点', 'De postre, helado de vainilla.'),
                ('La bebida', '饮料', '¿Qué bebida quiere tomar?'),
                ('El aperitivo', '开胃小菜', 'Nos pusieron un aperitivo.'),
                ('La ración', '一份（菜量）', 'Pedimos una ración para compartir.'),
                ('La tapa', '小份下酒菜', 'Vamos a tomar unas tapas.'),
                ('La cuenta', '账单', '¿Me trae la cuenta, por favor?'),
                ('La propina', '小费', 'Dejamos una propina pequeña.'),
                ('La reserva', '订位', 'Hice una reserva para cuatro.'),
                ('La mesa libre', '空桌', '¿Tienen alguna mesa libre?'),
                ('La terraza', '露天座位', 'Preferimos la terraza.'),
                ('El camarero', '服务员', 'El camarero tardó en venir.'),
                ('La especialidad', '招牌菜、特色', 'La especialidad de la casa es el arroz.'),
                ('El plato típico', '特色菜', 'Es un plato típico de la región.'),
                ('El ingrediente', '食材', 'Lleva pocos ingredientes.'),
                ('La receta', '食谱', 'La receta es de mi abuela.'),
                ('El sabor', '味道', 'Tiene un sabor muy suave.'),
                ('El sabor dulce', '甜味', 'Prefiero algo con sabor dulce.'),
                ('El sabor salado', '咸味', 'Este plato está muy salado.'),
                ('El sabor picante', '辣味', 'No me gusta el sabor picante.'),
                ('El sabor amargo', '苦味', 'El café tiene sabor amargo.'),
                ('La textura', '口感、质地', 'La textura es muy suave.'),
                ('Crudo', '生的', 'El pescado viene crudo.'),
                ('Poco hecho', '半熟的（肉）', 'Quiero la carne poco hecha.'),
                ('Al punto', '中等熟度', 'La prefiero al punto.'),
                ('Muy hecho', '全熟', 'La quiero muy hecha.'),
                ('A la plancha', '铁板煎的', 'El pescado a la plancha está buenísimo.'),
                ('A la parrilla', '烤的', 'Pidió verduras a la parrilla.'),
                ('Frito', '油炸的', 'Los calamares fritos son típicos.'),
                ('Al horno', '烤炉烤的', 'El pollo al horno tarda una hora.'),
                ('La ensalada', '沙拉', 'De primero, una ensalada mixta.'),
                ('La sopa', '汤', 'La sopa está caliente.'),
                ('El pan', '面包', 'Nos trajo pan sin pedirlo.'),
                ('La servilleta', '餐巾', 'Falta una servilleta.'),
                ('El tenedor', '叉子', 'Necesito otro tenedor.'),
                ('El cuchillo', '刀', 'El cuchillo no corta bien.'),
                ('La cuchara', '勺子', 'Pide una cuchara para la sopa.'),
                ('El vaso', '杯子', 'El vaso está vacío.'),
                ('La botella', '瓶子', 'Una botella de agua, por favor.'),
                ('La jarra', '大壶、扎壶', 'Una jarra de sangría.'),
                ('Sin gas', '不带气', 'Agua sin gas, por favor.'),
                ('Con gas', '带气', 'Prefiero el agua con gas.'),
                ('La cuenta aparte', '分开结账', '¿Podemos pagar la cuenta aparte?'),
                ('El menú infantil', '儿童套餐', '¿Tienen menú infantil?'),
                ('Para llevar', '打包带走', 'Lo quiero para llevar.'),
                ('La ración doble', '双份', 'Una ración doble de patatas.'),
                ('Apto para celíacos', '适合乳糜泻患者', '¿Este plato es apto para celíacos?'),
                ('Sin gluten', '无麸质', '¿Tienen opciones sin gluten?'),
                ('Vegetariano', '素食的', '¿Hay algún plato vegetariano?'),
                ('La alergia', '过敏', 'Tengo alergia a los frutos secos.'),
                ('La intoxicación', '食物中毒', 'Sospechamos una intoxicación alimentaria.'),
                ('Dejar propina', '留小费', 'Es costumbre dejar propina.'),
                ('Pedir la cuenta', '要账单', 'Vamos a pedir la cuenta.'),
            ],
            'grammar': [
                {'title': '点菜场景的礼貌句式', 'desc': '¿Me trae...? / ¿Nos pone...? / Quisiera... / Para mí, ... —— 点菜时用条件式或与格代词句式比命令式得体。Para mí 是「我要……」的常用说法。'},
                {'title': '食物状态的固定说法', 'desc': 'poco hecho / al punto / muy hecho（肉的熟度）；a la plancha / a la parrilla / al horno / frito（烹饪方式）。这些都是「介词 + 名词/形容词」的固定搭配，不能逐字直译。'},
                {'title': '过敏与饮食限制的表达', 'desc': 'Tengo alergia a... / Soy alérgico a... / ¿Es apto para celíacos? / ¿Lleva gluten? 在国外点菜时这是必备句式，注意 alergia a 的介词固定为 a。'},
            ],
        },
        {
            'id': 'a2-u18',
            'title': '运动与休闲活动',
            'subtitle': 'Deporte y Ocio',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('El deporte', '运动', 'Practico deporte tres días por semana.'),
                ('El equipo', '队伍', 'Mi equipo ganó el partido.'),
                ('El partido', '比赛', 'El partido empieza a las ocho.'),
                ('El campeonato', '锦标赛', 'Se celebra el campeonato nacional.'),
                ('El torneo', '联赛、锦标赛', 'Participamos en un torneo local.'),
                ('La liga', '联赛', 'La liga termina en mayo.'),
                ('El entrenamiento', '训练', 'El entrenamiento dura dos horas.'),
                ('El entrenador', '教练', 'El entrenador pidió más intensidad.'),
                ('El jugador', '球员', 'Ese jugador es muy rápido.'),
                ('El árbitro', '裁判', 'El árbitro pitó penalti.'),
                ('El gol', '进球', 'Marcó un gol espectacular.'),
                ('El punto', '得分', 'Ganó el último punto.'),
                ('El marcador', '比分', 'El marcador quedó dos a uno.'),
                ('El empate', '平局', 'El partido terminó en empate.'),
                ('La victoria', '胜利', 'Fue una victoria ajustada.'),
                ('La derrota', '失败', 'La derrota dolió mucho.'),
                ('El resultado', '结果、比分', 'El resultado fue justo.'),
                ('La lesión', '伤病', 'Se recuperó de una lesión grave.'),
                ('El calentamiento', '热身', 'Antes hay que hacer calentamiento.'),
                ('El gimnasio', '健身房', 'Voy al gimnasio por la mañana.'),
                ('La piscina', '游泳池', 'La piscina cierra a las nueve.'),
                ('La cancha', '球场', 'La cancha está en buen estado.'),
                ('El campo', '球场、田野', 'El campo estaba lleno.'),
                ('El vestuario', '更衣室', 'Nos cambiamos en el vestuario.'),
                ('La equipación', '运动装备、队服', 'Compró la equipación nueva.'),
                ('La zapatilla', '运动鞋', 'Estas zapatillas son muy cómodas.'),
                ('La raqueta', '球拍', 'Se le rompió la raqueta.'),
                ('El balón', '球', 'El balón salió fuera.'),
                ('La bicicleta', '自行车', 'Voy al trabajo en bicicleta.'),
                ('El atletismo', '田径', 'Practica atletismo desde niño.'),
                ('La natación', '游泳', 'La natación es un deporte completo.'),
                ('El ciclismo', '自行车运动', 'El ciclismo gana aficionados.'),
                ('El senderismo', '徒步', 'Hacemos senderismo los domingos.'),
                ('La escalada', '攀岩', 'La escalada requiere fuerza.'),
                ('El yoga', '瑜伽', 'El yoga me ayuda a relajarme.'),
                ('El ajedrez', '国际象棋', 'Juega al ajedrez muy bien.'),
                ('El aficionado', '爱好者', 'Es un aficionado al fútbol.'),
                ('La afición', '爱好、球迷群体', 'La afición animó sin parar.'),
                ('El socio', '会员', 'Es socio del club desde 2010.'),
                ('La cuota', '会费', 'La cuota anual subió.'),
                ('El horario', '时间表', 'El horario del gimnasio es amplio.'),
                ('La inscripción', '报名', 'La inscripción cierra el viernes.'),
                ('La clasificación', '排名、资格赛', 'El equipo subió en la clasificación.'),
                ('La final', '决赛', 'La final se juega el domingo.'),
                ('La semifinal', '半决赛', 'Perdimos en la semifinal.'),
                ('El descanso', '中场休息', 'En el descanso tomaron agua.'),
                ('La prórroga', '加时', 'El partido se decidió en la prórroga.'),
                ('El penalti', '点球', 'Falló el penalti decisivo.'),
                ('La falta', '犯规', 'Fue una falta clara.'),
                ('La tarjeta amarilla', '黄牌', 'Le sacaron tarjeta amarilla.'),
                ('Entrenar', '训练', 'Entrena cinco días a la semana.'),
                ('Ganar', '赢', 'Ganaron por dos a cero.'),
                ('Perder', '输', 'Perdimos en el último minuto.'),
                ('Empatar', '打平', 'Empataron a uno.'),
                ('Aficionarse a', '迷上', 'Se aficionó al ciclismo.'),
                ('Apuntarse a', '报名参加', 'Me apunté a un torneo de pádel.'),
                ('Mantenerse en forma', '保持体形', 'Corro para mantenerse en forma.'.replace('mantenerse','mantenerme')),
            ],
            'grammar': [
                {'title': '运动项目的搭配动词', 'desc': 'jugar a + 球类（jugar al fútbol / al tenis）；practicar + 运动（practicar natación）；hacer + 运动（hacer senderismo / yoga）；montar en bici。中文都用「打/做」，西语按项目分工。'},
                {'title': '比赛结果的表达', 'desc': 'ganar por dos a uno（以 2:1 获胜）/ empatar a uno（1:1 打平）/ perder contra（输给）。注意比分的读法用 a 连接：dos a uno。'},
                {'title': '自复动词表「开始迷上」', 'desc': 'aficionarse a / apuntarse a / engancharse a —— 加代词的自复形式表「使自己投入某事」。这类结构比「empezar a + 不定式」更能表达兴趣的产生。'},
            ],
        },
    ],
}
