# -*- coding: utf-8 -*-
"""批次 49：C2 补两个单元（伦理学与道德哲学 / 历史与时间）

C2 词汇 623 是六个等级里最低的。选题避开 C2 已有的 12 个单元
（文学修辞/书面语/专业文书/成语/哲学/美学/科学哲学/语言哲学/法学/
艺术审美/精确表达/语用修辞），选伦理学与历史学这两块尚未覆盖的领域。
"""

BATCH = {
    'C2': [
        {
            'id': 'c2-u13',
            'title': '伦理学与道德哲学',
            'subtitle': 'Ética y Filosofía Moral',
            'lessons': 12,
            'duration': '约 55 分钟',
            'vocab': [
                ('La ética', '伦理学', 'La ética no prescribe recetas.'),
                ('La moral', '道德', 'La moral varía entre culturas.'),
                ('El deber', '义务', 'Actuó por deber, no por interés.'),
                ('La obligación moral', '道德义务', 'La obligación moral no se negocia.'),
                ('El imperativo categórico', '绝对命令', 'El imperativo categórico no admite excepciones.'),
                ('La máxima', '准则、格言', 'Obra según una máxima universalizable.'),
                ('El utilitarismo', '功利主义', 'El utilitarismo maximiza el bienestar total.'),
                ('El consecuencialismo', '后果主义', 'El consecuencialismo juzga por resultados.'),
                ('La deontología', '义务论', 'La deontología atiende a la intención.'),
                ('La virtud', '德性', 'La virtud se adquiere con la práctica.'),
                ('El carácter', '品格', 'El carácter se forja con hábitos.'),
                ('La integridad', '正直', 'Su integridad nunca estuvo en duda.'),
                ('La dignidad', '尊严', 'La dignidad no admite precio.'),
                ('La autonomía', '自主', 'La autonomía es condición de la responsabilidad.'),
                ('La heteronomía', '他律', 'La heteronomía impide el juicio propio.'),
                ('El consentimiento', '同意', 'Sin consentimiento no hay legitimidad.'),
                ('La coerción', '强制', 'La coerción anula la voluntad.'),
                ('El daño', '伤害', 'El principio de no causar daño es mínimo.'),
                ('El beneficio', '利益、善', 'Buscaba el beneficio común.'),
                ('La equidad', '公平', 'La equidad corrige la igualdad formal.'),
                ('La imparcialidad', '不偏不倚', 'La imparcialidad exige abstraerse del propio caso.'),
                ('El deber de socorro', '救助义务', 'El deber de socorro está tipificado.'),
                ('La responsabilidad', '责任', 'La responsabilidad se atenúa sin intención.'),
                ('La culpa', '罪责', 'La culpa exige imputabilidad.'),
                ('La imputabilidad', '可归责性', 'Sin imputabilidad no hay culpa.'),
                ('La intención', '意图', 'La intención distingue el error del daño.'),
                ('La negligencia', '过失', 'La negligencia también es responsable.'),
                ('El dilema moral', '道德困境', 'El dilema moral no tiene salida limpia.'),
                ('El conflicto de valores', '价值冲突', 'Todo conflicto de valores exige jerarquía.'),
                ('La jerarquía de valores', '价值等级', 'No hay jerarquía de valores incuestionada.'),
                ('El relativismo', '相对主义', 'El relativismo evita juzgar.'),
                ('El universalismo', '普遍主义', 'El universalismo aspira a validez para todos.'),
                ('La tolerancia', '宽容', 'La tolerancia no equivale a indiferencia.'),
                ('La neutralidad', '中立', 'La neutralidad del Estado es discutida.'),
                ('El pacto', '契约', 'El pacto legitima la convivencia.'),
                ('El contrato social', '社会契约', 'El contrato social funda la obligación política.'),
                ('La reciprocidad', '互惠', 'La reciprocidad sostiene la cooperación.'),
                ('La solidaridad', '团结', 'La solidaridad no es caridad.'),
                ('La vulnerabilidad', '脆弱性', 'La vulnerabilidad genera deberes especiales.'),
                ('El paternalismo', '家长主义', 'El paternalismo restringe sin consentimiento.'),
                ('La coacción', '胁迫', 'La coacción invalida la promesa.'),
                ('La promesa', '承诺', 'Una promesa crea un deber.'),
                ('La lealtad', '忠诚', 'La lealtad tiene límites.'),
                ('La traición', '背叛', 'La traición rompe el vínculo.'),
                ('La reparación', '弥补、赔偿', 'La reparación busca restablecer el daño.'),
                ('El arrepentimiento', '悔意', 'El arrepentimiento no borra el hecho.'),
                ('El perdón', '宽恕', 'El perdón suspende la exigencia.'),
                ('La reconciliación', '和解', 'La reconciliación exige verdad previa.'),
                ('La justicia distributiva', '分配正义', 'La justicia distributiva reparte cargas.'),
                ('La justicia retributiva', '报应正义', 'La justicia retributiva mira al merecimiento.'),
                ('La buena fe', '善意、诚信', 'Actuó de buena fe.'),
                ('La mala fe', '恶意、不诚信', 'Hubo mala fe en la negociación.'),
                ('La objeción de conciencia', '良心拒绝', 'La objeción de conciencia es un derecho limitado.'),
                ('El mínimo moral', '道德底线', 'Todo sistema tiene un mínimo moral.'),
                ('Justificar', '辩护、证明正当', 'Intentó justificar su decisión.'),
                ('Juzgar', '评判', 'Juzgar exige criterios explícitos.'),
                ('Prescribir', '规定、开处方', 'La ética no prescribe conductas concretas.'),
                ('Obligar a', '迫使', 'La norma obliga a declarar.'),
                ('Eximir de', '免除', 'La ley exime de responsabilidad en ese caso.'),
                ('Imputar a', '归责于', 'Se le imputa una negligencia grave.'),
                ('Asumir las consecuencias', '承担后果', 'Quien decide asume las consecuencias.'),
                ('Reparar el daño', '弥补损害', 'Hay que reparar el daño causado.'),
            ],
            'grammar': [
                {'title': '表达义务与许可的层级', 'desc': 'deber + 不定式（道义上应当）/ tener que（客观必须）/ haber de（正式，多用于书面）/ poder（许可）。deber de + 不定式则表推测，与义务无关——这是最常被混淆的一对。'},
                {'title': '伦理文本的无人称与被动', 'desc': 'Se debe actuar... / No cabe justificar... / Está prohibido... —— 伦理与法律文本避免明确施动者，因为规范对象是所有人。cabe + 不定式 是书面语中「可以/值得」的正式表达。'},
                {'title': '让步与限定的精密表达', 'desc': 'En la medida en que... , ...（在……范围内）；Salvo que...（除非）；Siempre que no...（只要不……）；No porque A, sino porque B（不是因为 A，而是因为 B）。伦理讨论中精密的限定比绝对断言更有说服力。'},
            ],
        },
        {
            'id': 'c2-u14',
            'title': '历史与时间',
            'subtitle': 'Historia y Temporalidad',
            'lessons': 12,
            'duration': '约 55 分钟',
            'vocab': [
                ('La historiografía', '史学', 'La historiografía moderna nace en el XIX.'),
                ('La fuente primaria', '原始资料', 'Solo usó fuentes primarias.'),
                ('La fuente secundaria', '二手资料', 'Las fuentes secundarias interpretan.'),
                ('El archivo', '档案', 'El archivo municipal está digitalizado.'),
                ('El documento', '文献', 'El documento está fechado en 1521.'),
                ('El testimonio', '证言', 'El testimonio oral completa el archivo.'),
                ('La crónica', '编年记、纪实', 'La crónica mezcla observación y juicio.'),
                ('La periodización', '分期', 'La periodización es una convención.'),
                ('La época', '时代', 'Cada época lee el pasado a su modo.'),
                ('El período', '时期', 'Ese período duró apenas una década.'),
                ('El hito', '里程碑', 'La imprenta fue un hito.'),
                ('El acontecimiento', '事件', 'El acontecimiento cambió el rumbo.'),
                ('El proceso', '进程', 'Fue un proceso lento, no un estallido.'),
                ('La coyuntura', '时局、特定形势', 'La coyuntura favoreció la reforma.'),
                ('La estructura', '结构', 'La estructura social apenas cambió.'),
                ('La larga duración', '长时段', 'La larga duración relativiza lo inmediato.'),
                ('La causalidad histórica', '历史因果', 'La causalidad histórica es múltiple.'),
                ('El determinismo', '决定论', 'El determinismo simplifica lo imprevisible.'),
                ('La contingencia', '偶然性', 'La contingencia desmiente toda predicción.'),
                ('La retrospectiva', '回溯', 'La mirada retrospectiva distorsiona.'),
                ('El anacronismo', '时代错置', 'Juzgar el pasado con criterios actuales es anacronismo.'),
                ('La teleología', '目的论', 'La teleología lee el pasado hacia un fin.'),
                ('La memoria histórica', '历史记忆', 'La memoria histórica es objeto de disputa.'),
                ('El olvido', '遗忘', 'El olvido también es una política.'),
                ('El monumento', '纪念碑', 'El monumento fija una versión del pasado.'),
                ('El revisionismo', '修正主义', 'El revisionismo exige pruebas nuevas.'),
                ('La interpretación', '阐释', 'Toda interpretación es situada.'),
                ('La evidencia', '证据', 'La evidencia documental es fragmentaria.'),
                ('El indicio', '迹象、线索', 'Un indicio no es una prueba.'),
                ('La hipótesis', '假设', 'La hipótesis sigue sin confirmarse.'),
                ('La refutación', '驳斥', 'La refutación llegó décadas después.'),
                ('El consenso', '共识', 'El consenso historiográfico cambia.'),
                ('La controversia', '争议', 'La controversia sigue abierta.'),
                ('La perspectiva', '视角', 'Depende de la perspectiva adoptada.'),
                ('El sesgo', '偏向', 'El sesgo del vencedor impregna el relato.'),
                ('La imparcialidad', '不偏不倚', 'La imparcialidad absoluta no existe.'),
                ('La objetividad', '客观性', 'La objetividad es un horizonte, no un punto.'),
                ('La subjetividad', '主观性', 'La subjetividad del testigo condiciona.'),
                ('El contexto', '语境、背景', 'Sin contexto, la cita engaña.'),
                ('La continuidad', '延续性', 'Hay más continuidad que ruptura.'),
                ('La ruptura', '断裂', 'La ruptura fue más retórica que real.'),
                ('La transición', '过渡', 'La transición no fue pacífica.'),
                ('La decadencia', '衰落', 'La decadencia se percibe solo a posteriori.'),
                ('El auge', '兴盛', 'El auge duró medio siglo.'),
                ('La herencia', '遗产、遗留', 'La herencia del período es ambigua.'),
                ('El legado', '遗留物、传承', 'El legado institucional perdura.'),
                ('La genealogía', '谱系', 'Trazó la genealogía del concepto.'),
                ('El origen', '起源', 'El origen es más difuso de lo que parece.'),
                ('La datación', '断代', 'La datación por carbono confirmó la fecha.'),
                ('La cronología', '年代顺序', 'La cronología no implica causalidad.'),
                ('La sincronía', '共时', 'La sincronía compara dos momentos.'),
                ('La diacronía', '历时', 'La diacronía estudia el cambio.'),
                ('El devenir', '演变过程', 'El devenir histórico no es lineal.'),
                ('La memoria colectiva', '集体记忆', 'La memoria colectiva se transmite en relatos.'),
                ('Reconstruir', '重建、复原', 'Reconstruir el pasado exige imaginación disciplinada.'),
                ('Rastrear', '追溯', 'Rastreó el origen del término.'),
                ('Contextualizar', '放回语境', 'Hay que contextualizar la cita.'),
                ('Relativizar', '相对化', 'Conviene relativizar esa cifra.'),
                ('Periodizar', '分期', 'Periodizar siempre es arbitrario.'),
                ('Documentar', '用文献证明', 'Documentó cada afirmación.'),
                ('Contrastar fuentes', '比对资料来源', 'Contrastó fuentes de distinto origen.'),
            ],
            'grammar': [
                {'title': '历史叙述的时态体系', 'desc': '简单过去时叙述事件（llegó、cayó）；未完成过去时描述背景与常态（gobernaba、se vivía）；过去完成时交代先于主线的动作（había firmado）。三者的分工是历史写作的核心。'},
                {'title': '表达「据说」与史料归属', 'desc': 'Según las fuentes... / Se atribuye a... / Consta que... / Hay indicios de que + 虚拟式。历史文本需明确区分「有据可查」与「推测」，这些句式承担这一功能。'},
                {'title': '反事实与推测的书面结构', 'desc': 'De haber... , ...（要是当时……）；Si + 虚拟式过去完成时，主句用条件式完成时；Cabría suponer que...（不妨设想）。历史学常用反事实推理探讨「另一种可能」。'},
            ],
        },
    ],
}
