# -*- coding: utf-8 -*-
"""批次 28：B1 扩充（情绪表达 / 城市生活）"""

BATCH = {
    'B1': [
        {
            'id': 'b1-u7',
            'title': '情绪与感受',
            'subtitle': 'Emociones y Sentimientos',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('La alegría', '快乐', 'Su alegría era contagiosa.'),
                ('La tristeza', '悲伤', 'No podía disimular su tristeza.'),
                ('El miedo', '害怕', 'Le daba miedo hablar en público.'),
                ('La rabia', '愤怒', 'Sentí rabia al enterarme.'),
                ('El enfado', '生气', 'Se le pasó el enfado pronto.'),
                ('La sorpresa', '惊讶', 'Fue una sorpresa agradable.'),
                ('La ilusión', '期待、热情', 'Me hace mucha ilusión verte.'),
                ('La esperanza', '希望', 'No pierdas la esperanza.'),
                ('La decepción', '失望', 'La decepción fue enorme.'),
                ('La nostalgia', '怀旧', 'Siento nostalgia de aquellos años.'),
                ('La envidia', '羡慕、嫉妒', 'No le tengo envidia a nadie.'),
                ('Los celos', '吃醋', 'Los celos arruinan relaciones.'),
                ('El orgullo', '骄傲', 'Estoy orgulloso de ti.'),
                ('La vergüenza', '羞耻、尴尬', 'Me dio vergüenza preguntar.'),
                ('La culpa', '愧疚', 'Siento culpa por lo que dije.'),
                ('La preocupación', '担心', 'Su preocupación era evidente.'),
                ('El alivio', '宽慰', 'Sentí un gran alivio.'),
                ('La tranquilidad', '平静', 'Aquí encuentro tranquilidad.'),
                ('El agobio', '压抑、烦躁', 'Tengo mucho agobio en el trabajo.'),
                ('El estrés', '压力', 'El estrés me está afectando.'),
                ('La emoción', '激动', 'No pude contener la emoción.'),
                ('El cariño', '亲切、喜爱', 'Le tengo mucho cariño.'),
                ('El afecto', '情感、关爱', 'Necesita afecto y compañía.'),
                ('La confianza', '信任', 'Confío plenamente en ella.'),
                ('La desconfianza', '不信任', 'Su actitud generó desconfianza.'),
                ('Alegrarse de', '为……高兴', 'Me alegro de que estés bien.'),
                ('Preocuparse por', '为……担心', 'Se preocupa por todo.'),
                ('Enfadarse con', '生……的气', 'Se enfadó conmigo sin motivo.'),
                ('Quejarse de', '抱怨', 'Siempre se queja del tiempo.'),
                ('Disculparse por', '为……道歉', 'Se disculpó por llegar tarde.'),
                ('Echar de menos', '想念', 'Echo de menos a mi familia.'),
                ('Tener ganas de', '想要、渴望', 'Tengo ganas de verte.'),
                ('Dar igual', '无所谓', 'Me da igual lo que digan.'),
                ('Importar', '重要、在意', 'Me importa mucho tu opinión.'),
                ('Molestar', '打扰、烦扰', '¿Te molesta si abro la ventana?'),
                ('Agradecer', '感谢', 'Te agradezco la ayuda.'),
                ('Arrepentirse de', '后悔', 'Me arrepiento de no haber ido.'),
                ('Ilusionarse', '充满期待', 'Se ilusionó con el viaje.'),
                ('Decepcionarse', '失望', 'Me decepcioné con la película.'),
                ('Aguantar', '忍受', 'No aguanto este calor.'),
                ('Soportar', '忍受', 'No soporto los ruidos.'),
                ('Relajarse', '放松', 'Necesito relajarme un poco.'),
                ('Animarse', '振作起来', 'Anímate, todo saldrá bien.'),
                ('Tranquilizarse', '放心', 'Tranquilízate, no pasa nada.'),
                ('Sorprenderse de', '对……惊讶', 'Me sorprendió su reacción.'),
                ('Emocionarse', '激动起来', 'Se emocionó al verla.'),
                ('Reírse de', '嘲笑', 'No te rías de mí.'),
                ('Llorar', '哭', 'No pude evitar llorar.'),
                ('Sonreír', '微笑', 'Me sonrió al entrar.'),
                ('Sentirse solo', '感到孤独', 'Se siente solo desde que se mudó.'),
                ('Ponerse de buen humor', '心情变好', 'Se puso de buen humor enseguida.'),
                ('Perder los nervios', '失控', 'Perdió los nervios y gritó.'),
                ('Mantener la calma', '保持冷静', 'Hay que mantener la calma.'),
            ],
            'grammar': [
                {'title': '情感动词 + 虚拟式', 'desc': 'alegrarse de que / sentir que / molestar que / sorprender que 等表情感的动词，从句一律用虚拟式：Me alegro de que hayas venido。注意主语不同时才用从句，主语相同则用不定式：Me alegro de verte。'},
                {'title': 'gustar 类动词', 'desc': 'gustar / encantar / importar / molestar / doler / interesar 等，主语是被喜欢的事物，人用与格代词：Me gustan los libros（书是主语）。单复数取决于事物：Me gusta el libro / Me gustan los libros。'},
                {'title': 'estar + 形容词表情绪', 'desc': 'estar + 形容词表暂时状态：estoy contento / triste / preocupado / nervioso。与 ser + 形容词（本质特征）区分：Es una persona alegre（性格）vs Está alegre hoy（今天状态）。'},
            ],
        },
        {
            'id': 'b1-u8',
            'title': '城市生活与邻里',
            'subtitle': 'Vida Urbana y Vecindario',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('El ayuntamiento', '市政府', 'El ayuntamiento organiza actividades.'),
                ('La alcaldía', '市政厅', 'La alcaldía está en la plaza.'),
                ('El alcalde', '市长', 'El alcalde inauguró el parque.'),
                ('El barrio', '街区', 'Mi barrio es muy tranquilo.'),
                ('La plaza', '广场', 'Nos vimos en la plaza.'),
                ('El parque', '公园', 'Corro en el parque por las mañanas.'),
                ('El centro cívico', '社区中心', 'El centro cívico ofrece cursos.'),
                ('La biblioteca municipal', '市立图书馆', 'Estudio en la biblioteca municipal.'),
                ('El mercado', '市场', 'Compro en el mercado del barrio.'),
                ('El ambulatorio', '社区诊所', 'El ambulatorio abre a las ocho.'),
                ('La farmacia', '药店', 'La farmacia de guardia está cerca.'),
                ('El polideportivo', '体育馆', 'Entreno en el polideportivo.'),
                ('La piscina municipal', '市立游泳池', 'La piscina municipal es barata.'),
                ('El servicio de recogida', '垃圾收集服务', 'El servicio de recogida pasa los martes.'),
                ('El contenedor', '垃圾桶', 'Tira el vidrio al contenedor verde.'),
                ('El reciclaje', '回收', 'Aquí el reciclaje funciona bien.'),
                ('La limpieza', '清洁', 'La limpieza de la calle es deficiente.'),
                ('La acera', '人行道', 'La acera está en obras.'),
                ('La farola', '路灯', 'La farola lleva dos semanas rota.'),
                ('El banco', '长椅', 'Nos sentamos en un banco del parque.'),
                ('El árbol', '树', 'Plantaron árboles nuevos.'),
                ('La zona verde', '绿地', 'Faltan zonas verdes.'),
                ('El vecindario', '邻里（总称）', 'Todo el vecindario participó.'),
                ('La comunidad de vecinos', '业主委员会', 'La comunidad de vecinos se reúne hoy.'),
                ('La junta', '业主大会', 'La junta aprobó la reforma.'),
                ('El presidente de la comunidad', '业委会主任', 'El presidente de la comunidad dimitió.'),
                ('La derrama', '摊派费用', 'Aprobamos una derrama para el ascensor.'),
                ('La cuota', '每月分摊费', 'La cuota mensual es de cuarenta euros.'),
                ('La reunión', '会议', 'La reunión será el jueves.'),
                ('La queja', '投诉', 'Presentamos una queja formal.'),
                ('El ruido', '噪音', 'El ruido de obras molesta mucho.'),
                ('La convivencia', '邻里共处', 'La convivencia es bastante buena.'),
                ('El respeto', '尊重', 'El respeto mutuo es básico.'),
                ('La solidaridad', '互助', 'Hay mucha solidaridad en el edificio.'),
                ('La seguridad', '安全', 'La seguridad del barrio ha mejorado.'),
                ('La delincuencia', '犯罪', 'La delincuencia bajó este año.'),
                ('El tráfico', '交通', 'Cortaron la calle al tráfico.'),
                ('La peatonalización', '步行化', 'La peatonalización del centro avanza.'),
                ('El carril bici', '自行车道', 'El nuevo carril bici es muy útil.'),
                ('La zona azul', '收费停车区', 'Aparqué en zona azul.'),
                ('La accesibilidad', '无障碍', 'Falta accesibilidad en los edificios antiguos.'),
                ('La rampa', '坡道', 'Instalaron una rampa en la entrada.'),
                ('El ascensor', '电梯', 'El ascensor está averiado otra vez.'),
                ('La avería', '故障', 'La avería tardó días en repararse.'),
                ('La reforma', '改造', 'La reforma del portal costó mucho.'),
                ('Participar en', '参与', 'Participo en las actividades del centro.'),
                ('Colaborar con', '与……合作', 'Colaboro con una asociación.'),
                ('Quejarse de', '投诉、抱怨', 'Nos quejamos del ruido.'),
                ('Reclamar', '索赔、交涉', 'Reclamamos al ayuntamiento.'),
                ('Mudarse a', '搬到', 'Se mudó a otro barrio.'),
                ('Conocer a los vecinos', '认识邻居', 'Poco a poco conocí a los vecinos.'),
                ('Echar una mano', '帮个忙', 'Siempre está dispuesto a echar una mano.'),
            ],
            'grammar': [
                {'title': '无人称与被动 se（社区语境）', 'desc': 'Se ruega silencio / Se prohíbe tender ropa / Se avisa a los vecinos —— se 无人称与被动在社区通知中极常见，动词与主语保持数的一致。'},
                {'title': '表达投诉与要求', 'desc': 'Quisiera presentar una queja / Me gustaría reclamar / Les agradecería que + 虚拟式 —— 正式书面投诉的常用句式，避免直接指责。'},
                {'title': '相互动作的表达', 'desc': '相互代词 se：Se respetan（他们互相尊重）；el uno al otro / mutuamente 加强相互意义；entre nosotros/ vosotros/ ellos。'},
            ],
        },
    ],
}
