#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批次 62：B2 补 3 个单元（环境政策 / 教育体制 / 正式书面语与公开表达）

为什么补这三个：B2 原有 15 个单元、每单元 49.9 词，且缺少三个 B2 高频话题：
  - 环境政策：B1 有环境词汇、C1 有社会政策，B2 这一级反而没有环境政策的专门单元
  - 教育体制：B2 有「职场沟通」，但没有教育制度与学术规范的主题
  - 正式书面语与公开表达：B2 已有论证与反驳句式，但缺正式信函/报告/演讲的成体系词汇

所有词头已用全库比对校验：与现有 5100+ 词条零重复（含仅冠词/大小写不同的情况）。
"""

BATCH = {
    'B2': [
        {
            'id': 'b2-u16', 'title': '环境政策与可持续发展', 'subtitle': 'Política Medioambiental y Sostenibilidad',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
                ('La política medioambiental', '环境政策', 'La política medioambiental exige coordinación entre administraciones.'),
                ('El impacto ambiental', '环境影响', 'El proyecto requiere un estudio de impacto ambiental.'),
                ('La evaluación de impacto ambiental', '环境影响评估', 'La evaluación de impacto ambiental es obligatoria.'),
                ('La neutralidad de carbono', '碳中和', 'La neutralidad de carbono se busca para 2050.'),
                ('El compromiso climático', '气候承诺', 'El compromiso climático se revisa cada cinco años.'),
                ('La cumbre del clima', '气候峰会', 'En la cumbre del clima se firmó un acuerdo.'),
                ('La ratificación del acuerdo', '协定的批准', 'La ratificación del acuerdo depende del parlamento.'),
                ('La mitigación', '减缓', 'La mitigación reduce las emisiones.'),
                ('La adaptación al cambio climático', '适应气候变化', 'La adaptación al cambio climático protege las costas.'),
                ('La resiliencia climática', '气候韧性', 'La resiliencia climática se mide tras cada crisis.'),
                ('La exposición al riesgo', '风险暴露', 'La exposición al riesgo crece en zonas costeras.'),
                ('La capacidad de adaptación', '适应能力', 'La capacidad de adaptación varía por región.'),
                ('Las energías renovables', '可再生能源', 'Las energías renovables ya son más baratas.'),
                ('La energía hidráulica', '水力发电', 'La energía hidráulica depende de las lluvias.'),
                ('La biomasa', '生物质能', 'La biomasa aprovecha residuos orgánicos.'),
                ('El hidrógeno verde', '绿氢', 'El hidrógeno verde se produce con electricidad limpia.'),
                ('El consumo energético', '能源消耗', 'El consumo energético bajó con la nueva normativa.'),
                ('La red eléctrica', '电网', 'La red eléctrica necesita más inversión.'),
                ('El almacenamiento de energía', '储能', 'El almacenamiento de energía resuelve la intermitencia.'),
                ('El vehículo eléctrico', '电动汽车', 'El vehículo eléctrico gana cuota cada año.'),
                ('La movilidad sostenible', '可持续出行', 'La movilidad sostenible prioriza la bicicleta y el bus.'),
                ('La contaminación atmosférica', '大气污染', 'La contaminación atmosférica afecta a las ciudades.'),
                ('La calidad del aire', '空气质量', 'La calidad del aire se mide con estaciones fijas.'),
                ('Las partículas en suspensión', '悬浮颗粒物', 'Las partículas en suspensión dañan las vías respiratorias.'),
                ('La emisión de gases', '气体排放', 'La emisión de gases se redujo un cinco por ciento.'),
                ('El consumo de agua', '用水量', 'El consumo de agua bajó tras la campaña.'),
                ('La depuración', '污水处理', 'La depuración devuelve el agua limpia al río.'),
                ('La recogida selectiva', '分类回收', 'La recogida selectiva separa vidrio, papel y envases.'),
                ('La incineración', '焚烧', 'La incineración reduce volumen pero genera emisiones.'),
                ('La economía circular', '循环经济', 'La economía circular alarga la vida de los productos.'),
                ('El plástico de un solo uso', '一次性塑料', 'El plástico de un solo uso está gravado.'),
                ('La inspección ambiental', '环境检查', 'La inspección ambiental detectó vertidos ilegales.'),
                ('El principio de quien contamina paga', '污染者付费原则', 'El principio de quien contamina paga obliga a reparar.'),
                ('La subvención verde', '绿色补贴', 'La subvención verde financia la rehabilitación.'),
                ('La tasa ambiental', '环境税', 'La tasa ambiental grava los residuos no reciclables.'),
                ('La auditoría ambiental', '环境审计', 'La auditoría ambiental revisa consumos y residuos.'),
                ('La etiqueta ecológica', '环保标签', 'La etiqueta ecológica informa al consumidor.'),
                ('La memoria de sostenibilidad', '可持续发展报告', 'La memoria de sostenibilidad es obligatoria para grandes empresas.'),
                ('La responsabilidad social corporativa', '企业社会责任', 'La responsabilidad social corporativa va más allá de la ley.'),
                ('La acción climática', '气候行动', 'La acción climática exige cambios estructurales.'),
                ('El activismo ambiental', '环保行动主义', 'El activismo ambiental presiona a los gobiernos.'),
                ('La educación ambiental', '环境教育', 'La educación ambiental empieza en la escuela.'),
                ('La desertificación', '荒漠化', 'La desertificación avanza en el sureste.'),
                ('La acidificación del océano', '海洋酸化', 'La acidificación del océano daña los arrecifes.'),
                ('La pérdida de biodiversidad', '生物多样性丧失', 'La pérdida de biodiversidad es irreversible.'),
                ('La extinción de especies', '物种灭绝', 'La extinción de especies se acelera por el hábitat.'),
                ('La restauración ecológica', '生态修复', 'La restauración ecológica recupera humedales.'),
                ('La reforestación', '植树造林', 'La reforestación fija carbono y retiene suelo.'),
                ('La gestión del agua', '水资源管理', 'La gestión del agua es clave en zonas áridas.'),
                ('La conservación del litoral', '海岸保护', 'La conservación del litoral limita la construcción.'),
            ],
            'grammar': [
                {'title': '环境议题的被动与无人称结构', 'desc': 'se evalúa / se exige / se estima que + 陈述式。环境报告常用自复被动把施事隐去：Se exige un estudio de impacto ambiental。区分 se estima que（据估计）与 se exige que + 虚拟式（要求……）。'},
                {'title': '表达目标与期限的正式结构', 'desc': 'con el objetivo de + 不定式 / de cara a / para 2050 / en el horizonte de。注意 con el objetivo de que 后面要接虚拟式：con el objetivo de que se reduzcan las emisiones。'},
                {'title': '因果与后果的书面连接', 'desc': 'a causa de / debido a / como consecuencia de / lo que se traduce en。debido a 后面接名词短语；debido a que 接从句。'},
            ],
        },
        {
            'id': 'b2-u17', 'title': '教育体制与学术规范', 'subtitle': 'Sistema Educativo y Normas Académicas',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
                ('El sistema educativo', '教育体制', 'El sistema educativo combina centros públicos y privados.'),
                ('La etapa educativa', '教育阶段', 'Cada etapa educativa tiene objetivos propios.'),
                ('La educación infantil', '幼儿教育', 'La educación infantil no es obligatoria.'),
                ('La educación primaria', '小学教育', 'La educación primaria dura seis cursos.'),
                ('La educación secundaria', '中学教育', 'La educación secundaria es obligatoria.'),
                ('El bachillerato', '高中（西班牙学制）', 'El bachillerato prepara para la universidad.'),
                ('La formación profesional', '职业教育', 'La formación profesional tiene salida laboral.'),
                ('La universidad pública', '公立大学', 'La universidad pública cobra tasas moderadas.'),
                ('La universidad privada', '私立大学', 'La universidad privada es más cara.'),
                ('El expediente académico', '成绩档案', 'El expediente académico recoge todas las notas.'),
                ('La asignatura obligatoria', '必修课', 'Es una asignatura obligatoria en primero.'),
                ('La asignatura optativa', '选修课', 'Elegí una asignatura optativa de arte.'),
                ('El curso académico', '学年', 'El curso académico empieza en septiembre.'),
                ('El calendario escolar', '校历', 'El calendario escolar incluye los festivos.'),
                ('La convocatoria de examen', '考试场次', 'La convocatoria de examen es en junio.'),
                ('La nota de corte', '录取分数线', 'La nota de corte subió este año.'),
                ('La ayuda económica', '助学金', 'Solicitó una ayuda económica al ministerio.'),
                ('El acceso a la universidad', '大学入学', 'El acceso a la universidad depende de la nota.'),
                ('La prueba de acceso', '入学考试', 'La prueba de acceso evalúa varias materias.'),
                ('La orientación académica', '学业指导', 'La orientación académica ayuda a elegir itinerario.'),
                ('El orientador', '学业指导老师', 'El orientador revisó su expediente.'),
                ('El tutor', '导师、班主任', 'El tutor cita a las familias una vez al trimestre.'),
                ('El trabajo de fin de grado', '本科毕业论文', 'El trabajo de fin de grado tiene doce créditos.'),
                ('El trabajo de fin de máster', '硕士毕业论文', 'El trabajo de fin de máster se defiende en junio.'),
                ('La defensa de tesis', '论文答辩', 'La defensa de tesis dura una hora.'),
                ('El tribunal', '答辩委员会', 'El tribunal valoró la originalidad del trabajo.'),
                ('El director de tesis', '论文导师', 'El director de tesis corrigió el capítulo dos.'),
                ('La publicación científica', '科研发表', 'La publicación científica pasa por revisión.'),
                ('El índice de impacto', '影响因子', 'El índice de impacto mide las citas recibidas.'),
                ('La cita bibliográfica', '文献引用', 'La cita bibliográfica debe ser exacta.'),
                ('La integridad académica', '学术诚信', 'La integridad académica prohíbe copiar.'),
                ('El fraude académico', '学术造假', 'El fraude académico se sanciona con la expulsión.'),
                ('La originalidad', '原创性', 'La originalidad es el criterio principal.'),
                ('La contribución', '学术贡献', 'Su contribución al debate es clara.'),
                ('La metodología mixta', '混合研究方法', 'La metodología mixta combina encuestas y entrevistas.'),
                ('El grupo experimental', '实验组', 'El grupo experimental recibió el nuevo método.'),
                ('La alfabetización científica', '科学素养', 'La alfabetización científica se enseña desde primaria.'),
                ('El pensamiento crítico', '批判性思维', 'El pensamiento crítico se evalúa con casos abiertos.'),
                ('La competencia digital', '数字素养', 'La competencia digital es requisito del puesto.'),
                ('La formación continua', '继续教育', 'La formación continua se hace fuera del horario.'),
                ('El reciclaje profesional', '职业再培训', 'El reciclaje profesional evita el desempleo largo.'),
                ('La inserción laboral', '就业融入', 'La inserción laboral mejora con prácticas.'),
                ('La empleabilidad', '就业能力', 'La empleabilidad depende de las competencias.'),
                ('La orientación profesional', '职业指导', 'La orientación profesional revisa el perfil.'),
                ('La vocación', '志向', 'Descubrió su vocación a los dieciséis.'),
                ('El abandono escolar', '辍学', 'El abandono escolar bajó en la última década.'),
                ('El fracaso escolar', '学业失败', 'El fracaso escolar se asocia a la repetición.'),
                ('La desigualdad educativa', '教育不平等', 'La desigualdad educativa se refleja en los resultados.'),
                ('La brecha digital', '数字鸿沟', 'La brecha digital afecta a las zonas rurales.'),
                ('La atención a la diversidad', '关注多样性', 'La atención a la diversidad adapta el aula.'),
                ('Las necesidades educativas especiales', '特殊教育需求', 'Las necesidades educativas especiales requieren apoyo.'),
                ('El apoyo educativo', '教育支持', 'El apoyo educativo se refuerza fuera del aula.'),
                ('La evaluación continua', '过程性评价', 'La evaluación continua reparte la nota.'),
                ('La evaluación formativa', '形成性评价', 'La evaluación formativa orienta la mejora.'),
                ('La autoevaluación', '自我评估', 'La autoevaluación cierra cada unidad.'),
                ('La coevaluación', '同伴互评', 'La coevaluación reparte responsabilidad.'),
                ('La inclusión', '包容', 'La inclusión es un principio del sistema.'),
            ],
            'grammar': [
                {'title': '教育体制中的名词化与被动', 'desc': 'La escolarización obligatoria / La implantación de la reforma / Se contempla la posibilidad de…。制度文本偏爱名词化和无人称，注意 la implantación de（推行）与 la aplicación de（实施）的分工。'},
                {'title': '表达义务、条件与例外的正式结构', 'desc': 'queda prohibido / se permite / siempre que + 虚拟式 / a excepción de。规定类文本用 queda + 分词：queda prohibido el uso del móvil。'},
                {'title': '数量与统计的学术表述', 'desc': 'un tercio de / la mitad de / el porcentaje de / en torno a。注意 la mitad de los alumnos（半数学生）中动词的数随 la mitad 走：La mitad de los alumnos aprueba。'},
            ],
        },
        {
            'id': 'b2-u18', 'title': '正式书面语与公开表达', 'subtitle': 'Registro Formal y Expresión Pública',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
                ('La carta formal', '正式信函', 'La carta formal empieza con el saludo adecuado.'),
                ('El encabezamiento', '抬头', 'El encabezamiento incluye lugar y fecha.'),
                ('La fórmula de saludo', '称呼语', 'La fórmula de saludo depende del destinatario.'),
                ('La fórmula de despedida', '结束语', 'La fórmula de despedida cierra la carta.'),
                ('El destinatario', '收件人', 'El destinatario aparece arriba a la derecha.'),
                ('El remitente', '寄件人', 'El remitente firma al final.'),
                ('El asunto', '事由', 'El asunto resume el motivo en una línea.'),
                ('El adjunto', '附件', 'Revisa el adjunto antes de enviar.'),
                ('El anexo', '附录', 'El anexo incluye las tablas completas.'),
                ('La posdata', '附言', 'La posdata añade algo olvidado.'),
                ('El membrete', '信头', 'El membrete identifica a la institución.'),
                ('La rúbrica', '签名花押', 'La rúbrica acompaña a la firma.'),
                ('El registro formal', '正式语域', 'El registro formal evita contracciones.'),
                ('El tratamiento de usted', '敬称', 'El tratamiento de usted mantiene la distancia.'),
                ('El estilo impersonal', '无人称语体', 'El estilo impersonal oculta al autor.'),
                ('La pasiva refleja', '自复被动', 'La pasiva refleja es muy frecuente en español.'),
                ('La nominalización', '名词化', 'La nominalización alarga pero objetiviza.'),
                ('El conector discursivo', '语篇连接词', 'El conector discursivo ordena el argumento.'),
                ('El marcador textual', '篇章标记', 'El marcador textual guía al lector.'),
                ('El párrafo de apertura', '开篇段', 'El párrafo de apertura presenta la tesis.'),
                ('El párrafo de cierre', '结尾段', 'El párrafo de cierre resume sin repetir.'),
                ('La introducción', '引言', 'La introducción justifica el trabajo.'),
                ('La enumeración', '列举', 'La enumeración ordena los argumentos.'),
                ('La contraposición', '对比并列', 'La contraposición enfrenta dos posturas.'),
                ('La reformulación', '重述', 'La reformulación aclara sin repetir.'),
                ('La ejemplificación', '举例说明', 'La ejemplificación hace concreto lo abstracto.'),
                ('La paráfrasis', '释义', 'La paráfrasis reformula con otras palabras.'),
                ('El entrecomillado', '加引号', 'El entrecomillado marca las palabras ajenas.'),
                ('La referencia bibliográfica', '参考文献条目', 'La referencia bibliográfica sigue un formato fijo.'),
                ('El apartado', '章节', 'Cada apartado trata un solo punto.'),
                ('El epígrafe', '小节标题', 'El epígrafe numera las secciones.'),
                ('El simposio', '专题研讨会', 'El simposio reunió a especialistas.'),
                ('La mesa redonda', '圆桌讨论', 'La mesa redonda admitió preguntas.'),
                ('El debate abierto', '公开辩论', 'El debate abierto duró dos horas.'),
                ('El turno de réplica', '答辩轮次', 'Pidió el turno de réplica.'),
                ('El oyente', '听众个体', 'El oyente interpreta según su experiencia.'),
                ('El orador', '演讲者', 'El orador dominó la sala.'),
                ('La oratoria', '演讲术', 'La oratoria se entrena con práctica.'),
                ('El guion', '讲稿提纲', 'El guion marca las pausas.'),
                ('La ficha', '卡片、笔记卡', 'Preparó una ficha por idea.'),
                ('El apoyo visual', '视觉辅助', 'El apoyo visual no debe leerse en voz alta.'),
                ('La diapositiva', '幻灯片', 'La diapositiva tenía demasiado texto.'),
                ('La recapitulación', '回顾小结', 'La recapitulación cierra la exposición.'),
                ('La exhortación', '呼吁', 'La exhortación final buscó adhesión.'),
                ('La pregunta retórica', '反问', 'La pregunta retórica no espera respuesta.'),
                ('La entonación', '语调', 'La entonación evita el tono monótono.'),
                ('El lenguaje no verbal', '非语言表达', 'El lenguaje no verbal comunica tanto como el texto.'),
                ('El contacto visual', '眼神交流', 'El contacto visual mantiene la atención.'),
                ('La dicción', '咬字', 'La dicción clara mejora la comprensión.'),
                ('La vocalización', '发音清晰度', 'La vocalización se trabaja leyendo en voz alta.'),
                ('La claridad expositiva', '表达清晰度', 'La claridad expositiva es lo primero que se valora.'),
                ('La propiedad léxica', '用词恰当', 'La propiedad léxica evita el término impreciso.'),
                ('El lenguaje inclusivo', '包容性语言', 'El lenguaje inclusivo busca evitar sesgos.'),
            ],
            'grammar': [
                {'title': '书面语体的名词化与无人称', 'desc': '把动作写成名词以取得客观感：analizar → el análisis，aplicar → la aplicación。注意名词化过多会让句子失去施事，学术写作建议控制比例。'},
                {'title': '论证的连接与推进结构', 'desc': 'en primer lugar / por un lado / no obstante / en definitiva。区分 no obstante（转折，书面）与 sin embargo（同样书面但更中性）；en definitiva 用于收束。'},
                {'title': '强调与倒装', 'desc': 'Lo que más importa es… / Fue entonces cuando… / No solo… sino también…。强调句 lo que… es 把信息焦点后置；倒装 No solo… sino también 后接并列结构。'},
            ],
        },
    ],
}
