# -*- coding: utf-8 -*-
"""批次 54：A2 再补两个单元（节日与庆祝 / 邻里与社区服务）

A2（580）在 B2 补完后再次成为最低等级。选题避开 A2 已有 15 个单元
（家庭/外貌/过去/喜好/天气/医院/工作学习/旅行预订/打电话/交通/考试/
职业/银行/餐厅/运动）。
"""

BATCH = {
    'A2': [
        {
            'id': 'a2-u19',
            'title': '节日与庆祝',
            'subtitle': 'Fiestas y Celebraciones',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('La fiesta', '节日、聚会', 'La fiesta duró hasta la madrugada.'),
                ('La celebración', '庆祝活动', 'La celebración fue sencilla.'),
                ('El cumpleaños', '生日', 'Cumplo años el mes que viene.'),
                ('El aniversario', '周年纪念', 'Celebran su aniversario en familia.'),
                ('La boda', '婚礼', 'La boda será en junio.'),
                ('El banquete', '宴席', 'El banquete se sirvió a las tres.'),
                ('El brindis', '祝酒', 'Hicieron un brindis por los novios.'),
                ('La tarta', '蛋糕', 'La tarta tenía velas.'),
                ('La vela', '蜡烛', 'Sopló las velas de un golpe.'),
                ('El regalo', '礼物', 'Le regalaron un libro.'),
                ('La felicitación', '祝贺、贺词', 'Recibió muchas felicitaciones.'),
                ('La tarjeta', '贺卡', 'Le envió una tarjeta de cumpleaños.'),
                ('La invitación', '邀请', 'Llegó la invitación por correo.'),
                ('El invitado', '客人', 'Hubo cuarenta invitados.'),
                ('El anfitrión', '主人、东道主', 'El anfitrión recibió a todos.'),
                ('La decoración', '装饰', 'La decoración era muy sencilla.'),
                ('El globo', '气球', 'Los globos alegraron la sala.'),
                ('El fuego artificial', '烟花', 'Los fuegos artificiales duraron media hora.'),
                ('La verbena', '露天晚会', 'La verbena del barrio es tradicional.'),
                ('La procesión', '巡游', 'La procesión recorre el casco antiguo.'),
                ('La tradición', '传统', 'Es una tradición muy antigua.'),
                ('La costumbre', '习俗', 'Es costumbre cenar en familia.'),
                ('El desfile', '游行', 'El desfile pasó por la avenida.'),
                ('La cabalgata', '花车巡游', 'La cabalgata de Reyes llena las calles.'),
                ('Los Reyes Magos', '三王节（1月6日）', 'Los niños esperan a los Reyes Magos.'),
                ('La Nochevieja', '除夕夜', 'En Nochevieja se toman doce uvas.'),
                ('La Nochebuena', '平安夜', 'En Nochebuena cenan en familia.'),
                ('La Semana Santa', '圣周', 'La Semana Santa es muy solemne aquí.'),
                ('El puente', '连休（搭桥假）', 'Hicimos un puente de cuatro días.'),
                ('El día festivo', '法定假日', 'El lunes es día festivo.'),
                ('La verbena popular', '民众联欢会', 'La verbena popular atrajo a todo el barrio.'),
                ('El disfraz', '化装服', 'Se puso un disfraz de pirata.'),
                ('El carnaval', '狂欢节', 'El carnaval dura una semana.'),
                ('La chirigota', '狂欢歌曲团', 'Las chirigotas cantan críticas.'),
                ('La charanga', '吹奏乐队', 'La charanga animó el desfile.'),
                ('El castillo de fuegos', '烟火表演', 'El castillo de fuegos cerró la fiesta.'),
                ('La mascletá', '爆竹表演', 'La mascletá se dispara al mediodía.'),
                ('La falla', '法雅（瓦伦西亚）', 'La falla se quemó en la noche.'),
                ('El santo', '主保圣人节', 'Celebra su santo el 19 de marzo.'),
                ('La onomástica', '命名日', 'Aquí se celebra más la onomástica.'),
                ('El aguinaldo', '节日赏钱', 'Recibió un aguinaldo de la empresa.'),
                ('La lotería', '彩票', 'Compraron lotería de Navidad.'),
                ('El sorteo', '抽奖、开奖', 'El sorteo fue el 22 de diciembre.'),
                ('El premio', '奖金、奖品', 'Le tocó un premio pequeño.'),
                ('El cotillón', '舞会', 'El cotillón terminó a las cinco.'),
                ('La resaca', '宿醉', 'Al día siguiente tenía resaca.'),
                ('Felicit	ar', '祝贺', 'Hay que felicitar a los novios.'),
                ('Brindar por', '为……干杯', 'Brindaron por la salud de todos.'),
                ('Invitar a', '邀请', 'Me invitó a su cumpleaños.'),
                ('Celebrar', '庆祝', 'Celebramos el ascenso con una cena.'),
                ('Decorar', '装饰', 'Decoraron la sala con flores.'),
                ('Regalar', '赠送', 'Le regalaron una bicicleta.'),
                ('Reunirse', '聚会', 'La familia se reúne cada año.'),
                ('Disfrazarse de', '化装成', 'Se disfrazó de médico.'),
                ('Alegrarse por', '为……高兴', 'Me alegro por tu ascenso.'),
                ('Dar la enhorabuena', '道贺', 'Le dio la enhorabuena en persona.'),
            ],
            'grammar': [
                {'title': '表达祝贺与祝福的句式', 'desc': '¡Felicidades! / ¡Enhorabuena! / ¡Que cumplas muchos más! / ¡Que lo paséis bien! —— 注意 que + 虚拟式表祝愿，这是西语祝福语的固定格式，不用陈述式。'},
                {'title': '节日名称与冠词', 'desc': 'la Navidad / el Año Nuevo / los Reyes Magos / la Semana Santa。节日名一般带定冠词，且首字母不大写（与英语不同）。'},
                {'title': 'festejar / celebrar / brindar 的分工', 'desc': 'celebrar ＝ 庆祝（活动）；brindar por ＝ 为……干杯；festejar ＝ 庆祝、宴请（较书面）。注意 brindar 的介词固定为 por。'},
            ],
        },
        {
            'id': 'a2-u20',
            'title': '邻里与社区服务',
            'subtitle': 'Vecindario y Servicios',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('El barrio', '街区', 'Mi barrio es tranquilo y familiar.'),
                ('El vecino', '邻居', 'El vecino de al lado es amable.'),
                ('La comunidad', '业主共同体', 'La comunidad aprobó la reforma.'),
                ('La junta', '业主大会', 'La junta se reúne cada trimestre.'),
                ('El presidente', '业委会主任', 'El presidente convocó la reunión.'),
                ('La cuota', '物业费', 'La cuota mensual subió.'),
                ('La derrama', '临时摊派', 'Aprobaron una derrama para el ascensor.'),
                ('El portal', '门厅、楼门', 'El portal está recién pintado.'),
                ('El portero', '门卫', 'El portero recibe los paquetes.'),
                ('El buzón', '信箱', 'Hay una carta en el buzón.'),
                ('El timbre', '门铃', 'El timbre no suena.'),
                ('El ruido', '噪音', 'El ruido de obras molesta.'),
                ('La queja', '投诉', 'Presentamos una queja formal.'),
                ('El conflicto', '冲突', 'El conflicto se resolvió pronto.'),
                ('El acuerdo', '协议', 'Llegaron a un acuerdo.'),
                ('La reunión', '会议', 'La reunión duró una hora.'),
                ('La convocatoria', '召集通知', 'La convocatoria llegó por correo.'),
                ('El acta', '会议记录', 'El acta recoge los acuerdos.'),
                ('La mayoría', '多数', 'Se aprobó por mayoría.'),
                ('La abstención', '弃权', 'Hubo dos abstenciones.'),
                ('El servicio', '服务', 'El servicio de limpieza funciona.'),
                ('La limpieza', '清洁', 'La limpieza de la escalera es semanal.'),
                ('El mantenimiento', '维护', 'El mantenimiento sube cada año.'),
                ('La avería', '故障', 'La avería del ascensor duró días.'),
                ('El técnico', '技术员', 'El técnico vino por la tarde.'),
                ('La reforma', '改造', 'La reforma del tejado es urgente.'),
                ('La obra', '施工', 'La obra empezará en marzo.'),
                ('El presupuesto', '预算、报价', 'Pidieron tres presupuestos.'),
                ('El seguro', '保险', 'El seguro cubre los daños.'),
                ('El siniestro', '事故损失', 'El siniestro afectó a dos pisos.'),
                ('La fuga de agua', '漏水', 'Hubo una fuga de agua en el sótano.'),
                ('La humedad', '潮湿', 'La humedad sube por la pared.'),
                ('El sótano', '地下室', 'Guardamos las bicis en el sótano.'),
                ('El garaje', '车库', 'El garaje tiene dos plazas libres.'),
                ('La plaza de aparcamiento', '车位', 'Alquilamos una plaza de aparcamiento.'),
                ('La azotea', '屋顶平台', 'La azotea está reformada.'),
                ('El patio', '天井、院子', 'El patio interior da luz.'),
                ('La zona común', '公共区域', 'Las zonas comunes están cuidadas.'),
                ('La asociación de vecinos', '居民协会', 'La asociación de vecinos organiza actividades.'),
                ('La actividad', '活动', 'Las actividades del centro son gratuitas.'),
                ('El centro cívico', '社区中心', 'El centro cívico ofrece talleres.'),
                ('El taller', '工作坊', 'Hice un taller de cerámica.'),
                ('La biblioteca', '图书馆', 'La biblioteca abre hasta las nueve.'),
                ('El ambulatorio', '社区诊所', 'El ambulatorio está a dos calles.'),
                ('La farmacia de guardia', '值班药店', 'La farmacia de guardia está cerca.'),
                ('El mercado municipal', '市政市场', 'El mercado municipal abre los sábados.'),
                ('La piscina municipal', '市立游泳池', 'La piscina municipal es barata.'),
                ('El polideportivo', '体育馆', 'El polideportivo abre a las siete.'),
                ('La recogida de basura', '垃圾收集', 'La recogida de basura pasa cada noche.'),
                ('El contenedor', '垃圾桶', 'El contenedor amarillo es para plásticos.'),
                ('El punto limpio', '废弃物回收站', 'Llevamos los muebles al punto limpio.'),
                ('La acera', '人行道', 'La acera está en obras.'),
                ('La farola', '路灯', 'Una farola lleva semanas fundida.'),
                ('Quejarse de', '抱怨', 'Se quejan del ruido por la noche.'),
                ('Reclamar', '申诉、索赔', 'Reclamaron al ayuntamiento.'),
                ('Colaborar con', '与……协作', 'Colabora con la asociación.'),
                ('Participar en', '参与', 'Participo en las reuniones.'),
                ('Respetar', '尊重', 'Hay que respetar el descanso.'),
                ('Avisar a', '通知', 'Avisa a los vecinos del corte de agua.'),
            ],
            'grammar': [
                {'title': '投诉与交涉的表达', 'desc': 'Quisiera presentar una queja / Me gustaría reclamar / ¿Podrían revisar...? —— 对物业或政府提要求时用条件式，比命令式得体。注意 reclamar 可直接接宾语，也可 reclamar a + 机构。'},
                {'title': '无人称 se 在社区通知中', 'desc': 'Se ruega silencio / Se prohíbe tender ropa / Se avisa a los vecinos / Se ha detectado una avería。社区告示与通知几乎全部使用无人称 se 结构。'},
                {'title': '相互动作与共同行动', 'desc': 'Se respetan（他们互相尊重）/ colaborar con（与……合作）/ participar en（参与）/ ponerse de acuerdo（达成一致）。表共同行动时注意反身代词与介词的选择。'},
            ],
        },
    ],
}
