# -*- coding: utf-8 -*-
"""批次 36：清掉剩余的听说词汇缺口 + 补 B2/C1/C2 语法练习

一、词汇：audit 报出听说材料里仍有若干单词不在词库。逐条判定后：
   - 应入库的内容词：profesora / innovadores / inflamada / sincera / la constancia /
     el suplemento / la palabrería / el egresado / el decorado / catalogado /
     desmedido / encantada / escuchar
   - 不应入库（已在文档中说明，不计为缺陷）：
     · 动词变位形：conocerte / compré / decidimos / escribieras / insistiera /
       insistas / saldremos / avísame / convendría / síganme
     · 虚词：aunque
     · 专有名词：Almodóvar
     · 派生/分词形：proporcionado
二、语法：补 B2/C1/C2 各一组专项，缩减「语法点无练习」的缺口。
"""

BATCH = {
    'A1': [
        {
            'id': 'a1-u16',
            'title': '补充基础词',
            'subtitle': 'Vocabulario Básico Complementario',
            'lessons': 8,
            'duration': '约 25 分钟',
            'vocab': [
                ('La profesora', '女教师', 'La profesora explicó la lección.'),
                ('Encantada', '很高兴认识你（女方用语）', 'Encantada de conocerte.'),
                ('Escuchar', '听', 'Me gusta escuchar música.'),
                ('El suplemento', '增刊、补剂', 'El periódico trae un suplemento cultural.'),
                ('La constancia', '坚持、恒心', 'La constancia vale más que el talento.'),
                ('Sincera', '坦诚的（阴性）', 'Fue muy sincera conmigo.'),
                ('Innovador', '创新的', 'Es un enfoque innovador.'),
                ('Inflamado', '发炎的、红肿的', 'Tiene el tobillo inflamado.'),
                ('El decorado', '布景', 'El decorado cambia en cada acto.'),
                ('El egresado', '毕业生', 'Los egresados buscan trabajo.'),
                ('Catalogado', '被列入名录的', 'Es un edificio catalogado.'),
                ('Desmedido', '过度的、无节制的', 'Su ambición es desmedida.'),
                ('La palabrería', '空话', 'Su discurso es pura palabrería.'),
            ],
            'grammar': [
                {'title': '形容词的阴阳性（补充）', 'desc': 'sincero / sincera、innovador / innovadora、inflamado / inflamada —— 以 -o 结尾的形容词修饰阴性名词时改为 -a；以 -or 结尾的加 -a（trabajador / trabajadora），少数不变（inteligente）。'},
                {'title': 'encantado / encantada 的用法', 'desc': '初次见面说 Encantado（男）/ Encantada（女），意思是「很高兴认识你」。选择哪个形式取决于**说话人自己**的性别，而不是对方。'},
                {'title': 'escuchar 与 oír 的区别', 'desc': 'oír 是「听到」（被动接收声音），escuchar 是「听」（主动去听）。Escucho música（我在听音乐）vs Oigo un ruido（我听到一个响声）。'},
            ],
        },
    ],
    'B2': [
        {
            'id': 'b2-u13',
            'title': '论证与反驳句式',
            'subtitle': 'Estructuras de Argumentación y Refutación',
            'lessons': 12,
            'duration': '约 45 分钟',
            'vocab': [
                ('Sostener que', '主张', 'Sostiene que la medida es necesaria.'),
                ('Aducir que', '援引理由', 'Adujo que faltaba presupuesto.'),
                ('Objetar que', '提出异议', 'Objetó que el plazo era imposible.'),
                ('Rebatir', '反驳', 'Rebatió el argumento con datos.'),
                ('Refutar', '驳倒', 'Refutó la hipótesis por completo.'),
                ('Contraargumentar', '提出反论', 'Contraargumentó con un ejemplo.'),
                ('Conceder que', '承认（让步）', 'Concede que hay avances, pero insuficientes.'),
                ('Reconocer que', '承认', 'Reconoce que se equivocó.'),
                ('Cuestionar', '质疑', 'Cuestión la premisa del estudio.'),
                ('Matizar', '补充限定', 'Conviene matizar esa conclusión.'),
                ('Precisar', '明确说明', 'Precisó que no era una promesa.'),
                ('Recalcar', '强调', 'Recalcó la urgencia del problema.'),
                ('Incidir en', '强调、着重于', 'Incidió en la falta de datos.'),
                ('Poner de relieve', '凸显', 'Puso de relieve la contradicción.'),
                ('Pasar por alto', '忽略', 'No podemos pasar por alto ese detalle.'),
                ('Dar por sentado', '想当然', 'Dio por sentado lo que debía demostrar.'),
                ('Caer en', '陷入（错误）', 'Cae en una contradicción evidente.'),
                ('Incurrir en', '犯（错误）', 'Incurrió en el mismo error.'),
                ('Adolecer de', '有……缺陷', 'El estudio adolece de falta de muestra.'),
                ('Pecar de', '失之于', 'El informe peca de optimista.'),
                ('Carecer de', '缺乏', 'La propuesta carece de fundamento.'),
                ('Prescindir de', '舍弃、不考虑', 'Prescinde de los datos incómodos.'),
                ('Remitirse a', '援引、依据', 'Se remite a estudios previos.'),
                ('Atenerse a', '依据、遵循', 'Nos atenemos a los hechos.'),
                ('Cernirse a', '严格限于', 'El análisis se ciñe al caso español.'),
                ('Deslindar', '划清界限', 'Conviene deslindar ambos conceptos.'),
                ('Inferir de', '从……推断', 'De ahí se infiere una conclusión.'),
                ('Equivale a', '等于', 'Eso equivale a admitir el error.'),
                ('Traducirse en', '转化为', 'El esfuerzo se tradujo en resultados.'),
                ('Venir a decir', '等于说', 'Viene a decir que nadie es responsable.'),
                ('En rigor', '严格说来', 'En rigor, la afirmación es falsa.'),
                ('A todas luces', '显然', 'Es a todas luces insuficiente.'),
                ('En última instancia', '归根结底', 'En última instancia decide el poder.'),
                ('Por lo pronto', '就目前而言', 'Por lo pronto no hay cambios.'),
                ('De entrada', '一开始、首先', 'De entrada, la premisa es dudosa.'),
                ('Sin ir más lejos', '不必远求（就近举例）', 'Sin ir más lejos, este mismo caso.'),
                ('Ni mucho menos', '更谈不上', 'No es fácil, ni mucho menos obvio.'),
                ('Lejos de', '非但不……反而', 'Lejos de resolverse, empeoró.'),
                ('Antes bien', '反倒', 'No se debilitó, antes bien se reforzó.'),
                ('Todo lo contrario', '恰恰相反', 'Todo lo contrario: aumentó.'),
            ],
            'grammar': [
                {'title': '论证动词的语式选择', 'desc': 'sostener / aducir / reconocer / conceder que + 陈述式（陈述具体主张）；objetar / pedir / sugerir que + 虚拟式（表意志）。判断依据是从句所表达的是「事实断言」还是「意愿要求」。'},
                {'title': '让步—转折的三段式', 'desc': 'Concede que X, pero Y；Si bien X, Y；Es cierto que X, sin embargo Y。西语论证写作的标准让步结构：先承认对方最强的一点，再给出限定，比直接否定更有效。'},
                {'title': '介词化动词短语', 'desc': 'adolecer de / pecar de / carecer de / incurrir en / caer en / remitirse a / atenerse a / cernirse a —— 这些动词的介词搭配固定，用错会改变语义或使句子不成立，需要整块记忆。'},
            ],
        },
    ],
    'C1': [
        {
            'id': 'c1-u15',
            'title': '学术写作句式',
            'subtitle': 'Estructuras de Escritura Académica',
            'lessons': 12,
            'duration': '约 50 分钟',
            'vocab': [
                ('El planteamiento', '论述框架', 'El planteamiento del problema es claro.'),
                ('El marco teórico', '理论框架', 'El marco teórico es pertinente.'),
                ('El estado de la cuestión', '研究现状', 'Resume el estado de la cuestión.'),
                ('La delimitación', '界定', 'Falta delimitar el objeto de estudio.'),
                ('El corpus', '语料', 'El corpus consta de mil textos.'),
                ('La variable', '变量', 'Se controlaron tres variables.'),
                ('El indicador', '指标', 'El indicador es poco fiable.'),
                ('La robustez', '稳健性', 'La robustez del resultado es discutible.'),
                ('La validez externa', '外部效度', 'La validez externa queda en duda.'),
                ('La replicabilidad', '可复现性', 'La replicabilidad es un requisito.'),
                ('El sesgo de selección', '选择偏差', 'Hubo sesgo de selección en la muestra.'),
                ('La significatividad', '显著性', 'La significatividad estadística es baja.'),
                ('La correlación espuria', '虚假相关', 'Es una correlación espuria.'),
                ('El grupo de control', '对照组', 'El grupo de control no recibió tratamiento.'),
                ('La triangulación', '三角互证', 'La triangulación refuerza las conclusiones.'),
                ('El sesgo del investigador', '研究者偏差', 'El sesgo del investigador es inevitable.'),
                ('La revisión sistemática', '系统性综述', 'Publicaron una revisión sistemática.'),
                ('El metaanálisis', '元分析', 'El metaanálisis agrupa veinte estudios.'),
                ('La hipótesis nula', '零假设', 'Se rechazó la hipótesis nula.'),
                ('El intervalo de confianza', '置信区间', 'El intervalo de confianza es amplio.'),
                ('El tamaño del efecto', '效应量', 'El tamaño del efecto es pequeño.'),
                ('La generalización', '推广性', 'La generalización es arriesgada.'),
                ('El supuesto', '前提假定', 'El supuesto no se explicita.'),
                ('La limitación', '局限', 'El artículo reconoce sus limitaciones.'),
                ('El alcance', '研究范围', 'El alcance es deliberadamente acotado.'),
                ('La réplica', '重复研究', 'La réplica no confirmó el hallazgo.'),
                ('El acervo', '积累、总汇', 'El acervo documental es enorme.'),
                ('La controversia', '争议', 'La controversia sigue abierta.'),
                ('El consenso', '共识', 'No hay consenso sobre el método.'),
                ('La refutación', '反驳', 'La refutación es convincente.'),
                ('La falacia', '谬误', 'Es una falacia de composición.'),
                ('La circularidad', '循环论证', 'Hay circularidad en el argumento.'),
                ('La premisa implícita', '隐含前提', 'Detecta una premisa implícita dudosa.'),
                ('El contraejemplo', '反例', 'Basta un contraejemplo para refutarlo.'),
                ('La objeción', '反对意见', 'Anticipa tres objeciones posibles.'),
                ('La salvedad', '保留意见', 'Añade una salvedad metodológica.'),
                ('El escollo', '障碍、暗礁', 'Quedan dos escollos por salvar.'),
                ('El trasfondo', '背景、底层', 'El trasfondo ideológico es claro.'),
                ('La tesitura', '处境、局面', 'En esa tesitura, conviene esperar.'),
                ('La aquiescencia', '默许', 'Su aquiescencia fue silenciosa.'),
            ],
            'grammar': [
                {'title': '学术写作的无人称框架', 'desc': 'El presente trabajo se propone / Cabe señalar que / Procede advertir que / Conviene precisar que —— 西语学术论文用这些无人称句交代写作意图与限定，避免第一人称「我认为」。'},
                {'title': '表达方法与结果的时态', 'desc': '描述方法用过去时（se aplicó una encuesta）；陈述结果与结论用现在时（los datos muestran）。这一时态分工在学术写作中是固定的，混用会被视为不专业。'},
                {'title': '局限性与展望的固定表述', 'desc': 'Entre las limitaciones del estudio cabe mencionar... / Futuras investigaciones deberían... / Los resultados deben tomarse con cautela。论文的「局限」一节几乎完全由这些套语构成。'},
            ],
        },
    ],
    'C2': [
        {
            'id': 'c2-u12',
            'title': '语用与修辞手段',
            'subtitle': 'Pragmática y Recursos Retóricos',
            'lessons': 12,
            'duration': '约 55 分钟',
            'vocab': [
                ('La presuposición', '预设', 'La pregunta contiene una presuposición.'),
                ('La implicatura', '会话隐含', 'La implicatura no se dice, se infiere.'),
                ('El acto de habla', '言语行为', 'Prometer es un acto de habla.'),
                ('La deixis', '指示', 'La deixis sitúa el enunciado.'),
                ('La modalidad', '情态', 'La modalidad expresa duda o certeza.'),
                ('El registro', '语域', 'El registro cambia según el contexto.'),
                ('La atenuación', '缓和语', 'Usa atenuación para no imponer.'),
                ('La cortesía', '礼貌', 'La cortesía varía entre culturas.'),
                ('La ironía', '反讽', 'La ironía invierte el sentido literal.'),
                ('La litote', '曲言法', 'La litote niega lo contrario.'),
                ('La preterición', '阳否阴述', 'La preterición menciona al negarlo.'),
                ('El circunloquio', '迂回说法', 'Evitó el tema con circunloquios.'),
                ('La ambigüedad calculada', '刻意含混', 'La ambigüedad calculada permite negarlo.'),
                ('El doble sentido', '双关', 'El doble sentido es intencionado.'),
                ('La elipsis', '省略', 'La elipsis omite lo obvio.'),
                ('La anáfora', '首语重复', 'La anáfora insiste al repetir.'),
                ('El asíndeton', '连词省略', 'El asíndeton acelera el ritmo.'),
                ('El polisíndeton', '连词叠用', 'El polisíndeton frena y solemniza.'),
                ('La gradación', '层递', 'La gradación intensifica el argumento.'),
                ('La antítesis', '对照', 'La antítesis opone dos ideas.'),
                ('La paradoja', '悖论', 'La paradoja obliga a releer.'),
                ('El oxímoron', '矛盾修辞', 'El oxímoron une contrarios.'),
                ('El eufemismo', '委婉语', 'El eufemismo oculta la crudeza.'),
                ('La hipérbole', '夸张', 'La hipérbole debilita la tesis.'),
                ('La metonimia', '换喻', 'La metonimia sustituye por contigüidad.'),
                ('La sinécdoque', '提喻', 'La sinécdoque toma la parte por el todo.'),
                ('El apóstrofe', '呼语', 'El apóstrofe interpela al ausente.'),
                ('La reticencia', '欲言又止', 'La reticencia sugiere sin afirmar.'),
                ('La digresión', '离题', 'La digresión interrumpe el hilo.'),
                ('El tono', '语气', 'El tono condiciona la recepción.'),
                ('La vehemencia', '激烈', 'Habló con vehemencia inusual.'),
                ('La mesura', '节制', 'La mesura del estilo convence más.'),
                ('La rotundidad', '斩钉截铁', 'La rotundidad no sustituye la prueba.'),
                ('La ambigüedad', '含糊、歧义', 'La ambigüedad fue deliberada.'),
                ('La prolijidad', '冗长', 'La prolijidad cansa al lector.'),
                ('La concisión', '简洁', 'La concisión exige más trabajo.'),
                ('La pertinencia', '相关性', 'La pertinencia del ejemplo es dudosa.'),
                ('La oportunidad', '适时', 'La oportunidad del comentario es dudosa.'),
                ('La sutileza', '微妙', 'La sutileza del matiz se pierde.'),
                ('El matiz', '细微差别', 'Ese matiz cambia el sentido.'),
                ('La carga connotativa', '内涵色彩', 'La carga connotativa es negativa.'),
                ('La denotación', '外延、字面义', 'La denotación es neutra.'),
            ],
            'grammar': [
                {'title': '缓和语与礼貌策略', 'desc': 'Quizá / Tal vez / Me parece que / Si no me equivoco / Hasta cierto punto —— 西语用这些手段给自己的判断留退路。学术与商务场合几乎不使用无缓和的断言，这是语用能力的核心。'},
                {'title': '预设的识别与利用', 'desc': '「¿Por qué dejaste de fumar?」预设了对方曾吸烟。识别预设是辩论中的关键技能：否定一个含预设的问题，必须先指出预设本身不成立，否则会陷入对方设定的框架。'},
                {'title': '修辞格的辨识', 'desc': 'oxímoron（矛盾修辞，如 «silencio atronador»）、litote（曲言，如 «no está mal» 意为很好）、preterición（阳否阴述，声明不提却提了）。识别这些手段是理解反讽与言外之意的前提。'},
            ],
        },
    ],
}
