#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批次 76：C1 补「发展经济学与国际合作」单元（→ C1 达 20 单元）

为什么补这个：C1 有「经济与社会政策」（c1-u4）与「经济与社会」（c1-u12），
都偏国内政策与数据表述，但缺发展经济学与援助体系这一国际层面
（贫困测度、援助效率、债务减免、公平贸易、财政正义）。
这是 C1 阅读（国际组织报告、发展社论）的常见语域。

所有词头已用全库比对校验：与现有 6100+ 词条零重复。
"""

BATCH = {
    'C1': [
        {
            'id': 'c1-u23', 'title': '发展经济学与国际合作', 'subtitle': 'Economía del Desarrollo y Cooperación Internacional',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
                ('El subdesarrollo', '欠发达', 'El subdesarrollo limita las opciones vitales.'),
                ('El país menos adelantado', '最不发达国家', 'El país menos adelantado depende de la ayuda.'),
                ('La trampa de la pobreza', '贫困陷阱', 'La trampa de la pobreza se hereda entre generaciones.'),
                ('La pobreza extrema', '极端贫困', 'La pobreza extrema se mide por ingreso diario.'),
                ('La pobreza relativa', '相对贫困', 'La pobreza relativa depende del entorno.'),
                ('La línea de pobreza', '贫困线', 'La línea de pobreza se ajusta cada año.'),
                ('El umbral de pobreza', '贫困门槛', 'El umbral de pobreza varía por país.'),
                ('La desigualdad de ingresos', '收入不平等', 'La desigualdad de ingresos frenó el crecimiento.'),
                ('El coeficiente de Gini', '基尼系数', 'El coeficiente de Gini subió dos puntos.'),
                ('La distribución de la renta', '收入分配', 'La distribución de la renta es muy desigual.'),
                ('La progresividad fiscal', '税收累进性', 'La progresividad fiscal corrige desigualdades.'),
                ('El impuesto progresivo', '累进税', 'El impuesto progresivo grava más a quien más gana.'),
                ('El impuesto regresivo', '累退税', 'El impuesto regresivo golpea a los más pobres.'),
                ('La fuga de capitales', '资本外逃', 'La fuga de capitales vacía el país.'),
                ('El control de capitales', '资本管制', 'El control de capitales evitó la salida masiva.'),
                ('La ayuda oficial al desarrollo', '官方发展援助', 'La ayuda oficial al desarrollo ronda el 0,3 % del PIB.'),
                ('La eficacia de la ayuda', '援助效率', 'La eficacia de la ayuda exige apropiación local.'),
                ('La apropiación nacional', '国家自主权', 'La apropiación nacional es un principio de París.'),
                ('La deuda externa', '外债', 'La deuda externa consume el presupuesto.'),
                ('El servicio de la deuda', '偿债支出', 'El servicio de la deuda supera el gasto en salud.'),
                ('La sostenibilidad de la deuda', '债务可持续性', 'La sostenibilidad de la deuda se evalúa cada año.'),
                ('El canje de deuda por naturaleza', '债务换自然', 'El canje de deuda por naturaleza financia conservación.'),
                ('La financiación del desarrollo', '发展融资', 'La financiación del desarrollo combina público y privado.'),
                ('El banco de desarrollo', '开发银行', 'El banco de desarrollo presta a largo plazo.'),
                ('La microfinanciación', '微型金融', 'La microfinanciación llegó a zonas sin bancos.'),
                ('El microcrédito', '小额信贷', 'El microcrédito financió un pequeño taller.'),
                ('La inclusión financiera', '金融普惠', 'La inclusión financiera reduce la vulnerabilidad.'),
                ('El acceso al crédito', '获得信贷', 'El acceso al crédito sigue siendo desigual.'),
                ('La garantía solidaria', '联保', 'La garantía solidaria sustituye al aval.'),
                ('El emprendimiento social', '社会创业', 'El emprendimiento social busca impacto además de beneficio.'),
                ('La economía social', '社会经济', 'La economía social prioriza a las personas.'),
                ('La cooperativa', '合作社', 'La cooperativa reparte excedentes entre socios.'),
                ('El comercio justo', '公平贸易', 'El comercio justo garantiza un precio mínimo.'),
                ('El precio justo', '公平价格', 'El precio justo cubre costes y vida digna.'),
                ('La trazabilidad del producto', '产品可追溯', 'La trazabilidad del producto verifica el origen.'),
                ('El sello de comercio justo', '公平贸易认证', 'El sello de comercio justo certifica la cadena.'),
                ('La soberanía alimentaria', '粮食主权', 'La soberanía alimentaria decide qué se cultiva.'),
                ('La seguridad alimentaria', '粮食安全', 'La seguridad alimentaria exige acceso estable.'),
                ('La crisis alimentaria', '粮食危机', 'La crisis alimentaria se agravó con la sequía.'),
                ('La malnutrición', '营养不良', 'La malnutrición incluye el exceso de peso.'),
                ('La desnutrición crónica', '慢性营养不良', 'La desnutrición crónica afecta al desarrollo cognitivo.'),
                ('La ayuda alimentaria', '粮食援助', 'La ayuda alimentaria debe ser local cuando sea posible.'),
                ('El programa de transferencia monetaria', '现金转移项目', 'El programa de transferencia monetaria redujo la pobreza.'),
                ('La red de protección social', '社会保护网', 'La red de protección social amortigua las crisis.'),
                ('El seguro de desempleo', '失业保险', 'El seguro de desempleo cubre parte del salario.'),
                ('El ingreso básico universal', '全民基本收入', 'El ingreso básico universal se prueba en varios países.'),
                ('La pobreza energética', '能源贫困', 'La pobreza energética obliga a elegir entre luz y comida.'),
                ('La brecha de infraestructura', '基础设施缺口', 'La brecha de infraestructura frena la productividad.'),
                ('La asociación público-privada', '公私合作', 'La asociación público-privada reparte riesgos.'),
                ('La corrupción administrativa', '行政腐败', 'La corrupción administrativa desvía recursos.'),
                ('La malversación', '挪用公款', 'La malversación se castiga con prisión.'),
                ('La rendición de cuentas pública', '公共问责', 'La rendición de cuentas pública exige datos abiertos.'),
                ('La auditoría pública', '公共审计', 'La auditoría pública detectó pagos irregulares.'),
                ('La transparencia presupuestaria', '预算透明', 'La transparencia presupuestaria facilita el control.'),
                ('El presupuesto participativo', '参与式预算', 'El presupuesto participativo decide obras locales.'),
                ('La capacidad fiscal del Estado', '国家财政能力', 'La capacidad fiscal del Estado depende de la recaudación.'),
                ('La tributación de las multinacionales', '跨国公司纳税', 'La tributación de las multinacionales se negocia globalmente.'),
                ('El impuesto mínimo global', '全球最低税率', 'El impuesto mínimo global fija un suelo del 15 %.'),
                ('El intercambio de información fiscal', '税务信息交换', 'El intercambio de información fiscal cierra vías de elusión.'),
                ('La justicia fiscal', '税收正义', 'La justicia fiscal exige que quien más tiene, más aporte.'),
                ('La sostenibilidad fiscal', '财政可持续性', 'La sostenibilidad fiscal limita el gasto.'),
                ('El ajuste presupuestario', '预算调整', 'El ajuste presupuestario recortó inversión.'),
                ('La inversión social', '社会投资', 'La inversión social rinde a largo plazo.'),
                ('El retorno social de la inversión', '社会投资回报', 'El retorno social de la inversión se mide en indicadores.'),
                ('La teoría del cambio', '变革理论', 'La teoría del cambio explica cómo se produce el impacto.'),
                ('La línea de base', '基线', 'La línea de base mide la situación inicial.'),
                ('El grupo de comparación', '对照组', 'El grupo de comparación aísla el efecto.'),
                ('El indicador de resultado', '结果指标', 'El indicador de resultado mide el cambio real.'),
                ('El marco lógico', '逻辑框架', 'El marco lógico ordena objetivos y actividades.'),
                ('La participación comunitaria', '社区参与', 'La participación comunitaria asegura sostenibilidad.'),
                ('El enfoque de derechos', '权利本位方法', 'El enfoque de derechos exige rendición de cuentas.'),
                ('El empoderamiento', '赋权', 'El empoderamiento de las mujeres acelera el desarrollo.'),
                ('La capacitación', '能力建设', 'La capacitación fortalece a las organizaciones locales.'),
                ('El fortalecimiento institucional', '制度建设', 'El fortalecimiento institucional sostiene las reformas.'),
                ('La gobernanza local', '地方治理', 'La gobernanza local acerca las decisiones.'),
                ('La sociedad civil organizada', '有组织的公民社会', 'La sociedad civil organizada vigila el gasto público.'),
            ],
            'grammar': [
                {'title': '数量、比例与趋势的高阶表述', 'desc': 'el coeficiente de Gini / la tasa de / representar un tercio de / duplicarse respecto a。注意 porcentaje（百分比）与 puntos porcentuales（百分点）的区别：subió dos puntos, no dos por ciento。'},
                {'title': '表达因果链与条件依赖', 'desc': 'en la medida en que / siempre que + 虚拟式 / a condición de que + 虚拟式 / de ahí que + 虚拟式。发展经济学常写条件依赖：La ayuda es eficaz en la medida en que exista apropiación local。'},
                {'title': '学术论证中的让步与限定', 'desc': 'si bien es cierto que / conviene reconocer que / sin menoscabo de / aun reconociendo que。注意 sin menoscabo de（不减损）是法律与政策文本的高阶连接。'},
            ],
        },
    ],
}
