#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批次 61：C2 补 2 个单元（心灵与认知科学 / 经济与全球化）

为什么补这两个：C1 与 C2 各只有 14 个单元、每单元 50+ 词，是全库最"重"的两级
（A1 每单元 39 词、18 个单元）。C2 现有单元覆盖文学修辞、书面语、法律、惯用语、
哲学、美学、科学哲学、语言学、法学、艺术、语域、语用、伦理学、历史，
但**心灵与认知科学**和**经济与全球化**这两个 C2 高频话题没有专门单元。

所有词头已用全库比对校验：与现有 5000+ 词条零重复（含仅冠词/大小写不同的情况）。
"""

BATCH = {
    'C2': [
        {
            'id': 'c2-u15', 'title': '心灵与认知科学', 'subtitle': 'Mente y Ciencia Cognitiva',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
                ('La autoconciencia', '自我意识', 'La autoconciencia exige poder observarse a uno mismo.'),
                ('Lo mental', '心理的、心智的（中性冠词结构）', 'Lo mental no se reduce a lo físico sin discusión.'),
                ('El funcionalismo', '功能主义', 'El funcionalismo define la mente por su función.'),
                ('La intencionalidad', '意向性', 'La intencionalidad es la propiedad de dirigirse a algo.'),
                ('La representación mental', '心理表征', 'Toda representación mental tiene un contenido.'),
                ('El contenido mental', '心理内容', 'El contenido mental puede ser verdadero o falso.'),
                ('La cualidad subjetiva', '主观性质', 'La cualidad subjetiva de la experiencia resiste la medición.'),
                ('La experiencia subjetiva', '主观体验', 'La experiencia subjetiva no se observa desde fuera.'),
                ('La percepción', '感知', 'La percepción organiza los datos de los sentidos.'),
                ('La arquitectura cognitiva', '认知架构', 'La arquitectura cognitiva describe cómo se organiza el sistema.'),
                ('La modularidad', '模块性', 'La modularidad sostiene que la mente tiene partes especializadas.'),
                ('El conexionismo', '联结主义', 'El conexionismo modela la mente con redes de unidades.'),
                ('La red neuronal', '神经网络', 'Una red neuronal aprende ajustando sus pesos.'),
                ('El sesgo de automatización', '自动化偏见', 'El sesgo de automatización nos hace confiar demasiado en la máquina.'),
                ('La opacidad algorítmica', '算法不透明性', 'La opacidad algorítmica dificulta exigir responsabilidades.'),
                ('La caja negra', '黑箱', 'Un modelo de caja negra no explica sus decisiones.'),
                ('La atribución de agencia', '能动性归属', 'La atribución de agencia a una máquina plantea problemas éticos.'),
                ('El compatibilismo', '相容论', 'El compatibilismo sostiene que libertad y determinismo coexisten.'),
                ('La responsabilidad moral', '道德责任', 'Sin libertad, la responsabilidad moral pierde sentido.'),
                ('La agencia moral', '道德能动性', 'Solo un agente puede tener agencia moral.'),
                ('El razonamiento moral', '道德推理', 'El razonamiento moral procede por principios y casos.'),
                ('El juicio moral', '道德判断', 'El juicio moral varía menos de lo que se supone entre culturas.'),
                ('El experimento mental', '思想实验', 'El experimento mental aísla la intuición que queremos probar.'),
                ('La habitación china', '中文房间（塞尔的思想实验）', 'La habitación china cuestiona que manipular símbolos sea comprender.'),
                ('El test de Turing', '图灵测试', 'El test de Turing evalúa la conducta, no la experiencia.'),
                ('La simulación', '模拟', 'Simular un proceso no es necesariamente reproducirlo.'),
                ('La emulación', '仿真、等效实现', 'La emulación busca el mismo resultado por otra vía.'),
                ('La cognición encarnada', '具身认知', 'La cognición encarnada sitúa el pensamiento en el cuerpo.'),
                ('La cognición distribuida', '分布式认知', 'La cognición distribuida reparte el trabajo mental en el entorno.'),
                ('La cognición extendida', '延展认知', 'La cognición extendida incluye cuadernos y dispositivos como parte del sistema.'),
                ('El enactivismo', '生成论、行动主义', 'El enactivismo define conocer como actuar en el entorno.'),
                ('La evidencia introspectiva', '内省证据', 'La evidencia introspectiva es accesible solo en primera persona.'),
                ('El informe verbal', '口头报告', 'El informe verbal puede ser incompleto o reconstruido.'),
                ('La fiabilidad introspectiva', '内省的可靠性', 'La fiabilidad introspectiva se pone a prueba con experimentos.'),
                ('La racionalidad limitada', '有限理性', 'La racionalidad limitada describe decisiones con recursos escasos.'),
                ('La decisión racional', '理性决策', 'La decisión racional maximiza la utilidad esperada.'),
                ('La teoría de la decisión', '决策论', 'La teoría de la decisión formaliza la elección bajo incertidumbre.'),
                ('La utilidad esperada', '期望效用', 'La utilidad esperada pondera cada resultado por su probabilidad.'),
                ('La aversión al riesgo', '风险厌恶', 'La aversión al riesgo explica por qué preferimos lo seguro.'),
                ('La disponibilidad heurística', '可得性启发', 'La disponibilidad heurística juzga la frecuencia por lo que recordamos.'),
                ('La ilusión cognitiva', '认知错觉', 'Las ilusiones cognitivas persisten aunque conozcamos el mecanismo.'),
                ('La confianza epistémica', '认知信任', 'La confianza epistémica regula a quién creemos y por qué.'),
                ('La creencia justificada', '有正当理由的信念', 'Una creencia justificada necesita razones, no solo certeza.'),
                ('La creencia verdadera justificada', '有正当理由的真信念', 'La creencia verdadera justificada es la definición clásica de conocimiento.'),
                ('El problema de la inducción', '归纳问题', 'El problema de la inducción cuestiona generalizar desde casos finitos.'),
                ('La carga de la prueba epistémica', '认知举证责任', 'La carga de la prueba epistémica recae en quien afirma.'),
                ('La virtud epistémica', '认知德性', 'La virtud epistémica es una disposición a creer bien.'),
                ('La humildad epistémica', '认知谦逊', 'La humildad epistémica reconoce los límites del propio juicio.'),
                ('El reduccionismo explicativo', '解释性还原论', 'El reduccionismo explicativo pretende explicar lo complejo por lo simple.'),
                ('La sobredeterminación', '多重决定', 'La sobredeterminación admite varias causas suficientes a la vez.'),
                ('La causación descendente', '下行因果', 'La causación descendente va de lo global a lo local.'),
                ('El problema mente-cuerpo', '心身问题', 'El problema mente-cuerpo pregunta cómo se relacionan lo mental y lo físico.'),
                ('La brecha explicativa', '解释鸿沟', 'La brecha explicativa separa los datos físicos de la vivencia.'),
            ],
            'grammar': [
                {'title': '抽象名词化与无人称论述', 'desc': '把动词或形容词转成名词来论述：percibir → la percepción，consciente → la conciencia，explicar → la explicación。好处是客观、可作主语（La explicación de X exige…）；代价是句子变长、施事消失。学术写作里要控制比例，不要每句都名词化。'},
                {'title': '命题态度与归属的精密表达', 'desc': 'Sostener que / defender que / admitir que / objetar que / dar por sentado que。注意不同动词后跟的语式不同：afirmar que + 陈述式，negar que + 虚拟式（Niega que exista）。'},
                {'title': '限定与保留的书面表达', 'desc': 'en la medida en que / siempre que / a condición de que / salvo que / con la salvedad de que。a condición de que 与 salvo que 后面用虚拟式；en la medida en que 用陈述式。'},
            ],
        },
        {
            'id': 'c2-u16', 'title': '经济与全球化', 'subtitle': 'Economía y Globalización',
            'lessons': 12, 'duration': '约 50 分钟',
            'vocab': [
('El globalismo', '全球主义（意识形态）', 'El globalismo designa la ideología, no el proceso.'),
                ('La interdependencia económica', '经济相互依存', 'La interdependencia económica hace que las crisis viajen rápido.'),
                ('La deslocalización', '生产外迁', 'La deslocalización traslada la producción a otros países.'),
                ('La relocalización', '回岸、产业回流', 'La relocalización devuelve fábricas al país de origen.'),
                ('La cadena de valor global', '全球价值链', 'La cadena de valor global reparte las tareas entre países.'),
                ('La cadena de suministro', '供应链', 'La cadena de suministro se rompió por la pandemia.'),
                ('La logística internacional', '国际物流', 'La logística internacional encarece los envíos largos.'),
                ('El arancel', '关税', 'El arancel encarece el producto importado.'),
                ('La barrera arancelaria', '关税壁垒', 'Una barrera arancelaria es un impuesto al comercio.'),
                ('La barrera no arancelaria', '非关税壁垒', 'Las barreras no arancelarias son normas y cuotas.'),
                ('El proteccionismo', '保护主义', 'El proteccionismo protege sectores poco competitivos.'),
                ('El libre comercio', '自由贸易', 'El libre comercio reduce precios pero concentra riesgos.'),
                ('La cuota de importación', '进口配额', 'La cuota de importación limita el volumen permitido.'),
                ('El dumping', '倾销', 'El dumping vende por debajo del coste para ganar mercado.'),
                ('El subsidio estatal', '国家补贴', 'El subsidio estatal distorsiona la competencia.'),
                ('La política comercial', '贸易政策', 'La política comercial combina aranceles y acuerdos.'),
                ('El tratado de libre comercio', '自由贸易协定', 'El tratado de libre comercio elimina aranceles mutuos.'),
                ('El bloque comercial', '贸易集团', 'Un bloque comercial negocia como una sola voz.'),
                ('La integración regional', '区域一体化', 'La integración regional avanza a distintas velocidades.'),
                ('La unión aduanera', '关税同盟', 'La unión aduanera fija un arancel exterior común.'),
                ('El mercado único', '单一市场', 'El mercado único permite circular bienes y personas.'),
                ('La convergencia económica', '经济趋同', 'La convergencia económica acerca la renta por habitante.'),
                ('La divergencia económica', '经济分化', 'La divergencia económica amplía la brecha entre regiones.'),
                ('La brecha de desarrollo', '发展差距', 'La brecha de desarrollo se mide en productividad.'),
                ('La economía emergente', '新兴经济体', 'Las economías emergentes crecen más rápido que las maduras.'),
                ('El país en desarrollo', '发展中国家', 'El país en desarrollo depende de materias primas.'),
                ('La dependencia de la materia prima', '对原材料的依赖', 'La dependencia de la materia prima vuelve frágil la economía.'),
                ('La diversificación productiva', '生产多元化', 'La diversificación productiva reduce la vulnerabilidad externa.'),
                ('El valor añadido', '附加值', 'El valor añadido se queda donde se transforma el producto.'),
                ('La productividad total de los factores', '全要素生产率', 'La productividad total de los factores mide la eficiencia agregada.'),
                ('El déficit comercial', '贸易逆差', 'El déficit comercial crece cuando importamos más.'),
                ('El superávit comercial', '贸易顺差', 'El superávit comercial refleja más exportaciones que importaciones.'),
                ('La balanza de pagos', '国际收支', 'La balanza de pagos registra todas las operaciones externas.'),
                ('La inversión extranjera directa', '外商直接投资', 'La inversión extranjera directa busca plantas y mercados.'),
                ('El paraíso fiscal', '避税天堂', 'El paraíso fiscal opacidad y tipos muy bajos.'),
                ('La evasión fiscal', '逃税', 'La evasión fiscal es ilegal; la elusión, no siempre.'),
                ('La armonización fiscal', '税收协调', 'La armonización fiscal busca tipos mínimos comunes.'),
                ('El impuesto de sociedades', '企业所得税', 'El impuesto de sociedades grava el beneficio empresarial.'),
                ('El tipo de cambio', '汇率', 'El tipo de cambio afecta a exportadores e importadores.'),
                ('La apreciación', '升值', 'La apreciación encarece las exportaciones.'),
                ('La depreciación', '贬值', 'La depreciación alivia la deuda externa en moneda local.'),
                ('La paridad de poder adquisitivo', '购买力平价', 'La paridad de poder adquisitivo compara el poder de compra real.'),
                ('La volatilidad cambiaria', '汇率波动', 'La volatilidad cambiaria complica planificar a largo plazo.'),
                ('La cobertura de riesgo', '风险对冲', 'La cobertura de riesgo fija hoy el precio de mañana.'),
                ('El capital especulativo', '投机资本', 'El capital especulativo entra y sale en días.'),
                ('La desregulación', '放松管制', 'La desregulación eliminó controles sobre el capital.'),
                ('La recapitalización', '资本重组', 'La recapitalización inyecta fondos en la banca.'),
                ('El ajuste estructural', '结构调整', 'El ajuste estructural recorta gasto para estabilizar cuentas.'),
                ('La condicionalidad', '附加条件', 'La condicionalidad ata la ayuda a reformas concretas.'),
                ('El organismo multilateral', '多边机构', 'Los organismos multilaterales coordinan reglas comunes.'),
                ('La ayuda al desarrollo', '发展援助', 'La ayuda al desarrollo busca reducir la pobreza.'),
                ('La condonación de la deuda', '债务减免', 'La condonación de la deuda libera recursos fiscales.'),
                ('La externalidad negativa', '负外部性', 'La externalidad negativa la paga quien no la causó.'),
                ('El bien público global', '全球公共品', 'El clima estable es un bien público global.'),
            ],
            'grammar': [
                {'title': '经济论述中的因果与后果结构', 'desc': 'a raíz de（由于）/ como consecuencia de / de ahí que + 虚拟式 / lo que se traduce en。注意 de ahí que 强制虚拟式：De ahí que muchos gobiernos intervengan。'},
                {'title': '让步与限定的精密表达', 'desc': 'si bien / aun cuando / por más que + 虚拟式 / con todo。por más que insistan（无论他们怎么坚持）后面用虚拟式，这是 C2 常考点。'},
                {'title': '数量与趋势的学术表述', 'desc': 'registrar un aumento del X % / situarse en torno a / experimentar un descenso / mantenerse estable。用 registrar 与 experimentar 让句子脱离口语的 subir/bajar。'},
            ],
        },
    ],
}
