# -*- coding: utf-8 -*-
GROUPS = [
    ('现在进行时 estar + gerundio', [
        ('Ahora mismo ___ escribiendo un informe.', ['estoy', 'soy', 'tengo', 'hago'], 0,
         'estar + 副动词构成进行时。estar 按主语变位，副动词不变位。'),
        ('¿Qué ___ leyendo? Parece interesante.', ['estás', 'eres', 'tienes', 'lees'], 0,
         '问「你正在读什么」用 estar 的 tú 形式 estás + leyendo。若用 lees 则问的是习惯而非此刻。'),
        ('Los niños ___ oyendo un cuento.', ['están', 'son', 'tienen', 'oyen'], 0,
         'oír 的副动词是 oyendo（不规则）。第三人称复数用 están。'),
        ('No puedo hablar, ___ conduciendo.', ['estoy', 'soy', 'tengo', 'voy'], 0,
         'estoy conduciendo 表「我正在开车」。ir + 副动词表渐进过程，但此处指当下动作，用 estar。'),
        ('Ella ___ durmiendo desde las dos.', ['está', 'es', 'tiene', 'duerme'], 0,
         'dormir 的副动词是 durmiendo（o→u 词干变化）。注意 «lleva durmiendo» 才表持续时长。'),
    ]),
    ('doler 与身体部位', [
        ('___ duele la garganta desde ayer.', ['Me', 'Yo', 'Mi', 'Mí'], 0,
         'doler 的主语是身体部位，人用与格代词：me duele la garganta。部位是单数用 duele。'),
        ('Me ___ las piernas después de correr.', ['duelen', 'duele', 'doler', 'dolía'], 0,
         '部位是复数 las piernas，所以动词用 duelen。doler 的 o→ue 变化在单复数都要体现。'),
        ('¿Te ___ algo? ¿Quieres que llamemos al médico?', ['duele', 'duelen', 'doler', 'dolía'], 0,
         '主语是 algo（单数），所以用 duele。这是询问对方身体状况的常用句型。'),
        ('Tengo ___ y fiebre, creo que es gripe.', ['tos', 'toser', 'toso', 'la tos'], 0,
         'tener + 病痛名词：tener tos（咳嗽）、tener fiebre（发烧）。tos 前不加冠词。'),
        ('Se ___ un brazo esquiando.', ['rompió', 'rompía', 'rompe', 'romperá'], 0,
         '自复结构 romperse + 身体部位 ＝ 摔断/弄伤某个部位。一次性事件用简单过去时。'),
    ]),
    ('礼貌请求与指令', [
        ('¿___ ayudarme un momento, por favor?', ['Podría', 'Puedo', 'Puede', 'Podré'], 0,
         '¿Podría...? 是条件式，表委婉请求，比 ¿Puede...? 更客气。这是问对方能否帮忙。'),
        ('¿Le ___ si abro la ventana?', ['importaría', 'importa', 'importe', 'importará'], 0,
         '¿Le importaría si...? 是极礼貌的请求句式，importaría 用条件式。'),
        ('___ usted pasar por aquí, por favor.', ['Pase', 'Pasa', 'Pasar', 'Pasando'], 0,
         '正式（usted）肯定命令式用第三人称虚拟式形式：pase。tú 形式才是 pasa。'),
        ('No ___ usted el móvil durante la reunión.', ['use', 'usa', 'usar', 'usando'], 0,
         '正式否定命令式同样用虚拟式：no use。命令式的否定形式一律用虚拟式。'),
        ('___ tan amable de firmar aquí.', ['Sería', 'Es', 'Sea', 'Será'], 0,
         '¿Sería tan amable de...? 是公式化的客套请求，用条件式。'),
    ]),
    ('表达距离与位置', [
        ('La farmacia está ___ de aquí, a dos minutos.', ['cerca', 'cercano', 'cerca a', 'cercas'], 0,
         'cerca de ＝ 在……附近。注意是 cerca de，不是 cerca a（常见错误）。'),
        ('El hotel está ___ de la estación, justo enfrente.', ['al lado', 'en lado', 'a lado', 'de lado'], 0,
         'al lado de ＝ 在……旁边。介词搭配固定为 a + el = al。'),
        ('¿___ una biblioteca por aquí?', ['Hay', 'Está', 'Es', 'Tiene'], 0,
         '问「这附近有没有」用 hay（表存在）。若已知存在而问位置才用 está：¿Dónde está la biblioteca?'),
        ('El museo está ___ del parque, cruzando la calle.', ['enfrente', 'enfrente a', 'en frente', 'frente'], 0,
         'enfrente de ＝ 在……对面。也可以说 justo enfrente（就在对面）。'),
        ('Mi casa está ___ a la tuya, en el mismo edificio.', ['junto', 'juntos', 'junto de', 'junta'], 0,
         'junto a ＝ 紧邻着。junto 不随主语变化，是副词性用法。'),
    ]),
    ('天气表达', [
        ('Hoy ___ un frío terrible, ponte el abrigo.', ['hace', 'es', 'está', 'hay'], 0,
         '天气用 hacer + 名词：hace frío / hace calor / hace viento。es 用于描述天气的性质而非状态。'),
        ('En el norte ___ mucho en invierno.', ['llueve', 'llueven', 'llover', 'lloviendo'], 0,
         'llover 只有第三人称单数形式 llueve，没有主语。nevar → nieva 同理。'),
        ('El cielo ___ nublado desde esta mañana.', ['está', 'es', 'hace', 'hay'], 0,
         '天气的暂时状态用 estar：el cielo está nublado。对比 el clima es húmedo（气候特征用 ser）。'),
        ('¿Qué tiempo ___ mañana?', ['hará', 'será', 'estará', 'habrá'], 0,
         'hacer 表天气，问「明天天气如何」用 ¿Qué tiempo hará?。将来时用 hará。'),
        ('___ niebla en la carretera, conduce con cuidado.', ['Hay', 'Está', 'Hace', 'Es'], 0,
         '表「有雾」用 hay niebla（存在）。这与 hace frío（状态）不同，niebla 是可见的实体。'),
    ]),
    ('让步句 aunque / por más que / a pesar de', [
        ('___ llueva, saldremos a caminar.', ['Aunque', 'Porque', 'Cuando', 'Si'], 0,
         'aunque + 虚拟式表假设性让步（即使下雨）。若用陈述式 llueve 则表示已知事实。'),
        ('___ estaba enfermo, fue a trabajar.', ['Aunque', 'Por más que', 'A pesar', 'Si bien que'], 0,
         'aunque + 陈述式表已知事实的让步（虽然病了，还是去上班了）。'),
        ('Por más que ___, no cambiará de opinión.', ['insistas', 'insistes', 'insistirás', 'insistías'], 0,
         'por más que 后必须接虚拟式，表「无论怎么……」。这是固定搭配，与 aunque 的两种可能不同。'),
        ('___ del mal tiempo, la excursión fue un éxito.', ['A pesar', 'Aunque', 'Por más que', 'Si bien'], 0,
         'a pesar de + 名词（或不定式）。aunque 后面必须接完整从句，不能直接接名词。'),
        ('___ es joven, tiene mucha experiencia.', ['Si bien', 'Por más que', 'A pesar', 'Aunque que'], 0,
         'si bien 表书面让步（虽然），后接陈述式。语域比 aunque 更正式。'),
    ]),
    ('因果与后果的正式结构', [
        ('La reunión se aplazó ___ a la falta de quórum.', ['debido', 'por', 'a causa', 'como'], 0,
         'debido a ＝ 由于，是正式书面表达。por 后直接接名词时也可表原因，但不构成 debido a 这一固定短语。'),
        ('El proyecto fracasó ___ culpa de una mala planificación.', ['por', 'de', 'a', 'en'], 0,
         'por culpa de 表「由于（某人的过失）」，带负面评价。中性原因用 debido a 或 a causa de。'),
        ('No hay consenso; ___, la decisión se pospone.', ['por consiguiente', 'por consiguiente que', 'consiguiente', 'a consiguiente'], 0,
         'por consiguiente ＝ 因此（书面）。同义结构还有 en consecuencia / por lo tanto。'),
        ('Llovió toda la semana, ___ que se cancelara el partido.', ['de ahí', 'de ahí de', 'ahí', 'por ahí'], 0,
         'de ahí que + 虚拟式 ＝ 因此（导致某结果）。de ahí que 后必须用虚拟式，这是常考点。'),
        ('El plan se tradujo ___ una mejora notable del servicio.', ['en', 'a', 'de', 'por'], 0,
         'traducirse en ＝ 转化为、体现为。这是描述结果的标准搭配。'),
    ]),
]
